// Generated by `nuxi prepare`. The i18n composables are declared structurally
// by the module's own virtual module, so nothing here pulls a package that
// augments Vue's `ComponentCustomProperties`. `$t` therefore has no declaration
// anywhere in this project's type graph.
declare global {
  const useI18n: () => {
    locale: import("vue").WritableComputedRef<string>;
    t: (key: string) => string;
  };
  const useLocalePath: () => (path: string) => string;
}

export {};
