import type { PrimitiveElement } from "../../../primitive.ts";

/** Render state mirrored by {@link Avatar} through `data-state`. */
export type AvatarState = "fallback" | "image";

/** Presence state mirrored by {@link Avatar} through `data-image`, `data-name`, and `data-fallback`. */
export type AvatarPresence = "missing" | "present";

/** Consumer presence tokens mirrored by {@link Avatar} through `data-status`. */
export type AvatarStatus = "away" | "busy" | "none" | "offline" | "online";

/** Native image loading policies accepted by {@link Avatar}. */
export type AvatarImageLoading = "eager" | "lazy";

/** Native image decoding policies accepted by {@link Avatar}. */
export type AvatarImageDecoding = "async" | "auto" | "sync";

/** Native image fetch-priority hints accepted by {@link Avatar}. */
export type AvatarImageFetchPriority = "auto" | "high" | "low";

/** Native image CORS policies accepted by {@link Avatar}. */
export type AvatarImageCrossOrigin = "" | "anonymous" | "use-credentials";

/** Native image referrer policies accepted by {@link Avatar}. */
export type AvatarImageReferrerPolicy =
  | "no-referrer"
  | "no-referrer-when-downgrade"
  | "origin"
  | "origin-when-cross-origin"
  | "same-origin"
  | "strict-origin"
  | "strict-origin-when-cross-origin"
  | "unsafe-url";

/** Rendered root value exposed by {@link Avatar}. */
export type AvatarElement = PrimitiveElement;

/** Rendered native image part value exposed by {@link Avatar}. */
export type AvatarImageElement = HTMLImageElement;

/** Rendered native fallback part value exposed by {@link Avatar}. */
export type AvatarFallbackElement = HTMLSpanElement;

/** State exposed to Avatar slots. */
export interface AvatarSlotState {
  /** Current render branch. */
  readonly state: AvatarState;

  /** Consumer presence token mirrored to `data-status`. */
  readonly status: AvatarStatus;

  /** Image source passed to the native image part. */
  readonly src: string | undefined;

  /** Native image alternative text. */
  readonly alt: string;

  /** Consumer-owned display name, never transformed by Avatar. */
  readonly name: string | undefined;

  /** Consumer-owned fallback text, never generated by Avatar. */
  readonly fallback: string | undefined;

  /** Whether the image source hook is present. */
  readonly image: AvatarPresence;

  /** Whether the name hook is present. */
  readonly nameState: AvatarPresence;

  /** Whether fallback content is present through prop or slot. */
  readonly fallbackState: AvatarPresence;
}

/** Public component instance state exposed by the Avatar primitive. */
export interface AvatarExpose extends AvatarSlotState {
  /** Rendered root element or component instance. */
  readonly element: AvatarElement | null;

  /** Rendered native image part. */
  readonly imageElement: AvatarImageElement | null;

  /** Rendered native fallback part. */
  readonly fallbackElement: AvatarFallbackElement | null;
}
