import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const feedbackFamilyCatalog = [
  {
    canonicalName: "alert",
    title: "Alert",
    packageSubpath: "./alert",
    entryFile: "src/alert.ts",
    sourceFiles: ["src/alert.vue", "src/alert.ts", "src/alert-types.ts"],
    behaviorContract: "src/alert.behavior.md",
    tests: ["src/alert.test.ts"],
    typeTests: ["src/alert.types.test-d.ts"],
    rendererFixture: "alert.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Alert",
      retainedSignature: 'data-vize-ui":(?:`alert`|"alert"|\'alert\')',
      maximumJavaScriptGzipBytes: 750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["inline alert", "status alert", "callout primitive"],
    upstreamCoverage: ["WAI-ARIA alert role", "WAI-ARIA status role", "shadcn/ui Alert"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "badge",
    title: "Badge",
    packageSubpath: "./badge",
    entryFile: "src/badge.ts",
    sourceFiles: ["src/badge.vue", "src/badge.ts", "src/badge-types.ts"],
    behaviorContract: "src/badge.behavior.md",
    tests: ["src/badge.test.ts", "src/badge-ssr.test.ts"],
    typeTests: ["src/badge.types.test-d.ts"],
    rendererFixture: "BadgeConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Badge",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}badge",
      maximumJavaScriptGzipBytes: 600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["tag", "chip", "status badge", "count badge", "unread indicator"],
    upstreamCoverage: ["HTML span", "shadcn/ui Badge", "Radix Themes Badge", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "banner",
    title: "Banner",
    packageSubpath: "./banner",
    entryFile: "src/families/feedback/banner/banner.ts",
    sourceFiles: [
      "src/families/feedback/banner/banner.vue",
      "src/families/feedback/banner/banner.ts",
      "src/families/feedback/banner/banner-aria.ts",
      "src/families/feedback/banner/banner-types.ts",
    ],
    behaviorContract: "src/families/feedback/banner/banner.behavior.md",
    tests: [
      "src/families/feedback/banner/banner.test.ts",
      "src/families/feedback/banner/banner-aria.test.ts",
      "src/families/feedback/banner/banner-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/banner/banner.types.test-d.ts"],
    rendererFixture: "BannerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Banner",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}banner",
      maximumJavaScriptGzipBytes: 4_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["announcement banner", "dismissible notice", "page notice", "status banner"],
    upstreamCoverage: [
      "WAI-ARIA region role",
      "WAI-ARIA status role",
      "WAI-ARIA alert role",
      "shadcn/ui Alert",
      "Vuetify Alert",
      "React Aria live regions",
    ],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "block-ui",
    title: "BlockUI",
    packageSubpath: "./block-ui",
    entryFile: "src/block-ui.ts",
    sourceFiles: ["src/block-ui.vue", "src/block-ui.ts", "src/block-ui-types.ts"],
    behaviorContract: "src/block-ui.behavior.md",
    tests: ["src/block-ui.test.ts", "src/block-ui-ssr.test.ts"],
    typeTests: ["src/block-ui.types.test-d.ts"],
    rendererFixture: "BlockUIConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "BlockUI",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}block-ui",
      maximumJavaScriptGzipBytes: 975,
      maximumCssGzipBytes: 0,
    },
    aliases: ["blocking overlay", "busy region", "pending region", "stale content", "offline gate"],
    upstreamCoverage: ["HTML inert attribute", "WAI-ARIA aria-busy", "WAI-ARIA status role"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "callout",
    title: "Callout",
    packageSubpath: "./callout",
    entryFile: "src/families/feedback/callout/callout.ts",
    sourceFiles: [
      "src/families/feedback/callout/callout.vue",
      "src/families/feedback/callout/callout.ts",
      "src/families/feedback/callout/callout-runtime.ts",
      "src/families/feedback/callout/callout-types.ts",
    ],
    behaviorContract: "src/families/feedback/callout/callout.behavior.md",
    tests: [
      "src/families/feedback/callout/callout.test.ts",
      "src/families/feedback/callout/callout-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/callout/callout.types.test-d.ts"],
    rendererFixture: "CalloutConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Callout",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}callout",
      maximumJavaScriptGzipBytes: 2_175,
      maximumCssGzipBytes: 0,
    },
    aliases: ["callout", "banner", "inline message", "notice", "message"],
    upstreamCoverage: [
      "WAI-ARIA note role",
      "WAI-ARIA status role",
      "WAI-ARIA alert role",
      "Radix Themes Callout",
      "shadcn/ui Alert",
      "Vuetify Alert",
    ],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "empty-state",
    title: "EmptyState",
    packageSubpath: "./empty-state",
    entryFile: "src/empty-state.ts",
    sourceFiles: ["src/empty-state.vue", "src/empty-state.ts", "src/empty-state-types.ts"],
    behaviorContract: "src/empty-state.behavior.md",
    tests: ["src/empty-state.test.ts", "src/empty-state-ssr.test.ts"],
    typeTests: ["src/empty-state.types.test-d.ts"],
    rendererFixture: "EmptyStateConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "EmptyState",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}empty-state",
      maximumJavaScriptGzipBytes: 600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["empty content", "no results", "offline state", "retry prompt", "zero state"],
    upstreamCoverage: ["HTML section element", "consumer-owned ARIA status pattern"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "meter",
    title: "Meter",
    packageSubpath: "./meter",
    entryFile: "src/meter.ts",
    sourceFiles: ["src/meter.vue", "src/meter.ts", "src/meter-state.ts", "src/meter-types.ts"],
    behaviorContract: "src/meter.behavior.md",
    tests: ["src/meter.test.ts", "src/meter-ssr.test.ts"],
    typeTests: ["src/meter.types.test-d.ts"],
    rendererFixture: "MeterConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Meter",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}meter",
      maximumJavaScriptGzipBytes: 2_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["gauge", "usage meter", "storage meter", "threshold meter"],
    upstreamCoverage: ["HTML meter element", "WAI-ARIA meter role", "React Aria Meter"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "skeleton",
    title: "Skeleton",
    packageSubpath: "./skeleton",
    entryFile: "src/skeleton.ts",
    sourceFiles: ["src/skeleton.vue", "src/skeleton.ts", "src/skeleton-types.ts"],
    behaviorContract: "src/skeleton.behavior.md",
    tests: ["src/skeleton.test.ts", "src/skeleton-ssr.test.ts"],
    typeTests: ["src/skeleton.types.test-d.ts"],
    rendererFixture: "SkeletonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Skeleton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}skeleton",
      maximumJavaScriptGzipBytes: 1_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["placeholder", "loading skeleton", "deferred content", "suspense fallback"],
    upstreamCoverage: ["WAI-ARIA status role", "shadcn/ui Skeleton", "React Aria ProgressBar"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "spinner",
    title: "Spinner",
    packageSubpath: "./spinner",
    entryFile: "src/spinner.ts",
    sourceFiles: ["src/spinner.vue", "src/spinner.ts", "src/spinner-types.ts"],
    behaviorContract: "src/spinner.behavior.md",
    tests: ["src/spinner.test.ts", "src/spinner-ssr.test.ts"],
    typeTests: ["src/spinner.types.test-d.ts"],
    rendererFixture: "SpinnerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Spinner",
      retainedSignature: 'data-vize-ui":(?:`spinner`|"spinner"|\'spinner\')',
      maximumJavaScriptGzipBytes: 1_900,
      maximumCssGzipBytes: 0,
    },
    aliases: ["spinner", "loading indicator", "progress spinner", "activity indicator"],
    upstreamCoverage: ["WAI-ARIA status role", "WAI-ARIA progressbar role", "MUI CircularProgress"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "status-light",
    title: "StatusLight",
    packageSubpath: "./status-light",
    entryFile: "src/families/feedback/status-light/status-light.ts",
    sourceFiles: [
      "src/families/feedback/status-light/status-light.vue",
      "src/families/feedback/status-light/status-light.ts",
      "src/families/feedback/status-light/status-light-types.ts",
    ],
    behaviorContract: "src/families/feedback/status-light/status-light.behavior.md",
    tests: [
      "src/families/feedback/status-light/status-light.test.ts",
      "src/families/feedback/status-light/status-light-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/status-light/status-light.types.test-d.ts"],
    rendererFixture: "StatusLightConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "StatusLight",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}status-light",
      maximumJavaScriptGzipBytes: 1_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["presence indicator", "health indicator", "status dot", "traffic light"],
    upstreamCoverage: ["WAI-ARIA img role", "WAI-ARIA status role", "Radix Themes Badge"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
