import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";
import { avatarLayoutFamilyCatalog } from "./family-catalog-layout-avatar.ts";
import { iconLayoutFamilyCatalog } from "./family-catalog-layout-icon.ts";
import { listLayoutFamilyCatalog } from "./family-catalog-layout-list.ts";

export const layoutFamilyCatalog = [
  {
    canonicalName: "aspect-ratio",
    title: "Aspect Ratio",
    packageSubpath: "./aspect-ratio",
    entryFile: "src/aspect-ratio.ts",
    sourceFiles: [
      "src/aspect-ratio.vue",
      "src/aspect-ratio.ts",
      "src/aspect-ratio-runtime.ts",
      "src/aspect-ratio-types.ts",
    ],
    behaviorContract: "src/aspect-ratio.behavior.md",
    tests: ["src/aspect-ratio.test.ts", "src/aspect-ratio-ssr.test.ts"],
    typeTests: ["src/aspect-ratio.types.test-d.ts"],
    rendererFixture: "AspectRatioConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "AspectRatio",
      retainedSignature: "data-vize-ui.+aspect-ratio",
      maximumJavaScriptGzipBytes: 1_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["aspect ratio", "intrinsic ratio", "responsive media box"],
    upstreamCoverage: ["CSS aspect-ratio", "Radix UI AspectRatio", "Reka UI AspectRatio"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  ...avatarLayoutFamilyCatalog,
  ...iconLayoutFamilyCatalog,
  {
    canonicalName: "blockquote",
    title: "Blockquote",
    packageSubpath: "./blockquote",
    entryFile: "src/blockquote.ts",
    sourceFiles: ["src/blockquote.vue", "src/blockquote.ts", "src/blockquote-types.ts"],
    behaviorContract: "src/blockquote.behavior.md",
    tests: ["src/blockquote.test.ts", "src/blockquote-ssr.test.ts"],
    typeTests: ["src/blockquote.types.test-d.ts"],
    rendererFixture: "BlockquoteConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Blockquote",
      retainedSignature: 'data-vize-ui":(?:`blockquote`|"blockquote"|\'blockquote\')',
      maximumJavaScriptGzipBytes: 900,
      maximumCssGzipBytes: 0,
    },
    aliases: ["quote", "pull quote", "quoted text", "quotation block"],
    upstreamCoverage: ["HTML blockquote element", "HTML cite attribute", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "card",
    title: "Card",
    packageSubpath: "./card",
    entryFile: "src/card.ts",
    sourceFiles: ["src/card.vue", "src/card.ts", "src/card-types.ts"],
    behaviorContract: "src/card.behavior.md",
    tests: ["src/card.test.ts", "src/card-ssr.test.ts"],
    typeTests: ["src/card.types.test-d.ts"],
    rendererFixture: "CardConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Card",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}card",
      maximumJavaScriptGzipBytes: 625,
      maximumCssGzipBytes: 0,
    },
    aliases: ["surface card", "panel", "content surface", "section shell"],
    upstreamCoverage: ["HTML section", "HTML article", "shadcn/ui Card", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "code",
    title: "Code",
    packageSubpath: "./code",
    entryFile: "src/code.ts",
    sourceFiles: ["src/code.vue", "src/code.ts", "src/code-types.ts"],
    behaviorContract: "src/code.behavior.md",
    tests: ["src/code.test.ts", "src/code-ssr.test.ts"],
    typeTests: ["src/code.types.test-d.ts"],
    rendererFixture: "CodeConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Code",
      retainedSignature: 'data-vize-ui":(?:`code`|"code"|\'code\')',
      maximumJavaScriptGzipBytes: 850,
      maximumCssGzipBytes: 0,
    },
    aliases: ["inline code", "code snippet", "code block", "monospace text"],
    upstreamCoverage: ["HTML code element", "HTML pre element", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "cluster",
    title: "Cluster",
    packageSubpath: "./cluster",
    entryFile: "src/cluster.ts",
    sourceFiles: [
      "src/cluster.vue",
      "src/cluster.ts",
      "src/cluster-runtime.ts",
      "src/cluster-types.ts",
    ],
    behaviorContract: "src/cluster.behavior.md",
    tests: ["src/cluster.test.ts", "src/cluster-ssr.test.ts"],
    typeTests: ["src/cluster.types.test-d.ts"],
    rendererFixture: "ClusterConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Cluster",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}cluster",
      maximumJavaScriptGzipBytes: 1_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout cluster", "wrapping row", "inline group", "action group"],
    upstreamCoverage: ["CSS flexbox", "CSS gap", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "container",
    title: "Container",
    packageSubpath: "./container",
    entryFile: "src/container.ts",
    sourceFiles: [
      "src/container.vue",
      "src/container.ts",
      "src/container-runtime.ts",
      "src/container-types.ts",
    ],
    behaviorContract: "src/container.behavior.md",
    tests: ["src/container.test.ts", "src/container-ssr.test.ts"],
    typeTests: ["src/container.types.test-d.ts"],
    rendererFixture: "ContainerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Container",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}container",
      maximumJavaScriptGzipBytes: 1_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout container", "page container", "max width wrapper", "centered region"],
    upstreamCoverage: ["CSS logical properties", "CSS max-inline-size", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "grid",
    title: "Grid",
    packageSubpath: "./grid",
    entryFile: "src/grid.ts",
    sourceFiles: ["src/grid.vue", "src/grid.ts", "src/grid-runtime.ts", "src/grid-types.ts"],
    behaviorContract: "src/grid.behavior.md",
    tests: ["src/grid.test.ts", "src/grid-ssr.test.ts"],
    typeTests: ["src/grid.types.test-d.ts"],
    rendererFixture: "GridConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Grid",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}grid",
      maximumJavaScriptGzipBytes: 1_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout grid", "responsive grid", "two-dimensional layout", "card grid"],
    upstreamCoverage: ["CSS grid", "CSS gap", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  ...listLayoutFamilyCatalog,
  {
    canonicalName: "separator",
    title: "Separator",
    packageSubpath: "./separator",
    entryFile: "src/separator.ts",
    sourceFiles: ["src/separator.vue", "src/separator.ts", "src/separator-types.ts"],
    behaviorContract: "src/separator.behavior.md",
    tests: ["src/separator.test.ts", "src/separator-ssr.test.ts"],
    typeTests: ["src/separator.types.test-d.ts"],
    rendererFixture: "SeparatorConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Separator",
      retainedSignature: "data-vize-ui.+separator",
      maximumJavaScriptGzipBytes: 650,
      maximumCssGzipBytes: 0,
    },
    aliases: ["divider", "rule", "thematic break", "splitter boundary"],
    upstreamCoverage: ["HTML hr", "WAI-ARIA Separator", "Radix UI Separator", "Reka UI Separator"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "spacer",
    title: "Spacer",
    packageSubpath: "./spacer",
    entryFile: "src/spacer.ts",
    sourceFiles: [
      "src/spacer.vue",
      "src/spacer.ts",
      "src/spacer-runtime.ts",
      "src/spacer-types.ts",
    ],
    behaviorContract: "src/spacer.behavior.md",
    tests: ["src/spacer.test.ts", "src/spacer-ssr.test.ts"],
    typeTests: ["src/spacer.types.test-d.ts"],
    rendererFixture: "SpacerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Spacer",
      retainedSignature: "data-vize-ui.+spacer",
      maximumJavaScriptGzipBytes: 950,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout spacer", "gap spacer", "white space", "svg spacer"],
    upstreamCoverage: [
      "CSS logical properties",
      "HTML span",
      "SVG element host",
      "Reka UI Primitive",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "stack",
    title: "Stack",
    packageSubpath: "./stack",
    entryFile: "src/stack.ts",
    sourceFiles: ["src/stack.vue", "src/stack.ts", "src/stack-runtime.ts", "src/stack-types.ts"],
    behaviorContract: "src/stack.behavior.md",
    tests: ["src/stack.test.ts", "src/stack-ssr.test.ts"],
    typeTests: ["src/stack.types.test-d.ts"],
    rendererFixture: "StackConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Stack",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}stack",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout stack", "vertical stack", "logical stack", "single-axis layout"],
    upstreamCoverage: ["CSS flexbox", "CSS logical properties", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "heading",
    title: "Heading",
    packageSubpath: "./heading",
    entryFile: "src/heading.ts",
    sourceFiles: ["src/heading.vue", "src/heading.ts", "src/heading-types.ts"],
    behaviorContract: "src/heading.behavior.md",
    tests: ["src/heading.test.ts", "src/heading-ssr.test.ts"],
    typeTests: ["src/heading.types.test-d.ts"],
    rendererFixture: "HeadingConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Heading",
      retainedSignature: 'data-vize-ui":(?:`heading`|"heading"|\'heading\')',
      maximumJavaScriptGzipBytes: 950,
      maximumCssGzipBytes: 0,
    },
    aliases: ["semantic heading", "typography heading", "title", "section heading"],
    upstreamCoverage: ["HTML heading content", "ARIA document structure", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "text",
    title: "Text",
    packageSubpath: "./text",
    entryFile: "src/text.ts",
    sourceFiles: ["src/text.vue", "src/text.ts", "src/text-types.ts"],
    behaviorContract: "src/text.behavior.md",
    tests: ["src/text.test.ts", "src/text-ssr.test.ts"],
    typeTests: ["src/text.types.test-d.ts"],
    rendererFixture: "TextConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Text",
      retainedSignature: 'data-vize-ui":(?:`text`|"text"|\'text\')',
      maximumJavaScriptGzipBytes: 900,
      maximumCssGzipBytes: 0,
    },
    aliases: ["body text", "typography text", "copy", "inline text", "truncated text"],
    upstreamCoverage: ["HTML phrasing content", "CSS text-overflow", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "kbd",
    title: "Kbd",
    packageSubpath: "./kbd",
    entryFile: "src/kbd.ts",
    sourceFiles: ["src/kbd.vue", "src/kbd.ts", "src/kbd-types.ts"],
    behaviorContract: "src/kbd.behavior.md",
    tests: ["src/kbd.test.ts", "src/kbd-ssr.test.ts"],
    typeTests: ["src/kbd.types.test-d.ts"],
    rendererFixture: "KbdConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Kbd",
      retainedSignature: 'data-vize-ui":(?:`kbd`|"kbd"|\'kbd\')',
      maximumJavaScriptGzipBytes: 850,
      maximumCssGzipBytes: 0,
    },
    aliases: ["keyboard input", "shortcut", "keycap", "keyboard sequence"],
    upstreamCoverage: ["HTML kbd element", "CSS inline layout", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
