import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  stableQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const fieldFamilyRoot = "src/families/form/field/";
const fieldWiringFamilyRoot = "src/families/form/field-wiring/";
const errorSummaryFamilyRoot = "src/families/form/error-summary/";
const formFamilyRoot = "src/families/form/form/";
const foundationFamilyRoot = "src/families/foundations/";
const commandFamilyRoot = `${foundationFamilyRoot}command/`;
const contextFamilyRoot = `${foundationFamilyRoot}context/`;
const controllableStateFamilyRoot = `${foundationFamilyRoot}controllable-state/`;

export const foundationFamilyCatalog = [
  {
    canonicalName: "collection",
    title: "Collection Registry",
    packageSubpath: "./collection",
    entryFile: "src/collection.ts",
    sourceFiles: [
      "src/collection.ts",
      "src/collection-registry.ts",
      "src/collection-keys.ts",
      "src/collection-observer.ts",
      "src/collection-order.ts",
      "src/collection-text.ts",
      "src/collection-types.ts",
    ],
    behaviorContract: "src/collection.behavior.md",
    tests: ["src/collection.test.ts", "src/collection-dom.test.ts"],
    typeTests: ["src/collection.types.test-d.ts"],
    qualityGates: stableQualityGates,
    bundleBudget: {
      exportName: "createCollectionRegistry",
      retainedSignature: "VIZE_UI_COLLECTION_DISPOSED",
      maximumJavaScriptGzipBytes: 3_150,
      maximumCssGzipBytes: 0,
    },
    aliases: ["collection registry", "item registry", "logical focus registry"],
    upstreamCoverage: ["React Aria Collection", "Ariakit Composite Store", "Zag collection"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "command",
    title: "Command Router",
    packageSubpath: "./command",
    entryFile: `${commandFamilyRoot}command.ts`,
    sourceFiles: [`${commandFamilyRoot}command.ts`, `${commandFamilyRoot}command-types.ts`],
    behaviorContract: `${commandFamilyRoot}command.behavior.md`,
    tests: [`${commandFamilyRoot}command.test.ts`, `${commandFamilyRoot}command-ssr.test.ts`],
    typeTests: [`${commandFamilyRoot}command.types.test-d.ts`],
    rendererFixture: "CommandConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createCommandRouter",
      retainedSignature: "VIZE_UI_COMMAND_DISPOSED",
      maximumJavaScriptGzipBytes: 1_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["command registry", "command routing", "action dispatcher"],
    upstreamCoverage: ["VS Code command registry", "Ariakit Combobox commands", "kbar actions"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "composite-navigation",
    title: "Composite Navigation",
    packageSubpath: "./composite-navigation",
    entryFile: "src/composite-navigation.ts",
    sourceFiles: [
      "src/composite-navigation.ts",
      "src/composite-navigation-dom.ts",
      "src/composite-navigation-internal.ts",
      "src/composite-navigation-types.ts",
    ],
    behaviorContract: "src/composite-navigation.behavior.md",
    tests: [
      "src/composite-navigation.test.ts",
      "src/composite-navigation-active-descendant.test.ts",
      "src/composite-navigation-lifecycle.test.ts",
      "src/composite-navigation-ssr.test.ts",
    ],
    typeTests: ["src/composite-navigation.types.test-d.ts"],
    rendererFixture: "CompositeNavigationConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createCompositeNavigation",
      retainedSignature: "VIZE_UI_COMPOSITE_NAVIGATION_DISPOSED",
      allowedRetainedFamilies: ["typeahead"],
      maximumJavaScriptGzipBytes: 3_900,
      maximumCssGzipBytes: 0,
    },
    aliases: ["roving focus", "active descendant", "composite widget navigation"],
    upstreamCoverage: ["WAI-ARIA composite widgets", "Reka UI Roving Focus", "Ariakit Composite"],
    dependencies: ["collection", "typeahead"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "context",
    title: "Typed Component Context",
    packageSubpath: "./context",
    entryFile: `${contextFamilyRoot}context.ts`,
    sourceFiles: [`${contextFamilyRoot}context.ts`],
    behaviorContract: `${contextFamilyRoot}context.behavior.md`,
    tests: [`${contextFamilyRoot}context.test.ts`],
    typeTests: [`${contextFamilyRoot}context.types.test-d.ts`],
    qualityGates: stableQualityGates,
    bundleBudget: {
      exportName: "createContext",
      retainedSignature: "VIZE_UI_CONTEXT_MISSING",
      maximumJavaScriptGzipBytes: 450,
      maximumCssGzipBytes: 0,
    },
    aliases: ["provide inject context", "compound component context"],
    upstreamCoverage: ["Reka UI createContext", "Radix context scope"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "controllable-state",
    title: "Controlled and Uncontrolled State",
    packageSubpath: "./controllable-state",
    entryFile: `${controllableStateFamilyRoot}controllable-state.ts`,
    sourceFiles: [`${controllableStateFamilyRoot}controllable-state.ts`],
    behaviorContract: `${controllableStateFamilyRoot}controllable-state.behavior.md`,
    tests: [`${controllableStateFamilyRoot}controllable-state.test.ts`],
    typeTests: [`${controllableStateFamilyRoot}controllable-state.types.test-d.ts`],
    qualityGates: stableQualityGates,
    bundleBudget: {
      exportName: "useControllableState",
      retainedSignature: "defaultValue[\\s\\S]*Object\\.is[\\s\\S]*defaultValue",
      maximumJavaScriptGzipBytes: 550,
      maximumCssGzipBytes: 0,
    },
    aliases: ["controllable state", "controlled state", "uncontrolled state"],
    upstreamCoverage: ["Radix useControllableState", "React Aria controlled state"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "error-summary",
    title: "Error Summary",
    packageSubpath: "./error-summary",
    entryFile: `${errorSummaryFamilyRoot}error-summary.ts`,
    sourceFiles: [
      `${errorSummaryFamilyRoot}error-summary.vue`,
      `${errorSummaryFamilyRoot}error-summary.ts`,
      `${errorSummaryFamilyRoot}error-summary-runtime.ts`,
      `${errorSummaryFamilyRoot}error-summary-types.ts`,
    ],
    behaviorContract: `${errorSummaryFamilyRoot}error-summary.behavior.md`,
    tests: [
      `${errorSummaryFamilyRoot}error-summary.test.ts`,
      `${errorSummaryFamilyRoot}error-summary-ssr.test.ts`,
    ],
    typeTests: [`${errorSummaryFamilyRoot}error-summary.types.test-d.ts`],
    rendererFixture: "families/form/error-summary/error-summary.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ErrorSummary",
      retainedSignature: "VIZE_UI_ERROR_SUMMARY_DISPOSED",
      maximumJavaScriptGzipBytes: 2_600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["form error summary", "validation summary", "invalid field list"],
    upstreamCoverage: ["WCAG 2.2 error identification", "focusable validation summaries"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "field",
    title: "Field",
    packageSubpath: "./field",
    entryFile: `${fieldFamilyRoot}field.ts`,
    sourceFiles: [
      `${fieldFamilyRoot}field.vue`,
      `${fieldFamilyRoot}field-description.vue`,
      `${fieldFamilyRoot}field-error-message.vue`,
      `${fieldFamilyRoot}field-label.vue`,
      `${fieldFamilyRoot}field.ts`,
      `${fieldFamilyRoot}field-context.ts`,
      `${fieldFamilyRoot}field-types.ts`,
    ],
    behaviorContract: `${fieldFamilyRoot}field.behavior.md`,
    tests: [`${fieldFamilyRoot}field.test.ts`, `${fieldFamilyRoot}field-ssr.test.ts`],
    typeTests: [`${fieldFamilyRoot}field.types.test-d.ts`],
    rendererFixture: "FieldConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Field",
      retainedSignature: "data-vize-ui[\\s\\S]{0,16}field[\\s\\S]{0,16}part[\\s\\S]{0,16}root",
      allowedRetainedFamilies: ["context", "field-wiring"],
      maximumJavaScriptGzipBytes: 2_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["form field", "field label", "field description", "field error message"],
    upstreamCoverage: ["React Aria Field", "Radix Form Field", "Reka UI Form"],
    dependencies: ["context", "field-wiring", "form"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "field-wiring",
    title: "Field Wiring",
    packageSubpath: "./field-wiring",
    entryFile: `${fieldWiringFamilyRoot}field-wiring.ts`,
    sourceFiles: [
      `${fieldWiringFamilyRoot}field-wiring.ts`,
      `${fieldWiringFamilyRoot}field-wiring-runtime.ts`,
      `${fieldWiringFamilyRoot}field-wiring-types.ts`,
    ],
    behaviorContract: `${fieldWiringFamilyRoot}field-wiring.behavior.md`,
    tests: [
      `${fieldWiringFamilyRoot}field-wiring.test.ts`,
      `${fieldWiringFamilyRoot}field-wiring-ssr.test.ts`,
    ],
    typeTests: [`${fieldWiringFamilyRoot}field-wiring.types.test-d.ts`],
    rendererFixture: "FieldWiringConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "useFieldWiring",
      retainedSignature: "VIZE_UI_FIELD_WIRING_SETUP",
      maximumJavaScriptGzipBytes: 1_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["accessible field", "label wiring", "described by", "error message wiring"],
    upstreamCoverage: ["React Aria useField", "WAI-ARIA description relations"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "form",
    title: "Standard Schema Forms",
    packageSubpath: "./form",
    entryFile: `${formFamilyRoot}form.ts`,
    sourceFiles: [
      `${formFamilyRoot}form.ts`,
      `${formFamilyRoot}form-runtime.ts`,
      `${formFamilyRoot}form-types.ts`,
    ],
    behaviorContract: `${formFamilyRoot}form.behavior.md`,
    tests: [`${formFamilyRoot}form.test.ts`],
    typeTests: [`${formFamilyRoot}form.types.test-d.ts`],
    qualityGates: stableQualityGates,
    bundleBudget: {
      exportName: "validateStandardSchema",
      retainedSignature: "VIZE_UI_FORM_SCHEMA_RESULT",
      maximumJavaScriptGzipBytes: 2_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["forms", "standard schema forms", "validation forms"],
    upstreamCoverage: ["Standard Schema V1", "TanStack Form", "Formwerk"],
    dependencies: ["error-summary", "field-wiring"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "theme",
    title: "Design Tokens",
    packageSubpath: "./theme",
    entryFile: "src/theme.ts",
    sourceFiles: [
      "src/theme.ts",
      "src/theme.css",
      "src/theme-preset-headless.css",
      "src/theme-preset-atelier.css",
      "src/theme-preset-midnight.css",
      "src/theme-preset-paper.css",
      "src/theme-preset-play.css",
      "src/theme-preset-signal.css",
      "src/theme-preset-high-contrast.css",
      "src/theme-constants.ts",
      "src/theme-scope.ts",
      "src/theme-tokens.ts",
      "src/theme-types.ts",
    ],
    behaviorContract: "src/theme.behavior.md",
    tests: [
      "src/theme.test.ts",
      "src/theme-scope.test.ts",
      "src/theme-stylesheet.test.ts",
      "src/theme-ssr.test.ts",
    ],
    typeTests: ["src/theme.types.test-d.ts", "src/theme-scope.types.test-d.ts"],
    rendererFixture: "ThemeConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "setThemeTokens",
      retainedSignature: "VIZE_UI_THEME_",
      maximumJavaScriptGzipBytes: 1_500,
      // Covers the packaged stylesheet: the token contract and presets share
      // dist/style.css with every other styled family.
      maximumCssGzipBytes: 7_600,
    },
    aliases: [
      "design tokens",
      "semantic tokens",
      "feedback tones",
      "cascade layers",
      "presets",
      "headless",
      "atelier",
      "midnight",
      "paper",
      "play",
      "signal",
      "high-contrast",
    ],
    upstreamCoverage: [
      "CSS cascade layers",
      "CSS custom properties",
      "semantic feedback tones",
      "light-dark() color scheme",
      "forced-colors adaptations",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
