import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";
import { dialogFamilyCatalog } from "./family-catalog-dialogs.ts";
import { popoverFamilyCatalog } from "./family-catalog-popover.ts";

const portalFamilyRoot = "src/families/overlays/portal/";
const positionerFamilyRoot = "src/families/overlays/positioner/";
const presenceFamilyRoot = "src/families/overlays/presence/";
const transitionFamilyRoot = "src/families/overlays/transition/";

export const overlayFamilyCatalog = [
  ...dialogFamilyCatalog,
  {
    canonicalName: "motion",
    title: "Motion Tokens",
    packageSubpath: "./motion",
    entryFile: "src/motion.ts",
    sourceFiles: [
      "src/motion.ts",
      "src/motion.css",
      "src/motion-adapters.ts",
      "src/motion-tokens.ts",
      "src/motion-types.ts",
    ],
    behaviorContract: "src/motion.behavior.md",
    tests: ["src/motion.test.ts", "src/motion-stylesheet.test.ts", "src/motion-ssr.test.ts"],
    typeTests: ["src/motion.types.test-d.ts"],
    rendererFixture: "MotionConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "startViewTransition",
      retainedSignature: "VIZE_UI_MOTION_",
      maximumJavaScriptGzipBytes: 1_500,
      // Covers the packaged stylesheet: motion tokens and recipes share
      // dist/style.css with every other styled family.
      maximumCssGzipBytes: 7_600,
    },
    aliases: ["motion tokens", "easing", "view transitions", "starting style", "reduced motion"],
    upstreamCoverage: [
      "View Transitions API",
      "CSS @starting-style",
      "prefers-reduced-motion",
      "scroll-driven animations",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "portal",
    title: "Portal",
    packageSubpath: "./portal",
    entryFile: `${portalFamilyRoot}portal.ts`,
    sourceFiles: [
      `${portalFamilyRoot}portal.vue`,
      `${portalFamilyRoot}portal.ts`,
      `${portalFamilyRoot}portal-stack.ts`,
    ],
    behaviorContract: `${portalFamilyRoot}portal.behavior.md`,
    tests: [
      `${portalFamilyRoot}portal.test.ts`,
      `${portalFamilyRoot}portal-stack.test.ts`,
      `${portalFamilyRoot}portal-ssr.test.ts`,
    ],
    typeTests: [`${portalFamilyRoot}portal.types.test-d.ts`],
    rendererFixture: "families/overlays/portal/portal.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Portal",
      retainedSignature: "data-vize-ui.+portal",
      maximumJavaScriptGzipBytes: 800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["teleport", "portalled content", "nested portal stack"],
    upstreamCoverage: ["HTML Teleport", "document portal"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "positioner",
    title: "Positioner",
    packageSubpath: "./positioner",
    entryFile: `${positionerFamilyRoot}positioner.ts`,
    sourceFiles: [
      `${positionerFamilyRoot}positioner.vue`,
      `${positionerFamilyRoot}positioner-arrow.vue`,
      `${positionerFamilyRoot}positioner.ts`,
      `${positionerFamilyRoot}positioner-context.ts`,
      `${positionerFamilyRoot}positioner-geometry.ts`,
      `${positionerFamilyRoot}positioner-runtime.ts`,
      `${positionerFamilyRoot}positioner-size.ts`,
      `${positionerFamilyRoot}positioner-types.ts`,
      `${positionerFamilyRoot}positioner-viewport.ts`,
    ],
    behaviorContract: `${positionerFamilyRoot}positioner.behavior.md`,
    tests: [
      `${positionerFamilyRoot}positioner.test.ts`,
      `${positionerFamilyRoot}positioner-geometry.test.ts`,
      `${positionerFamilyRoot}positioner-size.test.ts`,
      `${positionerFamilyRoot}positioner-viewport.test.ts`,
      `${positionerFamilyRoot}positioner-ssr.test.ts`,
    ],
    typeTests: [`${positionerFamilyRoot}positioner.types.test-d.ts`],
    rendererFixture: "families/overlays/positioner/positioner.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createPositioner",
      retainedSignature: "VIZE_UI_POSITIONER_DISPOSED",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["floating", "anchor position", "collision", "arrow", "size", "safe area"],
    upstreamCoverage: [
      "CSS absolute positioning",
      "visual viewport",
      "collision flipping",
      "safe-area environment insets",
    ],
    dependencies: ["context"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "presence",
    title: "Presence",
    packageSubpath: "./presence",
    entryFile: `${presenceFamilyRoot}presence.ts`,
    sourceFiles: [
      `${presenceFamilyRoot}presence.vue`,
      `${presenceFamilyRoot}presence.ts`,
      `${presenceFamilyRoot}presence-runtime.ts`,
      `${presenceFamilyRoot}presence-types.ts`,
    ],
    behaviorContract: `${presenceFamilyRoot}presence.behavior.md`,
    tests: [`${presenceFamilyRoot}presence.test.ts`, `${presenceFamilyRoot}presence-ssr.test.ts`],
    typeTests: [`${presenceFamilyRoot}presence.types.test-d.ts`],
    rendererFixture: "families/overlays/presence/presence.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createPresence",
      retainedSignature: "VIZE_UI_PRESENCE_DISPOSED",
      maximumJavaScriptGzipBytes: 2_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["enter exit", "mount animation", "presence"],
    upstreamCoverage: ["CSS animations", "CSS transitions", "View Transitions"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  ...popoverFamilyCatalog,
  {
    canonicalName: "tooltip",
    title: "Tooltip",
    packageSubpath: "./tooltip",
    entryFile: "src/families/overlays/tooltip/tooltip.ts",
    sourceFiles: [
      "src/families/overlays/tooltip/tooltip-content.vue",
      "src/families/overlays/tooltip/tooltip-context.ts",
      "src/families/overlays/tooltip/tooltip-root.vue",
      "src/families/overlays/tooltip/tooltip-trigger.vue",
      "src/families/overlays/tooltip/tooltip.ts",
      "src/families/overlays/tooltip/tooltip-types.ts",
    ],
    behaviorContract: "src/families/overlays/tooltip/tooltip.behavior.md",
    tests: [
      "src/families/overlays/tooltip/tooltip.test.ts",
      "src/families/overlays/tooltip/tooltip-ssr.test.ts",
    ],
    typeTests: ["src/families/overlays/tooltip/tooltip.types.test-d.ts"],
    rendererFixture: "TooltipConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "TooltipRoot",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}tooltip-root",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 2_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["hover tip", "description bubble", "help text", "floating hint"],
    upstreamCoverage: ["WAI-ARIA tooltip pattern", "Radix Tooltip", "Reka UI Tooltip"],
    dependencies: [
      "context",
      "controllable-state",
      "dismissable-layer",
      "hover",
      "id",
      "portal",
      "positioner",
      "presence",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "transition",
    title: "Transition",
    packageSubpath: "./transition",
    entryFile: `${transitionFamilyRoot}transition.ts`,
    sourceFiles: [
      `${transitionFamilyRoot}transition.vue`,
      `${transitionFamilyRoot}transition.ts`,
      `${transitionFamilyRoot}transition-runtime.ts`,
      `${transitionFamilyRoot}transition-types.ts`,
    ],
    behaviorContract: `${transitionFamilyRoot}transition.behavior.md`,
    tests: [
      `${transitionFamilyRoot}transition.test.ts`,
      `${transitionFamilyRoot}transition-ssr.test.ts`,
    ],
    typeTests: [`${transitionFamilyRoot}transition.types.test-d.ts`],
    rendererFixture: "families/overlays/transition/transition.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createTransition",
      retainedSignature: "VIZE_UI_TRANSITION_DISPOSED",
      allowedRetainedFamilies: ["presence"],
      maximumJavaScriptGzipBytes: 1_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["css transition", "enter leave", "motion complete"],
    upstreamCoverage: ["CSS transitions", "CSS animations", "computed motion duration"],
    dependencies: ["presence"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
