import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const nativeSelectFamilyRoot = "src/families/selection/native-select/";

export const selectionFamilyCatalog = [
  {
    canonicalName: "listbox",
    title: "Listbox",
    packageSubpath: "./listbox",
    entryFile: "src/listbox.ts",
    sourceFiles: [
      "src/listbox.vue",
      "src/listbox-item.vue",
      "src/listbox.ts",
      "src/listbox-context.ts",
      "src/listbox-types.ts",
      "src/listbox-value.ts",
    ],
    behaviorContract: "src/listbox.behavior.md",
    tests: ["src/listbox.test.ts", "src/listbox-ssr.test.ts"],
    typeTests: ["src/listbox.types.test-d.ts"],
    rendererFixture: "ListboxConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Listbox",
      retainedSignature: 'data-vize-ui":(?:`listbox`|"listbox"|\'listbox\')',
      allowedRetainedFamilies: [
        "collection",
        "composite-navigation",
        "context",
        "controllable-state",
        "typeahead",
      ],
      maximumJavaScriptGzipBytes: 9_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["listbox", "option list", "single select", "multi select"],
    upstreamCoverage: [
      "WAI-ARIA listbox pattern",
      "React Aria ListBox",
      "Ariakit Select",
      "Reka UI Listbox",
    ],
    dependencies: [
      "collection",
      "composite-navigation",
      "context",
      "controllable-state",
      "id",
      "typeahead",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "native-select",
    title: "Native Select",
    packageSubpath: "./native-select",
    entryFile: `${nativeSelectFamilyRoot}native-select.ts`,
    sourceFiles: [
      `${nativeSelectFamilyRoot}native-select.vue`,
      `${nativeSelectFamilyRoot}native-select.ts`,
      `${nativeSelectFamilyRoot}native-select-types.ts`,
      `${nativeSelectFamilyRoot}native-select-value.ts`,
    ],
    behaviorContract: `${nativeSelectFamilyRoot}native-select.behavior.md`,
    tests: [
      `${nativeSelectFamilyRoot}native-select.test.ts`,
      `${nativeSelectFamilyRoot}native-select-ssr.test.ts`,
    ],
    typeTests: [`${nativeSelectFamilyRoot}native-select.types.test-d.ts`],
    rendererFixture: "families/selection/native-select/native-select.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "NativeSelect",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}native-select",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 4_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["native select", "select", "form select", "html select"],
    upstreamCoverage: [
      "HTML select element",
      "React Aria Select native escape hatch",
      "Radix Select native form fallback",
      "Reka UI Select hidden native select interop",
    ],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
