import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const dialogFamilyCatalog = [
  {
    canonicalName: "dialog",
    title: "Dialog",
    packageSubpath: "./dialog",
    entryFile: "src/dialog.ts",
    sourceFiles: [
      "src/dialog-close.vue",
      "src/dialog-content.vue",
      "src/dialog-context.ts",
      "src/dialog-description.vue",
      "src/dialog-overlay.vue",
      "src/dialog-portal.vue",
      "src/dialog-root.vue",
      "src/dialog-title.vue",
      "src/dialog-trigger.vue",
      "src/dialog.ts",
      "src/dialog-types.ts",
    ],
    behaviorContract: "src/dialog.behavior.md",
    tests: ["src/dialog.test.ts", "src/dialog-ssr.test.ts"],
    typeTests: ["src/dialog.types.test-d.ts"],
    rendererFixture: "DialogConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "DialogRoot",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}dialog-root",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 2_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["modal", "alert dialog", "sheet foundation", "overlay dialog"],
    upstreamCoverage: ["WAI-ARIA dialog pattern", "Radix Dialog", "Reka UI Dialog"],
    dependencies: [
      "context",
      "controllable-state",
      "dismissable-layer",
      "focus-guards",
      "focus-scope",
      "id",
      "inert-outside",
      "portal",
      "scroll-lock",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "alert-dialog",
    title: "Alert Dialog",
    packageSubpath: "./alert-dialog",
    entryFile: "src/alert-dialog.ts",
    sourceFiles: [
      "src/alert-dialog-content.vue",
      "src/alert-dialog.ts",
      "src/alert-dialog-types.ts",
    ],
    behaviorContract: "src/alert-dialog.behavior.md",
    tests: ["src/alert-dialog.test.ts", "src/alert-dialog-ssr.test.ts"],
    typeTests: ["src/alert-dialog.types.test-d.ts"],
    rendererFixture: "AlertDialogConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "AlertDialogContent",
      retainedSignature: "alert-dialog-content",
      allowedRetainedFamilies: [
        "context",
        "dismissable-layer",
        "focus-guards",
        "focus-scope",
        "inert-outside",
        "scroll-lock",
      ],
      maximumJavaScriptGzipBytes: 12_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["confirm dialog", "destructive confirmation", "modal alertdialog"],
    upstreamCoverage: ["WAI-ARIA alertdialog pattern", "Radix Alert Dialog", "Reka UI AlertDialog"],
    dependencies: [
      "context",
      "dialog",
      "dismissable-layer",
      "focus-guards",
      "focus-scope",
      "inert-outside",
      "scroll-lock",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
