import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const navigationFamilyCatalog = [
  {
    canonicalName: "breadcrumb",
    title: "Breadcrumb",
    packageSubpath: "./breadcrumb",
    entryFile: "src/breadcrumb.ts",
    sourceFiles: [
      "src/breadcrumb.vue",
      "src/breadcrumb-item.vue",
      "src/breadcrumb-link.vue",
      "src/breadcrumb-list.vue",
      "src/breadcrumb-separator.vue",
      "src/breadcrumb.ts",
      "src/breadcrumb-types.ts",
    ],
    behaviorContract: "src/breadcrumb.behavior.md",
    tests: ["src/breadcrumb.test.ts", "src/breadcrumb-ssr.test.ts"],
    typeTests: ["src/breadcrumb.types.test-d.ts"],
    rendererFixture: "BreadcrumbConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Breadcrumb",
      retainedSignature: 'data-vize-ui":(?:`breadcrumb`|"breadcrumb"|\'breadcrumb\')',
      maximumJavaScriptGzipBytes: 1_725,
      maximumCssGzipBytes: 0,
    },
    aliases: ["breadcrumb navigation", "route breadcrumb", "path trail", "hierarchy trail"],
    upstreamCoverage: [
      "HTML nav landmark",
      "WAI-ARIA breadcrumb pattern",
      "React Aria Breadcrumbs",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "skip-link",
    title: "Skip Link",
    packageSubpath: "./skip-link",
    entryFile: "src/families/navigation/skip-link/skip-link.ts",
    sourceFiles: [
      "src/families/navigation/skip-link/skip-link.vue",
      "src/families/navigation/skip-link/skip-link.ts",
      "src/families/navigation/skip-link/skip-link-types.ts",
    ],
    behaviorContract: "src/families/navigation/skip-link/skip-link.behavior.md",
    tests: [
      "src/families/navigation/skip-link/skip-link.test.ts",
      "src/families/navigation/skip-link/skip-link-ssr.test.ts",
    ],
    typeTests: ["src/families/navigation/skip-link/skip-link.types.test-d.ts"],
    rendererFixture: "SkipLinkConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "SkipLink",
      retainedSignature: 'data-vize-ui":(?:`skip-link`|"skip-link"|\'skip-link\')',
      maximumJavaScriptGzipBytes: 1_850,
      maximumCssGzipBytes: 0,
    },
    aliases: ["skip link", "skip navigation", "skip to content", "bypass block"],
    upstreamCoverage: [
      "WCAG bypass blocks",
      "HTML same-document fragment navigation",
      "WebAIM skip navigation links",
    ],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "tabs",
    title: "Tabs",
    packageSubpath: "./tabs",
    entryFile: "src/tabs.ts",
    sourceFiles: [
      "src/tabs-content.vue",
      "src/tabs-list.vue",
      "src/tabs-root.vue",
      "src/tabs-trigger.vue",
      "src/tabs.ts",
      "src/tabs-context.ts",
      "src/tabs-types.ts",
      "src/tabs-value.ts",
    ],
    behaviorContract: "src/tabs.behavior.md",
    tests: ["src/tabs.test.ts", "src/tabs-ssr.test.ts"],
    typeTests: ["src/tabs.types.test-d.ts"],
    rendererFixture: "TabsConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "TabsRoot",
      retainedSignature: 'data-vize-ui":(?:`tabs-root`|"tabs-root"|\'tabs-root\')',
      allowedRetainedFamilies: [
        "collection",
        "composite-navigation",
        "context",
        "controllable-state",
        "typeahead",
      ],
      maximumJavaScriptGzipBytes: 8_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["tablist", "tab panels", "segmented navigation", "application sections"],
    upstreamCoverage: ["WAI-ARIA tabs pattern", "React Aria Tabs", "Radix Tabs", "Reka UI Tabs"],
    dependencies: [
      "collection",
      "composite-navigation",
      "context",
      "controllable-state",
      "typeahead",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "stepper",
    title: "Stepper",
    packageSubpath: "./stepper",
    entryFile: "src/stepper.ts",
    sourceFiles: [
      "src/stepper-content.vue",
      "src/stepper-item.vue",
      "src/stepper-list.vue",
      "src/stepper-root.vue",
      "src/stepper-trigger.vue",
      "src/stepper.ts",
      "src/stepper-context.ts",
      "src/stepper-navigation.ts",
      "src/stepper-types.ts",
      "src/stepper-value.ts",
    ],
    behaviorContract: "src/stepper.behavior.md",
    tests: ["src/stepper.test.ts", "src/stepper-expose.test.ts", "src/stepper-ssr.test.ts"],
    typeTests: ["src/stepper.types.test-d.ts"],
    rendererFixture: "StepperConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "StepperRoot",
      retainedSignature: 'data-vize-ui":(?:`stepper-root`|"stepper-root"|\'stepper-root\')',
      allowedRetainedFamilies: [
        "collection",
        "composite-navigation",
        "context",
        "controllable-state",
        "typeahead",
      ],
      maximumJavaScriptGzipBytes: 9_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["stepper", "wizard", "multi-step flow", "checkout steps"],
    upstreamCoverage: [
      "WAI-ARIA aria-current step",
      "MUI Stepper",
      "Vuetify Stepper",
      "Reka UI Stepper",
    ],
    dependencies: [
      "collection",
      "composite-navigation",
      "context",
      "controllable-state",
      "id",
      "typeahead",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "pagination",
    title: "Pagination",
    packageSubpath: "./pagination",
    entryFile: "src/pagination.ts",
    sourceFiles: [
      "src/pagination.vue",
      "src/pagination-list.vue",
      "src/pagination-item.vue",
      "src/pagination-page.vue",
      "src/pagination-previous.vue",
      "src/pagination-next.vue",
      "src/pagination-ellipsis.vue",
      "src/pagination.ts",
      "src/pagination-context.ts",
      "src/pagination-range.ts",
      "src/pagination-types.ts",
    ],
    behaviorContract: "src/pagination.behavior.md",
    tests: ["src/pagination.test.ts", "src/pagination-edge.test.ts", "src/pagination-ssr.test.ts"],
    typeTests: ["src/pagination.types.test-d.ts"],
    rendererFixture: "PaginationConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Pagination",
      retainedSignature: 'data-vize-ui":(?:`pagination`|"pagination"|\'pagination\')',
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 2_750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["pagination", "pager", "page navigation", "page controls"],
    upstreamCoverage: [
      "HTML nav landmark",
      "WAI-ARIA aria-current page",
      "MUI Pagination",
      "Vuetify Pagination",
      "Reka UI Pagination",
    ],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
