import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const interactionFamilyCatalog = [
  {
    canonicalName: "long-press",
    title: "Long Press Interaction",
    packageSubpath: "./long-press",
    entryFile: "src/long-press.ts",
    sourceFiles: ["src/long-press.ts", "src/long-press-internal.ts", "src/long-press-types.ts"],
    behaviorContract: "src/long-press.behavior.md",
    tests: [
      "src/long-press.test.ts",
      "src/long-press-hardening.test.ts",
      "src/long-press-legacy.test.ts",
      "src/long-press-ssr.test.ts",
    ],
    typeTests: ["src/long-press.types.test-d.ts"],
    rendererFixture: "LongPressConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createLongPress",
      retainedSignature: "VIZE_UI_LONG_PRESS_DISPOSED",
      allowedRetainedFamilies: ["press"],
      maximumJavaScriptGzipBytes: 5_150,
      maximumCssGzipBytes: 0,
    },
    aliases: ["long press", "press and hold"],
    upstreamCoverage: ["React Aria useLongPress"],
    dependencies: ["press"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "measure",
    title: "Measurement Observers",
    packageSubpath: "./measure",
    entryFile: "src/measure.ts",
    sourceFiles: ["src/measure.ts", "src/measure-runtime.ts", "src/measure-types.ts"],
    behaviorContract: "src/measure.behavior.md",
    tests: ["src/measure.test.ts", "src/measure-ssr.test.ts"],
    typeTests: ["src/measure.types.test-d.ts"],
    rendererFixture: "MeasureConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSizeObserver",
      retainedSignature: "VIZE_UI_MEASURE_DISPOSED",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["resize observer", "intersection observer", "element size", "visibility"],
    upstreamCoverage: ["ResizeObserver", "IntersectionObserver"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "move",
    title: "Move Interaction",
    packageSubpath: "./move",
    entryFile: "src/move.ts",
    sourceFiles: ["src/move.ts", "src/move-internal.ts", "src/move-types.ts"],
    behaviorContract: "src/move.behavior.md",
    tests: ["src/move.test.ts", "src/move-internal.test.ts", "src/move-ssr.test.ts"],
    typeTests: ["src/move.types.test-d.ts"],
    rendererFixture: "MoveConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createMove",
      retainedSignature: "VIZE_UI_MOVE_DISPOSED",
      maximumJavaScriptGzipBytes: 2_750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["move", "drag movement", "keyboard move"],
    upstreamCoverage: ["React Aria useMove", "Pointer Events pointer capture"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "press",
    title: "Press Interaction",
    packageSubpath: "./press",
    entryFile: "src/press.ts",
    sourceFiles: [
      "src/press.ts",
      "src/press-activation-memory.ts",
      "src/press-event.ts",
      "src/press-handlers.ts",
      "src/press-lifecycle.ts",
      "src/press-types.ts",
    ],
    behaviorContract: "src/press.behavior.md",
    tests: [
      "src/press.test.ts",
      "src/press-lifecycle.test.ts",
      "src/press-legacy.test.ts",
      "src/press-ssr.test.ts",
    ],
    typeTests: ["src/press.types.test-d.ts"],
    rendererFixture: "PressConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createPress",
      retainedSignature: "VIZE_UI_PRESS_DISPOSED",
      maximumJavaScriptGzipBytes: 3_550,
      maximumCssGzipBytes: 0,
    },
    aliases: ["press", "activation", "pointer press"],
    upstreamCoverage: ["React Aria usePress", "Pointer Events activation"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "primitive",
    title: "Polymorphic Primitive",
    packageSubpath: "./primitive",
    entryFile: "src/primitive.ts",
    sourceFiles: ["src/primitive-element.vue", "src/primitive.ts"],
    behaviorContract: "src/primitive.behavior.md",
    tests: ["src/primitive.test.ts"],
    rendererFixture: "primitive-element.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Primitive",
      retainedSignature: "data-vize-ui.+primitive",
      maximumJavaScriptGzipBytes: 500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["as child", "polymorphic primitive", "slot forwarding primitive"],
    upstreamCoverage: ["Reka UI Primitive", "Radix Slot", "shadcn/ui Slot"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "scroll-lock",
    title: "Scroll Lock",
    packageSubpath: "./scroll-lock",
    entryFile: "src/scroll-lock.ts",
    sourceFiles: [
      "src/scroll-lock.ts",
      "src/scroll-lock-dom.ts",
      "src/scroll-lock-internal.ts",
      "src/scroll-lock-stack.ts",
      "src/scroll-lock-types.ts",
    ],
    behaviorContract: "src/scroll-lock.behavior.md",
    tests: ["src/scroll-lock.test.ts", "src/scroll-lock-ssr.test.ts"],
    typeTests: ["src/scroll-lock.types.test-d.ts"],
    rendererFixture: "ScrollLockConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createScrollLock",
      retainedSignature: "VIZE_UI_SCROLL_LOCK_DISPOSED",
      maximumJavaScriptGzipBytes: 2_150,
      maximumCssGzipBytes: 0,
    },
    aliases: ["body scroll lock", "document scroll lock", "overlay scroll lock"],
    upstreamCoverage: ["React Aria usePreventScroll", "Radix RemoveScroll"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "shortcut",
    title: "Keyboard Shortcut Registry",
    packageSubpath: "./shortcut",
    entryFile: "src/shortcut.ts",
    sourceFiles: [
      "src/shortcut.ts",
      "src/shortcut-format.ts",
      "src/shortcut-parse.ts",
      "src/shortcut-registry.ts",
      "src/shortcut-types.ts",
    ],
    behaviorContract: "src/shortcut.behavior.md",
    tests: [
      "src/shortcut.test.ts",
      "src/shortcut-format.test.ts",
      "src/shortcut-lifecycle.test.ts",
      "src/shortcut-ssr.test.ts",
    ],
    typeTests: ["src/shortcut.types.test-d.ts"],
    rendererFixture: "ShortcutConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createShortcutRegistry",
      retainedSignature: "VIZE_UI_SHORTCUT_DISPOSED",
      maximumJavaScriptGzipBytes: 4_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["keyboard shortcuts", "hotkeys", "keybindings", "kbd formatting"],
    upstreamCoverage: ["VS Code keybindings", "React Aria useKeyboard", "GitHub Hotkey"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "sortable",
    title: "Sortable",
    packageSubpath: "./sortable",
    entryFile: "src/sortable.ts",
    sourceFiles: [
      "src/sortable.ts",
      "src/sortable-internal.ts",
      "src/sortable-keyboard.ts",
      "src/sortable-types.ts",
    ],
    behaviorContract: "src/sortable.behavior.md",
    tests: ["src/sortable.test.ts", "src/sortable-ssr.test.ts"],
    typeTests: ["src/sortable.types.test-d.ts"],
    rendererFixture: "SortableConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSortable",
      retainedSignature: "VIZE_UI_SORTABLE_DISPOSED",
      allowedRetainedFamilies: ["drag-and-drop"],
      maximumJavaScriptGzipBytes: 9_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["sortable list", "reorder", "sortable grid", "sortable tree"],
    upstreamCoverage: ["React Aria useDraggableCollection", "ARIA APG drag reordering"],
    dependencies: ["drag-and-drop"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "spatial-navigation",
    title: "Spatial Navigation",
    packageSubpath: "./spatial-navigation",
    entryFile: "src/spatial-navigation.ts",
    sourceFiles: [
      "src/spatial-navigation.ts",
      "src/spatial-navigation-internal.ts",
      "src/spatial-navigation-types.ts",
    ],
    behaviorContract: "src/spatial-navigation.behavior.md",
    tests: [
      "src/spatial-navigation.test.ts",
      "src/spatial-navigation-lifecycle.test.ts",
      "src/spatial-navigation-ssr.test.ts",
    ],
    typeTests: ["src/spatial-navigation.types.test-d.ts"],
    rendererFixture: "SpatialNavigationConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSpatialNavigation",
      retainedSignature: "VIZE_UI_SPATIAL_NAVIGATION_DISPOSED",
      maximumJavaScriptGzipBytes: 4_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["spatial navigation", "grid navigation", "geometry navigation"],
    upstreamCoverage: ["CSS Spatial Navigation", "ARIA grid navigation"],
    dependencies: ["collection"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "typeahead",
    title: "Collection Typeahead",
    packageSubpath: "./typeahead",
    entryFile: "src/typeahead.ts",
    sourceFiles: ["src/typeahead.ts", "src/typeahead-internal.ts", "src/typeahead-types.ts"],
    behaviorContract: "src/typeahead.behavior.md",
    tests: ["src/typeahead.test.ts", "src/typeahead-ssr.test.ts"],
    typeTests: ["src/typeahead.types.test-d.ts"],
    rendererFixture: "TypeaheadConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createTypeahead",
      retainedSignature: "VIZE_UI_TYPEAHEAD_DISPOSED",
      maximumJavaScriptGzipBytes: 1_375,
      maximumCssGzipBytes: 0,
    },
    aliases: ["typeahead", "collection search", "keyboard search"],
    upstreamCoverage: ["React Aria useTypeSelect", "Ariakit composite typeahead"],
    dependencies: ["collection"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "virtualizer",
    title: "Virtualizer",
    packageSubpath: "./virtualizer",
    entryFile: "src/virtualizer.ts",
    sourceFiles: [
      "src/virtualizer.ts",
      "src/virtualizer-grid.ts",
      "src/virtualizer-infinite.ts",
      "src/virtualizer-measure-cache.ts",
      "src/virtualizer-options.ts",
      "src/virtualizer-runtime.ts",
      "src/virtualizer-types.ts",
      "src/virtualizer-viewport.ts",
      "src/virtualizer-window.ts",
    ],
    behaviorContract: "src/virtualizer.behavior.md",
    tests: [
      "src/virtualizer.test.ts",
      "src/virtualizer-grid.test.ts",
      "src/virtualizer-infinite.test.ts",
      "src/virtualizer-measure-cache.test.ts",
      "src/virtualizer-ssr.test.ts",
    ],
    typeTests: ["src/virtualizer.types.test-d.ts"],
    rendererFixture: "VirtualizerConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createVirtualizer",
      retainedSignature: "VIZE_UI_VIRTUALIZER_DISPOSED",
      allowedRetainedFamilies: ["measure"],
      maximumJavaScriptGzipBytes: 4_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["virtual list", "virtual scroll", "windowing", "infinite scroll"],
    upstreamCoverage: ["windowed rendering", "scroll anchoring", "scroll restoration"],
    dependencies: ["measure"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "visually-hidden",
    title: "Visually Hidden",
    packageSubpath: "./visually-hidden",
    entryFile: "src/visually-hidden.ts",
    sourceFiles: ["src/visually-hidden.vue", "src/visually-hidden.ts"],
    behaviorContract: "src/visually-hidden.behavior.md",
    tests: ["src/visually-hidden.test.ts"],
    rendererFixture: "visually-hidden.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "VisuallyHidden",
      retainedSignature: "visually-hidden",
      maximumJavaScriptGzipBytes: 400,
      // Covers the shared packaged stylesheet and motion tokens shipped with styled families.
      maximumCssGzipBytes: 7_600,
    },
    aliases: ["screen reader only", "sr-only", "visually hidden"],
    upstreamCoverage: ["React Aria VisuallyHidden", "Radix VisuallyHidden"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
