import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";
import { avatarLayoutFamilyCatalog } from "./family-catalog-layout-avatar.ts";
import { iconLayoutFamilyCatalog } from "./family-catalog-layout-icon.ts";
import { listLayoutFamilyCatalog } from "./family-catalog-layout-list.ts";
import { scrollAreaLayoutFamilyCatalog } from "./family-catalog-layout-scroll-area.ts";
import { surfaceLayoutFamilyCatalog } from "./family-catalog-layout-surface.ts";

const aspectRatioFamilyRoot = "src/families/layout/aspect-ratio/";
const cardFamilyRoot = "src/families/layout/card/";
const clusterFamilyRoot = "src/families/layout/cluster/";
const containerFamilyRoot = "src/families/layout/container/";
const gridFamilyRoot = "src/families/layout/grid/";
const separatorFamilyRoot = "src/families/layout/separator/";
const spacerFamilyRoot = "src/families/layout/spacer/";
const stackFamilyRoot = "src/families/layout/stack/";

export const layoutFamilyCatalog = [
  {
    canonicalName: "aspect-ratio",
    title: "Aspect Ratio",
    packageSubpath: "./aspect-ratio",
    entryFile: `${aspectRatioFamilyRoot}aspect-ratio.ts`,
    sourceFiles: [
      `${aspectRatioFamilyRoot}aspect-ratio.vue`,
      `${aspectRatioFamilyRoot}aspect-ratio.ts`,
      `${aspectRatioFamilyRoot}aspect-ratio-runtime.ts`,
      `${aspectRatioFamilyRoot}aspect-ratio-types.ts`,
    ],
    behaviorContract: `${aspectRatioFamilyRoot}aspect-ratio.behavior.md`,
    tests: [
      `${aspectRatioFamilyRoot}aspect-ratio.test.ts`,
      `${aspectRatioFamilyRoot}aspect-ratio-ssr.test.ts`,
    ],
    typeTests: [`${aspectRatioFamilyRoot}aspect-ratio.types.test-d.ts`],
    rendererFixture: "AspectRatioConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "AspectRatio",
      retainedSignature: "data-vize-ui.+aspect-ratio",
      maximumJavaScriptGzipBytes: 1_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["aspect ratio", "intrinsic ratio", "responsive media box"],
    upstreamCoverage: ["CSS aspect-ratio", "Radix UI AspectRatio", "Reka UI AspectRatio"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  ...avatarLayoutFamilyCatalog,
  ...iconLayoutFamilyCatalog,
  {
    canonicalName: "card",
    title: "Card",
    packageSubpath: "./card",
    entryFile: `${cardFamilyRoot}card.ts`,
    sourceFiles: [
      `${cardFamilyRoot}card.vue`,
      `${cardFamilyRoot}card.ts`,
      `${cardFamilyRoot}card-types.ts`,
    ],
    behaviorContract: `${cardFamilyRoot}card.behavior.md`,
    tests: [`${cardFamilyRoot}card.test.ts`, `${cardFamilyRoot}card-ssr.test.ts`],
    typeTests: [`${cardFamilyRoot}card.types.test-d.ts`],
    rendererFixture: "CardConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Card",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}card",
      maximumJavaScriptGzipBytes: 625,
      maximumCssGzipBytes: 0,
    },
    aliases: ["surface card", "panel", "content surface", "section shell"],
    upstreamCoverage: ["HTML section", "HTML article", "shadcn/ui Card", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "cluster",
    title: "Cluster",
    packageSubpath: "./cluster",
    entryFile: `${clusterFamilyRoot}cluster.ts`,
    sourceFiles: [
      `${clusterFamilyRoot}cluster.vue`,
      `${clusterFamilyRoot}cluster.ts`,
      `${clusterFamilyRoot}cluster-runtime.ts`,
      `${clusterFamilyRoot}cluster-types.ts`,
    ],
    behaviorContract: `${clusterFamilyRoot}cluster.behavior.md`,
    tests: [`${clusterFamilyRoot}cluster.test.ts`, `${clusterFamilyRoot}cluster-ssr.test.ts`],
    typeTests: [`${clusterFamilyRoot}cluster.types.test-d.ts`],
    rendererFixture: "ClusterConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Cluster",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}cluster",
      maximumJavaScriptGzipBytes: 1_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout cluster", "wrapping row", "inline group", "action group"],
    upstreamCoverage: ["CSS flexbox", "CSS gap", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "container",
    title: "Container",
    packageSubpath: "./container",
    entryFile: `${containerFamilyRoot}container.ts`,
    sourceFiles: [
      `${containerFamilyRoot}container.vue`,
      `${containerFamilyRoot}container.ts`,
      `${containerFamilyRoot}container-runtime.ts`,
      `${containerFamilyRoot}container-types.ts`,
    ],
    behaviorContract: `${containerFamilyRoot}container.behavior.md`,
    tests: [
      `${containerFamilyRoot}container.test.ts`,
      `${containerFamilyRoot}container-ssr.test.ts`,
    ],
    typeTests: [`${containerFamilyRoot}container.types.test-d.ts`],
    rendererFixture: "ContainerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Container",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}container",
      maximumJavaScriptGzipBytes: 1_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout container", "page container", "max width wrapper", "centered region"],
    upstreamCoverage: ["CSS logical properties", "CSS max-inline-size", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "grid",
    title: "Grid",
    packageSubpath: "./grid",
    entryFile: `${gridFamilyRoot}grid.ts`,
    sourceFiles: [
      `${gridFamilyRoot}grid.vue`,
      `${gridFamilyRoot}grid.ts`,
      `${gridFamilyRoot}grid-runtime.ts`,
      `${gridFamilyRoot}grid-types.ts`,
    ],
    behaviorContract: `${gridFamilyRoot}grid.behavior.md`,
    tests: [`${gridFamilyRoot}grid.test.ts`, `${gridFamilyRoot}grid-ssr.test.ts`],
    typeTests: [`${gridFamilyRoot}grid.types.test-d.ts`],
    rendererFixture: "GridConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Grid",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}grid",
      maximumJavaScriptGzipBytes: 1_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout grid", "responsive grid", "two-dimensional layout", "card grid"],
    upstreamCoverage: ["CSS grid", "CSS gap", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  ...listLayoutFamilyCatalog,
  ...scrollAreaLayoutFamilyCatalog,
  {
    canonicalName: "separator",
    title: "Separator",
    packageSubpath: "./separator",
    entryFile: `${separatorFamilyRoot}separator.ts`,
    sourceFiles: [
      `${separatorFamilyRoot}separator.vue`,
      `${separatorFamilyRoot}separator.ts`,
      `${separatorFamilyRoot}separator-types.ts`,
    ],
    behaviorContract: `${separatorFamilyRoot}separator.behavior.md`,
    tests: [
      `${separatorFamilyRoot}separator.test.ts`,
      `${separatorFamilyRoot}separator-ssr.test.ts`,
    ],
    typeTests: [`${separatorFamilyRoot}separator.types.test-d.ts`],
    rendererFixture: "SeparatorConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Separator",
      retainedSignature: "data-vize-ui.+separator",
      maximumJavaScriptGzipBytes: 650,
      maximumCssGzipBytes: 0,
    },
    aliases: ["divider", "rule", "thematic break", "splitter boundary"],
    upstreamCoverage: ["HTML hr", "WAI-ARIA Separator", "Radix UI Separator", "Reka UI Separator"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "spacer",
    title: "Spacer",
    packageSubpath: "./spacer",
    entryFile: `${spacerFamilyRoot}spacer.ts`,
    sourceFiles: [
      `${spacerFamilyRoot}spacer.vue`,
      `${spacerFamilyRoot}spacer.ts`,
      `${spacerFamilyRoot}spacer-runtime.ts`,
      `${spacerFamilyRoot}spacer-types.ts`,
    ],
    behaviorContract: `${spacerFamilyRoot}spacer.behavior.md`,
    tests: [`${spacerFamilyRoot}spacer.test.ts`, `${spacerFamilyRoot}spacer-ssr.test.ts`],
    typeTests: [`${spacerFamilyRoot}spacer.types.test-d.ts`],
    rendererFixture: "SpacerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Spacer",
      retainedSignature: "data-vize-ui.+spacer",
      maximumJavaScriptGzipBytes: 950,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout spacer", "gap spacer", "white space", "svg spacer"],
    upstreamCoverage: [
      "CSS logical properties",
      "HTML span",
      "SVG element host",
      "Reka UI Primitive",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "stack",
    title: "Stack",
    packageSubpath: "./stack",
    entryFile: `${stackFamilyRoot}stack.ts`,
    sourceFiles: [
      `${stackFamilyRoot}stack.vue`,
      `${stackFamilyRoot}stack.ts`,
      `${stackFamilyRoot}stack-runtime.ts`,
      `${stackFamilyRoot}stack-types.ts`,
    ],
    behaviorContract: `${stackFamilyRoot}stack.behavior.md`,
    tests: [`${stackFamilyRoot}stack.test.ts`, `${stackFamilyRoot}stack-ssr.test.ts`],
    typeTests: [`${stackFamilyRoot}stack.types.test-d.ts`],
    rendererFixture: "StackConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Stack",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}stack",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["layout stack", "vertical stack", "logical stack", "single-axis layout"],
    upstreamCoverage: ["CSS flexbox", "CSS logical properties", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  ...surfaceLayoutFamilyCatalog,
] as const satisfies readonly UiFamilyCatalogEntry[];
