import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const feedbackFamilyCatalog = [
  {
    canonicalName: "alert",
    title: "Alert",
    packageSubpath: "./alert",
    entryFile: "src/alert.ts",
    sourceFiles: ["src/alert.vue", "src/alert.ts", "src/alert-types.ts"],
    behaviorContract: "src/alert.behavior.md",
    tests: ["src/alert.test.ts"],
    typeTests: ["src/alert.types.test-d.ts"],
    rendererFixture: "alert.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Alert",
      retainedSignature: 'data-vize-ui":(?:`alert`|"alert"|\'alert\')',
      maximumJavaScriptGzipBytes: 750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["inline alert", "status alert", "callout primitive"],
    upstreamCoverage: ["WAI-ARIA alert role", "WAI-ARIA status role", "shadcn/ui Alert"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "badge",
    title: "Badge",
    packageSubpath: "./badge",
    entryFile: "src/badge.ts",
    sourceFiles: ["src/badge.vue", "src/badge.ts", "src/badge-types.ts"],
    behaviorContract: "src/badge.behavior.md",
    tests: ["src/badge.test.ts", "src/badge-ssr.test.ts"],
    typeTests: ["src/badge.types.test-d.ts"],
    rendererFixture: "BadgeConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Badge",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}badge",
      maximumJavaScriptGzipBytes: 600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["tag", "chip", "status badge", "count badge", "unread indicator"],
    upstreamCoverage: ["HTML span", "shadcn/ui Badge", "Radix Themes Badge", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "empty-state",
    title: "EmptyState",
    packageSubpath: "./empty-state",
    entryFile: "src/empty-state.ts",
    sourceFiles: ["src/empty-state.vue", "src/empty-state.ts", "src/empty-state-types.ts"],
    behaviorContract: "src/empty-state.behavior.md",
    tests: ["src/empty-state.test.ts", "src/empty-state-ssr.test.ts"],
    typeTests: ["src/empty-state.types.test-d.ts"],
    rendererFixture: "EmptyStateConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "EmptyState",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}empty-state",
      maximumJavaScriptGzipBytes: 600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["empty content", "no results", "offline state", "retry prompt", "zero state"],
    upstreamCoverage: ["HTML section element", "consumer-owned ARIA status pattern"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "meter",
    title: "Meter",
    packageSubpath: "./meter",
    entryFile: "src/meter.ts",
    sourceFiles: ["src/meter.vue", "src/meter.ts", "src/meter-state.ts", "src/meter-types.ts"],
    behaviorContract: "src/meter.behavior.md",
    tests: ["src/meter.test.ts", "src/meter-ssr.test.ts"],
    typeTests: ["src/meter.types.test-d.ts"],
    rendererFixture: "MeterConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Meter",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}meter",
      maximumJavaScriptGzipBytes: 2_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["gauge", "usage meter", "storage meter", "threshold meter"],
    upstreamCoverage: ["HTML meter element", "WAI-ARIA meter role", "React Aria Meter"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "skeleton",
    title: "Skeleton",
    packageSubpath: "./skeleton",
    entryFile: "src/skeleton.ts",
    sourceFiles: ["src/skeleton.vue", "src/skeleton.ts", "src/skeleton-types.ts"],
    behaviorContract: "src/skeleton.behavior.md",
    tests: ["src/skeleton.test.ts", "src/skeleton-ssr.test.ts"],
    typeTests: ["src/skeleton.types.test-d.ts"],
    rendererFixture: "SkeletonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Skeleton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}skeleton",
      maximumJavaScriptGzipBytes: 1_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["placeholder", "loading skeleton", "deferred content", "suspense fallback"],
    upstreamCoverage: ["WAI-ARIA status role", "shadcn/ui Skeleton", "React Aria ProgressBar"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
