import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const feedbackFamilyCatalog = [
  {
    canonicalName: "alert",
    title: "Alert",
    packageSubpath: "./alert",
    entryFile: "src/alert.ts",
    sourceFiles: ["src/alert.vue", "src/alert.ts", "src/alert-types.ts"],
    behaviorContract: "src/alert.behavior.md",
    tests: ["src/alert.test.ts"],
    typeTests: ["src/alert.types.test-d.ts"],
    rendererFixture: "alert.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Alert",
      retainedSignature: "data-vize-ui[\\s\\S]{0,16}alert",
      maximumJavaScriptGzipBytes: 750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["inline alert", "status alert", "callout primitive"],
    upstreamCoverage: ["WAI-ARIA alert role", "WAI-ARIA status role", "shadcn/ui Alert"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "skeleton",
    title: "Skeleton",
    packageSubpath: "./skeleton",
    entryFile: "src/skeleton.ts",
    sourceFiles: ["src/skeleton.vue", "src/skeleton.ts", "src/skeleton-types.ts"],
    behaviorContract: "src/skeleton.behavior.md",
    tests: ["src/skeleton.test.ts", "src/skeleton-ssr.test.ts"],
    typeTests: ["src/skeleton.types.test-d.ts"],
    rendererFixture: "SkeletonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Skeleton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}skeleton",
      maximumJavaScriptGzipBytes: 1_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["placeholder", "loading skeleton", "deferred content", "suspense fallback"],
    upstreamCoverage: ["WAI-ARIA status role", "shadcn/ui Skeleton", "React Aria ProgressBar"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
