import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const overlayFamilyCatalog = [
  {
    canonicalName: "announcer",
    title: "Announcer",
    packageSubpath: "./announcer",
    entryFile: "src/announcer.ts",
    sourceFiles: [
      "src/announcer-provider.vue",
      "src/announcer.ts",
      "src/announcer-busy.ts",
      "src/announcer-runtime.ts",
      "src/announcer-types.ts",
    ],
    behaviorContract: "src/announcer.behavior.md",
    tests: ["src/announcer.test.ts", "src/announcer-ssr.test.ts"],
    typeTests: ["src/announcer.types.test-d.ts"],
    rendererFixture: "announcer-provider.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "AnnouncerProvider",
      retainedSignature: "VIZE_UI_ANNOUNCER_DISPOSED",
      allowedRetainedFamilies: ["context", "live-region"],
      maximumJavaScriptGzipBytes: 2_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["announcement queue", "status announcer", "busy announcements"],
    upstreamCoverage: ["ARIA live regions", "coalesced announcement queues"],
    dependencies: ["context", "live-region"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "live-region",
    title: "Live Region",
    packageSubpath: "./live-region",
    entryFile: "src/live-region.ts",
    sourceFiles: [
      "src/live-region.vue",
      "src/live-region.ts",
      "src/live-region-runtime.ts",
      "src/live-region-types.ts",
    ],
    behaviorContract: "src/live-region.behavior.md",
    tests: ["src/live-region.test.ts", "src/live-region-ssr.test.ts"],
    typeTests: ["src/live-region.types.test-d.ts"],
    rendererFixture: "live-region.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createLiveRegion",
      retainedSignature: "VIZE_UI_LIVE_REGION_DISPOSED",
      maximumJavaScriptGzipBytes: 1_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["announcer", "aria live", "status region"],
    upstreamCoverage: ["ARIA live regions", "WAI-ARIA status and alert"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "locale",
    title: "Locale and Direction",
    packageSubpath: "./locale",
    entryFile: "src/locale.ts",
    sourceFiles: ["src/locale-provider.vue", "src/locale.ts", "src/locale-runtime.ts"],
    behaviorContract: "src/locale.behavior.md",
    tests: ["src/locale.test.ts", "src/locale-ssr.test.ts"],
    typeTests: ["src/locale.types.test-d.ts"],
    rendererFixture: "locale-provider.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "LocaleProvider",
      retainedSignature: "data-vize-ui.+locale",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 1_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["direction", "rtl", "writing mode", "i18n provider"],
    upstreamCoverage: ["HTML dir", "HTML lang", "Intl.Locale"],
    dependencies: ["context"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "motion",
    title: "Motion Tokens",
    packageSubpath: "./motion",
    entryFile: "src/motion.ts",
    sourceFiles: [
      "src/motion.ts",
      "src/motion.css",
      "src/motion-adapters.ts",
      "src/motion-tokens.ts",
      "src/motion-types.ts",
    ],
    behaviorContract: "src/motion.behavior.md",
    tests: ["src/motion.test.ts", "src/motion-stylesheet.test.ts", "src/motion-ssr.test.ts"],
    typeTests: ["src/motion.types.test-d.ts"],
    rendererFixture: "MotionConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "startViewTransition",
      retainedSignature: "VIZE_UI_MOTION_",
      maximumJavaScriptGzipBytes: 1_500,
      // Covers the packaged stylesheet: motion tokens and recipes share
      // dist/style.css with every other styled family.
      maximumCssGzipBytes: 3_500,
    },
    aliases: ["motion tokens", "easing", "view transitions", "starting style", "reduced motion"],
    upstreamCoverage: [
      "View Transitions API",
      "CSS @starting-style",
      "prefers-reduced-motion",
      "scroll-driven animations",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "pointer-grace",
    title: "Pointer Grace",
    packageSubpath: "./pointer-grace",
    entryFile: "src/pointer-grace.ts",
    sourceFiles: [
      "src/pointer-grace.ts",
      "src/pointer-grace-runtime.ts",
      "src/pointer-grace-types.ts",
    ],
    behaviorContract: "src/pointer-grace.behavior.md",
    tests: ["src/pointer-grace.test.ts", "src/pointer-grace-ssr.test.ts"],
    typeTests: ["src/pointer-grace.types.test-d.ts"],
    rendererFixture: "PointerGraceConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createPointerGrace",
      retainedSignature: "VIZE_UI_POINTER_GRACE_DISPOSED",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["safe triangle", "hover bridge", "pointer grace area"],
    upstreamCoverage: ["pointer safe triangle", "hover intent polygon"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "portal",
    title: "Portal",
    packageSubpath: "./portal",
    entryFile: "src/portal.ts",
    sourceFiles: ["src/portal.vue", "src/portal.ts", "src/portal-stack.ts"],
    behaviorContract: "src/portal.behavior.md",
    tests: ["src/portal.test.ts", "src/portal-stack.test.ts", "src/portal-ssr.test.ts"],
    typeTests: ["src/portal.types.test-d.ts"],
    rendererFixture: "portal.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Portal",
      retainedSignature: "data-vize-ui.+portal",
      maximumJavaScriptGzipBytes: 800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["teleport", "portalled content", "nested portal stack"],
    upstreamCoverage: ["HTML Teleport", "document portal"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "positioner",
    title: "Positioner",
    packageSubpath: "./positioner",
    entryFile: "src/positioner.ts",
    sourceFiles: [
      "src/positioner.vue",
      "src/positioner-arrow.vue",
      "src/positioner.ts",
      "src/positioner-context.ts",
      "src/positioner-geometry.ts",
      "src/positioner-runtime.ts",
      "src/positioner-size.ts",
      "src/positioner-types.ts",
      "src/positioner-viewport.ts",
    ],
    behaviorContract: "src/positioner.behavior.md",
    tests: [
      "src/positioner.test.ts",
      "src/positioner-geometry.test.ts",
      "src/positioner-size.test.ts",
      "src/positioner-viewport.test.ts",
      "src/positioner-ssr.test.ts",
    ],
    typeTests: ["src/positioner.types.test-d.ts"],
    rendererFixture: "positioner.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createPositioner",
      retainedSignature: "VIZE_UI_POSITIONER_DISPOSED",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["floating", "anchor position", "collision", "arrow", "size", "safe area"],
    upstreamCoverage: [
      "CSS absolute positioning",
      "visual viewport",
      "collision flipping",
      "safe-area environment insets",
    ],
    dependencies: ["context"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "presence",
    title: "Presence",
    packageSubpath: "./presence",
    entryFile: "src/presence.ts",
    sourceFiles: [
      "src/presence.vue",
      "src/presence.ts",
      "src/presence-runtime.ts",
      "src/presence-types.ts",
    ],
    behaviorContract: "src/presence.behavior.md",
    tests: ["src/presence.test.ts", "src/presence-ssr.test.ts"],
    typeTests: ["src/presence.types.test-d.ts"],
    rendererFixture: "presence.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createPresence",
      retainedSignature: "VIZE_UI_PRESENCE_DISPOSED",
      maximumJavaScriptGzipBytes: 2_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["enter exit", "mount animation", "presence"],
    upstreamCoverage: ["CSS animations", "CSS transitions", "View Transitions"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "transition",
    title: "Transition",
    packageSubpath: "./transition",
    entryFile: "src/transition.ts",
    sourceFiles: [
      "src/transition.vue",
      "src/transition.ts",
      "src/transition-runtime.ts",
      "src/transition-types.ts",
    ],
    behaviorContract: "src/transition.behavior.md",
    tests: ["src/transition.test.ts", "src/transition-ssr.test.ts"],
    typeTests: ["src/transition.types.test-d.ts"],
    rendererFixture: "transition.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createTransition",
      retainedSignature: "VIZE_UI_TRANSITION_DISPOSED",
      allowedRetainedFamilies: ["presence"],
      maximumJavaScriptGzipBytes: 1_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["css transition", "enter leave", "motion complete"],
    upstreamCoverage: ["CSS transitions", "CSS animations", "computed motion duration"],
    dependencies: ["presence"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
