import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

export const basicFamilyCatalog = [
  {
    canonicalName: "button",
    title: "Button",
    packageSubpath: "./button",
    entryFile: "src/button.ts",
    sourceFiles: ["src/action-button.vue", "src/button.ts", "src/button-keyboard.ts"],
    behaviorContract: "src/button.behavior.md",
    tests: ["src/button.test.ts"],
    rendererFixture: "action-button.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Button",
      retainedSignature: "aria-busy",
      maximumJavaScriptGzipBytes: 1_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["action-button", "button primitive"],
    upstreamCoverage: ["shadcn/ui Button", "Reka UI Primitive", "React Aria Button"],
    dependencies: ["primitive", "press"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "link",
    title: "Link",
    packageSubpath: "./link",
    entryFile: "src/link.ts",
    sourceFiles: ["src/link-anchor.vue", "src/link.ts", "src/link-types.ts"],
    behaviorContract: "src/link.behavior.md",
    tests: ["src/link.test.ts"],
    typeTests: ["src/link.types.test-d.ts"],
    rendererFixture: "link-anchor.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Link",
      retainedSignature: "aria-current",
      maximumJavaScriptGzipBytes: 1_650,
      maximumCssGzipBytes: 0,
    },
    aliases: ["anchor", "navigation link", "disabled link"],
    upstreamCoverage: ["HTML anchor", "React Aria Link", "Reka UI Primitive"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "toggle",
    title: "Toggle",
    packageSubpath: "./toggle",
    entryFile: "src/toggle.ts",
    sourceFiles: ["src/toggle-button.vue", "src/toggle.ts", "src/toggle-types.ts"],
    behaviorContract: "src/toggle.behavior.md",
    tests: ["src/toggle.test.ts"],
    typeTests: ["src/toggle.types.test-d.ts"],
    rendererFixture: "toggle-button.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Toggle",
      retainedSignature: "aria-pressed",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 1_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["toggle button", "pressed button", "on off button"],
    upstreamCoverage: ["WAI-ARIA toggle button", "React Aria ToggleButton", "Reka UI Toggle"],
    dependencies: ["controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "input",
    title: "Input",
    packageSubpath: "./input",
    entryFile: "src/input.ts",
    sourceFiles: ["src/text-input.vue", "src/input.ts", "src/input-types.ts"],
    behaviorContract: "src/input.behavior.md",
    tests: ["src/input.test.ts"],
    typeTests: ["src/input.types.test-d.ts"],
    rendererFixture: "text-input.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Input",
      retainedSignature: 'data-vize-ui":(?:`input`|"input"|\'input\')',
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 2_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["text input", "field input", "textbox"],
    upstreamCoverage: ["HTML input", "React Aria TextField", "Reka UI Primitive"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "search-field",
    title: "Search Field",
    packageSubpath: "./search-field",
    entryFile: "src/search-field.ts",
    sourceFiles: ["src/search-field.vue", "src/search-field.ts", "src/search-field-types.ts"],
    behaviorContract: "src/search-field.behavior.md",
    tests: ["src/search-field.test.ts"],
    typeTests: ["src/search-field.types.test-d.ts"],
    rendererFixture: "search-field.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "SearchField",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}search-field",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 3_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["search box", "search input", "query field"],
    upstreamCoverage: ["HTML search input", "React Aria SearchField", "Reka UI Primitive"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "textarea",
    title: "Textarea",
    packageSubpath: "./textarea",
    entryFile: "src/textarea.ts",
    sourceFiles: ["src/textarea-control.vue", "src/textarea.ts", "src/textarea-types.ts"],
    behaviorContract: "src/textarea.behavior.md",
    tests: ["src/textarea.test.ts"],
    typeTests: ["src/textarea.types.test-d.ts"],
    rendererFixture: "textarea-control.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Textarea",
      retainedSignature: "data-vize-ui.+textarea",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 2_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["text area", "multiline input", "textarea field"],
    upstreamCoverage: ["HTML textarea", "React Aria TextField", "Reka UI Primitive"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "checkbox",
    title: "Checkbox",
    packageSubpath: "./checkbox",
    entryFile: "src/checkbox.ts",
    sourceFiles: ["src/checkbox-control.vue", "src/checkbox.ts", "src/checkbox-state.ts"],
    behaviorContract: "src/checkbox.behavior.md",
    tests: ["src/checkbox.test.ts"],
    rendererFixture: "checkbox-control.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Checkbox",
      retainedSignature: "aria-checked",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 1_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["checkbox control", "mixed checkbox"],
    upstreamCoverage: ["shadcn/ui Checkbox", "Reka UI Checkbox", "React Aria Checkbox"],
    dependencies: ["controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
