import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const buttonFamilyRoot = "src/families/actions/button/";

export const actionFamilyCatalog = [
  {
    canonicalName: "button",
    title: "Button",
    packageSubpath: "./button",
    entryFile: `${buttonFamilyRoot}button.ts`,
    sourceFiles: [
      `${buttonFamilyRoot}button.vue`,
      `${buttonFamilyRoot}button.ts`,
      `${buttonFamilyRoot}button-keyboard.ts`,
    ],
    behaviorContract: `${buttonFamilyRoot}button.behavior.md`,
    tests: [`${buttonFamilyRoot}button.test.ts`],
    rendererFixture: "families/actions/button/button.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Button",
      retainedSignature: 'data-vize-ui":(?:`button`|"button"|\'button\')',
      maximumJavaScriptGzipBytes: 1_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["action-button", "button primitive"],
    upstreamCoverage: ["shadcn/ui Button", "Reka UI Primitive", "React Aria Button"],
    dependencies: ["primitive", "press"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "button-group",
    title: "Button Group",
    packageSubpath: "./button-group",
    entryFile: "src/families/actions/button-group/button-group.ts",
    sourceFiles: [
      "src/families/actions/button-group/button-group.vue",
      "src/families/actions/button-group/button-group-item.vue",
      "src/families/actions/button-group/button-group.ts",
      "src/families/actions/button-group/button-group-context.ts",
      "src/families/actions/button-group/button-group-types.ts",
    ],
    behaviorContract: "src/families/actions/button-group/button-group.behavior.md",
    tests: [
      "src/families/actions/button-group/button-group.test.ts",
      "src/families/actions/button-group/button-group-ssr.test.ts",
    ],
    typeTests: ["src/families/actions/button-group/button-group.types.test-d.ts"],
    rendererFixture: "ButtonGroupConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ButtonGroup",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}button-group",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 1_900,
      maximumCssGzipBytes: 0,
    },
    aliases: ["button group", "button bar", "action group", "toolbar"],
    upstreamCoverage: ["WAI-ARIA Toolbar", "React Aria Toolbar", "shadcn/ui Button"],
    dependencies: ["context"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "copy-button",
    title: "Copy Button",
    packageSubpath: "./copy-button",
    entryFile: "src/families/actions/copy-button/copy-button.ts",
    sourceFiles: [
      "src/families/actions/copy-button/copy-button.vue",
      "src/families/actions/copy-button/copy-button.ts",
      "src/families/actions/copy-button/copy-button-types.ts",
    ],
    behaviorContract: "src/families/actions/copy-button/copy-button.behavior.md",
    tests: [
      "src/families/actions/copy-button/copy-button.test.ts",
      "src/families/actions/copy-button/copy-button-ssr.test.ts",
    ],
    typeTests: ["src/families/actions/copy-button/copy-button.types.test-d.ts"],
    rendererFixture: "CopyButtonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "CopyButton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}copy-button",
      maximumJavaScriptGzipBytes: 1_650,
      maximumCssGzipBytes: 0,
    },
    aliases: ["copy button", "clipboard button", "copy to clipboard", "clipboard action"],
    upstreamCoverage: ["shadcn/ui Copy Button", "React Aria Button", "WAI-ARIA Button"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "fullscreen-button",
    title: "Fullscreen Button",
    packageSubpath: "./fullscreen-button",
    entryFile: "src/families/actions/fullscreen-button/fullscreen-button.ts",
    sourceFiles: [
      "src/families/actions/fullscreen-button/fullscreen-button.vue",
      "src/families/actions/fullscreen-button/fullscreen-button.ts",
      "src/families/actions/fullscreen-button/fullscreen-button-types.ts",
    ],
    behaviorContract: "src/families/actions/fullscreen-button/fullscreen-button.behavior.md",
    tests: [
      "src/families/actions/fullscreen-button/fullscreen-button.test.ts",
      "src/families/actions/fullscreen-button/fullscreen-button-slot-expose.test.ts",
      "src/families/actions/fullscreen-button/fullscreen-button-ssr.test.ts",
    ],
    typeTests: ["src/families/actions/fullscreen-button/fullscreen-button.types.test-d.ts"],
    rendererFixture: "FullscreenButtonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "FullscreenButton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}fullscreen-button",
      allowedRetainedFamilies: ["toggle"],
      maximumJavaScriptGzipBytes: 2_750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["fullscreen button", "fullscreen toggle", "fullscreen action", "screen control"],
    upstreamCoverage: ["Fullscreen API", "React Aria Button", "WAI-ARIA Button"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "print-button",
    title: "Print Button",
    packageSubpath: "./print-button",
    entryFile: "src/families/actions/print-button/print-button.ts",
    sourceFiles: [
      "src/families/actions/print-button/print-button.vue",
      "src/families/actions/print-button/print-button.ts",
      "src/families/actions/print-button/print-button-types.ts",
    ],
    behaviorContract: "src/families/actions/print-button/print-button.behavior.md",
    tests: [
      "src/families/actions/print-button/print-button.test.ts",
      "src/families/actions/print-button/print-button-ssr.test.ts",
    ],
    typeTests: ["src/families/actions/print-button/print-button.types.test-d.ts"],
    rendererFixture: "PrintButtonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "PrintButton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}print-button",
      maximumJavaScriptGzipBytes: 1_650,
      maximumCssGzipBytes: 0,
    },
    aliases: ["print button", "browser print", "print action", "print control"],
    upstreamCoverage: ["HTML button", "React Aria Button", "WAI-ARIA Button"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "share-button",
    title: "Share Button",
    packageSubpath: "./share-button",
    entryFile: "src/families/actions/share-button/share-button.ts",
    sourceFiles: [
      "src/families/actions/share-button/share-button.vue",
      "src/families/actions/share-button/share-button.ts",
      "src/families/actions/share-button/share-button-types.ts",
    ],
    behaviorContract: "src/families/actions/share-button/share-button.behavior.md",
    tests: [
      "src/families/actions/share-button/share-button.test.ts",
      "src/families/actions/share-button/share-button-slot-expose.test.ts",
      "src/families/actions/share-button/share-button-ssr.test.ts",
    ],
    typeTests: ["src/families/actions/share-button/share-button.types.test-d.ts"],
    rendererFixture: "ShareButtonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ShareButton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}share-button",
      maximumJavaScriptGzipBytes: 1_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["share button", "web share button", "share action", "share control"],
    upstreamCoverage: ["Web Share API", "React Aria Button", "WAI-ARIA Button"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "toolbar",
    title: "Toolbar",
    packageSubpath: "./toolbar",
    entryFile: "src/families/actions/toolbar/toolbar.ts",
    sourceFiles: [
      "src/families/actions/toolbar/toolbar.vue",
      "src/families/actions/toolbar/toolbar-item.vue",
      "src/families/actions/toolbar/toolbar.ts",
      "src/families/actions/toolbar/toolbar-context.ts",
      "src/families/actions/toolbar/toolbar-contracts.ts",
      "src/families/actions/toolbar/toolbar-types.ts",
    ],
    behaviorContract: "src/families/actions/toolbar/toolbar.behavior.md",
    tests: [
      "src/families/actions/toolbar/toolbar.test.ts",
      "src/families/actions/toolbar/toolbar-ssr.test.ts",
    ],
    typeTests: ["src/families/actions/toolbar/toolbar.types.test-d.ts"],
    rendererFixture: "ToolbarConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Toolbar",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}toolbar",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 1_900,
      maximumCssGzipBytes: 0,
    },
    aliases: ["toolbar", "action toolbar", "editor toolbar", "command toolbar"],
    upstreamCoverage: ["WAI-ARIA Toolbar", "React Aria Toolbar", "Radix Toolbar"],
    dependencies: ["context"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
