import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const collapsibleFamilyRoot = "src/families/disclosure/collapsible/";
const inputFamilyRoot = "src/families/form/input/";
const linkFamilyRoot = "src/families/navigation/link/";
const searchFieldFamilyRoot = "src/families/form/search-field/";
const textareaFamilyRoot = "src/families/form/textarea/";

export const basicFamilyCatalog = [
  {
    canonicalName: "collapsible",
    title: "Collapsible",
    packageSubpath: "./collapsible",
    entryFile: `${collapsibleFamilyRoot}collapsible.ts`,
    sourceFiles: [
      `${collapsibleFamilyRoot}collapsible-root.vue`,
      `${collapsibleFamilyRoot}collapsible-trigger.vue`,
      `${collapsibleFamilyRoot}collapsible-content.vue`,
      `${collapsibleFamilyRoot}collapsible.ts`,
      `${collapsibleFamilyRoot}collapsible-context.ts`,
      `${collapsibleFamilyRoot}collapsible-types.ts`,
    ],
    behaviorContract: `${collapsibleFamilyRoot}collapsible.behavior.md`,
    tests: [
      `${collapsibleFamilyRoot}collapsible.test.ts`,
      `${collapsibleFamilyRoot}collapsible-ssr.test.ts`,
    ],
    typeTests: [`${collapsibleFamilyRoot}collapsible.types.test-d.ts`],
    rendererFixture: "CollapsibleConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Collapsible",
      retainedSignature: "collapsible-(?:root|trigger|content)",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 1_850,
      maximumCssGzipBytes: 0,
    },
    aliases: ["disclosure", "collapsible region", "expand collapse"],
    upstreamCoverage: ["WAI-ARIA Disclosure", "Radix UI Collapsible", "Reka UI Collapsible"],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "link",
    title: "Link",
    packageSubpath: "./link",
    entryFile: `${linkFamilyRoot}link.ts`,
    sourceFiles: [
      `${linkFamilyRoot}link-anchor.vue`,
      `${linkFamilyRoot}link.ts`,
      `${linkFamilyRoot}link-types.ts`,
    ],
    behaviorContract: `${linkFamilyRoot}link.behavior.md`,
    tests: [`${linkFamilyRoot}link.test.ts`],
    typeTests: [`${linkFamilyRoot}link.types.test-d.ts`],
    rendererFixture: "families/navigation/link/link-anchor.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Link",
      retainedSignature: "aria-current",
      maximumJavaScriptGzipBytes: 1_650,
      maximumCssGzipBytes: 0,
    },
    aliases: ["anchor", "navigation link", "disabled link"],
    upstreamCoverage: ["HTML anchor", "React Aria Link", "Reka UI Primitive"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "input",
    title: "Input",
    packageSubpath: "./input",
    entryFile: `${inputFamilyRoot}input.ts`,
    sourceFiles: [
      `${inputFamilyRoot}text-input.vue`,
      `${inputFamilyRoot}input.ts`,
      `${inputFamilyRoot}input-types.ts`,
    ],
    behaviorContract: `${inputFamilyRoot}input.behavior.md`,
    tests: [`${inputFamilyRoot}input.test.ts`],
    typeTests: [`${inputFamilyRoot}input.types.test-d.ts`],
    rendererFixture: "families/form/input/text-input.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Input",
      retainedSignature: 'data-vize-ui":(?:`input`|"input"|\'input\')',
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 2_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["text input", "field input", "textbox"],
    upstreamCoverage: ["HTML input", "React Aria TextField", "Reka UI Primitive"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "search-field",
    title: "Search Field",
    packageSubpath: "./search-field",
    entryFile: `${searchFieldFamilyRoot}search-field.ts`,
    sourceFiles: [
      `${searchFieldFamilyRoot}search-field.vue`,
      `${searchFieldFamilyRoot}search-field.ts`,
      `${searchFieldFamilyRoot}search-field-types.ts`,
    ],
    behaviorContract: `${searchFieldFamilyRoot}search-field.behavior.md`,
    tests: [`${searchFieldFamilyRoot}search-field.test.ts`],
    typeTests: [`${searchFieldFamilyRoot}search-field.types.test-d.ts`],
    rendererFixture: "families/form/search-field/search-field.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "SearchField",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}search-field",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 3_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["search box", "search input", "query field"],
    upstreamCoverage: ["HTML search input", "React Aria SearchField", "Reka UI Primitive"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "textarea",
    title: "Textarea",
    packageSubpath: "./textarea",
    entryFile: `${textareaFamilyRoot}textarea.ts`,
    sourceFiles: [
      `${textareaFamilyRoot}textarea-control.vue`,
      `${textareaFamilyRoot}textarea.ts`,
      `${textareaFamilyRoot}textarea-types.ts`,
    ],
    behaviorContract: `${textareaFamilyRoot}textarea.behavior.md`,
    tests: [`${textareaFamilyRoot}textarea.test.ts`],
    typeTests: [`${textareaFamilyRoot}textarea.types.test-d.ts`],
    rendererFixture: "families/form/textarea/textarea-control.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Textarea",
      retainedSignature: "data-vize-ui.+textarea",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 2_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["text area", "multiline input", "textarea field"],
    upstreamCoverage: ["HTML textarea", "React Aria TextField", "Reka UI Primitive"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
