import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const idFamilyRoot = "src/families/foundations/id/";
const dismissableLayerFamilyRoot = "src/families/overlays/dismissable-layer/";
const dragAndDropFamilyRoot = "src/families/interaction/drag-and-drop/";
const historyFamilyRoot = "src/families/interaction/history/";

export const focusFamilyCatalog = [
  {
    canonicalName: "dismissable-layer",
    title: "Dismissable Layer",
    packageSubpath: "./dismissable-layer",
    entryFile: `${dismissableLayerFamilyRoot}dismissable-layer.ts`,
    sourceFiles: [
      `${dismissableLayerFamilyRoot}dismissable-layer.ts`,
      `${dismissableLayerFamilyRoot}dismissable-layer-internal.ts`,
      `${dismissableLayerFamilyRoot}dismissable-layer-stack.ts`,
      `${dismissableLayerFamilyRoot}dismissable-layer-types.ts`,
    ],
    behaviorContract: `${dismissableLayerFamilyRoot}dismissable-layer.behavior.md`,
    tests: [
      `${dismissableLayerFamilyRoot}dismissable-layer.test.ts`,
      `${dismissableLayerFamilyRoot}dismissable-layer-ssr.test.ts`,
    ],
    typeTests: [`${dismissableLayerFamilyRoot}dismissable-layer.types.test-d.ts`],
    rendererFixture: "DismissableLayerConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createDismissableLayer",
      retainedSignature: "VIZE_UI_DISMISSABLE_LAYER_DISPOSED",
      maximumJavaScriptGzipBytes: 2_850,
      maximumCssGzipBytes: 0,
    },
    aliases: ["dismissible layer", "outside interaction", "escape routing", "overlay stack"],
    upstreamCoverage: [
      "Radix DismissableLayer",
      "React Aria overlay dismissal",
      "Reka UI DismissableLayer",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "drag-and-drop",
    title: "Drag and Drop",
    packageSubpath: "./drag-and-drop",
    entryFile: `${dragAndDropFamilyRoot}drag-and-drop.ts`,
    sourceFiles: [
      `${dragAndDropFamilyRoot}drag-and-drop.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-announce.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-autoscroll.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-controller-types.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-internal.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-keyboard.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-listeners.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-session.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-transfer.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-types.ts`,
    ],
    behaviorContract: `${dragAndDropFamilyRoot}drag-and-drop.behavior.md`,
    tests: [
      `${dragAndDropFamilyRoot}drag-and-drop.test.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-keyboard.test.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-legacy.test.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-ssr.test.ts`,
      `${dragAndDropFamilyRoot}drag-and-drop-transfer.test.ts`,
    ],
    typeTests: [`${dragAndDropFamilyRoot}drag-and-drop.types.test-d.ts`],
    rendererFixture: "DragAndDropConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createDragAndDrop",
      retainedSignature: "VIZE_UI_DRAG_AND_DROP_DISPOSED",
      maximumJavaScriptGzipBytes: 6_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["drag and drop", "dnd", "drag handle", "drop target", "drop indicator"],
    upstreamCoverage: [
      "React Aria useDrag and useDrop",
      "Pragmatic drag and drop adapters",
      "HTML Drag and Drop DataTransfer",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "history",
    title: "Undo/Redo History",
    packageSubpath: "./history",
    entryFile: `${historyFamilyRoot}history.ts`,
    sourceFiles: [
      `${historyFamilyRoot}history.ts`,
      `${historyFamilyRoot}history-editable.ts`,
      `${historyFamilyRoot}history-stack.ts`,
      `${historyFamilyRoot}history-types.ts`,
    ],
    behaviorContract: `${historyFamilyRoot}history.behavior.md`,
    tests: [
      `${historyFamilyRoot}history.test.ts`,
      `${historyFamilyRoot}history-editable.test.ts`,
      `${historyFamilyRoot}history-ssr.test.ts`,
    ],
    typeTests: [`${historyFamilyRoot}history.types.test-d.ts`],
    rendererFixture: "HistoryConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createHistory",
      retainedSignature: "VIZE_UI_HISTORY_DISPOSED",
      maximumJavaScriptGzipBytes: 1_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["undo/redo", "undo stack", "history timeline", "editable transaction"],
    upstreamCoverage: ["ProseMirror history", "CodeMirror history", "Redux undo"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "id",
    title: "Deterministic ID Provider",
    packageSubpath: "./id",
    entryFile: `${idFamilyRoot}id.ts`,
    sourceFiles: [
      `${idFamilyRoot}deterministic-id-provider.vue`,
      `${idFamilyRoot}id.ts`,
      `${idFamilyRoot}deterministic-id.ts`,
    ],
    behaviorContract: `${idFamilyRoot}id.behavior.md`,
    tests: [`${idFamilyRoot}id.test.ts`],
    typeTests: [`${idFamilyRoot}id.types.test-d.ts`],
    rendererFixture: "families/foundations/id/deterministic-id-provider.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "IdProvider",
      retainedSignature: "deterministic-id-provider",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["id provider", "deterministic ids", "hydration ids"],
    upstreamCoverage: ["React Aria SSRProvider", "Vue useId"],
    dependencies: ["context"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
