import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
// Paths are resolved from the package cwd: the runner virtualizes import.meta.url.
import path from "node:path";

import { test } from "vite-plus/test";

import { formatSfcLintResults, lintSfcFiles } from "@vizejs/ui-tooling/lint-sfc";
import type { SfcLintFunction } from "@vizejs/ui-tooling/lint-sfc";

test("discovers every SFC with the opinionated Vize contract", async () => {
  const requests: Parameters<SfcLintFunction>[1][] = [];
  const lint: SfcLintFunction = (_source, options) => {
    requests.push(options);
    return { diagnostics: [] };
  };
  const results = await lintSfcFiles(lint);

  assert.deepEqual(
    results.map((result) => result.filename),
    [
      "src/action-button.vue",
      "src/alert-dialog-content.vue",
      "src/announcer-provider.vue",
      "src/breadcrumb-item.vue",
      "src/breadcrumb-link.vue",
      "src/breadcrumb-list.vue",
      "src/breadcrumb-separator.vue",
      "src/breadcrumb.vue",
      "src/checkbox-control.vue",
      "src/collapsible-content.vue",
      "src/collapsible-root.vue",
      "src/collapsible-trigger.vue",
      "src/deterministic-id-provider.vue",
      "src/error-summary.vue",
      "src/families/actions/button-group/button-group-item.vue",
      "src/families/actions/button-group/button-group.vue",
      "src/families/actions/copy-button/copy-button.vue",
      "src/families/actions/fullscreen-button/fullscreen-button.vue",
      "src/families/actions/print-button/print-button.vue",
      "src/families/actions/share-button/share-button.vue",
      "src/families/actions/toolbar/toolbar-item.vue",
      "src/families/actions/toolbar/toolbar.vue",
      "src/families/data/table/table-body.vue",
      "src/families/data/table/table-caption.vue",
      "src/families/data/table/table-cell.vue",
      "src/families/data/table/table-head.vue",
      "src/families/data/table/table-header.vue",
      "src/families/data/table/table-row.vue",
      "src/families/data/table/table.vue",
      "src/families/feedback/alert/alert.vue",
      "src/families/feedback/badge/badge.vue",
      "src/families/feedback/banner/banner.vue",
      "src/families/feedback/block-ui/block-ui.vue",
      "src/families/feedback/callout/callout.vue",
      "src/families/feedback/empty-state/empty-state.vue",
      "src/families/feedback/meter/meter.vue",
      "src/families/feedback/progress-bar/progress-bar.vue",
      "src/families/feedback/progress/progress.vue",
      "src/families/feedback/skeleton/skeleton.vue",
      "src/families/feedback/spinner/spinner.vue",
      "src/families/feedback/status-light/status-light.vue",
      "src/families/form/rating/rating.vue",
      "src/families/form/slider/slider.vue",
      "src/families/i18n/locale/locale-provider.vue",
      "src/families/layout/aspect-ratio/aspect-ratio.vue",
      "src/families/layout/avatar/avatar.vue",
      "src/families/layout/card/card.vue",
      "src/families/layout/cluster/cluster.vue",
      "src/families/layout/container/container.vue",
      "src/families/layout/grid/grid.vue",
      "src/families/layout/icon/icon-button.vue",
      "src/families/layout/icon/icon.vue",
      "src/families/layout/list/list.vue",
      "src/families/layout/scroll-area/scroll-area.vue",
      "src/families/layout/separator/separator.vue",
      "src/families/layout/spacer/spacer.vue",
      "src/families/layout/stack/stack.vue",
      "src/families/layout/surface/surface.vue",
      "src/families/navigation/skip-link/skip-link.vue",
      "src/families/overlays/dialog/dialog-close.vue",
      "src/families/overlays/dialog/dialog-content.vue",
      "src/families/overlays/dialog/dialog-description.vue",
      "src/families/overlays/dialog/dialog-overlay.vue",
      "src/families/overlays/dialog/dialog-portal.vue",
      "src/families/overlays/dialog/dialog-root.vue",
      "src/families/overlays/dialog/dialog-title.vue",
      "src/families/overlays/dialog/dialog-trigger.vue",
      "src/families/overlays/popover/popover-arrow.vue",
      "src/families/overlays/popover/popover-content.vue",
      "src/families/overlays/popover/popover-root.vue",
      "src/families/overlays/popover/popover-trigger.vue",
      "src/families/overlays/tooltip/tooltip-content.vue",
      "src/families/overlays/tooltip/tooltip-root.vue",
      "src/families/overlays/tooltip/tooltip-trigger.vue",
      "src/families/selection/native-select/native-select.vue",
      "src/families/typography/blockquote/blockquote.vue",
      "src/families/typography/code/code.vue",
      "src/families/typography/heading/heading.vue",
      "src/families/typography/kbd/kbd.vue",
      "src/families/typography/text/text.vue",
      "src/field-description.vue",
      "src/field-error-message.vue",
      "src/field-label.vue",
      "src/field.vue",
      "src/link-anchor.vue",
      "src/listbox-item.vue",
      "src/listbox.vue",
      "src/live-region.vue",
      "src/pagination-ellipsis.vue",
      "src/pagination-item.vue",
      "src/pagination-list.vue",
      "src/pagination-next.vue",
      "src/pagination-page.vue",
      "src/pagination-previous.vue",
      "src/pagination.vue",
      "src/portal.vue",
      "src/positioner-arrow.vue",
      "src/positioner.vue",
      "src/presence.vue",
      "src/primitive-element.vue",
      "src/radio-group-item.vue",
      "src/radio-group.vue",
      "src/search-field.vue",
      "src/stepper-content.vue",
      "src/stepper-item.vue",
      "src/stepper-list.vue",
      "src/stepper-root.vue",
      "src/stepper-trigger.vue",
      "src/switch-control.vue",
      "src/tabs-content.vue",
      "src/tabs-list.vue",
      "src/tabs-root.vue",
      "src/tabs-trigger.vue",
      "src/text-input.vue",
      "src/textarea-control.vue",
      "src/toggle-button.vue",
      "src/toggle-group-item.vue",
      "src/toggle-group.vue",
      "src/transition.vue",
      "src/visually-hidden.vue",
    ],
  );
  assert.deepEqual(
    requests,
    [
      "action-button.vue",
      "alert-dialog-content.vue",
      "announcer-provider.vue",
      "breadcrumb-item.vue",
      "breadcrumb-link.vue",
      "breadcrumb-list.vue",
      "breadcrumb-separator.vue",
      "breadcrumb.vue",
      "checkbox-control.vue",
      "collapsible-content.vue",
      "collapsible-root.vue",
      "collapsible-trigger.vue",
      "deterministic-id-provider.vue",
      "error-summary.vue",
      "families/actions/button-group/button-group-item.vue",
      "families/actions/button-group/button-group.vue",
      "families/actions/copy-button/copy-button.vue",
      "families/actions/fullscreen-button/fullscreen-button.vue",
      "families/actions/print-button/print-button.vue",
      "families/actions/share-button/share-button.vue",
      "families/actions/toolbar/toolbar-item.vue",
      "families/actions/toolbar/toolbar.vue",
      "families/data/table/table-body.vue",
      "families/data/table/table-caption.vue",
      "families/data/table/table-cell.vue",
      "families/data/table/table-head.vue",
      "families/data/table/table-header.vue",
      "families/data/table/table-row.vue",
      "families/data/table/table.vue",
      "families/feedback/alert/alert.vue",
      "families/feedback/badge/badge.vue",
      "families/feedback/banner/banner.vue",
      "families/feedback/block-ui/block-ui.vue",
      "families/feedback/callout/callout.vue",
      "families/feedback/empty-state/empty-state.vue",
      "families/feedback/meter/meter.vue",
      "families/feedback/progress-bar/progress-bar.vue",
      "families/feedback/progress/progress.vue",
      "families/feedback/skeleton/skeleton.vue",
      "families/feedback/spinner/spinner.vue",
      "families/feedback/status-light/status-light.vue",
      "families/form/rating/rating.vue",
      "families/form/slider/slider.vue",
      "families/i18n/locale/locale-provider.vue",
      "families/layout/aspect-ratio/aspect-ratio.vue",
      "families/layout/avatar/avatar.vue",
      "families/layout/card/card.vue",
      "families/layout/cluster/cluster.vue",
      "families/layout/container/container.vue",
      "families/layout/grid/grid.vue",
      "families/layout/icon/icon-button.vue",
      "families/layout/icon/icon.vue",
      "families/layout/list/list.vue",
      "families/layout/scroll-area/scroll-area.vue",
      "families/layout/separator/separator.vue",
      "families/layout/spacer/spacer.vue",
      "families/layout/stack/stack.vue",
      "families/layout/surface/surface.vue",
      "families/navigation/skip-link/skip-link.vue",
      "families/overlays/dialog/dialog-close.vue",
      "families/overlays/dialog/dialog-content.vue",
      "families/overlays/dialog/dialog-description.vue",
      "families/overlays/dialog/dialog-overlay.vue",
      "families/overlays/dialog/dialog-portal.vue",
      "families/overlays/dialog/dialog-root.vue",
      "families/overlays/dialog/dialog-title.vue",
      "families/overlays/dialog/dialog-trigger.vue",
      "families/overlays/popover/popover-arrow.vue",
      "families/overlays/popover/popover-content.vue",
      "families/overlays/popover/popover-root.vue",
      "families/overlays/popover/popover-trigger.vue",
      "families/overlays/tooltip/tooltip-content.vue",
      "families/overlays/tooltip/tooltip-root.vue",
      "families/overlays/tooltip/tooltip-trigger.vue",
      "families/selection/native-select/native-select.vue",
      "families/typography/blockquote/blockquote.vue",
      "families/typography/code/code.vue",
      "families/typography/heading/heading.vue",
      "families/typography/kbd/kbd.vue",
      "families/typography/text/text.vue",
      "field-description.vue",
      "field-error-message.vue",
      "field-label.vue",
      "field.vue",
      "link-anchor.vue",
      "listbox-item.vue",
      "listbox.vue",
      "live-region.vue",
      "pagination-ellipsis.vue",
      "pagination-item.vue",
      "pagination-list.vue",
      "pagination-next.vue",
      "pagination-page.vue",
      "pagination-previous.vue",
      "pagination.vue",
      "portal.vue",
      "positioner-arrow.vue",
      "positioner.vue",
      "presence.vue",
      "primitive-element.vue",
      "radio-group-item.vue",
      "radio-group.vue",
      "search-field.vue",
      "stepper-content.vue",
      "stepper-item.vue",
      "stepper-list.vue",
      "stepper-root.vue",
      "stepper-trigger.vue",
      "switch-control.vue",
      "tabs-content.vue",
      "tabs-list.vue",
      "tabs-root.vue",
      "tabs-trigger.vue",
      "text-input.vue",
      "textarea-control.vue",
      "toggle-button.vue",
      "toggle-group-item.vue",
      "toggle-group.vue",
      "transition.vue",
      "visually-hidden.vue",
    ].map((basename) => ({
      filename: path.resolve("src", basename),
      preset: "opinionated" as const,
      typeAware: true as const,
      helpLevel: "short" as const,
    })),
  );
  assert.equal(formatSfcLintResults(results), "");
});

test("package lint:sfc stays wired to the shared Vize SFC gate", async () => {
  const manifest = JSON.parse(await readFile(path.resolve("package.json"), "utf8")) as {
    scripts?: Record<string, string>;
  };
  const lintScript = await readFile(path.resolve("scripts/lint-sfc.ts"), "utf8");

  assert.equal(
    manifest.scripts?.["lint:sfc"],
    "vp exec node scripts/lint-sfc.ts src && vp exec node scripts/check-renderers.ts src",
  );
  assert.match(lintScript, /import \{ lintPatinaSfc \} from "@vizejs\/native";/);
  assert.match(lintScript, /const lintCoreSfc: SfcLintFunction = \(source, options\) =>/);
  assert.match(lintScript, /corsaPath: workspaceCorsaPath/);
  assert.match(lintScript, /lintFiles\(lintCoreSfc, sourceRoots\)/);
  assert.match(
    lintScript,
    /runSfcLintCli\(lintCoreSfc, sourceRoots\.length > 0 \? sourceRoots : "src"\)/,
  );
});
