import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
// Paths are resolved from the package cwd: the runner virtualizes import.meta.url.
import path from "node:path";

import { test } from "vite-plus/test";

import { formatSfcLintResults, lintSfcFiles } from "@vizejs/ui-tooling/lint-sfc";
import type { SfcLintFunction } from "@vizejs/ui-tooling/lint-sfc";

test("discovers every SFC with the opinionated Vize contract", async () => {
  const requests: Parameters<SfcLintFunction>[1][] = [];
  const lint: SfcLintFunction = (_source, options) => {
    requests.push(options);
    return { diagnostics: [] };
  };
  const results = await lintSfcFiles(lint);

  assert.deepEqual(
    results.map((result) => result.filename),
    [
      "src/action-button.vue",
      "src/alert-dialog-content.vue",
      "src/alert.vue",
      "src/announcer-provider.vue",
      "src/aspect-ratio.vue",
      "src/avatar.vue",
      "src/badge.vue",
      "src/block-ui.vue",
      "src/blockquote.vue",
      "src/breadcrumb-item.vue",
      "src/breadcrumb-link.vue",
      "src/breadcrumb-list.vue",
      "src/breadcrumb-separator.vue",
      "src/breadcrumb.vue",
      "src/card.vue",
      "src/checkbox-control.vue",
      "src/cluster.vue",
      "src/code.vue",
      "src/collapsible-content.vue",
      "src/collapsible-root.vue",
      "src/collapsible-trigger.vue",
      "src/container.vue",
      "src/deterministic-id-provider.vue",
      "src/dialog-close.vue",
      "src/dialog-content.vue",
      "src/dialog-description.vue",
      "src/dialog-overlay.vue",
      "src/dialog-portal.vue",
      "src/dialog-root.vue",
      "src/dialog-title.vue",
      "src/dialog-trigger.vue",
      "src/empty-state.vue",
      "src/error-summary.vue",
      "src/families/actions/button-group/button-group-item.vue",
      "src/families/actions/button-group/button-group.vue",
      "src/families/feedback/status-light/status-light.vue",
      "src/families/form/slider/slider.vue",
      "src/families/layout/icon/icon-button.vue",
      "src/families/layout/icon/icon.vue",
      "src/families/layout/surface/surface.vue",
      "src/families/overlays/popover/popover-arrow.vue",
      "src/families/overlays/popover/popover-content.vue",
      "src/families/overlays/popover/popover-root.vue",
      "src/families/overlays/popover/popover-trigger.vue",
      "src/families/selection/native-select/native-select.vue",
      "src/field-description.vue",
      "src/field-error-message.vue",
      "src/field-label.vue",
      "src/field.vue",
      "src/grid.vue",
      "src/heading.vue",
      "src/kbd.vue",
      "src/link-anchor.vue",
      "src/list.vue",
      "src/listbox-item.vue",
      "src/listbox.vue",
      "src/live-region.vue",
      "src/locale-provider.vue",
      "src/meter.vue",
      "src/pagination-ellipsis.vue",
      "src/pagination-item.vue",
      "src/pagination-list.vue",
      "src/pagination-next.vue",
      "src/pagination-page.vue",
      "src/pagination-previous.vue",
      "src/pagination.vue",
      "src/portal.vue",
      "src/positioner-arrow.vue",
      "src/positioner.vue",
      "src/presence.vue",
      "src/primitive-element.vue",
      "src/progress-bar.vue",
      "src/radio-group-item.vue",
      "src/radio-group.vue",
      "src/search-field.vue",
      "src/separator.vue",
      "src/skeleton.vue",
      "src/spacer.vue",
      "src/spinner.vue",
      "src/stack.vue",
      "src/stepper-content.vue",
      "src/stepper-item.vue",
      "src/stepper-list.vue",
      "src/stepper-root.vue",
      "src/stepper-trigger.vue",
      "src/switch-control.vue",
      "src/tabs-content.vue",
      "src/tabs-list.vue",
      "src/tabs-root.vue",
      "src/tabs-trigger.vue",
      "src/text-input.vue",
      "src/text.vue",
      "src/textarea-control.vue",
      "src/toggle-button.vue",
      "src/toggle-group-item.vue",
      "src/toggle-group.vue",
      "src/tooltip-content.vue",
      "src/tooltip-root.vue",
      "src/tooltip-trigger.vue",
      "src/transition.vue",
      "src/visually-hidden.vue",
    ],
  );
  assert.deepEqual(
    requests,
    [
      "action-button.vue",
      "alert-dialog-content.vue",
      "alert.vue",
      "announcer-provider.vue",
      "aspect-ratio.vue",
      "avatar.vue",
      "badge.vue",
      "block-ui.vue",
      "blockquote.vue",
      "breadcrumb-item.vue",
      "breadcrumb-link.vue",
      "breadcrumb-list.vue",
      "breadcrumb-separator.vue",
      "breadcrumb.vue",
      "card.vue",
      "checkbox-control.vue",
      "cluster.vue",
      "code.vue",
      "collapsible-content.vue",
      "collapsible-root.vue",
      "collapsible-trigger.vue",
      "container.vue",
      "deterministic-id-provider.vue",
      "dialog-close.vue",
      "dialog-content.vue",
      "dialog-description.vue",
      "dialog-overlay.vue",
      "dialog-portal.vue",
      "dialog-root.vue",
      "dialog-title.vue",
      "dialog-trigger.vue",
      "empty-state.vue",
      "error-summary.vue",
      "families/actions/button-group/button-group-item.vue",
      "families/actions/button-group/button-group.vue",
      "families/feedback/status-light/status-light.vue",
      "families/form/slider/slider.vue",
      "families/layout/icon/icon-button.vue",
      "families/layout/icon/icon.vue",
      "families/layout/surface/surface.vue",
      "families/overlays/popover/popover-arrow.vue",
      "families/overlays/popover/popover-content.vue",
      "families/overlays/popover/popover-root.vue",
      "families/overlays/popover/popover-trigger.vue",
      "families/selection/native-select/native-select.vue",
      "field-description.vue",
      "field-error-message.vue",
      "field-label.vue",
      "field.vue",
      "grid.vue",
      "heading.vue",
      "kbd.vue",
      "link-anchor.vue",
      "list.vue",
      "listbox-item.vue",
      "listbox.vue",
      "live-region.vue",
      "locale-provider.vue",
      "meter.vue",
      "pagination-ellipsis.vue",
      "pagination-item.vue",
      "pagination-list.vue",
      "pagination-next.vue",
      "pagination-page.vue",
      "pagination-previous.vue",
      "pagination.vue",
      "portal.vue",
      "positioner-arrow.vue",
      "positioner.vue",
      "presence.vue",
      "primitive-element.vue",
      "progress-bar.vue",
      "radio-group-item.vue",
      "radio-group.vue",
      "search-field.vue",
      "separator.vue",
      "skeleton.vue",
      "spacer.vue",
      "spinner.vue",
      "stack.vue",
      "stepper-content.vue",
      "stepper-item.vue",
      "stepper-list.vue",
      "stepper-root.vue",
      "stepper-trigger.vue",
      "switch-control.vue",
      "tabs-content.vue",
      "tabs-list.vue",
      "tabs-root.vue",
      "tabs-trigger.vue",
      "text-input.vue",
      "text.vue",
      "textarea-control.vue",
      "toggle-button.vue",
      "toggle-group-item.vue",
      "toggle-group.vue",
      "tooltip-content.vue",
      "tooltip-root.vue",
      "tooltip-trigger.vue",
      "transition.vue",
      "visually-hidden.vue",
    ].map((basename) => ({
      filename: path.resolve("src", basename),
      preset: "opinionated" as const,
      typeAware: true as const,
      helpLevel: "short" as const,
    })),
  );
  assert.equal(formatSfcLintResults(results), "");
});

test("package lint:sfc stays wired to the shared Vize SFC gate", async () => {
  const manifest = JSON.parse(await readFile(path.resolve("package.json"), "utf8")) as {
    scripts?: Record<string, string>;
  };
  const lintScript = await readFile(path.resolve("scripts/lint-sfc.ts"), "utf8");

  assert.equal(
    manifest.scripts?.["lint:sfc"],
    "vp exec node scripts/lint-sfc.ts src && vp exec node scripts/check-renderers.ts src",
  );
  assert.match(lintScript, /import \{ lintPatinaSfc \} from "@vizejs\/native";/);
  assert.match(lintScript, /lintFiles\(lintPatinaSfc, sourceRoots\)/);
  assert.match(
    lintScript,
    /runSfcLintCli\(lintPatinaSfc, sourceRoots\.length > 0 \? sourceRoots : "src"\)/,
  );
});
