//! Build cached art-template virtual TypeScript in the matching script scope.

#![allow(clippy::disallowed_types, clippy::disallowed_methods)]

use vize_atelier_sfc::SfcScriptBlock;

use crate::virtual_code::{
    ArtScriptChunk, MappingFeatures, SourceMap, SourceMapping, SourceRange, VirtualDocument,
    VirtualDocuments, analyze_art_script_setup,
};

pub(super) fn attach(
    documents: &mut VirtualDocuments,
    script_setup: Option<&SfcScriptBlock<'_>>,
    isolate: bool,
) {
    let default_template_uri = documents
        .template
        .as_ref()
        .map(|template| template.uri.clone());
    let script = documents.script.clone();
    let setup = script_setup
        .map(|block| analyze_art_script_setup(block.content.as_ref(), block.loc.start, isolate));
    let setup_generic = script_setup
        .and_then(|block| block.attrs.get("generic"))
        .map(|value| value.as_ref());

    for (variant_index, template) in documents.art_templates.iter_mut().enumerate() {
        let Some(original) = template.take() else {
            continue;
        };
        *template = Some(build_variant_document(
            original,
            script.as_ref(),
            setup.as_ref(),
            setup_generic,
            variant_index,
        ));
    }

    if let Some(default_template_uri) = default_template_uri
        && let Some(default_template) = documents
            .art_templates
            .iter()
            .flatten()
            .find(|template| template.uri == default_template_uri)
    {
        documents.template = Some(default_template.clone());
    }
}

fn build_variant_document(
    template: VirtualDocument,
    script: Option<&VirtualDocument>,
    setup: Option<&crate::virtual_code::ArtScriptSetupParts>,
    setup_generic: Option<&str>,
    variant_index: usize,
) -> VirtualDocument {
    let mut content = String::new();
    let mut mappings = Vec::new();
    content.push_str("// Typed virtual TypeScript for art variant\n");
    content.push_str("// Generated by vize_maestro\n");
    content.push_str("export {};\n\n");

    if let Some(script) = script {
        append_document(&mut content, &mut mappings, script);
        ensure_blank_line(&mut content);
    }

    if let Some(setup) = setup {
        for import in &setup.shared_imports {
            append_chunk(&mut content, &mut mappings, import);
        }
        ensure_blank_line(&mut content);
        content.push_str(vize_canon::virtual_ts::VUE_TYPE_HELPERS);
        ensure_blank_line(&mut content);

        let function_name = if setup.isolate {
            vize_s0::cstr!("__VIZE_art_variant_{variant_index}_setup")
        } else {
            "__VIZE_art_shared_setup".into()
        };
        let generic = setup_generic.filter(|generic| !generic.trim().is_empty());
        if let Some(generic) = generic {
            vize_s0::append!(content, "async function {function_name}<{generic}>() {{\n");
        } else {
            vize_s0::append!(content, "async function {function_name}() {{\n");
        }
        content.push_str(vize_canon::virtual_ts::VUE_SETUP_HELPERS);
        content.push('\n');
        for chunk in &setup.isolated_body {
            append_chunk(&mut content, &mut mappings, chunk);
        }
        append_template_payload(&mut content, &mut mappings, &template);
        content.push_str("}\n");
    } else if script.is_some() {
        append_template_payload(&mut content, &mut mappings, &template);
    } else {
        append_document(&mut content, &mut mappings, &template);
    }

    VirtualDocument {
        uri: template.uri,
        content,
        language: template.language,
        source_map: SourceMap::from_mappings(mappings),
    }
}

fn append_document(
    output: &mut String,
    mappings: &mut Vec<SourceMapping>,
    document: &VirtualDocument,
) {
    let generated_base = output.len() as u32;
    output.push_str(&document.content);
    for mapping in document.source_map.mappings() {
        mappings.push(shift_mapping(
            mapping,
            document.source_map.block_offset,
            generated_base,
        ));
    }
}

fn append_chunk(output: &mut String, mappings: &mut Vec<SourceMapping>, chunk: &ArtScriptChunk) {
    let generated_start = output.len() as u32;
    output.push_str(&chunk.text);
    let generated_end = output.len() as u32;
    mappings.push(SourceMapping::with_features(
        SourceRange::new(chunk.source_start as u32, chunk.source_end as u32),
        SourceRange::new(generated_start, generated_end),
        MappingFeatures::all(),
    ));
    if !output.ends_with('\n') {
        output.push('\n');
    }
}

fn append_template_payload(
    output: &mut String,
    mappings: &mut Vec<SourceMapping>,
    template: &VirtualDocument,
) {
    const MARKER: &str = "// Template expressions";
    let payload_start = template.content.find(MARKER).unwrap_or(0);
    let removals = synthetic_context_prefix_removals(template, payload_start as u32);
    let generated_base = output.len() as u32;
    append_without_ranges(output, &template.content, payload_start, &removals);
    if !output.ends_with('\n') {
        output.push('\n');
    }

    for mapping in template.source_map.mappings() {
        if mapping.generated.start < payload_start as u32 {
            continue;
        }
        let mut shifted = mapping.clone();
        shifted.source.start += template.source_map.block_offset;
        shifted.source.end += template.source_map.block_offset;
        shifted.generated.start = generated_base + mapping.generated.start
            - payload_start as u32
            - removed_bytes_before(mapping.generated.start, &removals);
        shifted.generated.end = generated_base + mapping.generated.end
            - payload_start as u32
            - removed_bytes_before(mapping.generated.end, &removals);
        mappings.push(shifted);
    }
}

fn synthetic_context_prefix_removals(
    template: &VirtualDocument,
    payload_start: u32,
) -> Vec<SourceRange> {
    const PREFIX: &str = "__VIZE_ctx.";

    let mut removals = template
        .source_map
        .mappings()
        .iter()
        .filter_map(|mapping| {
            let prefix_start = mapping.generated.start.checked_sub(PREFIX.len() as u32)?;
            if prefix_start < payload_start {
                return None;
            }
            let prefix = template
                .content
                .get(prefix_start as usize..mapping.generated.start as usize)?;
            (prefix == PREFIX).then(|| SourceRange::new(prefix_start, mapping.generated.start))
        })
        .collect::<Vec<_>>();
    removals.sort_by_key(|range| range.start);
    removals.dedup_by_key(|range| range.start);
    removals
}

fn append_without_ranges(
    output: &mut String,
    content: &str,
    start: usize,
    removals: &[SourceRange],
) {
    let mut cursor = start;
    for removal in removals {
        let removal_start = removal.start as usize;
        let removal_end = removal.end as usize;
        if removal_end <= start || removal_start < cursor {
            continue;
        }
        output.push_str(&content[cursor..removal_start]);
        cursor = removal_end;
    }
    output.push_str(&content[cursor..]);
}

fn removed_bytes_before(offset: u32, removals: &[SourceRange]) -> u32 {
    removals
        .iter()
        .map(|removal| {
            if offset <= removal.start {
                0
            } else if offset >= removal.end {
                removal.len()
            } else {
                offset - removal.start
            }
        })
        .sum()
}

fn shift_mapping(mapping: &SourceMapping, source_base: u32, generated_base: u32) -> SourceMapping {
    let mut shifted = mapping.clone();
    shifted.source.start += source_base;
    shifted.source.end += source_base;
    shifted.generated.start += generated_base;
    shifted.generated.end += generated_base;
    shifted
}

fn ensure_blank_line(output: &mut String) {
    if !output.ends_with('\n') {
        output.push('\n');
    }
    if !output.ends_with("\n\n") {
        output.push('\n');
    }
}
