[package]
name = "vize_carton"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Carton - The artist's toolbox for Vize compiler"
metadata.vize.stability = "alpha-supported"

[dependencies]
vize_l0 = { workspace = true }

[features]
default = []
extension = ["vize_l0/extension"]
lint-glob = ["vize_l0/lint-glob"]

[dev-dependencies]
serde_json.workspace = true
davinci_test_support.workspace = true
insta.workspace = true
tempfile.workspace = true

[lints]
workspace = true
