//! Structured source maps for the assembled SFC module (Davinci P3-9).
//!
//! `compile_sfc` assembles its module from pieces: statement slices of the
//! authored `<script>` / `<script setup>`, rebuilt imports, synthesized macro
//! bindings and component plumbing, and (for `lang="ts"` into JavaScript) an oxc
//! re-print of the whole. Each stage that copies authored text records where
//! the copy came from as [`Runs`]; a stage that regenerates text from a known
//! authored construct records a point anchor at it; a re-print contributes the
//! token provenance oxc's codegen records. Chaining the stages yields the
//! provenance of every emitted byte that has any, and nothing is recovered by
//! comparing text.
//!
//! The map emits one segment per token start inside a verbatim run (so a copied
//! statement maps token by token) plus one per point anchor. Runs are verified
//! byte-for-byte against the `.vue` source before they are emitted.

mod reprint;
mod runs;
mod traced;

#[cfg(test)]
mod sfc_tests;
#[cfg(test)]
mod tests;

use vize_atelier_core::codegen::source_map::SourceMapBuilder;
use vize_carton::String;

pub(crate) use reprint::{remap_reprinted, reprint_points};
pub(crate) use runs::{Run, Runs, apply_edits, edit_runs, replace_traced};
pub(crate) use traced::TracedText;

/// Whether a character continues an identifier-like token.
fn is_word(ch: char) -> bool {
    ch.is_alphanumeric() || ch == '_' || ch == '$'
}

/// Offsets inside a verbatim run where a token starts: the run's first
/// non-whitespace character, every non-whitespace character after
/// whitespace, and every change between word and punctuation characters.
pub(crate) fn token_starts(generated: &str, run: Run) -> impl Iterator<Item = usize> + '_ {
    let text = &generated[run.out..run.out + run.len];
    let mut previous: Option<char> = None;
    text.char_indices().filter_map(move |(index, ch)| {
        let starts = !ch.is_whitespace()
            && match previous {
                None => true,
                Some(prev) => prev.is_whitespace() || is_word(prev) != is_word(ch) || !is_word(ch),
            };
        previous = Some(ch);
        starts.then_some(run.out + index)
    })
}

/// Serialize the provenance of `generated` into `.vue` offsets as a Source Map
/// v3 document naming `filename`, or `None` when no byte is accounted for.
pub(crate) fn build_module_map(
    generated: &str,
    provenance: Runs,
    filename: &str,
    source: &str,
) -> Option<String> {
    let provenance = provenance.verified(generated, source);
    let mut segments: Vec<(usize, usize)> = Vec::new();
    for &run in provenance.runs() {
        segments.extend(token_starts(generated, run).map(|out| (out, run.src + (out - run.out))));
    }
    segments.extend(provenance.points().iter().copied());
    if segments.is_empty() {
        return None;
    }
    // A verbatim token wins over a point anchor at the same generated byte.
    segments.sort_by_key(|&(out, _)| out);
    segments.dedup_by_key(|segment| segment.0);
    let mut builder = SourceMapBuilder::new();
    for (out, src) in segments {
        builder.add_raw(out, src as u32);
    }
    Some(builder.finish(generated, filename, source))
}

/// [`build_module_map`] as the `SfcCompileResult.map` field carries it.
pub(crate) fn module_map_value(
    generated: &str,
    provenance: Runs,
    filename: &str,
    source: &str,
) -> Option<serde_json::Value> {
    let json = build_module_map(generated, provenance, filename, source)?;
    serde_json::from_str(&json).ok()
}
