/**
 * Vite plugin that mocks Nuxt auto-imports and components for Musea galleries.
 */

import type { Plugin } from "vite";
import type { NuxtMuseaOptions } from "./types.js";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VIRTUAL_IMPORTS_ID = "\0musea-nuxt:imports";
const VIRTUAL_NUXT_COMPONENTS_ID = "\0musea-nuxt:components";
const NUXT_IMPORT_IDS = new Set(["#imports", "#app", "#build", "nuxt/app"]);
const NUXT_COMPONENT_IDS = new Set([
  "#components",
  "#build/components",
  "nuxt/dist/app/components",
]);

export function createNuxtMuseaPlugin(options: NuxtMuseaOptions = {}): Plugin {
  const srcDir = path.dirname(fileURLToPath(import.meta.url));

  return {
    name: "vite-plugin-musea-nuxt",
    enforce: "pre",

    resolveId(id) {
      // Resolve Nuxt component imports before the broad #build/* import alias.
      if (NUXT_COMPONENT_IDS.has(id)) {
        return VIRTUAL_NUXT_COMPONENTS_ID;
      }

      // Resolve #imports and related aliases
      if (NUXT_IMPORT_IDS.has(id) || id.startsWith("#app/") || id.startsWith("#build/")) {
        return VIRTUAL_IMPORTS_ID;
      }

      return null;
    },

    load(id) {
      if (id === VIRTUAL_IMPORTS_ID) {
        return generateImportsModule(srcDir, options);
      }

      if (id === VIRTUAL_NUXT_COMPONENTS_ID) {
        return generateComponentsModule(srcDir);
      }

      return null;
    },
  };
}

function generateImportsModule(srcDir: string, options: NuxtMuseaOptions): string {
  const autoImportsPath = path.join(srcDir, "auto-imports.js").replace(/\\/g, "/");
  const configJson = JSON.stringify(options);

  return `
// Auto-generated by @vizejs/musea-nuxt
export * from '${autoImportsPath}';

// Configure mocks with provided options
import { configureNuxtMuseaMocks } from '${path.join(srcDir, "context.js").replace(/\\/g, "/")}';

const _config = ${configJson};
configureNuxtMuseaMocks(_config);
`;
}

function generateComponentsModule(srcDir: string): string {
  const componentsPath = path.join(srcDir, "mocks", "components.js").replace(/\\/g, "/");

  return `
// Auto-generated by @vizejs/musea-nuxt
export {
  NuxtLink,
  NuxtPage,
  ClientOnly,
  NuxtLayout,
  NuxtLoadingIndicator,
  NuxtErrorBoundary,
  NuxtRouteAnnouncer,
  NuxtWelcome,
  NuxtIsland,
  NuxtClientFallback,
  NuxtImg,
  NuxtPicture,
} from '${componentsPath}';
`;
}
