//! The recipes that turn the WHATWG snapshot excerpt into `whatwg.tsv`.
//!
//! One function per row. Each reads exactly the clause its anchor names and
//! fails loudly when the clause no longer says what the recipe expects, so a
//! spec edit that changes a set is a regeneration diff, never a silent drift.

use crate::html_spec::{Rule, Spec, start_tags};

pub const EXCERPT_HEADER: &str = "# WHATWG HTML Living Standard excerpt (Davinci P4-11a snapshot).\n# source: https://html.spec.whatwg.org/multipage/ — Last Updated 21 September 2026\n# Generated by: rust-script tools/commands/davinci/html-content-model.rs --extract\n";

const TABLE_HEADER: &str = include_str!("html_spec_table_header.txt");

/// Elements whose index Children column is a phrasing content model the
/// checker reads (`phrasing`, `phrasing*`, with heading content or ruby
/// annotations): every such row of the index is taken.
const PHRASING_EXTRAS: [(&str, &str); 3] = [
    ("phrasing; heading content", "@phrasing @heading"),
    ("phrasing*; heading content", "@phrasing @heading"),
    ("phrasing; rt; rp*", "@phrasing rt rp"),
];

/// Parents whose explicit children list the checker reads. `select`,
/// `optgroup`, `option` and `datalist` stay outside the domain while
/// browsers converge on the customizable-select content models; `html`
/// and `head` are document structure.
const LISTED_PARENTS: [&str; 12] = [
    "ul", "ol", "menu", "dl", "hgroup", "picture", "table", "thead", "tbody", "tfoot", "tr",
    "colgroup",
];

pub struct Row {
    kind: &'static str,
    name: String,
    anchor: String,
    members: Vec<String>,
}

pub fn row(kind: &'static str, name: &str, anchor: &str, members: Vec<String>) -> Row {
    Row {
        kind,
        name: name.to_string(),
        anchor: anchor.to_string(),
        members,
    }
}

pub fn dedupe(members: Vec<String>) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for member in members {
        if !out.contains(&member) {
            out.push(member);
        }
    }
    out
}

/// "MathML mi" / "SVG foreignObject" / "address" → table member syntax.
pub fn member(name: &str) -> String {
    let name = name.trim().trim_start_matches("and ").trim();
    if let Some(local) = name.strip_prefix("MathML ") {
        format!("math:{local}")
    } else if let Some(local) = name.strip_prefix("SVG ") {
        format!("svg:{local}")
    } else {
        name.trim_end_matches(" in the HTML namespace").to_string()
    }
}

pub fn between<'a>(text: &'a str, start: &str, end: &str) -> Result<&'a str, String> {
    let from = text
        .find(start)
        .ok_or_else(|| format!("clause changed: `{start}` not found"))?
        + start.len();
    let to = text[from..]
        .find(end)
        .ok_or_else(|| format!("clause changed: `{end}` not found after `{start}`"))?;
    Ok(&text[from..from + to])
}

/// The `- item` lines following `intro`.
pub fn items_after(text: &str, intro: &str) -> Result<Vec<String>, String> {
    let at = text
        .find(intro)
        .ok_or_else(|| format!("clause changed: `{intro}` not found"))?;
    Ok(text[at..]
        .lines()
        .skip(1)
        .take_while(|line| line.starts_with("- "))
        .map(|line| line[2..].to_string())
        .collect())
}

pub fn start_tag_rules<'r>(rules: &'r [Rule]) -> impl Iterator<Item = (Vec<String>, &'r Rule)> {
    rules.iter().map(|rule| {
        let tags = rule
            .conditions
            .iter()
            .flat_map(|condition| start_tags(condition))
            .collect();
        (tags, rule)
    })
}

/// The start tags of rules whose steps contain `phrase`.
pub fn tags_where(rules: &[Rule], phrase: &str) -> Vec<String> {
    start_tag_rules(rules)
        .filter(|(_, rule)| rule.steps.contains(phrase))
        .flat_map(|(tags, _)| tags)
        .collect()
}

/// The start tags of the first rule whose condition contains `needle`.
pub fn rule_tags(rules: &[Rule], needle: &str) -> Result<Vec<String>, String> {
    rules
        .iter()
        .find(|rule| {
            rule.conditions
                .iter()
                .any(|condition| condition.contains(needle))
        })
        .map(|rule| {
            rule.conditions
                .iter()
                .flat_map(|condition| start_tags(condition))
                .collect()
        })
        .ok_or_else(|| format!("clause changed: no rule for `{needle}`"))
}

pub fn table(spec: &Spec) -> Result<String, String> {
    let mut rows = crate::sets::sets(spec)?;
    rows.extend(categories(spec)?);
    rows.extend(children(spec)?);
    let mut out = String::from(TABLE_HEADER);
    let mut kind = "";
    for row in rows {
        if row.kind != kind && !kind.is_empty() {
            out.push('\n');
        }
        kind = row.kind;
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\n",
            row.kind,
            row.name,
            row.anchor,
            row.members.join(" ")
        ));
    }
    Ok(out)
}

fn categories(spec: &Spec) -> Result<Vec<Row>, String> {
    let find = |name: &str| {
        spec.categories
            .iter()
            .find(|cells| cells.first().is_some_and(|cell| cell == name))
            .ok_or_else(|| format!("index has no category {name}"))
    };
    let mut rows = Vec::new();
    for (name, label, anchor) in [
        ("phrasing", "Phrasing content", "dom.html#phrasing-content"),
        ("heading", "Heading content", "dom.html#heading-content"),
        (
            "interactive",
            "Interactive content",
            "dom.html#interactive-content",
        ),
        (
            "script-supporting",
            "Script-supporting elements",
            "dom.html#script-supporting-elements-2",
        ),
    ] {
        let cells = find(label)?;
        let mut members: Vec<String> = cells[1]
            .split("; ")
            .filter(|item| {
                *item != "autonomous custom elements" && *item != "form-associated custom elements"
            })
            .map(|item| {
                if item == "Text" {
                    "#text".to_string()
                } else {
                    member(item)
                }
            })
            .collect();
        for exception in cells.get(2).map_or("", String::as_str).split("); ") {
            if exception == "—" || exception.is_empty() {
                continue;
            }
            members.extend(conditional(exception)?);
        }
        rows.push(row("category", name, anchor, members));
    }
    Ok(rows)
}

/// "a (if the href attribute is present" → `a?href` (and friends).
fn conditional(exception: &str) -> Result<Vec<String>, String> {
    let exception = exception.trim_end_matches(')');
    let (name, condition) = exception
        .split_once(" (")
        .ok_or_else(|| format!("unrecognized category exception `{exception}`"))?;
    let conditions: &[&str] = match condition {
        "if it is a descendant of a map element" => &["in-map"],
        "if it is allowed in the body" => &["body-ok"],
        "if the itemprop attribute is present" => &["itemprop"],
        "if the href attribute is present" => &["href"],
        "if the controls attribute is present" => &["controls"],
        "if the usemap or controls attribute is present" => &["usemap", "controls"],
        "if the type attribute is not in the Hidden state" => &["type-not-hidden"],
        _ => return Err(format!("unrecognized category exception `{exception}`")),
    };
    Ok(conditions
        .iter()
        .map(|condition| format!("{name}?{condition}"))
        .collect())
}

fn children(spec: &Spec) -> Result<Vec<Row>, String> {
    let mut rows = Vec::new();
    let mut listed: Vec<Row> = Vec::new();
    for cells in &spec.elements {
        let (Some(names), Some(model)) = (cells.first(), cells.get(4)) else {
            continue;
        };
        for name in names.split(", ") {
            let anchor = anchor_for(name);
            let phrasing = match model.as_str() {
                "phrasing" | "phrasing*" => Some("@phrasing"),
                other => PHRASING_EXTRAS
                    .iter()
                    .find(|(text, _)| *text == other)
                    .map(|(_, members)| *members),
            };
            if let Some(members) = phrasing {
                rows.push(row(
                    "children",
                    name,
                    &anchor,
                    members.split(' ').map(str::to_string).collect(),
                ));
            } else if LISTED_PARENTS.contains(&name) {
                let members = model
                    .split("; ")
                    .map(|item| item.trim_end_matches('*'))
                    .map(|item| match item {
                        "script-supporting elements" => "@script-supporting".to_string(),
                        "one img" => "img".to_string(),
                        other => other.to_string(),
                    })
                    .collect();
                listed.push(row("children", name, &anchor, members));
            }
        }
    }
    listed.sort_by_key(|row| LISTED_PARENTS.iter().position(|name| *name == row.name));
    rows.extend(listed);
    Ok(rows)
}

fn anchor_for(name: &str) -> String {
    match name {
        "h1" | "h2" | "h3" | "h4" | "h5" | "h6" => {
            "sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements".to_string()
        }
        "sub" | "sup" => "text-level-semantics.html#the-sub-and-sup-elements".to_string(),
        _ => format!("indices.html#elements-3:{name}"),
    }
}
