//! `moonc` diagnostics, mapped back to the SFC through the span links.
//!
//! `moonc -error-format json` prints one object per line:
//! `{"$message_type":"diagnostic","level":"error","error_code":4014,
//! "path":"vize/sfc/App.vue.mbt","loc":"41:6-41:17","message":…}` with
//! `loc` in 1-based lines and end-exclusive columns counted in Unicode
//! scalar values ([`crate::lines`]). Mapping is exact or explicit:
//!
//! 1. a range inside one [`SpanLink`] maps to the authored bytes it was
//!    copied from, offset for offset;
//! 2. a range inside a position's projected statement but outside its
//!    links (the demand scaffolding) belongs to that position and maps to
//!    its whole expression;
//! 3. anything else is [`Origin::Projection`] — a diagnostic about the
//!    generated scaffolding itself, which the fixtures pin to zero.

use core::fmt;

use serde_json::Value;
use vize_s0::{Span, String, ToCompactString, cstr};

use crate::lines::{LineCol, Lines};
use crate::projection::{Projection, Role, SpanLink};

/// A diagnostic's severity, as `moonc` spells it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Level {
    /// `"error"`.
    Error,
    /// `"warning"`.
    Warning,
}

impl Level {
    /// The spelling `moonc` and the renderer use.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Error => "error",
            Self::Warning => "warning",
        }
    }
}

/// One `moonc` diagnostic line, parsed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MooncDiagnostic {
    /// Severity.
    pub level: Level,
    /// `moonc`'s error or warning number.
    pub code: u32,
    /// The package-qualified virtual path (`vize/sfc/App.vue.mbt`).
    pub path: String,
    /// Start position (inclusive).
    pub start: LineCol,
    /// End position (exclusive).
    pub end: LineCol,
    /// The message, verbatim.
    pub message: String,
}

/// Why a `moonc` line was not a diagnostic this dialect reads.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseError(pub String);

impl fmt::Display for ParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "unreadable moonc diagnostic: {}", self.0)
    }
}

/// Parse one `moonc -error-format json` line.
///
/// # Errors
///
/// [`ParseError`] naming the first field that is missing or malformed.
pub fn parse_line(line: &str) -> Result<MooncDiagnostic, ParseError> {
    let value: Value =
        serde_json::from_str(line).map_err(|error| ParseError(cstr!("not JSON ({error})")))?;
    let text = |field: &str| {
        value
            .get(field)
            .and_then(Value::as_str)
            .ok_or_else(|| ParseError(cstr!("`{field}` is not a string")))
    };
    if text("$message_type")? != "diagnostic" {
        return Err(ParseError(cstr!("`$message_type` is not \"diagnostic\"")));
    }
    let level = match text("level")? {
        "error" => Level::Error,
        "warning" => Level::Warning,
        other => return Err(ParseError(cstr!("unknown level `{other}`"))),
    };
    let code = value
        .get("error_code")
        .and_then(Value::as_u64)
        .and_then(|code| u32::try_from(code).ok())
        .ok_or_else(|| ParseError(cstr!("`error_code` is not a u32")))?;
    let loc = text("loc")?;
    let (start, end) = loc
        .split_once('-')
        .and_then(|(start, end)| Some((line_col(start)?, line_col(end)?)))
        .ok_or_else(|| ParseError(cstr!("`loc` `{loc}` is not `L:C-L:C`")))?;
    Ok(MooncDiagnostic {
        level,
        code,
        path: text("path")?.to_compact_string(),
        start,
        end,
        message: text("message")?.to_compact_string(),
    })
}

fn line_col(text: &str) -> Option<LineCol> {
    let (line, col) = text.split_once(':')?;
    Some(LineCol {
        line: line.parse().ok()?,
        col: col.parse().ok()?,
    })
}

/// Where a mapped diagnostic points.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Origin {
    /// The script block (the binding environment).
    Script,
    /// A template expression: the index into [`Projection::positions`].
    Template(usize),
    /// The generated scaffolding; no authored range exists.
    Projection,
}

/// A `moonc` diagnostic mapped back onto the SFC.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mapped {
    /// The diagnostic as `moonc` reported it.
    pub diagnostic: MooncDiagnostic,
    /// Which part of the SFC it belongs to.
    pub origin: Origin,
    /// The file-absolute authored range; `None` for
    /// [`Origin::Projection`].
    pub span: Option<Span>,
    /// The generated byte range in the projection (when it resolves).
    pub generated: Option<Span>,
}

/// Map one diagnostic through `projection`'s links.
#[must_use]
pub fn map(projection: &Projection<'_>, diagnostic: MooncDiagnostic) -> Mapped {
    let lines = Lines::new(&projection.text);
    let generated = lines
        .offset(diagnostic.start)
        .zip(lines.offset(diagnostic.end))
        .and_then(|(start, end)| {
            Some(Span::new(
                u32::try_from(start).ok()?,
                u32::try_from(end).ok()?,
            ))
        });
    let Some(range) = generated.filter(|range| range.start <= range.end) else {
        return Mapped {
            diagnostic,
            origin: Origin::Projection,
            span: None,
            generated,
        };
    };
    let (origin, span) = if let Some(link) = projection
        .links
        .iter()
        .find(|link| inside(range, link.generated))
    {
        let origin = match link.role {
            Role::Script => Origin::Script,
            Role::Expression(index) => Origin::Template(index),
        };
        (origin, Some(through(link, range)))
    } else if let Some((index, position)) = projection
        .positions
        .iter()
        .enumerate()
        .find(|(_, position)| inside(range, position.statement))
    {
        (Origin::Template(index), Some(position.expr.span))
    } else {
        (Origin::Projection, None)
    };
    Mapped {
        diagnostic,
        origin,
        span,
        generated,
    }
}

fn inside(range: Span, outer: Span) -> bool {
    outer.start <= range.start && range.end <= outer.end
}

/// The authored range for `range` inside `link`: offset for offset when
/// the link is a verbatim copy, the whole authored range otherwise.
fn through(link: &SpanLink, range: Span) -> Span {
    if link.generated.len() != link.source.len() {
        return link.source;
    }
    let start = link.source.start + (range.start - link.generated.start);
    Span::new(start, start + range.len())
}

/// Parse and map every line of one answer, in order.
///
/// # Errors
///
/// The first line that is not a diagnostic.
pub fn map_all(projection: &Projection<'_>, lines: &[String]) -> Result<Vec<Mapped>, ParseError> {
    lines
        .iter()
        .map(|line| parse_line(line).map(|diagnostic| map(projection, diagnostic)))
        .collect()
}
