//! Span-carrying emission for the DOM codegen (Davinci P3-9, S4).
//!
//! Every mapped token is written through one of these methods, which append
//! the generated bytes and record the authored span they come from in the same
//! call. The map is still assembled by the shared
//! [`SourceMapBuilder`](crate::codegen::source_map::SourceMapBuilder), and the
//! code buffer receives exactly the bytes a plain `push` would write, so the
//! emitted JavaScript is identical with maps on or off (TS-11).

use vize_s0::Span;

use super::CodegenContext;
use crate::codegen::helpers::escape_js_string;
use crate::codegen::spanned::expression_anchors;
use crate::{DirectiveNode, ElementNode, RootNode, RuntimeHelper, TemplateChildNode, TextNode};

/// Authored offset of the tag name of the first element (document order)
/// whose tag is exactly `tag`.
fn first_tag_offset(children: &[TemplateChildNode<'_>], tag: &str) -> Option<u32> {
    children.iter().find_map(|child| match child {
        TemplateChildNode::Element(el) if el.tag == tag => Some(el.loc.span.start + 1),
        TemplateChildNode::Element(el) => first_tag_offset(&el.children, tag),
        TemplateChildNode::If(node) => node
            .branches
            .iter()
            .find_map(|branch| first_tag_offset(&branch.children, tag)),
        TemplateChildNode::IfBranch(branch) => first_tag_offset(&branch.children, tag),
        TemplateChildNode::For(node) => first_tag_offset(&node.children, tag),
        _ => None,
    })
}

impl CodegenContext {
    /// Push `code` anchored at the authored byte `source_offset`.
    ///
    /// Used for tokens that are copies of authored bytes (tag names, static
    /// text, slot names) and for constructs that open an authored structural
    /// unit (a block, a branch, a slot function), anchored at the unit's `<`.
    #[inline]
    pub(in crate::codegen) fn push_mapped(&mut self, code: &str, source_offset: u32) {
        self.record_mapping(source_offset);
        self.push(code);
    }

    /// Push an element's tag name anchored at the authored tag name, the byte
    /// after the element's opening `<`.
    #[inline]
    pub(in crate::codegen) fn push_tag(&mut self, el: &ElementNode<'_>) {
        self.push_mapped(el.tag, el.loc.span.start + 1);
    }

    /// Push a text node's content as JavaScript string contents, anchored at
    /// the authored text.
    #[inline]
    pub(in crate::codegen) fn push_text(&mut self, text: &TextNode<'_>) {
        self.push_mapped(&escape_js_string(text.content), text.loc.span.start);
    }

    /// Push a slot's emitted name anchored at the `v-slot` argument that
    /// authored it; an argument-less `v-slot` authors no name token.
    #[inline]
    pub(in crate::codegen) fn push_slot_name(&mut self, code: &str, dir: &DirectiveNode<'_>) {
        match &dir.arg {
            Some(arg) => self.push_mapped(code, arg.loc().span.start),
            None => self.push(code),
        }
    }

    /// Push the `_withCtx` helper opening a slot function, anchored at the
    /// authored unit that carries the slot (`<template #name>` or the
    /// component with a root `v-slot`).
    pub(in crate::codegen) fn push_slot_function(&mut self, unit_start: u32) {
        self.use_helper(RuntimeHelper::WithCtx);
        self.push_mapped(self.helper(RuntimeHelper::WithCtx), unit_start);
    }

    /// Push a resolved component name anchored at the first element that
    /// authors it by that exact tag (asset resolution is shared by every use).
    pub(in crate::codegen) fn push_component_name(&mut self, name: &str, root: &RootNode<'_>) {
        if self.map_builder.is_some()
            && let Some(offset) = first_tag_offset(&root.children, name)
        {
            self.record_mapping(offset);
        }
        self.push(name);
    }

    /// Push a dynamic expression's emitted text anchored at its authored span.
    ///
    /// Besides the whole-expression anchor, every identifier the rewrite
    /// scoped (`_ctx.x`, `$setup.x`, `_unref(x)`) is anchored at its own first
    /// authored byte and carries its name, when the emitted text provably
    /// decomposes into the authored text plus rewrite insertions.
    ///
    /// An expression without an authored span (a synthesized node carrying the
    /// empty stub location) is emitted unanchored rather than mapped to the
    /// template start.
    pub(in crate::codegen) fn push_expression(&mut self, code: &str, span: Span) {
        if let Some(builder) = self.map_builder.as_mut() {
            builder.add_anchors(
                self.code.len(),
                &expression_anchors(code, span, &self.source),
            );
        }
        self.push(code);
    }
}
