//! Authored event forms exercised by the standard tsgo LSP oracle.

/// `(file, usage, declaration, name, ty, renamed, reference_shift, reference_len,
/// rename_supported)` for every authored event form the oracle navigates.
pub(crate) const EVENT_CASES: [(&str, &str, &str, &str, &str, &str, usize, usize, bool); 11] = [
    (
        "Child.vue",
        "@save",
        "save: [value",
        "save",
        "number",
        "renamedSave",
        0,
        "save".len(),
        true,
    ),
    (
        "ConditionalGenericChild.vue",
        "@confirm",
        "confirm: [value",
        "confirm",
        "\\\"conditional\\\"",
        "renamedConfirm",
        0,
        "confirm".len(),
        true,
    ),
    (
        "Child.vue",
        "@save-item",
        "saveItem: [id",
        "saveItem",
        "string",
        "renamedSaveItem",
        0,
        "saveItem".len(),
        false,
    ),
    (
        "CallSignatureChild.vue",
        "@submit",
        "\"submit\"",
        "submit",
        "boolean",
        "renamedSubmit",
        1,
        "submit".len(),
        true,
    ),
    (
        "DefaultModelChild.vue",
        "@update:modelValue",
        "defineModel",
        "update:modelValue",
        "number",
        "renamedModelValue",
        0,
        "defineModel".len(),
        false,
    ),
    (
        "DynamicGenericChild.vue",
        "@choose",
        "choose: [value",
        "choose",
        "\\\"top-level\\\"",
        "renamedChoose",
        0,
        "choose".len(),
        true,
    ),
    (
        "GenericChild.vue",
        "@pick",
        "pick: [value",
        "pick",
        "\\\"chosen\\\"",
        "renamedPick",
        0,
        "pick".len(),
        true,
    ),
    (
        "ModelChild.vue",
        "@update:title",
        "\"title\"",
        "update:title",
        "string",
        "renamedTitle",
        0,
        "\"title\"".len(),
        false,
    ),
    (
        "NestedGenericChild.vue",
        "@select",
        "select: [value",
        "select",
        "\\\"nested\\\"",
        "renamedSelect",
        0,
        "select".len(),
        true,
    ),
    (
        "RuntimeChild.vue",
        "@cancel",
        "cancel:",
        "cancel",
        "string",
        "renamedCancel",
        0,
        "cancel".len(),
        true,
    ),
    (
        "SlotGenericChild.vue",
        "@activate",
        "activate: [value",
        "activate",
        "\\\"slot\\\"",
        "renamedActivate",
        0,
        "activate".len(),
        true,
    ),
];
