/**
 * Generate one Musea story (`*.art.vue`) per `@vizejs/ui` family from its
 * `examples/*.vue` usage demos.
 *
 *   node scripts/generate-gallery.ts [--out <dir>]
 *
 * Stories are build outputs written to `gallery/stories/<area>/<family>.art.vue`
 * (gitignored). `examples/vite-musea` serves them with `pnpm gallery:ui`.
 * Each example becomes one variant; the first is the default. The story
 * targets the family's first exported SFC so Musea's prop palette and
 * docs panels describe the real component.
 */
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { uiFamilyCatalog } from "../src/catalog/family-catalog.ts";
import type { UiFamilyCatalogEntry } from "../src/catalog/family-catalog-types.ts";
import { componentExports } from "./reference-docs/extract.ts";
import { exampleOwner, exampleTitle } from "./source-registry-bundle/examples.ts";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Default output directory for generated stories. */
export const GALLERY_STORIES_DIRECTORY = path.join(packageRoot, "gallery", "stories");

/** One family's generated story. */
export interface GalleryStory {
  readonly family: string;
  /** Path relative to the stories directory. */
  readonly file: string;
  readonly examples: readonly string[];
  readonly source: string;
}

/** `src/families/<area>/…` -> `<area>`. */
export function familyArea(entry: UiFamilyCatalogEntry): string {
  return /^src\/families\/([^/]+)\//.exec(entry.entryFile)?.[1] ?? "other";
}

/** Absolute paths of a family's examples (`examples/<family>-*.vue`), sorted. */
export function familyExamples(entry: UiFamilyCatalogEntry): readonly string[] {
  const directory = path.join(packageRoot, path.dirname(entry.entryFile), "examples");
  if (!existsSync(directory)) return [];
  const siblings = uiFamilyCatalog
    .filter((candidate) => path.dirname(candidate.entryFile) === path.dirname(entry.entryFile))
    .map((candidate) => candidate.canonicalName);
  return readdirSync(directory)
    .filter((name) => name.endsWith(".vue") && exampleOwner(name, siblings) === entry.canonicalName)
    .sort()
    .map((name) => path.join(directory, name));
}

function pascal(name: string): string {
  return name
    .replace(/\.vue$/, "")
    .replace(/^[^a-z]*/, "")
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function titleCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function posixRelative(from: string, to: string): string {
  const relative = path.relative(from, to).split(path.sep).join("/");
  return relative.startsWith(".") ? relative : `./${relative}`;
}

/** Render the story for one family, or `null` when it has no examples. */
export function renderFamilyStory(
  entry: UiFamilyCatalogEntry,
  storiesDirectory = GALLERY_STORIES_DIRECTORY,
): GalleryStory | null {
  const examples = familyExamples(entry);
  if (examples.length === 0) return null;
  const file = `${familyArea(entry)}/${entry.canonicalName}.art.vue`;
  const storyDirectory = path.dirname(path.join(storiesDirectory, file));
  const target =
    componentExports(path.join(packageRoot, entry.entryFile))[0]?.file ?? examples[0] ?? "";
  const bindings = examples.map((example) => `${pascal(path.basename(example))}Example`);
  const meta = {
    title: entry.title,
    category: titleCase(familyArea(entry)),
    status:
      entry.maturity === "stable"
        ? "ready"
        : entry.maturity === "deprecated"
          ? "deprecated"
          : "draft",
    tags: [entry.canonicalName, ...entry.aliases],
  };
  const lines = [
    `<!-- Generated by npm/ui/scripts/generate-gallery.ts from ${entry.canonicalName}'s examples. Do not edit. -->`,
    '<script setup lang="ts">',
    ...examples.map(
      (example, index) =>
        `import ${bindings[index]} from ${JSON.stringify(posixRelative(storyDirectory, example))};`,
    ),
    "",
    `defineArt(${JSON.stringify(posixRelative(storyDirectory, target))}, {`,
    `  title: ${JSON.stringify(meta.title)},`,
    `  category: ${JSON.stringify(meta.category)},`,
    `  status: ${JSON.stringify(meta.status)},`,
    `  tags: ${JSON.stringify(meta.tags)},`,
    "});",
    "</script>",
    "",
    "<art>",
    ...examples.flatMap((example, index) => [
      `  <variant name=${JSON.stringify(exampleTitle(path.basename(example), entry.canonicalName))}${index === 0 ? " default" : ""}>`,
      `    <${bindings[index]} />`,
      "  </variant>",
    ]),
    "</art>",
    "",
  ];
  return {
    family: entry.canonicalName,
    file,
    examples: examples.map((example) =>
      path.relative(packageRoot, example).split(path.sep).join("/"),
    ),
    source: lines.join("\n"),
  };
}

/** Stories for every family that ships examples, in catalog order. */
export function renderGallery(
  storiesDirectory = GALLERY_STORIES_DIRECTORY,
): readonly GalleryStory[] {
  return uiFamilyCatalog.flatMap((entry) => {
    const story = renderFamilyStory(entry, storiesDirectory);
    return story == null ? [] : [story];
  });
}

/** Replace the stories directory with freshly generated stories. */
export function writeGallery(storiesDirectory = GALLERY_STORIES_DIRECTORY): number {
  const stories = renderGallery(storiesDirectory);
  rmSync(storiesDirectory, { recursive: true, force: true });
  for (const story of stories) {
    const target = path.join(storiesDirectory, story.file);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, story.source);
  }
  return stories.length;
}

/** Component families (entry exports at least one SFC) without any example. */
export function familiesMissingExamples(): readonly string[] {
  return uiFamilyCatalog
    .filter(
      (entry) =>
        componentExports(path.join(packageRoot, entry.entryFile)).length > 0 &&
        familyExamples(entry).length === 0,
    )
    .map((entry) => entry.canonicalName);
}

if (
  import.meta.url === pathToFileURL(process.argv[1] ?? "").href &&
  process.argv.includes("--check")
) {
  const missing = familiesMissingExamples();
  if (missing.length > 0) {
    process.stderr.write(
      `families without examples/<family>-basic.vue:\n${missing.map((name) => `  ${name}`).join("\n")}\n`,
    );
    process.exitCode = 1;
  } else {
    process.stdout.write("every component family ships at least one example\n");
  }
} else if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const outIndex = process.argv.indexOf("--out");
  const out =
    outIndex === -1 ? GALLERY_STORIES_DIRECTORY : path.resolve(process.argv[outIndex + 1] ?? ".");
  const count = writeGallery(out);
  process.stdout.write(`wrote ${count} Musea stories to ${path.relative(process.cwd(), out)}\n`);
}
