import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

// Read-only source-bound API observations. This does not accept a failed full
// workflow, execute Linux observers locally, or grant native/compiler closure.
const [zipFile, runFile, jobsFile, metadataFile, logFile, outputFile] = process.argv.slice(2);
assert(outputFile, "usage: ZIP RUN.json ATTEMPT_JOBS.json META.json JOB.log OUT.json");
assert(!fs.existsSync(outputFile), "never overwrite an existing capture audit");
const root = "/private/tmp/vize-compiler-history-foundation-main-20261002";
const review = "/private/tmp/vize-compiler-dd6-review-20261002";
const stage = path.join(review, "closure-3");
const source = "34b1713bc2156929a6087648e028129823db4cef";
const sourceTree = "969ea15a40444314ed6d30d9acdd222d663d3253";
const read = (file: string) => fs.readFileSync(file);
const json = (file: string) => JSON.parse(read(file).toString());
const hash = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
const raw = (...args: string[]) => execFileSync("git", ["--no-replace-objects", ...args], { cwd: root, maxBuffer: 32 * 1024 * 1024 });
const git = (...args: string[]) => raw(...args).toString().trimEnd();
assert.equal(git("rev-parse", `${source}^{tree}`), sourceTree);
assert.equal(git("rev-parse", "HEAD"), source);
assert.equal(git("status", "--porcelain=v1"), "");
const closure = json(path.join(review, "closure-3-receipt.json"));
// The exact recursive imports were strictly checked before the source freeze.
const closureFiles = ["tests/differential/compiler-api.ts", "tests/differential/compiler-api-manifest.ts", "tests/differential/compiler-api-types.ts", "tests/differential/observer-build.ts", "tests/differential/harness.mjs", "tests/differential/acceptance-rates.mjs"];
for (const file of closureFiles) assert(read(path.join(stage, file)).equals(raw("show", `${source}:${file}`)), `actual imported source ${file}`);
assert(closure, "retain the original strict closure receipt");
const manifest = await import(pathToFileURL(path.join(stage, "tests/differential/compiler-api-manifest.ts")).href);
const adapter = await import(pathToFileURL(path.join(stage, "tests/differential/compiler-api.ts")).href);
const harness = await import(pathToFileURL(path.join(stage, "tests/differential/harness.mjs")).href);
const plan = json(path.join(review, "temporary-proof-campaign/plan.json"));
assert.equal(plan.source.revision, source);
assert.equal(plan.source.tree, sourceTree);
assert.deepEqual(Object.keys(manifest.COMPILER_TARGET_CONTRACTS), ["dom", "ssr", "vapor"]);
assert.deepEqual(plan.actualApiCapture.cohorts.map((cohort: { target: string }) => cohort.target), ["dom", "ssr", "vapor"]);
const run = json(runFile), allJobs = json(jobsFile), metadata = json(metadataFile);
assert.equal(run.id, 36952506161);
assert.equal(run.head_sha, source);
assert.equal(run.head_branch, plan.source.temporaryRef);
assert.equal(run.run_attempt, 1);
assert.equal(run.event, "workflow_dispatch");
assert.equal(run.path, ".github/workflows/check.yml");
assert.equal(run.repository.full_name, "ubugeeei-prod/vize");
assert.equal(run.status, "completed", "record the final full workflow conclusion");
assert(["success", "failure"].includes(run.conclusion));
assert.equal(allJobs.jobs.length, allJobs.total_count, "complete actual attempt jobs, not a partial page");
const matching = allJobs.jobs.filter((job: { name: string; run_attempt: number }) => job.name === "test-scripts" && job.run_attempt === run.run_attempt);
assert.equal(matching.length, 1);
const job = matching[0];
assert.equal(job.id, 110668305314);
assert.equal(job.run_id, run.id);
assert.equal(job.head_sha, source);
assert.equal(job.status, "completed");
assert(["success", "failure"].includes(job.conclusion));
for (const name of ["Build vize CLI", "Install vize CLI", "Prepare the pinned plugin isolation runtime"]) {
  const steps = job.steps.filter((step: { name: string }) => step.name === name);
  assert.equal(steps.length, 1);
  assert.equal(steps[0].conclusion, "success");
}
assert.equal(metadata.expired, false);
assert.equal(metadata.workflow_run.id, run.id);
assert.equal(metadata.workflow_run.head_sha, source);
assert.equal(metadata.workflow_run.head_branch, run.head_branch);
assert.equal(metadata.name, `formatter-api-corpus-${run.id}-${run.run_attempt}-test-scripts-full`);
assert.equal(metadata.digest, `sha256:${hash(read(zipFile))}`);
assert.equal(metadata.size_in_bytes, fs.statSync(zipFile).size);
const listed = spawnSync("unzip", ["-Z", "-1", zipFile], { encoding: "utf8", maxBuffer: 8 * 1024 * 1024 });
assert.equal(listed.status, 0, listed.stderr);
const entries = listed.stdout.trimEnd().split("\n");
assert(entries.every((entry: string) => !path.isAbsolute(entry) && !entry.split("/").some(part => [".", ".."].includes(part))));
const evidenceFiles: { path: string; bytes: number; sha256: string }[] = [];
function evidence(relative: string): Buffer {
  assert.equal(entries.filter((entry: string) => entry === relative).length, 1);
  const extracted = spawnSync("unzip", ["-p", zipFile, relative], { maxBuffer: 128 * 1024 * 1024 });
  assert.equal(extracted.status, 0, extracted.stderr?.toString());
  const bytes = extracted.stdout;
  if (!evidenceFiles.some(file => file.path === relative)) evidenceFiles.push({ path: relative, bytes: bytes.length, sha256: hash(bytes) });
  return bytes;
}
const evidenceJson = (relative: string) => JSON.parse(evidence(relative).toString());
const log = read(logFile).toString();
const resultLines = log.split("\n").map(line => line.replace(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z\s+/, "").replace(/\u001b\[[\d;]*m/g, ""));
assert(log.includes(source), "retain the actual checkout/source receipt in the authenticated job log");
const cli = evidenceJson("ci/vize.differential-build.json");
assert.equal(cli.sourceRevision, source);
assert(log.includes(`"sourceRevision": "${source}"`));
assert(log.includes(`"binarySha256": "${cli.binarySha256}"`));
const expectedSummary = { plannedCases: 5, legacyMatches: 5, baselineDrift: 0, legacyFailures: 0, nativeUnsupported: 5, nativeHandled: 0, nativeEquivalent: 0, pairedComparisons: 0 };
const outcomes = [];
for (const cohort of plan.actualApiCapture.cohorts) {
  const loaded = manifest.loadCompilerApiManifest(path.join(stage, cohort.manifestFile), stage);
  assert.equal(loaded.target, cohort.target);
  assert.equal(loaded.manifestSha256, cohort.manifestSha256);
  assert.deepEqual(loaded.contract.spec, cohort.spec);
  assert.equal(loaded.cases.length, 5);
  assert(read(path.join(stage, cohort.manifestFile)).equals(raw("show", `${source}:${cohort.manifestFile}`)));
  for (const fixture of loaded.cases) assert(fixture.input.equals(raw("show", `${source}:${fixture.inputs.files[0].path}`)));
  const relative = (file: string) => `differential/compiler-api/${cohort.target}/${file}`;
  const report = evidenceJson(relative("report.json"));
  harness.validateResultEnvelope(loaded, report, source);
  assert.equal(report.failure, null);
  assert.deepEqual(report.summary, expectedSummary);
  assert.deepEqual(report.rows, adapter.compilerApiRows(loaded, report.attempts, null));
  assert.deepEqual(evidenceJson(relative("unverified-report.json")), report);
  const receipt = evidenceJson(relative("build-receipt.json"));
  assert.deepEqual(receipt, report.buildReceipt);
  assert.equal(receipt.schema, "vize.differential.observer-build");
  assert.equal(receipt.version, 1);
  assert.deepEqual(receipt.spec, cohort.spec);
  assert.deepEqual(receipt.source, { sourceRevision: source, sourceTree, productSourceTree: git("rev-parse", `${source}:crates/${cohort.spec.packageName}/src`), cargoLockSha256: hash(raw("show", `${source}:Cargo.lock`)), observerSourceSha256: hash(raw("show", `${source}:${cohort.spec.sourcePath}`)) });
  assert.equal(receipt.profileName, "ci");
  assert.equal(receipt.offline, false);
  assert.equal(receipt.exitStatus, 0);
  assert.deepEqual(receipt.command, cohort.cargoCommand);
  assert.match(receipt.toolchain.rustc, /^rustc \d+\.\d+\.\d+/);
  assert.match(receipt.toolchain.cargo, /^cargo \d+\.\d+\.\d+/);
  assert.equal(receipt.probes.length, 1);
  const probe = receipt.probes[0];
  assert.deepEqual(probe.argv, ["--contract"]);
  assert.equal(probe.exitStatus, 0);
  const probeBytes = Buffer.from(probe.stdoutBase64, "base64");
  assert.equal(probeBytes.toString("base64"), probe.stdoutBase64);
  assert.equal(hash(probeBytes), probe.sha256);
  assert.deepEqual(JSON.parse(probeBytes.toString()), { schema: loaded.contract.packetSchema, version: 1, cases: loaded.contract.ids, fields: loaded.contract.fields, native: "unsupported" });
  assert.deepEqual(receipt.artifact.features, cohort.spec.expectedFeatures);
  assert.equal(receipt.artifact.target.name, cohort.spec.exampleName);
  assert.deepEqual(receipt.artifact.target.kind, ["example"]);
  assert.equal(receipt.artifact.profile.test, false);
  assert(receipt.artifact.target.src_path.endsWith(`/${cohort.spec.sourcePath}`));
  assert.equal(hash(evidence(relative(cohort.spec.exampleName))), receipt.artifact.sha256);
  const cargoStdout = evidence(relative("cargo.jsonl"));
  assert.equal(hash(cargoStdout), receipt.logs.stdout.sha256);
  assert.equal(hash(evidence(relative("cargo.stderr.txt"))), receipt.logs.stderr.sha256);
  const cargo = cargoStdout.toString().trim().split("\n").map((line: string) => JSON.parse(line));
  assert.deepEqual(cargo.filter((entry: { reason: string }) => entry.reason === "build-finished").map((entry: { success: boolean }) => entry.success), [true]);
  const selected = cargo.filter((entry: { reason: string; target?: { name: string }; executable?: string }) => entry.reason === "compiler-artifact" && entry.target?.name === cohort.spec.exampleName && entry.executable);
  assert.equal(selected.length, 1);
  for (const [key, expected] of Object.entries({ target: receipt.artifact.target, features: receipt.artifact.features, profile: receipt.artifact.profile, package_id: receipt.artifact.packageId, executable: receipt.artifact.cargoExecutable })) assert.deepEqual(selected[0][key], expected);
  const attempts = ["first", "repeat", "revalidation"].map(label => evidenceJson(relative(`${label}.attempt.json`)));
  assert.deepEqual(attempts[0], report.attempts[0]);
  assert.deepEqual(attempts[1], report.attempts[1]);
  assert.deepEqual(attempts[2], attempts[0]);
  for (const attempt of attempts) {
    assert.equal(Buffer.from(attempt.stdoutBase64, "base64").toString("base64"), attempt.stdoutBase64);
    assert.equal(Buffer.from(attempt.stderrBase64, "base64").toString("base64"), attempt.stderrBase64);
    assert.equal(attempt.stderrBase64, "");
  }
  const title = `shared compiler ${cohort.target} corpus observes five complete outputs from its source-built artifact`;
  const escaped = title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const passed = new RegExp(`^(?:ok \\d+ - |✔ )${escaped}(?:$| \\()`);
  const failed = new RegExp(`^(?:not ok \\d+ - |✖ )${escaped}(?:$| \\(| #)`);
  assert(resultLines.some(line => passed.test(line)), `actual successful API test ${cohort.target}`);
  assert(!resultLines.some(line => failed.test(line)), `failed API result cannot authenticate ${cohort.target}`);
  outcomes.push({ target: cohort.target, ids: report.rows.map((row: { id: string }) => row.id), summary: report.summary, originalOptionsAndCompleteResultsVerified: true, manifestSha256: loaded.manifestSha256, sourceBuiltObserverSha256: receipt.artifact.sha256, repeatedStdoutSha256: attempts[0].stdoutSha256, toolchain: receipt.toolchain });
}
assert.equal(outcomes.length, 3);
assert.deepEqual(outcomes.map(outcome => outcome.target), ["dom", "ssr", "vapor"]);
const verifiedCaseIds = outcomes.flatMap(outcome => outcome.ids);
const verifiedCaseCount = new Set<string>(verifiedCaseIds).size;
assert.equal(verifiedCaseIds.length, 15);
assert.equal(verifiedCaseCount, verifiedCaseIds.length, "all fifteen actual case identities must be distinct");
for (const outcome of outcomes) assert.deepEqual(outcome.toolchain, outcomes[0].toolchain);
const failedJobs = allJobs.jobs.filter((job: { conclusion: string }) => job.conclusion === "failure").map((job: { id: number; name: string; steps: { name: string; conclusion: string }[] }) => ({ id: job.id, name: job.name, failedSteps: job.steps.filter(step => step.conclusion === "failure").map(step => step.name) }));
const result = { schema: "vize.compiler.api-observations.partial-workflow-audit", version: 1, source: { revision: source, tree: sourceTree }, host: { runId: run.id, attempt: run.run_attempt, jobId: job.id, artifactId: metadata.id, artifactDigest: metadata.digest }, fullWorkflow: { status: run.status, conclusion: run.conclusion, accepted: run.conclusion === "success", failedJobs }, toolingJob: { status: job.status, conclusion: job.conclusion, accepted: job.conclusion === "success" }, downloadedZipBytesVerified: true, cargoLogsAndSelectedBinaryBytesVerified: true, allOriginalInputsOptionsAndCompleteResultsVerified: true, actualRepeatAndRevalidationBytesVerified: true, localCargoOrObserverExecution: false, actualApiCasesAtThisExactSource: verifiedCaseCount, differentHeadCaptureCredit: 0, outcomes, evidenceFiles: evidenceFiles.sort((a, b) => a.path.localeCompare(b.path)), authenticatedInputHashes: [runFile, jobsFile, metadataFile, logFile].map(file => ({ path: file, sha256: hash(read(file)) })), authority: "Authenticated GitHub connector/raw root transport inputs are required. Literal ZIP bytes and authentic successful in-job API laws establish this bounded source proof; this does not waive any failed full workflow or credit a later head.", fullHistoryClosed: false, semanticDenominator: null, nativeHandled: 0, nativeEquivalent: 0 };
fs.writeFileSync(outputFile, JSON.stringify(result, null, 2) + "\n");
console.log(JSON.stringify({ outputFile, source, actualApiCases: verifiedCaseCount, fullWorkflowConclusion: run.conclusion, fullWorkflowAccepted: result.fullWorkflow.accepted, toolingJobConclusion: job.conclusion, nativeHandled: 0 }));
