//! Type-aware probes read the checker’s virtual TypeScript document.
//!
//! The text is the S4 emission document Canon returns. Markers are inserted
//! at the setup close that document writes, `// Invoke setup to verify types`.

use vize_atelier_sfc::SfcDescriptor;
use vize_atelier_sfc::croquis::{SfcCroquisOptions, analyze_sfc_descriptor};
use vize_canon::virtual_ts::{
    ProjectionMapping, VirtualTsOptions, generate_virtual_ts_with_offsets,
    generate_virtual_ts_with_offsets_options_api,
};
use vize_relief::RootNode;
use vize_s0::String;

pub(super) struct TypeAwareDocument {
    pub content: String,
    pub mapping: ProjectionMapping,
}

impl TypeAwareDocument {
    /// Generated byte for an authored SFC offset, when the document maps it.
    pub(super) fn generated_offset(&self, source_offset: u32) -> Option<u32> {
        self.mapping
            .to_generated(source_offset as usize)
            .and_then(|offset| u32::try_from(offset).ok())
    }
}

pub(super) fn project_type_aware<'a>(
    descriptor: &SfcDescriptor<'a>,
    script_content: &str,
    template: Option<&RootNode<'a>>,
    script_offset: u32,
    template_offset: u32,
    filename: &str,
) -> TypeAwareDocument {
    // Lint analysis skips template expressions. The checker document needs
    // them so a probe can type the expression the author wrote.
    let mut options = SfcCroquisOptions::lint_demand();
    options.analyzer_options.collect_template_expressions = true;
    let analysis = analyze_sfc_descriptor(descriptor, template, options);
    let ts_options = VirtualTsOptions::default();
    let output = if descriptor.script_setup.is_none() && descriptor.script.is_some() {
        generate_virtual_ts_with_offsets_options_api(
            &analysis,
            Some(script_content),
            template,
            script_offset,
            template_offset,
            &ts_options,
        )
    } else {
        generate_virtual_ts_with_offsets(
            &analysis,
            Some(script_content),
            template,
            script_offset,
            template_offset,
            &ts_options,
        )
    };
    let mut document = TypeAwareDocument {
        content: output.code,
        mapping: output.mapping,
    };
    super::expression_bindings::hoist_type_imports(&mut document, script_content);
    super::expression_bindings::bind_template_expressions(&mut document);
    super::relative_imports::absolutize_relative_imports(&mut document, filename);
    // An unresolved `Ref` is `any` to this check, and the stock alias then
    // forces that prop through the boolean intersection. The alias text is
    // pinned in Canon snapshots, so only this checker document changes.
    keep_any_out_of_boolean_keys(&mut document);
    document
}

const BOOLEAN_KEY_ALIAS: &str = "type __VizeBooleanKey<T, K extends keyof T = keyof T> = K extends any ? [Exclude<T[K], undefined>] extends [never] ? never : [Exclude<T[K], undefined>] extends [boolean] ? K : never : never;";
const BOOLEAN_KEY_PATCHED: &str = "type __VizeBooleanKey<T, K extends keyof T = keyof T> = K extends any ? __VizeIsAny<Exclude<T[K], undefined>> extends true ? never : [Exclude<T[K], undefined>] extends [never] ? never : [Exclude<T[K], undefined>] extends [boolean] ? K : never : never;";

fn keep_any_out_of_boolean_keys(document: &mut TypeAwareDocument) {
    let mut text = document.content.clone();
    let mut found = Vec::new();
    let mut search = 0usize;
    while let Some(relative) = text
        .get(search..)
        .and_then(|rest| rest.find(BOOLEAN_KEY_ALIAS))
    {
        let at = search + relative;
        found.push(at);
        search = at + BOOLEAN_KEY_ALIAS.len();
    }
    for start in found.into_iter().rev() {
        document.mapping.note_generated_replacement(
            start,
            BOOLEAN_KEY_ALIAS.len(),
            BOOLEAN_KEY_PATCHED.len(),
        );
        text.replace_range(start..start + BOOLEAN_KEY_ALIAS.len(), BOOLEAN_KEY_PATCHED);
    }
    document.content = text;
}

#[cfg(test)]
#[expect(clippy::string_slice, reason = "tests assert by panicking")]
mod tests {
    use super::{BOOLEAN_KEY_PATCHED, project_type_aware};
    use crate::linter::native_type_aware::markers::marker_insert_offset;

    #[test]
    fn canon_document_closes_setup_where_markers_insert() {
        let source = "<script setup lang=\"ts\">\nconst message = 'Hello'\n</script>\n<template><p>{{ message }}</p></template>\n";
        let descriptor =
            vize_atelier_sfc::parse_sfc(source, vize_atelier_sfc::SfcParseOptions::default())
                .expect("sfc");
        let template = descriptor.template.as_ref().expect("template");
        let allocator = vize_s0::Allocator::new();
        let (root, _) = vize_armature::parse(&allocator, template.content.as_ref());
        let script = descriptor.script_setup.as_ref().expect("script");
        let document = project_type_aware(
            &descriptor,
            script.content.as_ref(),
            Some(&root),
            script.loc.start as u32,
            template.loc.start as u32,
            "Fixture.vue",
        );
        let insert = marker_insert_offset(&document.content).expect("setup close");
        let marker = "}\n\n// Invoke setup to verify types\n";
        assert_eq!(&document.content[insert..insert + marker.len()], marker);
    }

    #[test]
    fn member_expression_maps_into_the_checker_document() {
        let source = "<script setup lang=\"ts\">\nconst payload: any = { title: \"Untyped\" };\n</script>\n\n<template>\n  <p>{{ payload.title }}</p>\n</template>\n";
        let descriptor =
            vize_atelier_sfc::parse_sfc(source, vize_atelier_sfc::SfcParseOptions::default())
                .expect("sfc");
        let template = descriptor.template.as_ref().expect("template");
        let allocator = vize_s0::Allocator::new();
        let (root, _) = vize_armature::parse(&allocator, template.content.as_ref());
        let script = descriptor.script_setup.as_ref().expect("script");
        let document = project_type_aware(
            &descriptor,
            script.content.as_ref(),
            Some(&root),
            script.loc.start as u32,
            template.loc.start as u32,
            "Fixture.vue",
        );
        let body = template.content.as_ref();
        let at = body.find("payload.title").expect("expression");
        let source_offset =
            template.loc.start as u32 + at as u32 + "payload.title".len() as u32 - 1;
        assert!(
            document.generated_offset(source_offset).is_some(),
            "template expression was not projected"
        );
    }

    #[test]
    fn an_unresolved_ref_is_not_forced_through_the_boolean_key() {
        let source = "<script setup lang=\"ts\">\nimport type { Ref } from 'vue'\nconst props = defineProps<{ count: Ref<number> }>()\n</script>\n";
        let descriptor =
            vize_atelier_sfc::parse_sfc(source, vize_atelier_sfc::SfcParseOptions::default())
                .expect("sfc");
        let script = descriptor.script_setup.as_ref().expect("script");
        let document = project_type_aware(
            &descriptor,
            script.content.as_ref(),
            None,
            script.loc.start as u32,
            0,
            "Component.vue",
        );
        let expected_alias = format!(
            "{BOOLEAN_KEY_PATCHED} type __DefineProps<T, __BKeys extends keyof T = __VizeBooleanKey<T>> = Readonly<T> & {{ readonly [K in __BKeys]-?: boolean }};"
        );
        let boolean_aliases: Vec<_> = document
            .content
            .as_str()
            .lines()
            .filter(|line| line.starts_with("type __VizeBooleanKey<"))
            .collect();
        assert_eq!(boolean_aliases, vec![expected_alias.as_str()]);
    }
}
