//! Type-aware probes read the checker’s virtual TypeScript document.
//!
//! The text is the S4 emission document Canon returns. Markers are inserted
//! at the setup close that document writes, `// Invoke setup to verify types`.

use vize_atelier_sfc::SfcDescriptor;
use vize_atelier_sfc::croquis::{SfcCroquisOptions, analyze_sfc_descriptor};
use vize_canon::virtual_ts::{
    ProjectionMapping, VirtualTsOptions, generate_virtual_ts_with_offsets,
};
use vize_relief::RootNode;
use vize_s0::String;

pub(super) struct TypeAwareDocument {
    pub content: String,
    pub mapping: ProjectionMapping,
}

impl TypeAwareDocument {
    /// Generated byte for an authored SFC offset, when the document maps it.
    pub(super) fn generated_offset(&self, source_offset: u32) -> Option<u32> {
        self.mapping
            .to_generated(source_offset as usize)
            .and_then(|offset| u32::try_from(offset).ok())
    }
}

pub(super) fn project_type_aware<'a>(
    descriptor: &SfcDescriptor<'a>,
    script_content: &str,
    template: Option<&RootNode<'a>>,
    script_offset: u32,
    template_offset: u32,
) -> TypeAwareDocument {
    // Lint analysis skips template expressions. The checker document needs
    // them so a probe can type the expression the author wrote.
    let mut options = SfcCroquisOptions::for_lint();
    options.analyzer_options.collect_template_expressions = true;
    let analysis = analyze_sfc_descriptor(descriptor, template, options);
    let output = generate_virtual_ts_with_offsets(
        &analysis,
        Some(script_content),
        template,
        script_offset,
        template_offset,
        &VirtualTsOptions::default(),
    );
    TypeAwareDocument {
        content: output.code,
        mapping: output.mapping,
    }
}

#[cfg(test)]
mod tests {
    use super::project_type_aware;
    use crate::linter::native_type_aware::markers::marker_insert_offset;

    #[test]
    fn canon_document_closes_setup_where_markers_insert() {
        let source = "<script setup lang=\"ts\">\nconst message = 'Hello'\n</script>\n<template><p>{{ message }}</p></template>\n";
        let descriptor =
            vize_atelier_sfc::parse_sfc(source, vize_atelier_sfc::SfcParseOptions::default())
                .expect("sfc");
        let template = descriptor.template.as_ref().expect("template");
        let allocator = vize_s0::Allocator::new();
        let (root, _) = vize_armature::parse(&allocator, template.content.as_ref());
        let script = descriptor.script_setup.as_ref().expect("script");
        let document = project_type_aware(
            &descriptor,
            script.content.as_ref(),
            Some(&root),
            script.loc.start as u32,
            template.loc.start as u32,
        );
        let insert = marker_insert_offset(&document.content).expect("setup close");
        assert!(
            document.content[insert..].starts_with("}\n\n// Invoke setup to verify types\n"),
            "{}",
            &document.content[insert.saturating_sub(40)..]
        );
    }

    #[test]
    fn member_expression_maps_into_the_checker_document() {
        let source = "<script setup lang=\"ts\">\nconst payload: any = { title: \"Untyped\" };\n</script>\n\n<template>\n  <p>{{ payload.title }}</p>\n</template>\n";
        let descriptor =
            vize_atelier_sfc::parse_sfc(source, vize_atelier_sfc::SfcParseOptions::default())
                .expect("sfc");
        let template = descriptor.template.as_ref().expect("template");
        let allocator = vize_s0::Allocator::new();
        let (root, _) = vize_armature::parse(&allocator, template.content.as_ref());
        let script = descriptor.script_setup.as_ref().expect("script");
        let document = project_type_aware(
            &descriptor,
            script.content.as_ref(),
            Some(&root),
            script.loc.start as u32,
            template.loc.start as u32,
        );
        let body = template.content.as_ref();
        let at = body.find("payload.title").expect("expression");
        let source_offset =
            template.loc.start as u32 + at as u32 + "payload.title".len() as u32 - 1;
        assert!(
            document.generated_offset(source_offset).is_some(),
            "template expression was not projected"
        );
    }
}
