//! Script virtual code generation.
//!
//! Preserves script content and generates bindings export for template.
#![allow(clippy::disallowed_types, clippy::disallowed_methods)]

use vize_atelier_sfc::SfcScriptBlock;
use vize_croquis::{Drawer, DrawerOptions};

use super::{
    MappingFeatures, SourceMap, SourceMapping, SourceRange, VirtualDocument, VirtualLanguage,
};

/// Script code generator.
pub struct ScriptCodeGenerator {
    /// Generated output
    output: String,
    /// Source mappings
    mappings: Vec<SourceMapping>,
    /// Current position in generated output
    gen_offset: u32,
    /// Block offset in original SFC
    block_offset: u32,
}

impl ScriptCodeGenerator {
    /// Create a new script code generator.
    pub fn new() -> Self {
        Self {
            output: String::new(),
            mappings: Vec::new(),
            gen_offset: 0,
            block_offset: 0,
        }
    }

    /// Generate virtual TypeScript from a script block.
    pub fn generate(&mut self, script: &SfcScriptBlock, is_setup: bool) -> VirtualDocument {
        // Reset state
        self.output.clear();
        self.mappings.clear();
        self.gen_offset = 0;
        self.block_offset = script.loc.start as u32;

        // Generate header comment
        if is_setup {
            self.write_line("// Virtual TypeScript for <script setup>");
        } else {
            self.write_line("// Virtual TypeScript for <script>");
        }
        self.write_line("// Generated by vize_maestro");
        self.write_line("");

        // Track the start of the actual content
        let content_gen_start = self.gen_offset;

        // Write the script content with 1:1 mapping
        let content = script.content.as_ref();
        self.write(content);

        // Create a mapping for the entire content
        let content_len = content.len() as u32;
        if content_len > 0 {
            self.mappings.push(SourceMapping::with_features(
                SourceRange::new(0, content_len),
                SourceRange::new(content_gen_start, content_gen_start + content_len),
                MappingFeatures::all(),
            ));
        }

        // Add newline if needed
        if !content.ends_with('\n') {
            self.write_line("");
        }

        // Create source map
        let mut source_map = SourceMap::from_mappings(self.mappings.clone());
        source_map.set_block_offset(self.block_offset);

        VirtualDocument {
            uri: String::new(), // Will be set by generator
            content: self.output.clone(),
            language: if is_setup {
                VirtualLanguage::ScriptSetup
            } else {
                VirtualLanguage::Script
            },
            source_map,
        }
    }

    /// Generate with binding exports for template usage.
    pub fn generate_with_exports(
        &mut self,
        script: &SfcScriptBlock,
        is_setup: bool,
        bindings: &[String],
    ) -> VirtualDocument {
        // Reset state
        self.output.clear();
        self.mappings.clear();
        self.gen_offset = 0;
        self.block_offset = script.loc.start as u32;

        // Generate header
        if is_setup {
            self.write_line("// Virtual TypeScript for <script setup> with exports");
        } else {
            self.write_line("// Virtual TypeScript for <script> with exports");
        }
        self.write_line("// Generated by vize_maestro");
        self.write_line("");

        // Track content start
        let content_gen_start = self.gen_offset;

        // Write the script content
        let content = script.content.as_ref();
        self.write(content);

        // Create mapping for content
        let content_len = content.len() as u32;
        if content_len > 0 {
            self.mappings.push(SourceMapping::with_features(
                SourceRange::new(0, content_len),
                SourceRange::new(content_gen_start, content_gen_start + content_len),
                MappingFeatures::all(),
            ));
        }

        // Add newline
        if !content.ends_with('\n') {
            self.write_line("");
        }

        // Generate export for template context
        if !bindings.is_empty() {
            self.write_line("");
            self.write_line("// Exports for template");
            self.write("export { ");
            self.write(&bindings.join(", "));
            self.write_line(" };");
        }

        // Create source map
        let mut source_map = SourceMap::from_mappings(self.mappings.clone());
        source_map.set_block_offset(self.block_offset);

        VirtualDocument {
            uri: String::new(),
            content: self.output.clone(),
            language: if is_setup {
                VirtualLanguage::ScriptSetup
            } else {
                VirtualLanguage::Script
            },
            source_map,
        }
    }

    fn write(&mut self, s: &str) {
        self.output.push_str(s);
        self.gen_offset += s.len() as u32;
    }

    fn write_line(&mut self, s: &str) {
        self.output.push_str(s);
        self.output.push('\n');
        self.gen_offset += s.len() as u32 + 1;
    }
}

impl Default for ScriptCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

/// Extract binding names from script content.
///
/// The compatibility name is retained for downstream callers, but extraction
/// is backed by Croquis' parsed semantic snapshot rather than source scanning.
pub fn extract_simple_bindings(content: &str, is_setup: bool) -> Vec<String> {
    if !is_setup {
        return Vec::new();
    }

    let mut drawer = Drawer::with_options(DrawerOptions {
        analyze_script: true,
        ..DrawerOptions::default()
    });
    drawer.analyze_script_setup(content);
    drawer
        .croquis()
        .semantic_snapshot()
        .bindings
        .into_iter()
        .map(|binding| binding.name.to_string())
        .collect()
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::extract_simple_bindings;

    #[test]
    fn semantic_binding_extraction_handles_complete_binding_patterns() {
        let content = r#"
import DefaultWidget, {
    helper as importedHelper,
    type SourceShape,
} from './source'
import * as utilities from './utilities'
import type { TypeOnly } from './types'

const {
    api: client,
    label: localLabel = 'fallback',
    nested: { value: nestedValue },
    urls: [firstUrl, ...remainingUrls],
    ...runtimeRest
} = useRuntimeConfig()
const [head, , { value: tailValue = 0 }, ...tailItems] = remainingUrls
const 挨拶 = 'こんにちは'
function handleClick() {}
class Controller {}
"#;

        let actual = extract_simple_bindings(content, true)
            .into_iter()
            .collect::<BTreeSet<_>>();
        let expected = [
            "Controller",
            "DefaultWidget",
            "client",
            "firstUrl",
            "handleClick",
            "head",
            "importedHelper",
            "localLabel",
            "nestedValue",
            "remainingUrls",
            "runtimeRest",
            "tailItems",
            "tailValue",
            "utilities",
            "挨拶",
        ]
        .into_iter()
        .map(str::to_string)
        .collect::<BTreeSet<_>>();

        assert_eq!(actual, expected);
        for property_key in ["api", "label", "nested", "urls", "value"] {
            assert!(!actual.contains(property_key));
        }
        assert!(!actual.contains("SourceShape"));
        assert!(!actual.contains("TypeOnly"));
    }

    #[test]
    fn non_setup_compatibility_path_remains_empty() {
        assert!(extract_simple_bindings("const value = 1", false).is_empty());
    }
}
