import type { ComposableEntryMetadata, ComposableRootEntryMetadata } from "./catalog-schema.ts";

/** Canonical runtime target ordering used by the catalog. */
export const allTargets = ["web", "server", "worker", "native", "desktop", "terminal"] as const;

/** Aggregate entry policy, including intentionally isolated subpaths. */
export const rootEntry = {
  subpath: ".",
  source: "src/index.ts",
  gzipBudget: "sum-of-reexported-entry-budgets",
  reexportedEntries: [
    "./abort-signal",
    "./active-element",
    "./async-resource",
    "./battery",
    "./capability",
    "./catalog",
    "./device-motion",
    "./device-orientation",
    "./device-pixel-ratio",
    "./disposal-scope",
    "./document-visibility",
    "./element-bounding",
    "./element-target",
    "./event-listener",
    "./focus",
    "./fps",
    "./geolocation",
    "./idle",
    "./intersection-observer",
    "./locale",
    "./magic-keys",
    "./media-query",
    "./mouse",
    "./mouse-in-element",
    "./mutation-observer",
    "./network",
    "./page-leave",
    "./pinch",
    "./pointer",
    "./pointer-lock",
    "./preferences",
    "./preferred-languages",
    "./resize-observer",
    "./retry-async",
    "./retry-delay",
    "./scope",
    "./screen-orientation",
    "./scroll",
    "./swipe",
    "./text-selection",
    "./timeout-scheduler",
    "./use-broadcast-channel",
    "./use-cookie",
    "./use-counter",
    "./use-debounced",
    "./use-event-source",
    "./use-fetch",
    "./use-history",
    "./use-indexed-db",
    "./use-previous",
    "./use-storage",
    "./use-throttled",
    "./use-toggle",
    "./use-url-hash",
    "./use-url-search-params",
    "./use-websocket",
    "./use-worker-fn",
    "./window-size",
  ],
  isolatedEntries: ["./temporal"],
} as const satisfies ComposableRootEntryMetadata;

/** Independently importable entries in package export-map order. */
export const entries = [
  {
    subpath: "./abort-signal",
    source: "src/abort-signal.ts",
    gzipBudgetBytes: 3 * 1024,
    runtimeExports: ["anyAbortSignal", "timeoutAbortSignal", "deadlineAbortSignal"],
    utilities: ["anyAbortSignal", "timeoutAbortSignal", "deadlineAbortSignal"],
  },
  {
    subpath: "./active-element",
    source: "src/active-element.ts",
    gzipBudgetBytes: 1.25 * 1024,
    runtimeExports: ["useActiveElement"],
    utilities: ["useActiveElement"],
  },
  {
    subpath: "./async-resource",
    source: "src/async-resource.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useAsyncResource"],
    utilities: ["useAsyncResource"],
  },
  {
    subpath: "./battery",
    source: "src/battery.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["useBattery"],
    utilities: ["useBattery"],
  },
  {
    subpath: "./capability",
    source: "src/capability.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: [
      "availableCapability",
      "unavailableCapability",
      "isCapabilityAvailable",
      "isCapabilityUnavailable",
    ],
    utilities: [
      "availableCapability",
      "unavailableCapability",
      "isCapabilityAvailable",
      "isCapabilityUnavailable",
    ],
  },
  {
    subpath: "./catalog",
    source: "src/catalog.ts",
    gzipBudgetBytes: 8 * 1024,
    runtimeExports: ["COMPOSABLE_CATALOG"],
    utilities: [],
  },
  {
    subpath: "./device-motion",
    source: "src/device-motion.ts",
    gzipBudgetBytes: 2.25 * 1024,
    runtimeExports: ["useDeviceMotion"],
    utilities: ["useDeviceMotion"],
  },
  {
    subpath: "./device-orientation",
    source: "src/device-orientation.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["useDeviceOrientation", "requestMotionPermission"],
    utilities: ["useDeviceOrientation", "requestMotionPermission"],
  },
  {
    subpath: "./device-pixel-ratio",
    source: "src/device-pixel-ratio.ts",
    gzipBudgetBytes: 1.25 * 1024,
    runtimeExports: ["useDevicePixelRatio"],
    utilities: ["useDevicePixelRatio"],
  },
  {
    subpath: "./disposal-scope",
    source: "src/disposal-scope.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["DISPOSAL_ERROR_CODE", "DisposalError", "createDisposalScope"],
    utilities: ["createDisposalScope"],
  },
  {
    subpath: "./document-visibility",
    source: "src/document-visibility.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useDocumentVisibility"],
    utilities: ["useDocumentVisibility"],
  },
  {
    subpath: "./element-bounding",
    source: "src/element-bounding.ts",
    gzipBudgetBytes: 3.75 * 1024,
    runtimeExports: ["useElementBounding"],
    utilities: ["useElementBounding"],
  },
  {
    subpath: "./element-target",
    source: "src/element-target.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: ["isElementNode", "resolveElement", "resolveElements"],
    utilities: ["isElementNode", "resolveElement", "resolveElements"],
  },
  {
    subpath: "./event-listener",
    source: "src/event-listener.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useEventListener"],
    utilities: ["useEventListener"],
  },
  {
    subpath: "./focus",
    source: "src/focus.ts",
    gzipBudgetBytes: 2.5 * 1024,
    runtimeExports: ["useFocus", "useFocusWithin"],
    utilities: ["useFocus", "useFocusWithin"],
  },
  {
    subpath: "./fps",
    source: "src/fps.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useFps"],
    utilities: ["useFps"],
  },
  {
    subpath: "./geolocation",
    source: "src/geolocation.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useGeolocation"],
    utilities: ["useGeolocation"],
  },
  {
    subpath: "./idle",
    source: "src/idle.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["DEFAULT_IDLE_EVENTS", "useIdle"],
    utilities: ["useIdle"],
  },
  {
    subpath: "./intersection-observer",
    source: "src/intersection-observer.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["useIntersectionObserver", "useElementVisibility"],
    utilities: ["useIntersectionObserver", "useElementVisibility"],
  },
  {
    subpath: "./locale",
    source: "src/locale.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useLocale"],
    utilities: ["useLocale"],
  },
  {
    subpath: "./magic-keys",
    source: "src/magic-keys.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["DEFAULT_KEY_ALIASES", "normalizeKeyName", "useMagicKeys", "useKeyPressed"],
    utilities: ["normalizeKeyName", "useMagicKeys", "useKeyPressed"],
  },
  {
    subpath: "./media-query",
    source: "src/media-query.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: ["useMediaQuery", "useReducedMotion"],
    utilities: ["useMediaQuery", "useReducedMotion"],
  },
  {
    subpath: "./mouse",
    source: "src/mouse.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["useMouse"],
    utilities: ["useMouse"],
  },
  {
    subpath: "./mouse-in-element",
    source: "src/mouse-in-element.ts",
    gzipBudgetBytes: 3 * 1024,
    runtimeExports: ["useMouseInElement"],
    utilities: ["useMouseInElement"],
  },
  {
    subpath: "./mutation-observer",
    source: "src/mutation-observer.ts",
    gzipBudgetBytes: 2.25 * 1024,
    runtimeExports: ["useMutationObserver"],
    utilities: ["useMutationObserver"],
  },
  {
    subpath: "./network",
    source: "src/network.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["useNetwork", "useOnline"],
    utilities: ["useNetwork", "useOnline"],
  },
  {
    subpath: "./page-leave",
    source: "src/page-leave.ts",
    gzipBudgetBytes: 1.25 * 1024,
    runtimeExports: ["usePageLeave"],
    utilities: ["usePageLeave"],
  },
  {
    subpath: "./pinch",
    source: "src/pinch.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["usePinch"],
    utilities: ["usePinch"],
  },
  {
    subpath: "./pointer",
    source: "src/pointer.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["usePointer", "toPointerKind"],
    utilities: ["usePointer", "toPointerKind"],
  },
  {
    subpath: "./pointer-lock",
    source: "src/pointer-lock.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["PointerLockError", "usePointerLock"],
    utilities: ["usePointerLock"],
  },
  {
    subpath: "./preferences",
    source: "src/preferences.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: [
      "usePreferredDark",
      "usePreferredColorScheme",
      "usePreferredContrast",
      "usePreferredReducedTransparency",
    ],
    utilities: [
      "usePreferredDark",
      "usePreferredColorScheme",
      "usePreferredContrast",
      "usePreferredReducedTransparency",
    ],
  },
  {
    subpath: "./preferred-languages",
    source: "src/preferred-languages.ts",
    gzipBudgetBytes: 1.25 * 1024,
    runtimeExports: ["usePreferredLanguages"],
    utilities: ["usePreferredLanguages"],
  },
  {
    subpath: "./resize-observer",
    source: "src/resize-observer.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["useResizeObserver", "useElementSize"],
    utilities: ["useResizeObserver", "useElementSize"],
  },
  {
    subpath: "./retry-async",
    source: "src/retry-async.ts",
    gzipBudgetBytes: 5.5 * 1024,
    runtimeExports: ["retryAsync"],
    utilities: ["retryAsync"],
  },
  {
    subpath: "./retry-delay",
    source: "src/retry-delay.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["calculateRetryDelay"],
    utilities: ["calculateRetryDelay"],
  },
  {
    subpath: "./scope",
    source: "src/scope.ts",
    gzipBudgetBytes: 0.5 * 1024,
    runtimeExports: ["tryOnScopeDispose"],
    utilities: ["tryOnScopeDispose"],
  },
  {
    subpath: "./screen-orientation",
    source: "src/screen-orientation.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useScreenOrientation"],
    utilities: ["useScreenOrientation"],
  },
  {
    subpath: "./scroll",
    source: "src/scroll.ts",
    gzipBudgetBytes: 3 * 1024,
    runtimeExports: ["useScroll", "useWindowScroll"],
    utilities: ["useScroll", "useWindowScroll"],
  },
  {
    subpath: "./swipe",
    source: "src/swipe.ts",
    gzipBudgetBytes: 4.25 * 1024,
    runtimeExports: ["swipeDirection", "useSwipe", "usePointerSwipe"],
    utilities: ["swipeDirection", "useSwipe", "usePointerSwipe"],
  },
  {
    subpath: "./temporal",
    source: "src/temporal.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["Temporal", "TemporalIntl", "useTemporalNow", "useTemporalZonedDateTime"],
    utilities: ["useTemporalNow", "useTemporalZonedDateTime"],
  },
  {
    subpath: "./text-selection",
    source: "src/text-selection.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useTextSelection"],
    utilities: ["useTextSelection"],
  },
  {
    subpath: "./timeout-scheduler",
    source: "src/timeout-scheduler.ts",
    gzipBudgetBytes: 0.25 * 1024,
    runtimeExports: [],
    utilities: [],
  },
  {
    subpath: "./use-broadcast-channel",
    source: "src/use-broadcast-channel.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useBroadcastChannel"],
    utilities: ["useBroadcastChannel"],
  },
  {
    subpath: "./use-cookie",
    source: "src/use-cookie.ts",
    gzipBudgetBytes: 4.5 * 1024,
    runtimeExports: [
      "COOKIE_ADAPTER_KEY",
      "parseCookieHeader",
      "provideCookieAdapter",
      "serializeCookie",
      "useCookie",
    ],
    utilities: ["parseCookieHeader", "serializeCookie", "provideCookieAdapter", "useCookie"],
  },
  {
    subpath: "./use-counter",
    source: "src/use-counter.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useCounter"],
    utilities: ["useCounter"],
  },
  {
    subpath: "./use-debounced",
    source: "src/use-debounced.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useDebounced"],
    utilities: ["useDebounced"],
  },
  {
    subpath: "./use-event-source",
    source: "src/use-event-source.ts",
    gzipBudgetBytes: 4.5 * 1024,
    runtimeExports: ["useEventSource"],
    utilities: ["useEventSource"],
  },
  {
    subpath: "./use-fetch",
    source: "src/use-fetch.ts",
    gzipBudgetBytes: 9.25 * 1024,
    runtimeExports: ["useFetch"],
    utilities: ["useFetch"],
  },
  {
    subpath: "./use-history",
    source: "src/use-history.ts",
    gzipBudgetBytes: 2.5 * 1024,
    runtimeExports: ["useHistory"],
    utilities: ["useHistory"],
  },
  {
    subpath: "./use-indexed-db",
    source: "src/use-indexed-db.ts",
    gzipBudgetBytes: 3.75 * 1024,
    runtimeExports: ["createIndexedDBKeyval", "useIndexedDB"],
    utilities: ["createIndexedDBKeyval", "useIndexedDB"],
  },
  {
    subpath: "./use-previous",
    source: "src/use-previous.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: ["usePrevious"],
    utilities: ["usePrevious"],
  },
  {
    subpath: "./use-storage",
    source: "src/use-storage.ts",
    gzipBudgetBytes: 4.5 * 1024,
    runtimeExports: [
      "inferStorageSerializerKind",
      "storageSerializers",
      "useLocalStorage",
      "useSessionStorage",
      "useStorage",
    ],
    utilities: ["inferStorageSerializerKind", "useStorage", "useLocalStorage", "useSessionStorage"],
  },
  {
    subpath: "./use-throttled",
    source: "src/use-throttled.ts",
    gzipBudgetBytes: 2.5 * 1024,
    runtimeExports: ["useThrottled"],
    utilities: ["useThrottled"],
  },
  {
    subpath: "./use-toggle",
    source: "src/use-toggle.ts",
    gzipBudgetBytes: 0.5 * 1024,
    runtimeExports: ["useToggle"],
    utilities: ["useToggle"],
  },
  {
    subpath: "./use-url-hash",
    source: "src/use-url-hash.ts",
    gzipBudgetBytes: 2.5 * 1024,
    runtimeExports: ["useUrlHash"],
    utilities: ["useUrlHash"],
  },
  {
    subpath: "./use-url-search-params",
    source: "src/use-url-search-params.ts",
    gzipBudgetBytes: 4 * 1024,
    runtimeExports: [
      "parseSearchParams",
      "searchParam",
      "serializeSearchParams",
      "useUrlSearchParams",
    ],
    utilities: ["parseSearchParams", "serializeSearchParams", "useUrlSearchParams"],
  },
  {
    subpath: "./use-websocket",
    source: "src/use-websocket.ts",
    gzipBudgetBytes: 4.75 * 1024,
    runtimeExports: ["useWebSocket"],
    utilities: ["useWebSocket"],
  },
  {
    subpath: "./use-worker-fn",
    source: "src/use-worker-fn.ts",
    gzipBudgetBytes: 3.25 * 1024,
    runtimeExports: ["createWorkerFnScript", "useWorkerFn"],
    utilities: ["createWorkerFnScript", "useWorkerFn"],
  },
  {
    subpath: "./window-size",
    source: "src/window-size.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useWindowSize"],
    utilities: ["useWindowSize"],
  },
] as const satisfies readonly ComposableEntryMetadata[];
