import type { ComposableEntryMetadata, ComposableRootEntryMetadata } from "./catalog-schema.ts";

/** Canonical runtime target ordering used by the catalog. */
export const allTargets = ["web", "server", "worker", "native", "desktop", "terminal"] as const;

/** Aggregate entry policy, including intentionally isolated subpaths. */
export const rootEntry = {
  subpath: ".",
  source: "src/index.ts",
  gzipBudget: "sum-of-reexported-entry-budgets",
  reexportedEntries: [
    "./abort-signal",
    "./active-element",
    "./async-resource",
    "./capability",
    "./catalog",
    "./disposal-scope",
    "./document-visibility",
    "./element-bounding",
    "./element-target",
    "./event-listener",
    "./focus",
    "./intersection-observer",
    "./locale",
    "./magic-keys",
    "./media-query",
    "./mouse",
    "./mouse-in-element",
    "./mutation-observer",
    "./pinch",
    "./pointer",
    "./pointer-lock",
    "./resize-observer",
    "./retry-async",
    "./retry-delay",
    "./scope",
    "./scroll",
    "./swipe",
    "./text-selection",
    "./timeout-scheduler",
    "./use-counter",
    "./use-debounced",
    "./use-history",
    "./use-previous",
    "./use-throttled",
    "./use-toggle",
    "./window-size",
  ],
  isolatedEntries: ["./temporal"],
} as const satisfies ComposableRootEntryMetadata;

/** Independently importable entries in package export-map order. */
export const entries = [
  {
    subpath: "./abort-signal",
    source: "src/abort-signal.ts",
    gzipBudgetBytes: 3 * 1024,
    runtimeExports: ["anyAbortSignal", "timeoutAbortSignal", "deadlineAbortSignal"],
    utilities: ["anyAbortSignal", "timeoutAbortSignal", "deadlineAbortSignal"],
  },
  {
    subpath: "./active-element",
    source: "src/active-element.ts",
    gzipBudgetBytes: 1.25 * 1024,
    runtimeExports: ["useActiveElement"],
    utilities: ["useActiveElement"],
  },
  {
    subpath: "./async-resource",
    source: "src/async-resource.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useAsyncResource"],
    utilities: ["useAsyncResource"],
  },
  {
    subpath: "./capability",
    source: "src/capability.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: [
      "availableCapability",
      "unavailableCapability",
      "isCapabilityAvailable",
      "isCapabilityUnavailable",
    ],
    utilities: [
      "availableCapability",
      "unavailableCapability",
      "isCapabilityAvailable",
      "isCapabilityUnavailable",
    ],
  },
  {
    subpath: "./catalog",
    source: "src/catalog.ts",
    gzipBudgetBytes: 4 * 1024,
    runtimeExports: ["COMPOSABLE_CATALOG"],
    utilities: [],
  },
  {
    subpath: "./disposal-scope",
    source: "src/disposal-scope.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["DISPOSAL_ERROR_CODE", "DisposalError", "createDisposalScope"],
    utilities: ["createDisposalScope"],
  },
  {
    subpath: "./document-visibility",
    source: "src/document-visibility.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useDocumentVisibility"],
    utilities: ["useDocumentVisibility"],
  },
  {
    subpath: "./element-bounding",
    source: "src/element-bounding.ts",
    gzipBudgetBytes: 3.75 * 1024,
    runtimeExports: ["useElementBounding"],
    utilities: ["useElementBounding"],
  },
  {
    subpath: "./element-target",
    source: "src/element-target.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: ["isElementNode", "resolveElement", "resolveElements"],
    utilities: ["isElementNode", "resolveElement", "resolveElements"],
  },
  {
    subpath: "./event-listener",
    source: "src/event-listener.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useEventListener"],
    utilities: ["useEventListener"],
  },
  {
    subpath: "./focus",
    source: "src/focus.ts",
    gzipBudgetBytes: 2.5 * 1024,
    runtimeExports: ["useFocus", "useFocusWithin"],
    utilities: ["useFocus", "useFocusWithin"],
  },
  {
    subpath: "./intersection-observer",
    source: "src/intersection-observer.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["useIntersectionObserver", "useElementVisibility"],
    utilities: ["useIntersectionObserver", "useElementVisibility"],
  },
  {
    subpath: "./locale",
    source: "src/locale.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useLocale"],
    utilities: ["useLocale"],
  },
  {
    subpath: "./magic-keys",
    source: "src/magic-keys.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["DEFAULT_KEY_ALIASES", "normalizeKeyName", "useMagicKeys", "useKeyPressed"],
    utilities: ["normalizeKeyName", "useMagicKeys", "useKeyPressed"],
  },
  {
    subpath: "./media-query",
    source: "src/media-query.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: ["useMediaQuery", "useReducedMotion"],
    utilities: ["useMediaQuery", "useReducedMotion"],
  },
  {
    subpath: "./mouse",
    source: "src/mouse.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["useMouse"],
    utilities: ["useMouse"],
  },
  {
    subpath: "./mouse-in-element",
    source: "src/mouse-in-element.ts",
    gzipBudgetBytes: 3 * 1024,
    runtimeExports: ["useMouseInElement"],
    utilities: ["useMouseInElement"],
  },
  {
    subpath: "./mutation-observer",
    source: "src/mutation-observer.ts",
    gzipBudgetBytes: 2.25 * 1024,
    runtimeExports: ["useMutationObserver"],
    utilities: ["useMutationObserver"],
  },
  {
    subpath: "./pinch",
    source: "src/pinch.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["usePinch"],
    utilities: ["usePinch"],
  },
  {
    subpath: "./pointer",
    source: "src/pointer.ts",
    gzipBudgetBytes: 1.75 * 1024,
    runtimeExports: ["usePointer", "toPointerKind"],
    utilities: ["usePointer", "toPointerKind"],
  },
  {
    subpath: "./pointer-lock",
    source: "src/pointer-lock.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["PointerLockError", "usePointerLock"],
    utilities: ["usePointerLock"],
  },
  {
    subpath: "./resize-observer",
    source: "src/resize-observer.ts",
    gzipBudgetBytes: 2.75 * 1024,
    runtimeExports: ["useResizeObserver", "useElementSize"],
    utilities: ["useResizeObserver", "useElementSize"],
  },
  {
    subpath: "./retry-async",
    source: "src/retry-async.ts",
    gzipBudgetBytes: 5.5 * 1024,
    runtimeExports: ["retryAsync"],
    utilities: ["retryAsync"],
  },
  {
    subpath: "./retry-delay",
    source: "src/retry-delay.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["calculateRetryDelay"],
    utilities: ["calculateRetryDelay"],
  },
  {
    subpath: "./scope",
    source: "src/scope.ts",
    gzipBudgetBytes: 0.5 * 1024,
    runtimeExports: ["tryOnScopeDispose"],
    utilities: ["tryOnScopeDispose"],
  },
  {
    subpath: "./scroll",
    source: "src/scroll.ts",
    gzipBudgetBytes: 3 * 1024,
    runtimeExports: ["useScroll", "useWindowScroll"],
    utilities: ["useScroll", "useWindowScroll"],
  },
  {
    subpath: "./swipe",
    source: "src/swipe.ts",
    gzipBudgetBytes: 4.25 * 1024,
    runtimeExports: ["swipeDirection", "useSwipe", "usePointerSwipe"],
    utilities: ["swipeDirection", "useSwipe", "usePointerSwipe"],
  },
  {
    subpath: "./temporal",
    source: "src/temporal.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["Temporal", "TemporalIntl", "useTemporalNow", "useTemporalZonedDateTime"],
    utilities: ["useTemporalNow", "useTemporalZonedDateTime"],
  },
  {
    subpath: "./text-selection",
    source: "src/text-selection.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useTextSelection"],
    utilities: ["useTextSelection"],
  },
  {
    subpath: "./timeout-scheduler",
    source: "src/timeout-scheduler.ts",
    gzipBudgetBytes: 0.25 * 1024,
    runtimeExports: [],
    utilities: [],
  },
  {
    subpath: "./use-counter",
    source: "src/use-counter.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useCounter"],
    utilities: ["useCounter"],
  },
  {
    subpath: "./use-debounced",
    source: "src/use-debounced.ts",
    gzipBudgetBytes: 2 * 1024,
    runtimeExports: ["useDebounced"],
    utilities: ["useDebounced"],
  },
  {
    subpath: "./use-history",
    source: "src/use-history.ts",
    gzipBudgetBytes: 2.5 * 1024,
    runtimeExports: ["useHistory"],
    utilities: ["useHistory"],
  },
  {
    subpath: "./use-previous",
    source: "src/use-previous.ts",
    gzipBudgetBytes: 1024,
    runtimeExports: ["usePrevious"],
    utilities: ["usePrevious"],
  },
  {
    subpath: "./use-throttled",
    source: "src/use-throttled.ts",
    gzipBudgetBytes: 2.5 * 1024,
    runtimeExports: ["useThrottled"],
    utilities: ["useThrottled"],
  },
  {
    subpath: "./use-toggle",
    source: "src/use-toggle.ts",
    gzipBudgetBytes: 0.5 * 1024,
    runtimeExports: ["useToggle"],
    utilities: ["useToggle"],
  },
  {
    subpath: "./window-size",
    source: "src/window-size.ts",
    gzipBudgetBytes: 1.5 * 1024,
    runtimeExports: ["useWindowSize"],
    utilities: ["useWindowSize"],
  },
] as const satisfies readonly ComposableEntryMetadata[];
