import { allTargets } from "./catalog-entries.ts";
import type { ComposableUtilityMetadata } from "./catalog-schema.ts";

const reactiveTargets = allTargets;
const browserTargets = ["web", "desktop"] as const;

/** Operational metadata for every public runtime utility. */
export const utilities = [
  {
    name: "anyAbortSignal",
    entry: "./abort-signal",
    category: "async",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: ["AbortController", "AbortSignal"],
    dependencies: [],
  },
  {
    name: "timeoutAbortSignal",
    entry: "./abort-signal",
    category: "timing",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: ["AbortController", "AbortSignal", "DOMException", "globalThis"],
    dependencies: ["anyAbortSignal"],
  },
  {
    name: "deadlineAbortSignal",
    entry: "./abort-signal",
    category: "timing",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: [],
    dependencies: ["timeoutAbortSignal"],
  },
  {
    name: "useActiveElement",
    entry: "./active-element",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useAsyncResource",
    entry: "./async-resource",
    category: "async",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["AbortController", "DOMException"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useBattery",
    entry: "./battery",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "availableCapability",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "unavailableCapability",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "isCapabilityAvailable",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "isCapabilityUnavailable",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useDeviceMotion",
    entry: "./device-motion",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["requestMotionPermission", "tryOnScopeDispose"],
  },
  {
    name: "useDeviceOrientation",
    entry: "./device-orientation",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["requestMotionPermission", "tryOnScopeDispose"],
  },
  {
    name: "requestMotionPermission",
    entry: "./device-orientation",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useDevicePixelRatio",
    entry: "./device-pixel-ratio",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "createDisposalScope",
    entry: "./disposal-scope",
    category: "lifecycle",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useDocumentVisibility",
    entry: "./document-visibility",
    category: "events",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: [],
  },
  {
    name: "useElementBounding",
    entry: "./element-bounding",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["resolveElement", "useEventListener", "useResizeObserver", "tryOnScopeDispose"],
  },
  {
    name: "isElementNode",
    entry: "./element-target",
    category: "dom",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "resolveElement",
    entry: "./element-target",
    category: "dom",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: ["isElementNode"],
  },
  {
    name: "resolveElements",
    entry: "./element-target",
    category: "dom",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: ["isElementNode"],
  },
  {
    name: "useEventListener",
    entry: "./event-listener",
    category: "events",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useFocus",
    entry: "./focus",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useFocusWithin",
    entry: "./focus",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useFps",
    entry: "./fps",
    category: "performance",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useGeolocation",
    entry: "./geolocation",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["availableCapability", "unavailableCapability", "tryOnScopeDispose"],
  },
  {
    name: "useIdle",
    entry: "./idle",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useIntersectionObserver",
    entry: "./intersection-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "IntersectionObserver"],
    dependencies: ["resolveElement", "resolveElements", "tryOnScopeDispose"],
  },
  {
    name: "useElementVisibility",
    entry: "./intersection-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "IntersectionObserver"],
    dependencies: ["useIntersectionObserver"],
  },
  {
    name: "useLocale",
    entry: "./locale",
    category: "i18n",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["none"],
    runtimeGlobals: ["Intl", "navigator"],
    dependencies: [],
  },
  {
    name: "normalizeKeyName",
    entry: "./magic-keys",
    category: "input",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useMagicKeys",
    entry: "./magic-keys",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["normalizeKeyName", "tryOnScopeDispose"],
  },
  {
    name: "useKeyPressed",
    entry: "./magic-keys",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["normalizeKeyName", "tryOnScopeDispose"],
  },
  {
    name: "useMediaQuery",
    entry: "./media-query",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useReducedMotion",
    entry: "./media-query",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "useMouse",
    entry: "./mouse",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useMouseInElement",
    entry: "./mouse-in-element",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMouse", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useMutationObserver",
    entry: "./mutation-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "MutationObserver"],
    dependencies: ["resolveElements", "tryOnScopeDispose"],
  },
  {
    name: "useNetwork",
    entry: "./network",
    category: "networking",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useOnline",
    entry: "./network",
    category: "networking",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useNetwork"],
  },
  {
    name: "usePageLeave",
    entry: "./page-leave",
    category: "events",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "usePinch",
    entry: "./pinch",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "usePointer",
    entry: "./pointer",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["toPointerKind", "tryOnScopeDispose"],
  },
  {
    name: "toPointerKind",
    entry: "./pointer",
    category: "input",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "usePointerLock",
    entry: "./pointer-lock",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "usePreferredDark",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredColorScheme",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredContrast",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredReducedTransparency",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredLanguages",
    entry: "./preferred-languages",
    category: "i18n",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useResizeObserver",
    entry: "./resize-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "ResizeObserver"],
    dependencies: ["resolveElements", "tryOnScopeDispose"],
  },
  {
    name: "useElementSize",
    entry: "./resize-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "ResizeObserver"],
    dependencies: ["useResizeObserver", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "retryAsync",
    entry: "./retry-async",
    category: "async",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: ["AbortController"],
    dependencies: ["timeoutAbortSignal", "calculateRetryDelay"],
  },
  {
    name: "calculateRetryDelay",
    entry: "./retry-delay",
    category: "timing",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "tryOnScopeDispose",
    entry: "./scope",
    category: "lifecycle",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useScreenOrientation",
    entry: "./screen-orientation",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useScroll",
    entry: "./scroll",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis"],
    dependencies: ["isElementNode", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useWindowScroll",
    entry: "./scroll",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["useScroll"],
  },
  {
    name: "swipeDirection",
    entry: "./swipe",
    category: "input",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useSwipe",
    entry: "./swipe",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["swipeDirection", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "usePointerSwipe",
    entry: "./swipe",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["swipeDirection", "toPointerKind", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useTemporalNow",
    entry: "./temporal",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: [],
  },
  {
    name: "useTemporalZonedDateTime",
    entry: "./temporal",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["useTemporalNow"],
  },
  {
    name: "useTextSelection",
    entry: "./text-selection",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useCounter",
    entry: "./use-counter",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useDebounced",
    entry: "./use-debounced",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useHistory",
    entry: "./use-history",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "usePrevious",
    entry: "./use-previous",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useThrottled",
    entry: "./use-throttled",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useToggle",
    entry: "./use-toggle",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useWindowSize",
    entry: "./window-size",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
] as const satisfies readonly ComposableUtilityMetadata[];
