import { allTargets } from "./catalog-entries.ts";
import type { ComposableUtilityMetadata } from "./catalog-schema.ts";

const reactiveTargets = allTargets;
const browserTargets = ["web", "desktop"] as const;

/** Operational metadata for every public runtime utility. */
export const utilities = [
  {
    name: "anyAbortSignal",
    entry: "./abort-signal",
    category: "async",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: ["AbortController", "AbortSignal"],
    dependencies: [],
  },
  {
    name: "timeoutAbortSignal",
    entry: "./abort-signal",
    category: "timing",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: ["AbortController", "AbortSignal", "DOMException", "globalThis"],
    dependencies: ["anyAbortSignal"],
  },
  {
    name: "deadlineAbortSignal",
    entry: "./abort-signal",
    category: "timing",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: [],
    dependencies: ["timeoutAbortSignal"],
  },
  {
    name: "useActiveElement",
    entry: "./active-element",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useAnimate",
    entry: "./animate",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useAsyncResource",
    entry: "./async-resource",
    category: "async",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["AbortController", "DOMException"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useBattery",
    entry: "./battery",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useBreakpoints",
    entry: "./breakpoints",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery", "toPixels"],
  },
  {
    name: "toPixels",
    entry: "./breakpoints",
    category: "media",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "availableCapability",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "unavailableCapability",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "isCapabilityAvailable",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "isCapabilityUnavailable",
    entry: "./capability",
    category: "capability",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useColorMode",
    entry: "./color-mode",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document", "window"],
    dependencies: ["useMediaQuery", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useDark",
    entry: "./color-mode",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document", "window"],
    dependencies: ["useColorMode"],
  },
  {
    name: "useDeviceMotion",
    entry: "./device-motion",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["requestMotionPermission", "tryOnScopeDispose"],
  },
  {
    name: "useDeviceOrientation",
    entry: "./device-orientation",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["requestMotionPermission", "tryOnScopeDispose"],
  },
  {
    name: "requestMotionPermission",
    entry: "./device-orientation",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useDevicePixelRatio",
    entry: "./device-pixel-ratio",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "createDisposalScope",
    entry: "./disposal-scope",
    category: "lifecycle",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useDocumentVisibility",
    entry: "./document-visibility",
    category: "events",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: [],
  },
  {
    name: "useDraggable",
    entry: "./draggable",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "isElementNode", "toPointerKind", "tryOnScopeDispose"],
  },
  {
    name: "useElementBounding",
    entry: "./element-bounding",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["resolveElement", "useEventListener", "useResizeObserver", "tryOnScopeDispose"],
  },
  {
    name: "useElementByPoint",
    entry: "./element-by-point",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useElementHover",
    entry: "./element-hover",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis"],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useElementRef",
    entry: "./element-ref",
    category: "dom",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: ["resolveElement"],
  },
  {
    name: "isElementNode",
    entry: "./element-target",
    category: "dom",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "resolveElement",
    entry: "./element-target",
    category: "dom",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: ["isElementNode"],
  },
  {
    name: "resolveElements",
    entry: "./element-target",
    category: "dom",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: ["isElementNode"],
  },
  {
    name: "useEventListener",
    entry: "./event-listener",
    category: "events",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useFocus",
    entry: "./focus",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useFocusWithin",
    entry: "./focus",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useFps",
    entry: "./fps",
    category: "performance",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useGeolocation",
    entry: "./geolocation",
    category: "sensors",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["availableCapability", "unavailableCapability", "tryOnScopeDispose"],
  },
  {
    name: "useIdle",
    entry: "./idle",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useInfiniteScroll",
    entry: "./infinite-scroll",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis"],
    dependencies: ["useScroll", "tryOnScopeDispose"],
  },
  {
    name: "useIntersectionObserver",
    entry: "./intersection-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "IntersectionObserver"],
    dependencies: ["resolveElement", "resolveElements", "tryOnScopeDispose"],
  },
  {
    name: "useElementVisibility",
    entry: "./intersection-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "IntersectionObserver"],
    dependencies: ["useIntersectionObserver"],
  },
  {
    name: "useLocale",
    entry: "./locale",
    category: "i18n",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["none"],
    runtimeGlobals: ["Intl", "navigator"],
    dependencies: [],
  },
  {
    name: "normalizeKeyName",
    entry: "./magic-keys",
    category: "input",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useMagicKeys",
    entry: "./magic-keys",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["normalizeKeyName", "tryOnScopeDispose"],
  },
  {
    name: "useKeyPressed",
    entry: "./magic-keys",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["normalizeKeyName", "tryOnScopeDispose"],
  },
  {
    name: "useMediaQuery",
    entry: "./media-query",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useReducedMotion",
    entry: "./media-query",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "useMouse",
    entry: "./mouse",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useMouseInElement",
    entry: "./mouse-in-element",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMouse", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useMutationObserver",
    entry: "./mutation-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "MutationObserver"],
    dependencies: ["resolveElements", "tryOnScopeDispose"],
  },
  {
    name: "useNetwork",
    entry: "./network",
    category: "networking",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useOnline",
    entry: "./network",
    category: "networking",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useNetwork"],
  },
  {
    name: "onClickOutside",
    entry: "./on-click-outside",
    category: "events",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "onKeyStroke",
    entry: "./on-key-stroke",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["normalizeKeyName", "tryOnScopeDispose"],
  },
  {
    name: "onKeyDown",
    entry: "./on-key-stroke",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["onKeyStroke"],
  },
  {
    name: "onKeyUp",
    entry: "./on-key-stroke",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["onKeyStroke"],
  },
  {
    name: "onLongPress",
    entry: "./on-long-press",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis"],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "isTypingKeystroke",
    entry: "./on-start-typing",
    category: "input",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "onStartTyping",
    entry: "./on-start-typing",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: ["isTypingKeystroke", "tryOnScopeDispose"],
  },
  {
    name: "usePageLeave",
    entry: "./page-leave",
    category: "events",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useParentElement",
    entry: "./parent-element",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["isElementNode", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "usePinch",
    entry: "./pinch",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "usePointer",
    entry: "./pointer",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["toPointerKind", "tryOnScopeDispose"],
  },
  {
    name: "toPointerKind",
    entry: "./pointer",
    category: "input",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "usePointerLock",
    entry: "./pointer-lock",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "usePreferredDark",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredColorScheme",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredContrast",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredReducedTransparency",
    entry: "./preferences",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaQuery"],
  },
  {
    name: "usePreferredLanguages",
    entry: "./preferred-languages",
    category: "i18n",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useResizeObserver",
    entry: "./resize-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "ResizeObserver"],
    dependencies: ["resolveElements", "tryOnScopeDispose"],
  },
  {
    name: "useElementSize",
    entry: "./resize-observer",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "ResizeObserver"],
    dependencies: ["useResizeObserver", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "retryAsync",
    entry: "./retry-async",
    category: "async",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: ["AbortController"],
    dependencies: ["timeoutAbortSignal", "calculateRetryDelay"],
  },
  {
    name: "calculateRetryDelay",
    entry: "./retry-delay",
    category: "timing",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "tryOnScopeDispose",
    entry: "./scope",
    category: "lifecycle",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useScreenOrientation",
    entry: "./screen-orientation",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useScroll",
    entry: "./scroll",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis"],
    dependencies: ["isElementNode", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useWindowScroll",
    entry: "./scroll",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["useScroll"],
  },
  {
    name: "useScrollLock",
    entry: "./scroll-lock",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "swipeDirection",
    entry: "./swipe",
    category: "input",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useSwipe",
    entry: "./swipe",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["swipeDirection", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "usePointerSwipe",
    entry: "./swipe",
    category: "input",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["swipeDirection", "toPointerKind", "resolveElement", "tryOnScopeDispose"],
  },
  {
    name: "useTemporalNow",
    entry: "./temporal",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: [],
  },
  {
    name: "useTemporalZonedDateTime",
    entry: "./temporal",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["useTemporalNow"],
  },
  {
    name: "useTextSelection",
    entry: "./text-selection",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["document"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useTextareaAutosize",
    entry: "./textarea-autosize",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "ResizeObserver"],
    dependencies: ["resolveElement", "useResizeObserver", "tryOnScopeDispose"],
  },
  {
    name: "useTransition",
    entry: "./transition",
    category: "timing",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["cubicBezier", "tryOnScopeDispose"],
  },
  {
    name: "cubicBezier",
    entry: "./transition",
    category: "timing",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useBroadcastChannel",
    entry: "./use-broadcast-channel",
    category: "networking",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["MessageEvent", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useClipboard",
    entry: "./use-clipboard",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose", "usePermission"],
  },
  {
    name: "parseCookieHeader",
    entry: "./use-cookie",
    category: "storage",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "serializeCookie",
    entry: "./use-cookie",
    category: "storage",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "provideCookieAdapter",
    entry: "./use-cookie",
    category: "storage",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useCookie",
    entry: "./use-cookie",
    category: "storage",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["parseCookieHeader", "serializeCookie", "tryOnScopeDispose"],
  },
  {
    name: "useCounter",
    entry: "./use-counter",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useCssVar",
    entry: "./use-css-var",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useDebounced",
    entry: "./use-debounced",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useDisplayMedia",
    entry: "./use-display-media",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaStream"],
  },
  {
    name: "useDocumentTitle",
    entry: "./use-document-title",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "matchesAccept",
    entry: "./use-drop-zone",
    category: "events",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useDropZone",
    entry: "./use-drop-zone",
    category: "events",
    stability: "experimental",
    targets: browserTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["matchesAccept", "tryOnScopeDispose"],
  },
  {
    name: "useEventSource",
    entry: "./use-event-source",
    category: "networking",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["calculateRetryDelay", "tryOnScopeDispose"],
  },
  {
    name: "useEyeDropper",
    entry: "./use-eye-dropper",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["none"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useFavicon",
    entry: "./use-favicon",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useFetch",
    entry: "./use-fetch",
    category: "networking",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["AbortController", "DOMException", "globalThis", "window"],
    dependencies: ["retryAsync", "tryOnScopeDispose"],
  },
  {
    name: "useFileDialog",
    entry: "./use-file-dialog",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useFileSystemAccess",
    entry: "./use-file-system-access",
    category: "storage",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["none"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useFullscreen",
    entry: "./use-fullscreen",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useHistory",
    entry: "./use-history",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useImage",
    entry: "./use-image",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "createIndexedDBKeyval",
    entry: "./use-indexed-db",
    category: "storage",
    stability: "experimental",
    targets: browserTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["returned-value"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useIndexedDB",
    entry: "./use-indexed-db",
    category: "storage",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["createIndexedDBKeyval", "tryOnScopeDispose"],
  },
  {
    name: "useMediaControls",
    entry: "./use-media-controls",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useWebNotification",
    entry: "./use-notification",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useObjectUrl",
    entry: "./use-object-url",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "usePermission",
    entry: "./use-permission",
    category: "capability",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "usePrevious",
    entry: "./use-previous",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useScriptTag",
    entry: "./use-script-tag",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useShare",
    entry: "./use-share",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["none"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useSpeechRecognition",
    entry: "./use-speech-recognition",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: [],
  },
  {
    name: "useSpeechSynthesis",
    entry: "./use-speech-synthesis",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "inferStorageSerializerKind",
    entry: "./use-storage",
    category: "storage",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useStorage",
    entry: "./use-storage",
    category: "storage",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["CustomEvent", "window"],
    dependencies: ["inferStorageSerializerKind", "tryOnScopeDispose"],
  },
  {
    name: "useLocalStorage",
    entry: "./use-storage",
    category: "storage",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: [],
    dependencies: ["useStorage"],
  },
  {
    name: "useSessionStorage",
    entry: "./use-storage",
    category: "storage",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useStorage"],
  },
  {
    name: "useStyleTag",
    entry: "./use-style-tag",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useThrottled",
    entry: "./use-throttled",
    category: "timing",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useToggle",
    entry: "./use-toggle",
    category: "state",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "safe",
    hydration: "stable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useUrlHash",
    entry: "./use-url-hash",
    category: "state",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "parseSearchParams",
    entry: "./use-url-search-params",
    category: "state",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: ["URL", "URLSearchParams"],
    dependencies: [],
  },
  {
    name: "serializeSearchParams",
    entry: "./use-url-search-params",
    category: "state",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: ["URL", "URLSearchParams"],
    dependencies: [],
  },
  {
    name: "useUrlSearchParams",
    entry: "./use-url-search-params",
    category: "state",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["parseSearchParams", "serializeSearchParams", "tryOnScopeDispose"],
  },
  {
    name: "useMediaStream",
    entry: "./use-user-media",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useUserMedia",
    entry: "./use-user-media",
    category: "media",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["useMediaStream"],
  },
  {
    name: "useVibrate",
    entry: "./use-vibrate",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["globalThis", "window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useWakeLock",
    entry: "./use-wake-lock",
    category: "system",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
  {
    name: "useWebSocket",
    entry: "./use-websocket",
    category: "networking",
    stability: "experimental",
    targets: reactiveTargets,
    ssr: "deterministic-fallback",
    hydration: "caller-managed",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["Blob", "globalThis", "window"],
    dependencies: ["calculateRetryDelay", "tryOnScopeDispose"],
  },
  {
    name: "createWorkerFnScript",
    entry: "./use-worker-fn",
    category: "performance",
    stability: "experimental",
    targets: allTargets,
    ssr: "safe",
    hydration: "not-applicable",
    cleanupOwners: ["none"],
    runtimeGlobals: [],
    dependencies: [],
  },
  {
    name: "useWorkerFn",
    entry: "./use-worker-fn",
    category: "performance",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["caller", "reactive-scope"],
    runtimeGlobals: ["Blob", "globalThis", "window"],
    dependencies: ["createWorkerFnScript", "tryOnScopeDispose"],
  },
  {
    name: "useVirtualList",
    entry: "./virtual-list",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["globalThis", "ResizeObserver"],
    dependencies: ["useElementRef", "useResizeObserver"],
  },
  {
    name: "useWindowSize",
    entry: "./window-size",
    category: "dom",
    stability: "experimental",
    targets: browserTargets,
    ssr: "deterministic-fallback",
    hydration: "stable",
    cleanupOwners: ["reactive-scope"],
    runtimeGlobals: ["window"],
    dependencies: ["tryOnScopeDispose"],
  },
] as const satisfies readonly ComposableUtilityMetadata[];
