import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "node:test";

import { COMPOSABLE_CATALOG } from "./catalog.ts";
import {
  VizeComposableResolver,
  createVizeComposableDeclarations,
  listVizeComposableImports,
  readComposableLockfile,
  vizeComposableImports,
} from "./resolver.ts";

void test("covers every runtime export of every importable catalog entry", () => {
  const imports = listVizeComposableImports();
  const names = new Set(imports.map((item) => item.name));
  for (const entry of COMPOSABLE_CATALOG.entries) {
    if (entry.subpath === "./catalog" || entry.subpath === "./resolver") continue;
    for (const name of entry.runtimeExports)
      assert.ok(names.has(name), `${name} (${entry.subpath}) is not resolvable`);
  }
  assert.ok(!names.has("COMPOSABLE_CATALOG"), "tooling entries are excluded");
  assert.ok(!names.has("VizeComposableResolver"));
  assert.equal(
    new Set(imports.map((item) => item.name)).size,
    imports.length,
    "each name resolves once",
  );
  for (const item of imports) {
    const subpath = `./${item.from.slice("@vizejs/composable/".length)}`;
    assert.ok(
      COMPOSABLE_CATALOG.entries.some(
        (entry) =>
          entry.subpath === subpath &&
          entry.runtimeExports.some((name: string) => name === item.name),
      ),
      `${item.name} must come from its own subpath`,
    );
  }
});

void test("resolves names to direct subpaths and honors include, exclude, and names", () => {
  const resolve = VizeComposableResolver();
  assert.deepEqual(resolve("useToggle"), {
    name: "useToggle",
    from: "@vizejs/composable/use-toggle",
  });
  assert.deepEqual(resolve("useFormFieldProps"), {
    name: "useFormFieldProps",
    from: "@vizejs/composable/use-form-field-props",
  });
  assert.equal(resolve("useSomethingElse"), undefined);

  const filtered = VizeComposableResolver({
    exclude: ["use-toggle"],
    names: ["useToggle", "useCounter"],
  });
  assert.equal(filtered("useToggle"), undefined);
  assert.deepEqual(filtered("useCounter"), {
    name: "useCounter",
    from: "@vizejs/composable/use-counter",
  });
  assert.equal(filtered("useDebounced"), undefined);

  assert.deepEqual(vizeComposableImports({ include: ["use-toggle"] }), {
    "@vizejs/composable/use-toggle": ["useToggle"],
  });
});

void test("local mode resolves pulled entries from vize-lib.lock.json", () => {
  const root = mkdtempSync(path.join(tmpdir(), "vize-compose-resolver-"));
  writeFileSync(
    path.join(root, "vize-lib.lock.json"),
    JSON.stringify({
      lockfileVersion: 1,
      items: [
        { name: "use-toggle", kind: "composable", dir: "src/composables/vize" },
        { name: "button", kind: "ui", dir: "src/components/vize" },
      ],
    }),
  );
  const local = VizeComposableResolver({ source: "local", root });
  assert.deepEqual(local("useToggle"), {
    name: "useToggle",
    from: `${root.split(path.sep).join("/")}/src/composables/vize/use-toggle.ts`,
  });
  assert.deepEqual(local("useCounter"), {
    name: "useCounter",
    from: "@vizejs/composable/use-counter",
  });
  const strict = VizeComposableResolver({
    source: "local",
    fallback: false,
    root: "/app",
    lockfile: {
      lockfileVersion: 1,
      items: [{ name: "use-counter", kind: "composable", dir: "lib" }],
    },
  });
  assert.deepEqual(strict("useCounter"), { name: "useCounter", from: "/app/lib/use-counter.ts" });
  assert.equal(strict("useToggle"), undefined);

  writeFileSync(path.join(root, "bad.json"), '{"items": [1]}');
  assert.throws(
    () => readComposableLockfile(path.join(root, "bad.json")),
    /VIZE_COMPOSE_RESOLVER_LOCKFILE/,
  );
  assert.throws(
    () => VizeComposableResolver({ source: "local", root, lockfile: "nope.json" }),
    /VIZE_COMPOSE_RESOLVER_LOCKFILE/,
  );
});

void test("generated global declarations reference each export's subpath", () => {
  const declarations = createVizeComposableDeclarations({ include: ["use-toggle", "use-counter"] });
  assert.equal(
    declarations,
    [
      "// Generated by @vizejs/composable/resolver. Do not edit.",
      "export {};",
      "declare global {",
      '  const useCounter: typeof import("@vizejs/composable/use-counter")["useCounter"];',
      '  const useToggle: typeof import("@vizejs/composable/use-toggle")["useToggle"];',
      "}",
      "",
    ].join("\n"),
  );
});
