//! Raw SSR output references for three historical compiler fixes.
//!
//! Code, preamble and map strings keep every byte, including terminal
//! whitespace and CRLF. Expected output is never regenerated by this test.

use serde_json::Value;

#[path = "support/fix_history.rs"]
mod fixtures;

const EXPECTED: &str = include_str!("fixtures/fix-history/capture-22dec/first.stdout.json");

#[test]
fn three_history_fixes_preserve_complete_ssr_outputs() {
    let expected = serde_json::from_str::<Value>(EXPECTED).expect("valid immutable capture");
    assert_eq!(
        fixtures::options().expect("original defaults must be admitted"),
        expected.get("options").expect("captured options").clone(),
        "default SSR options differ from the captured historical workload"
    );
    let cases = expected
        .get("cases")
        .and_then(Value::as_array)
        .expect("captured cases");
    assert_eq!(cases.len(), fixtures::CASES.len());
    for ((id, source), expected) in fixtures::CASES.iter().zip(cases) {
        assert_eq!(
            expected.get("id").and_then(Value::as_str),
            Some(*id),
            "fixture order changed"
        );
        assert_eq!(
            fixtures::observe(source).expect("serialize complete output"),
            expected.get("output").expect("captured output").clone(),
            "complete SSR output changed for {id}"
        );
    }
}
