import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
// Paths are resolved from the package cwd: the runner virtualizes import.meta.url.
import path from "node:path";

import { test } from "vite-plus/test";

import { formatSfcLintResults, lintSfcFiles } from "../../scripts/source-quality/lint-sfc.ts";
import type { SfcLintFunction } from "../../scripts/source-quality/lint-sfc.ts";

test("discovers every SFC with the opinionated Vize contract", async () => {
  const requests: Parameters<SfcLintFunction>[1][] = [];
  const lint: SfcLintFunction = (_source, options) => {
    requests.push(options);
    return { diagnostics: [] };
  };
  const results = await lintSfcFiles(lint);

  assert.deepEqual(
    results.map((result) => result.filename),
    [
      "src/families/accessibility/announcer/announcer-provider.vue",
      "src/families/accessibility/live-region/live-region.vue",
      "src/families/accessibility/visually-hidden/visually-hidden.vue",
      "src/families/actions/button-group/button-group-item.vue",
      "src/families/actions/button-group/button-group.vue",
      "src/families/actions/button/button.vue",
      "src/families/actions/copy-button/copy-button.vue",
      "src/families/actions/fullscreen-button/fullscreen-button.vue",
      "src/families/actions/print-button/print-button.vue",
      "src/families/actions/share-button/share-button.vue",
      "src/families/actions/toolbar/toolbar-item.vue",
      "src/families/actions/toolbar/toolbar.vue",
      "src/families/data/table/table-body.vue",
      "src/families/data/table/table-caption.vue",
      "src/families/data/table/table-cell.vue",
      "src/families/data/table/table-head.vue",
      "src/families/data/table/table-header.vue",
      "src/families/data/table/table-row.vue",
      "src/families/data/table/table.vue",
      "src/families/disclosure/collapsible/collapsible-content.vue",
      "src/families/disclosure/collapsible/collapsible-root.vue",
      "src/families/disclosure/collapsible/collapsible-trigger.vue",
      "src/families/feedback/alert/alert.vue",
      "src/families/feedback/badge/badge.vue",
      "src/families/feedback/banner/banner.vue",
      "src/families/feedback/block-ui/block-ui.vue",
      "src/families/feedback/callout/callout.vue",
      "src/families/feedback/empty-state/empty-state.vue",
      "src/families/feedback/meter/meter.vue",
      "src/families/feedback/progress-bar/progress-bar.vue",
      "src/families/feedback/progress/progress.vue",
      "src/families/feedback/skeleton/skeleton.vue",
      "src/families/feedback/spinner/spinner.vue",
      "src/families/feedback/status-light/status-light.vue",
      "src/families/form/error-summary/error-summary.vue",
      "src/families/form/field/field-description.vue",
      "src/families/form/field/field-error-message.vue",
      "src/families/form/field/field-label.vue",
      "src/families/form/field/field.vue",
      "src/families/form/input/text-input.vue",
      "src/families/form/rating/rating.vue",
      "src/families/form/search-field/search-field.vue",
      "src/families/form/slider/slider.vue",
      "src/families/form/textarea/textarea-control.vue",
      "src/families/foundations/id/deterministic-id-provider.vue",
      "src/families/foundations/primitive/primitive-element.vue",
      "src/families/i18n/locale/locale-provider.vue",
      "src/families/layout/aspect-ratio/aspect-ratio.vue",
      "src/families/layout/avatar/avatar.vue",
      "src/families/layout/card/card.vue",
      "src/families/layout/cluster/cluster.vue",
      "src/families/layout/container/container.vue",
      "src/families/layout/grid/grid.vue",
      "src/families/layout/icon/icon-button.vue",
      "src/families/layout/icon/icon.vue",
      "src/families/layout/list/list.vue",
      "src/families/layout/scroll-area/scroll-area.vue",
      "src/families/layout/separator/separator.vue",
      "src/families/layout/spacer/spacer.vue",
      "src/families/layout/stack/stack.vue",
      "src/families/layout/surface/surface.vue",
      "src/families/navigation/breadcrumb/breadcrumb-item.vue",
      "src/families/navigation/breadcrumb/breadcrumb-link.vue",
      "src/families/navigation/breadcrumb/breadcrumb-list.vue",
      "src/families/navigation/breadcrumb/breadcrumb-separator.vue",
      "src/families/navigation/breadcrumb/breadcrumb.vue",
      "src/families/navigation/link/link-anchor.vue",
      "src/families/navigation/pagination/pagination-ellipsis.vue",
      "src/families/navigation/pagination/pagination-item.vue",
      "src/families/navigation/pagination/pagination-list.vue",
      "src/families/navigation/pagination/pagination-next.vue",
      "src/families/navigation/pagination/pagination-page.vue",
      "src/families/navigation/pagination/pagination-previous.vue",
      "src/families/navigation/pagination/pagination.vue",
      "src/families/navigation/skip-link/skip-link.vue",
      "src/families/navigation/stepper/stepper-content.vue",
      "src/families/navigation/stepper/stepper-item.vue",
      "src/families/navigation/stepper/stepper-list.vue",
      "src/families/navigation/stepper/stepper-root.vue",
      "src/families/navigation/stepper/stepper-trigger.vue",
      "src/families/navigation/tabs/tabs-content.vue",
      "src/families/navigation/tabs/tabs-list.vue",
      "src/families/navigation/tabs/tabs-root.vue",
      "src/families/navigation/tabs/tabs-trigger.vue",
      "src/families/overlays/alert-dialog/alert-dialog-content.vue",
      "src/families/overlays/dialog/dialog-close.vue",
      "src/families/overlays/dialog/dialog-content.vue",
      "src/families/overlays/dialog/dialog-description.vue",
      "src/families/overlays/dialog/dialog-overlay.vue",
      "src/families/overlays/dialog/dialog-portal.vue",
      "src/families/overlays/dialog/dialog-root.vue",
      "src/families/overlays/dialog/dialog-title.vue",
      "src/families/overlays/dialog/dialog-trigger.vue",
      "src/families/overlays/popover/popover-arrow.vue",
      "src/families/overlays/popover/popover-content.vue",
      "src/families/overlays/popover/popover-root.vue",
      "src/families/overlays/popover/popover-trigger.vue",
      "src/families/overlays/portal/portal.vue",
      "src/families/overlays/positioner/positioner-arrow.vue",
      "src/families/overlays/positioner/positioner.vue",
      "src/families/overlays/presence/presence.vue",
      "src/families/overlays/tooltip/tooltip-content.vue",
      "src/families/overlays/tooltip/tooltip-root.vue",
      "src/families/overlays/tooltip/tooltip-trigger.vue",
      "src/families/overlays/transition/transition.vue",
      "src/families/selection/checkbox/checkbox-control.vue",
      "src/families/selection/listbox/listbox-item.vue",
      "src/families/selection/listbox/listbox.vue",
      "src/families/selection/native-select/native-select.vue",
      "src/families/selection/radio-group/radio-group-item.vue",
      "src/families/selection/radio-group/radio-group.vue",
      "src/families/selection/switch/switch-control.vue",
      "src/families/selection/toggle-group/toggle-group-item.vue",
      "src/families/selection/toggle-group/toggle-group.vue",
      "src/families/selection/toggle/toggle-button.vue",
      "src/families/typography/blockquote/blockquote.vue",
      "src/families/typography/code/code.vue",
      "src/families/typography/heading/heading.vue",
      "src/families/typography/kbd/kbd.vue",
      "src/families/typography/text/text.vue",
    ],
  );
  assert.deepEqual(
    requests,
    [
      "families/accessibility/announcer/announcer-provider.vue",
      "families/accessibility/live-region/live-region.vue",
      "families/accessibility/visually-hidden/visually-hidden.vue",
      "families/actions/button-group/button-group-item.vue",
      "families/actions/button-group/button-group.vue",
      "families/actions/button/button.vue",
      "families/actions/copy-button/copy-button.vue",
      "families/actions/fullscreen-button/fullscreen-button.vue",
      "families/actions/print-button/print-button.vue",
      "families/actions/share-button/share-button.vue",
      "families/actions/toolbar/toolbar-item.vue",
      "families/actions/toolbar/toolbar.vue",
      "families/data/table/table-body.vue",
      "families/data/table/table-caption.vue",
      "families/data/table/table-cell.vue",
      "families/data/table/table-head.vue",
      "families/data/table/table-header.vue",
      "families/data/table/table-row.vue",
      "families/data/table/table.vue",
      "families/disclosure/collapsible/collapsible-content.vue",
      "families/disclosure/collapsible/collapsible-root.vue",
      "families/disclosure/collapsible/collapsible-trigger.vue",
      "families/feedback/alert/alert.vue",
      "families/feedback/badge/badge.vue",
      "families/feedback/banner/banner.vue",
      "families/feedback/block-ui/block-ui.vue",
      "families/feedback/callout/callout.vue",
      "families/feedback/empty-state/empty-state.vue",
      "families/feedback/meter/meter.vue",
      "families/feedback/progress-bar/progress-bar.vue",
      "families/feedback/progress/progress.vue",
      "families/feedback/skeleton/skeleton.vue",
      "families/feedback/spinner/spinner.vue",
      "families/feedback/status-light/status-light.vue",
      "families/form/error-summary/error-summary.vue",
      "families/form/field/field-description.vue",
      "families/form/field/field-error-message.vue",
      "families/form/field/field-label.vue",
      "families/form/field/field.vue",
      "families/form/input/text-input.vue",
      "families/form/rating/rating.vue",
      "families/form/search-field/search-field.vue",
      "families/form/slider/slider.vue",
      "families/form/textarea/textarea-control.vue",
      "families/foundations/id/deterministic-id-provider.vue",
      "families/foundations/primitive/primitive-element.vue",
      "families/i18n/locale/locale-provider.vue",
      "families/layout/aspect-ratio/aspect-ratio.vue",
      "families/layout/avatar/avatar.vue",
      "families/layout/card/card.vue",
      "families/layout/cluster/cluster.vue",
      "families/layout/container/container.vue",
      "families/layout/grid/grid.vue",
      "families/layout/icon/icon-button.vue",
      "families/layout/icon/icon.vue",
      "families/layout/list/list.vue",
      "families/layout/scroll-area/scroll-area.vue",
      "families/layout/separator/separator.vue",
      "families/layout/spacer/spacer.vue",
      "families/layout/stack/stack.vue",
      "families/layout/surface/surface.vue",
      "families/navigation/breadcrumb/breadcrumb-item.vue",
      "families/navigation/breadcrumb/breadcrumb-link.vue",
      "families/navigation/breadcrumb/breadcrumb-list.vue",
      "families/navigation/breadcrumb/breadcrumb-separator.vue",
      "families/navigation/breadcrumb/breadcrumb.vue",
      "families/navigation/link/link-anchor.vue",
      "families/navigation/pagination/pagination-ellipsis.vue",
      "families/navigation/pagination/pagination-item.vue",
      "families/navigation/pagination/pagination-list.vue",
      "families/navigation/pagination/pagination-next.vue",
      "families/navigation/pagination/pagination-page.vue",
      "families/navigation/pagination/pagination-previous.vue",
      "families/navigation/pagination/pagination.vue",
      "families/navigation/skip-link/skip-link.vue",
      "families/navigation/stepper/stepper-content.vue",
      "families/navigation/stepper/stepper-item.vue",
      "families/navigation/stepper/stepper-list.vue",
      "families/navigation/stepper/stepper-root.vue",
      "families/navigation/stepper/stepper-trigger.vue",
      "families/navigation/tabs/tabs-content.vue",
      "families/navigation/tabs/tabs-list.vue",
      "families/navigation/tabs/tabs-root.vue",
      "families/navigation/tabs/tabs-trigger.vue",
      "families/overlays/alert-dialog/alert-dialog-content.vue",
      "families/overlays/dialog/dialog-close.vue",
      "families/overlays/dialog/dialog-content.vue",
      "families/overlays/dialog/dialog-description.vue",
      "families/overlays/dialog/dialog-overlay.vue",
      "families/overlays/dialog/dialog-portal.vue",
      "families/overlays/dialog/dialog-root.vue",
      "families/overlays/dialog/dialog-title.vue",
      "families/overlays/dialog/dialog-trigger.vue",
      "families/overlays/popover/popover-arrow.vue",
      "families/overlays/popover/popover-content.vue",
      "families/overlays/popover/popover-root.vue",
      "families/overlays/popover/popover-trigger.vue",
      "families/overlays/portal/portal.vue",
      "families/overlays/positioner/positioner-arrow.vue",
      "families/overlays/positioner/positioner.vue",
      "families/overlays/presence/presence.vue",
      "families/overlays/tooltip/tooltip-content.vue",
      "families/overlays/tooltip/tooltip-root.vue",
      "families/overlays/tooltip/tooltip-trigger.vue",
      "families/overlays/transition/transition.vue",
      "families/selection/checkbox/checkbox-control.vue",
      "families/selection/listbox/listbox-item.vue",
      "families/selection/listbox/listbox.vue",
      "families/selection/native-select/native-select.vue",
      "families/selection/radio-group/radio-group-item.vue",
      "families/selection/radio-group/radio-group.vue",
      "families/selection/switch/switch-control.vue",
      "families/selection/toggle-group/toggle-group-item.vue",
      "families/selection/toggle-group/toggle-group.vue",
      "families/selection/toggle/toggle-button.vue",
      "families/typography/blockquote/blockquote.vue",
      "families/typography/code/code.vue",
      "families/typography/heading/heading.vue",
      "families/typography/kbd/kbd.vue",
      "families/typography/text/text.vue",
    ].map((basename) => ({
      filename: path.resolve("src", basename),
      preset: "opinionated" as const,
      typeAware: true as const,
      helpLevel: "short" as const,
    })),
  );
  assert.equal(formatSfcLintResults(results), "");
});

test("package lint:sfc stays wired to the shared Vize SFC gate", async () => {
  const manifest = JSON.parse(await readFile(path.resolve("package.json"), "utf8")) as {
    scripts?: Record<string, string>;
  };
  const lintScript = await readFile(path.resolve("scripts/lint-sfc.ts"), "utf8");

  assert.equal(
    manifest.scripts?.["lint:sfc"],
    "vp exec node scripts/lint-sfc.ts src && vp exec node scripts/check-renderers.ts src",
  );
  assert.match(lintScript, /import \{ lintPatinaSfc \} from "@vizejs\/native";/);
  assert.match(lintScript, /const lintCoreSfc: SfcLintFunction = \(source, options\) =>/);
  assert.match(lintScript, /corsaPath: workspaceCorsaPath/);
  assert.match(lintScript, /lintFiles\(lintCoreSfc, sourceRoots\)/);
  assert.match(
    lintScript,
    /runSfcLintCli\(lintCoreSfc, sourceRoots\.length > 0 \? sourceRoots : "src"\)/,
  );
});
