// Reviewed original local-alias defaults-key identity source delta (#8011).
// These exact paths qualify the before/after source pair; the original400
// workload, input digests, native/build recipes and numeric ceilings are unchanged.
export const aliasHostPaths = [
  "crates/vize/tests/lsp_type_alias_original_transactions_cli.rs",
  "crates/vize_canon/src/batch/source_map/sfc.rs",
  "crates/vize_canon/src/batch/virtual_project/build.rs",
  "crates/vize_canon/src/batch/virtual_project/content_mapper.rs",
  "crates/vize_canon/src/batch/virtual_project/document.rs",
  "crates/vize_canon/src/batch/virtual_project/mapping/materialized_sources.rs",
  "crates/vize_canon/src/batch/virtual_project/vue_codegen.rs",
  "crates/vize_canon/src/batch/virtual_project/vue_codegen/types.rs",
  "crates/vize_canon/src/virtual_ts/defaults_key_links_tests.rs",
  "crates/vize_canon/src/virtual_ts/generator/binding_output.rs",
  "crates/vize_canon/src/virtual_ts/generator/setup_props.rs",
  "crates/vize_canon/src/virtual_ts/mapping/model.rs",
  "crates/vize_canon/src/virtual_ts/mapping/model/binding_links.rs",
  "crates/vize_canon/src/virtual_ts/mapping/model/generated_ranges.rs",
  "crates/vize_canon/src/virtual_ts/props/mappings.rs",
  "crates/vize_canon/src/virtual_ts/semantic_links.rs",
  "crates/vize_croquis/src/macros/defaults.rs",
  "crates/vize_croquis/src/macros/tracker.rs",
  "crates/vize_croquis/src/script_parser/extract/with_defaults.rs",
  "crates/vize_croquis/src/script_parser/props_ranges_tests.rs",
  "crates/vize_maestro/src/ide/corsa_support.rs",
  "crates/vize_maestro/src/ide/corsa_support/canonical.rs",
  "crates/vize_maestro/src/ide/corsa_support/canonical/script.rs",
  "crates/vize_maestro/src/ide/corsa_support/canonical/semantic_links.rs",
  "crates/vize_maestro/src/ide/corsa_support/canonical/semantic_links/binding_links.rs",
  "crates/vize_maestro/src/ide/corsa_support/canonical/semantic_links/component_props.rs",
  "crates/vize_maestro/src/ide/corsa_support/canonical_tests.rs",
  "crates/vize_maestro/src/ide/diagnostics/corsa.rs",
  "crates/vize_maestro/src/ide/diagnostics/corsa/collect_script.rs",
  "crates/vize_maestro/src/ide/diagnostics/corsa/prop_default_key_link_tests.rs",
  "crates/vize_maestro/src/ide/diagnostics/corsa/virtual_ts.rs",
  "crates/vize_maestro/src/ide/diagnostics/corsa/virtual_ts_art.rs",
  "crates/vize_maestro/src/ide/diagnostics/corsa/virtual_ts_inline_art.rs",
  "crates/vize_maestro/src/ide/references/canonical.rs",
  "crates/vize_maestro/src/ide/rename/canonical.rs",
  "crates/vize_maestro/src/ide/script_symbols/tests.rs",
] as const;
