import assert from "node:assert/strict";
import { test } from "node:test";
import {
  applyFixes,
  defineFactProvider,
  defineOutputPlugin,
  definePlugin,
  defineTransformPlugin,
} from "../../npm/plugin-sdk/index.js";

const batch = {
  schema: 1,
  parents: [-1, 0],
  nodes: [
    { id: 0, kind: "ui.element", name: "button" },
    { id: 1, kind: "ui.bind", name: "disabled", value: "true" },
  ],
  facts: {},
};

test("rule visits are immutable and reports contain no user-supplied ranges", () => {
  const plugin = definePlugin({
    name: "boolean-shorthand",
    version: "1",
    visit: ["ui.bind"],
    cacheInputs: [],
    rules: {
      shorthand(ctx) {
        assert.throws(() => {
          ctx.nodes = [];
        }, TypeError);
        assert.throws(() => {
          ctx.nodes[1].value = "false";
        }, TypeError);
        ctx.report(ctx.nodes[1], "Use the boolean attribute.", "disabled");
      },
    },
  });
  assert.deepEqual(JSON.parse(plugin.run(JSON.stringify(batch))), [
    { rule: "shorthand", node: 1, message: "Use the boolean attribute.", fix: "disabled" },
  ]);
  assert.equal(Object.isFrozen(plugin), true);
  assert.equal(Object.isFrozen(plugin.cacheInputs), true);
});

test("synchronous hooks refuse Promise results and undeclared fact reads", () => {
  const asyncRule = definePlugin({ name: "async", version: "1", rules: { async check() {} } });
  assert.throws(() => asyncRule.run(JSON.stringify(batch)), /asynchronous rules are unsupported/);
  const undeclared = definePlugin({
    name: "facts",
    version: "1",
    rules: {
      check(ctx) {
        ctx.facts("bindings");
      },
    },
  });
  assert.throws(() => undeclared.run(JSON.stringify(batch)), /was not declared in demands/);
});

test("autofixes use UTF-8 byte offsets and refuse conflicts atomically", () => {
  const source = '<template>日本語😀<button :disabled="true" /></template>';
  const start = Buffer.byteLength(source.slice(0, source.indexOf(":disabled")));
  const fix = { start, end: start + Buffer.byteLength(':disabled="true"'), text: "disabled" };
  assert.equal(applyFixes(source, [fix, fix]), source.replace(':disabled="true"', "disabled"));
  assert.throws(() => applyFixes(source, [fix, { ...fix, text: "required" }]), /overlapping/);
  assert.throws(() => applyFixes(source, [{ start: 11, end: 12, text: "x" }]), /UTF-8/);
  assert.throws(() => applyFixes(source, [{ start: 0, end: 1000, text: "x" }]), /UTF-8/);
  assert.equal(applyFixes(source, []), source);
});

test("transform, provider and output helpers encode their native wire contracts", () => {
  const transform = defineTransformPlugin({
    name: "design-system",
    version: "1",
    cacheInputs: [],
    transform(input) {
      assert.equal(Object.isFrozen(input.nodes), true);
      return [
        {
          kind: "replace-static-attribute",
          node: input.nodes[0].id,
          name: "class",
          value: "ds-button",
        },
      ];
    },
  });
  const input = { schema: 1, stage: "s2-precanonical-static-attributes", nodes: [{ id: 0 }] };
  assert.deepEqual(JSON.parse(transform.run(JSON.stringify(input))), {
    schema: 1,
    edits: [{ kind: "replace-static-attribute", node: 0, name: "class", value: "ds-button" }],
  });
  assert.throws(() => transform.run(JSON.stringify({ ...input, schema: 2 })), /unsupported L2/);
  const provider = defineFactProvider({
    name: "design",
    version: "1",
    provides: ["design/tokens"],
    cacheInputs: [],
    provide() {
      return { "design/tokens": [[0, "primary"]] };
    },
  });
  assert.deepEqual(JSON.parse(provider.run(JSON.stringify(batch))), {
    "design/tokens": [[0, "primary"]],
  });
  const output = defineOutputPlugin({
    name: "banner",
    version: "1",
    family: "output",
    cacheInputs: [],
    output() {
      return [{ placement: "prepend", comment: "Generated by Vize" }];
    },
  });
  assert.deepEqual(
    JSON.parse(
      output.run(
        JSON.stringify({
          schema: 1,
          family: "output",
          offsetEncoding: "utf8",
          compiled: { code: "export{}" },
        }),
      ),
    ),
    [{ placement: "prepend", comment: "Generated by Vize" }],
  );
});
