import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { readRepoFile, workflowJobBody } from "./support/github-workflows.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const packageDir = path.join(root, "npm/fresco-native");
const verifier = path.join(packageDir, "scripts/verify-generated-contract.mjs");

function declarationFiles(directory: string, prefix = ""): string[] {
  const found: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      found.push(...declarationFiles(path.join(directory, entry.name), relative));
    } else if (entry.name.endsWith(".d.ts")) {
      found.push(relative);
    }
  }
  return found.sort();
}

function runVerifier(committedDir: string, generatedDir: string) {
  return spawnSync(
    process.execPath,
    [verifier, "--package-dir", committedDir, "--generated-dir", generatedDir],
    { cwd: root, encoding: "utf8" },
  );
}

function writeContract(directory: string, declaration: string, exports: string[]): void {
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, "index.d.ts"), declaration);
  fs.writeFileSync(
    path.join(directory, "index.js"),
    `${exports.map((name) => `module.exports.${name} = nativeBinding.${name}`).join("\n")}\n`,
  );
}

test("fresco-native ships one generated declaration and exposes strict contract checks", () => {
  const manifest = JSON.parse(readRepoFile("npm", "fresco-native", "package.json")) as {
    files: string[];
    scripts?: Record<string, string>;
    types: string;
    devDependencies?: Record<string, string>;
  };

  assert.deepEqual(declarationFiles(packageDir), ["index.d.ts"]);
  assert.deepEqual(manifest.files, ["index.js", "index.d.ts", "*.node"]);
  assert.equal(manifest.types, "index.d.ts");
  assert.equal(
    manifest.scripts?.["check:generated"],
    "node ./scripts/verify-generated-contract.mjs --profile ci",
  );
  assert.equal(manifest.scripts?.["check:types"], "node ./scripts/verify-consumer-types.mjs");
  assert.equal(manifest.devDependencies?.typescript, "catalog:typescript");
  assert.match(
    readRepoFile("npm", "fresco-native", "tests", "types", "consumer.ts"),
    /from "@vizejs\/fresco-native"/,
  );
  assert.match(readRepoFile("npm", "fresco-native", "index.d.ts"), /auto-generated by NAPI-RS/);
  assert.match(
    readRepoFile("vite.config.ts"),
    /localGeneratedIgnorePatterns = \[[\s\S]*"npm\/fresco-native\/index\.d\.ts"/,
  );
});

test("fresco-native verifier rejects declaration and loader export drift", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "fresco-native-contract-"));
  const committedDir = path.join(tempDir, "committed");
  const generatedDir = path.join(tempDir, "generated");
  const declaration = [
    "/* auto-generated by NAPI-RS */",
    "export declare function alpha(): void",
    "export declare function beta(value: string): number",
    "",
  ].join("\n");

  try {
    writeContract(committedDir, declaration, ["alpha", "beta"]);
    writeContract(generatedDir, declaration, ["alpha", "beta"]);
    const valid = runVerifier(committedDir, generatedDir);
    assert.equal(valid.status, 0, `${valid.stderr}\n${valid.stdout}`.trim());

    fs.appendFileSync(path.join(generatedDir, "index.d.ts"), "// drift\n");
    const declarationDrift = runVerifier(committedDir, generatedDir);
    assert.notEqual(declarationDrift.status, 0);
    assert.match(declarationDrift.stderr, /generated index\.d\.ts differs byte-for-byte/);

    writeContract(generatedDir, declaration, ["alpha"]);
    const generatedLoaderDrift = runVerifier(committedDir, generatedDir);
    assert.notEqual(generatedLoaderDrift.status, 0);
    assert.match(generatedLoaderDrift.stderr, /generated loader exports/);

    writeContract(generatedDir, declaration, ["alpha", "beta"]);
    writeContract(committedDir, declaration, ["alpha"]);
    const committedLoaderDrift = runVerifier(committedDir, generatedDir);
    assert.notEqual(committedLoaderDrift.status, 0);
    assert.match(committedLoaderDrift.stderr, /committed loader exports/);

    const tempEntriesBefore = fs
      .readdirSync(os.tmpdir())
      .filter((entry) => entry.startsWith("vize-fresco-native-generated-"))
      .sort();
    const failedBuild = spawnSync(
      process.execPath,
      [verifier, "--package-dir", committedDir, "--profile", "ci"],
      { cwd: root, encoding: "utf8" },
    );
    assert.notEqual(failedBuild.status, 0);
    assert.match(failedBuild.stderr, /NAPI declaration build failed/);
    const tempEntriesAfter = fs
      .readdirSync(os.tmpdir())
      .filter((entry) => entry.startsWith("vize-fresco-native-generated-"))
      .sort();
    assert.deepEqual(tempEntriesAfter, tempEntriesBefore);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
});

test("build CI verifies generated Fresco declarations and consumer types", () => {
  const workflow = readRepoFile(".github", "workflows", "check.yml");
  const buildJob = workflowJobBody(workflow, "build-js-packages");

  assert.match(buildJob, /\bcheck:generated\b/);
  assert.match(buildJob, /\bcheck:types\b/);
  assert.ok(
    buildJob.indexOf("check:generated") < buildJob.indexOf("check:types") &&
      buildJob.indexOf("check:types") < buildJob.indexOf("name: Build JS packages"),
    "declaration parity must fail before JavaScript package artifacts are built",
  );
});
