import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const lintRuleSnapshotPath = path.join(
  repoRoot,
  "crates",
  "vize_patina",
  "src",
  "preset",
  "snapshots",
  "vize_patina__preset__tests__lint_preset_rule_membership.snap",
);
const lintRuleTypesPath = path.join(repoRoot, "npm", "cli", "src", "types", "rules.ts");
const ruleTypesScriptPath = path.join(repoRoot, "tools", "commands", "generate", "rule-types.rs");

function collectLintRuleNames(snapshotContent: string): string[] {
  const frontmatterEnd = snapshotContent.indexOf("\n---\n", 4);

  if (!snapshotContent.startsWith("---\n") || frontmatterEnd === -1) {
    throw new Error("Invalid insta snapshot format for lint preset rule membership");
  }

  const snapshotValue = JSON.parse(snapshotContent.slice(frontmatterEnd + "\n---\n".length)) as
    | Record<string, unknown>
    | unknown[];

  assert.ok(
    snapshotValue != null && !Array.isArray(snapshotValue) && typeof snapshotValue === "object",
  );

  const ruleNames = new Set<string>();
  for (const [preset, names] of Object.entries(snapshotValue)) {
    assert.ok(Array.isArray(names), `Expected ${preset} rules to be an array`);

    for (const name of names) {
      assert.equal(typeof name, "string", `Expected ${preset} rule name to be a string`);
      ruleNames.add(name);
    }
  }

  return [...ruleNames].sort();
}

function generateLintRuleTypes(ruleNames: readonly string[]): string {
  const ruleEntries = ruleNames.map((name) => `  ${JSON.stringify(name)},`).join("\n");

  return `// This file is generated by \`rust-script tools/commands/generate/rule-types.rs\`.
// Do not edit it by hand.

import type { RuleSeverity } from "./generated.js";

export const LINT_RULE_NAMES = [
${ruleEntries}
] as const;

export type LintRuleName = (typeof LINT_RULE_NAMES)[number];

export type LintRulesConfig = Partial<Record<LintRuleName, RuleSeverity>>;
`;
}

test("rule type generator keeps generated lint rule types in sync", () => {
  const expected = generateLintRuleTypes(
    collectLintRuleNames(fs.readFileSync(lintRuleSnapshotPath, "utf8")),
  );

  assert.equal(fs.readFileSync(lintRuleTypesPath, "utf8"), expected);

  const result = spawnSync("rust-script", [ruleTypesScriptPath], {
    cwd: repoRoot,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, `${result.stderr}\n${result.stdout}`.trim());
  assert.equal(fs.readFileSync(lintRuleTypesPath, "utf8"), expected);
});
