/**
 * A pinned fixture `tsconfig` must be one `vue-tsc` actually typechecks the
 * fixture's `.vue` files under (#3513).
 *
 * The divergence ledger compares vize against a `vue-tsc` baseline. When the
 * pinned config makes `vue-tsc` check *nothing*, every vize diagnostic is scored
 * as a false positive by construction, and the run still exits with a code the
 * report accepts. That is how the ledger came to report 662 false positives for
 * element-plus while the two sides had never been compared at a single
 * diagnostic.
 *
 * `evaluateBudget` classifies that as `unusable` rather than as a vize
 * regression, but classifying it after a shard has run is not the same as not
 * shipping it. This is the cheap static half: a solution-style config —
 * `"files": []` with `"references"` — is *known* to check zero files, because
 * `vue-tsc` does not follow project references without `--build`. It never has
 * to run to be wrong.
 *
 * Checked only for hydrated fixtures, so this passes in a shallow clone.
 */

import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const REGISTRY = path.join(REPO_ROOT, "tests/_fixtures/vue-ecosystem-fixtures.json");

type Project = {
  id: string;
  fixturePath: string;
  tsconfig?: string;
  coverage?: string[];
};

function projects(): Project[] {
  const registry = JSON.parse(fs.readFileSync(REGISTRY, "utf8")) as { projects: Project[] };
  return registry.projects;
}

/**
 * Strip JSONC — line and block comments, trailing commas — string-aware.
 *
 * The scan tracks string state because a regex pass cannot: `"src/**\/*"`, an
 * ordinary include glob, contains `/**\/`, which a block-comment pattern
 * happily eats, silently rewriting the config it was asked to read.
 */
function stripJsonc(text: string): string {
  let out = "";
  let inString = false;
  for (let i = 0; i < text.length; i += 1) {
    const ch = text[i];
    if (inString) {
      out += ch;
      if (ch === "\\") {
        out += text[i + 1] ?? "";
        i += 1;
      } else if (ch === '"') {
        inString = false;
      }
      continue;
    }
    if (ch === '"') {
      inString = true;
      out += ch;
      continue;
    }
    if (ch === "/" && text[i + 1] === "/") {
      while (i < text.length && text[i] !== "\n") i += 1;
      out += "\n";
      continue;
    }
    if (ch === "/" && text[i + 1] === "*") {
      i += 2;
      while (i + 1 < text.length && !(text[i] === "*" && text[i + 1] === "/")) i += 1;
      i += 1;
      continue;
    }
    out += ch;
  }
  return out.replace(/,(\s*[}\]])/g, "$1");
}

/** `null` when the config does not parse; this test is not about JSON hygiene. */
function readTsconfig(
  file: string,
): { files?: unknown[]; include?: unknown[]; references?: unknown[] } | null {
  try {
    const value: unknown = JSON.parse(stripJsonc(fs.readFileSync(file, "utf8")));
    return typeof value === "object" && value !== null ? (value as never) : null;
  } catch {
    return null;
  }
}

/**
 * Fixtures already pinning a solution-style config when this guard was added,
 * with what each one would have to be repointed to.
 *
 * Listed rather than skipped silently, because the ledger's numbers for these
 * projects are not measurements of vize and that has to stay visible. #3513
 * named two of them; the guard found twelve.
 */
const KNOWN_SOLUTION_STYLE: Record<string, string> = {
  elk: "./.nuxt/* — generated by `nuxt prepare`, which the matrix does not run",
  "inspira-ui": "./.nuxt/* — generated by `nuxt prepare`, which the matrix does not run",
  "vaul-vue": "./tsconfig.app.json is the likely repoint; unverified",
  "vue-termui": "./tsconfig.build.json is the likely repoint; unverified",
  filebrowser: "./tsconfig.app.json is the likely repoint; unverified",
  "mall-admin-web": "./tsconfig.app.json is the likely repoint; unverified",
  douyin: "./tsconfig.app.json is the likely repoint; unverified",
  "vue-fabric-editor": "only ./tsconfig.node.json is referenced; no app config in the pinned tree",
  "sigma-file-manager": "./tsconfig.app.json is the likely repoint; unverified",
  "vue-bits": "./tsconfig.app.json is the likely repoint; unverified",
  "portal-vue": "./tsconfig.app.json is the likely repoint; unverified",
};

test("no typechecked fixture pins a solution-style tsconfig", () => {
  const offenders: string[] = [];
  const unusedExemptions = new Set(Object.keys(KNOWN_SOLUTION_STYLE));
  const readable = new Set<string>();

  for (const project of projects()) {
    if (!project.coverage?.includes("typechecker")) continue;
    const relative = project.tsconfig ?? "tsconfig.json";
    const configPath = path.join(REPO_ROOT, project.fixturePath, relative);
    if (!fs.existsSync(configPath)) continue;

    const config = readTsconfig(configPath);
    if (config === null) continue;
    readable.add(project.id);

    const checksNothing =
      Array.isArray(config.files) &&
      config.files.length === 0 &&
      Array.isArray(config.references) &&
      config.references.length > 0;
    if (!checksNothing) continue;

    if (project.id in KNOWN_SOLUTION_STYLE) {
      unusedExemptions.delete(project.id);
      continue;
    }
    offenders.push(
      `${project.id} pins ${relative}, which is solution-style ("files": [] with ` +
        `"references"). vue-tsc does not follow project references without --build, so it ` +
        `typechecks zero files and every vize diagnostic is scored a false positive. Pin the ` +
        `config that includes the .vue sources.`,
    );
  }

  assert.deepEqual(offenders, [], offenders.join("\n"));

  // An exemption outliving its problem is removed here rather than left to rot.
  // Only fixtures actually read count, so an unhydrated one never looks fixed.
  const resolved = [...unusedExemptions].filter((id) => readable.has(id));
  assert.deepEqual(
    resolved,
    [],
    `these fixtures no longer pin a solution-style tsconfig; drop them from ` +
      `KNOWN_SOLUTION_STYLE: ${resolved.join(", ")}`,
  );
});

test("SPlayer pins the concrete web tsconfig used by Vue sources", () => {
  const project = projects().find((candidate) => candidate.id === "splayer");
  assert.ok(project, "SPlayer fixture must stay registered");
  const tsconfig = project.tsconfig;
  assert.ok(tsconfig, "SPlayer tsconfig path must be set");
  assert.equal(tsconfig, "tsconfig.web.json");

  const configPath = path.join(REPO_ROOT, project.fixturePath, tsconfig);
  if (!fs.existsSync(configPath)) return;

  const config = readTsconfig(configPath);
  assert.ok(config, "SPlayer web tsconfig must be readable when hydrated");
  assert.ok(
    Array.isArray(config.include) &&
      config.include.some((entry) => typeof entry === "string" && entry.includes(".vue")),
    "SPlayer web tsconfig must include Vue source globs",
  );
});
