import { defineConfig } from "vite-plus";

export default defineConfig({
  lint: {
    ignorePatterns: ["dist/**"],
    options: { typeAware: true },
  },
  fmt: { ignorePatterns: ["dist/**"] },
  pack: {
    entry: {
      index: "src/index.ts",
      "abort-signal": "src/abort-signal.ts",
      "active-element": "src/active-element.ts",
      "async-resource": "src/async-resource.ts",
      battery: "src/battery.ts",
      capability: "src/capability.ts",
      catalog: "src/catalog.ts",
      "device-motion": "src/device-motion.ts",
      "device-orientation": "src/device-orientation.ts",
      "device-pixel-ratio": "src/device-pixel-ratio.ts",
      "disposal-scope": "src/disposal-scope.ts",
      "document-visibility": "src/document-visibility.ts",
      "element-bounding": "src/element-bounding.ts",
      "element-target": "src/element-target.ts",
      "event-listener": "src/event-listener.ts",
      focus: "src/focus.ts",
      fps: "src/fps.ts",
      geolocation: "src/geolocation.ts",
      idle: "src/idle.ts",
      "intersection-observer": "src/intersection-observer.ts",
      locale: "src/locale.ts",
      "magic-keys": "src/magic-keys.ts",
      "media-query": "src/media-query.ts",
      mouse: "src/mouse.ts",
      "mouse-in-element": "src/mouse-in-element.ts",
      "mutation-observer": "src/mutation-observer.ts",
      network: "src/network.ts",
      "page-leave": "src/page-leave.ts",
      pinch: "src/pinch.ts",
      pointer: "src/pointer.ts",
      "pointer-lock": "src/pointer-lock.ts",
      preferences: "src/preferences.ts",
      "preferred-languages": "src/preferred-languages.ts",
      "resize-observer": "src/resize-observer.ts",
      "retry-async": "src/retry-async.ts",
      "retry-delay": "src/retry-delay.ts",
      scope: "src/scope.ts",
      "screen-orientation": "src/screen-orientation.ts",
      scroll: "src/scroll.ts",
      swipe: "src/swipe.ts",
      temporal: "src/temporal.ts",
      "text-selection": "src/text-selection.ts",
      "timeout-scheduler": "src/timeout-scheduler.ts",
      "use-broadcast-channel": "src/use-broadcast-channel.ts",
      "use-clipboard": "src/use-clipboard.ts",
      "use-cookie": "src/use-cookie.ts",
      "use-counter": "src/use-counter.ts",
      "use-css-var": "src/use-css-var.ts",
      "use-debounced": "src/use-debounced.ts",
      "use-display-media": "src/use-display-media.ts",
      "use-document-title": "src/use-document-title.ts",
      "use-drop-zone": "src/use-drop-zone.ts",
      "use-event-source": "src/use-event-source.ts",
      "use-eye-dropper": "src/use-eye-dropper.ts",
      "use-favicon": "src/use-favicon.ts",
      "use-fetch": "src/use-fetch.ts",
      "use-file-dialog": "src/use-file-dialog.ts",
      "use-file-system-access": "src/use-file-system-access.ts",
      "use-fullscreen": "src/use-fullscreen.ts",
      "use-history": "src/use-history.ts",
      "use-image": "src/use-image.ts",
      "use-indexed-db": "src/use-indexed-db.ts",
      "use-media-controls": "src/use-media-controls.ts",
      "use-notification": "src/use-notification.ts",
      "use-object-url": "src/use-object-url.ts",
      "use-permission": "src/use-permission.ts",
      "use-previous": "src/use-previous.ts",
      "use-script-tag": "src/use-script-tag.ts",
      "use-share": "src/use-share.ts",
      "use-speech-recognition": "src/use-speech-recognition.ts",
      "use-speech-synthesis": "src/use-speech-synthesis.ts",
      "use-storage": "src/use-storage.ts",
      "use-style-tag": "src/use-style-tag.ts",
      "use-throttled": "src/use-throttled.ts",
      "use-toggle": "src/use-toggle.ts",
      "use-url-hash": "src/use-url-hash.ts",
      "use-url-search-params": "src/use-url-search-params.ts",
      "use-user-media": "src/use-user-media.ts",
      "use-vibrate": "src/use-vibrate.ts",
      "use-wake-lock": "src/use-wake-lock.ts",
      "use-websocket": "src/use-websocket.ts",
      "use-worker-fn": "src/use-worker-fn.ts",
      "window-size": "src/window-size.ts",
    },
    format: "esm",
    dts: true,
    clean: true,
    deps: {
      neverBundle: ["vue"],
    },
  },
});
