// Generated by `nuxi prepare` (committed so `vize check` runs without a Nuxt
// install). Re-exports the auto-imported composables and declares them as
// globals. Re-exporting `vue-i18n` is what puts that package's
// `ComponentCustomProperties` augmentation — the declaration `$t` comes from —
// into the project's type graph, exactly as a prepared Nuxt app does.
export { useI18n } from "vue-i18n";

declare global {
  const useI18n: typeof import("vue-i18n")["useI18n"];
  const useLocalePath: () => (path: string) => string;
  const queryCollection: (collection: string) => {
    path: (path: string) => { first: () => Promise<{ title: string } | null> };
  };
}

export {};
