use std::fs;

use crate::virtual_ts::VirtualTsOptions;

use super::super::{
    AUTO_IMPORT_STUBS_FILE, MODULE_AUGMENTATION_STUB_PREFIX, MODULE_AUGMENTATION_STUBS_FILE,
    VirtualProject,
};
use super::unique_case_dir;

#[test]
fn materialize_writes_module_augmentations_as_external_module_file() {
    let case_dir = unique_case_dir("materialize-module-augmentations");
    let _ = fs::remove_dir_all(&case_dir);
    let src_dir = case_dir.join("src");
    fs::create_dir_all(&src_dir).unwrap();
    let vue_path = src_dir.join("App.vue");
    fs::write(
        &vue_path,
        r#"<script setup lang="ts">
const message = 'Hello'
</script>
"#,
    )
    .unwrap();

    let mut project = VirtualProject::new(&case_dir).unwrap();
    let mut options = VirtualTsOptions::default();
    options
        .auto_import_stubs
        .push("declare function autoGenerated(): string;".into());
    options.auto_import_stubs.push(format!(
        "{MODULE_AUGMENTATION_STUB_PREFIX}declare module \"resolved-package\" {{\n  interface Context {{ injected: string }}\n}}\n"
    )
    .into());
    project.set_virtual_ts_options(options);
    project.register_path(&vue_path).unwrap();
    project.materialize().unwrap();

    let virtual_root = project.virtual_root();
    let auto_imports = fs::read_to_string(virtual_root.join(AUTO_IMPORT_STUBS_FILE)).unwrap();
    let augmentations =
        fs::read_to_string(virtual_root.join(MODULE_AUGMENTATION_STUBS_FILE)).unwrap();
    let tsconfig: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(virtual_root.join("tsconfig.json")).unwrap())
            .unwrap();

    assert!(auto_imports.contains("declare function autoGenerated"));
    assert!(!auto_imports.contains("resolved-package"));
    assert!(augmentations.contains("export {};"));
    assert!(augmentations.contains("declare module \"resolved-package\""));
    assert!(
        tsconfig["include"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| entry.as_str() == Some(MODULE_AUGMENTATION_STUBS_FILE))
    );

    let _ = fs::remove_dir_all(&case_dir);
}

#[test]
fn materialize_rewrites_relative_vue_module_declaration_names() {
    let case_dir = unique_case_dir("materialize-module-declaration-name");
    let _ = fs::remove_dir_all(&case_dir);
    let src_dir = case_dir.join("src");
    fs::create_dir_all(&src_dir).unwrap();

    let vue_path = src_dir.join("App.vue");
    fs::write(&vue_path, "<template />\n").unwrap();

    let augment_path = src_dir.join("augment.ts");
    fs::write(
        &augment_path,
        r#"declare module "./App.vue" {
  export const marker: true;
}
declare module "*.vue" {
  const component: unknown;
  export default component;
}
"#,
    )
    .unwrap();

    let mut project = VirtualProject::new(&case_dir).unwrap();
    project.register_path(&vue_path).unwrap();
    project.register_path(&augment_path).unwrap();
    project.materialize().unwrap();

    let materialized = fs::read_to_string(project.virtual_root().join("src/augment.ts")).unwrap();
    assert!(
        materialized.contains(r#"declare module "./App.vue.ts""#),
        "{materialized}"
    );
    assert!(
        materialized.contains(r#"declare module "*.vue""#),
        "{materialized}"
    );

    let _ = fs::remove_dir_all(&case_dir);
}
