/** Reviewed physical host callers, ordered by metadata/canonical/Windows-normalization API. */
export const pathHostFunctions = [
  "is_git_metadata_path",
  "canonicalize_non_verbatim",
  "normalize_windows_verbatim_path",
] as const;

export const pathHostCallers: Record<string, readonly [number, number, number]> = {
  "crates/vize/src/commands/build/runner/collect.rs": [3, 1, 0],
  "crates/vize/src/commands/build/runner/declarations.rs": [0, 1, 0],
  "crates/vize/src/commands/check/imports_generated_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/imports_js_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/imports_magic_comments_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/imports_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/nuxt/generated.rs": [1, 0, 0],
  "crates/vize/src/commands/check/nuxt/generated_dir.rs": [1, 0, 0],
  "crates/vize/src/commands/check/nuxt/plugins.rs": [1, 0, 0],
  "crates/vize/src/commands/check/nuxt/source_scan.rs": [2, 0, 0],
  "crates/vize/src/commands/check/nuxt/tsconfig_aliases.rs": [0, 1, 0],
  "crates/vize/src/commands/check/nuxt/virtual_modules.rs": [1, 0, 0],
  "crates/vize/src/commands/check/path_cache.rs": [0, 2, 0],
  "crates/vize/src/commands/check/runner/collect.rs": [6, 1, 0],
  "crates/vize/src/commands/check/runner/default_imports_explicit_ambient_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/runner/default_imports_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/runner/diagnostics.rs": [0, 2, 0],
  "crates/vize/src/commands/check/runner/execution.rs": [0, 2, 0],
  "crates/vize/src/commands/check/runner/global_components/workspace_declarations.rs": [1, 0, 0],
  "crates/vize/src/commands/check/runner/ignores.rs": [0, 1, 0],
  "crates/vize/src/commands/check/runner/input_scope.rs": [0, 2, 0],
  "crates/vize/src/commands/check/runner/invocation.rs": [0, 1, 0],
  "crates/vize/src/commands/check/runner/nuxt_tsconfig.rs": [0, 1, 0],
  "crates/vize/src/commands/check/runner/nuxt_tsconfig/cache.rs": [0, 4, 0],
  "crates/vize/src/commands/check/runner/nuxt_tsconfig/path_options_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/runner/resolve.rs": [0, 5, 0],
  "crates/vize/src/commands/check/tsconfig_inputs.rs": [1, 0, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/collect.rs": [2, 0, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/default_exclude_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/glob.rs": [0, 1, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/ownership.rs": [1, 0, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/ownership_shared_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/package_folder_tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/tests.rs": [0, 1, 0],
  "crates/vize/src/commands/check/tsconfig_inputs/type_references/tsconfig_types.rs": [0, 1, 0],
  "crates/vize/src/commands/doctor/discovery.rs": [2, 0, 0],
  "crates/vize/src/commands/fmt/files.rs": [4, 0, 0],
  "crates/vize/src/commands/inspector/input_files.rs": [6, 2, 0],
  "crates/vize/src/commands/lint/collect.rs": [4, 1, 0],
  "crates/vize/tests/check_cli.rs": [0, 1, 0],
  "crates/vize/tests/check_declaration_emit_cli/workspace_package_vue_exports.rs": [0, 2, 0],
  "crates/vize/tests/check_default_imports_cli.rs": [0, 1, 0],
  "crates/vize/tests/support/default_run_root.rs": [0, 2, 0],
  "crates/vize/tests/support/lsp_process.rs": [0, 1, 0],
  "crates/vize_canon/src/batch/type_checker/tests/recent_issues/css_side_effect_import.rs": [
    0, 1, 0,
  ],
  "crates/vize_maestro/src/ide/corsa_support/canonical.rs": [0, 4, 0],
  "crates/vize_maestro/src/ide/corsa_support/canonical/open.rs": [0, 3, 0],
  "crates/vize_maestro/src/ide/corsa_support/canonical/project.rs": [0, 2, 0],
  "crates/vize_maestro/src/ide/corsa_support/canonical/semantic_links.rs": [0, 2, 0],
  "crates/vize_maestro/src/ide/corsa_support/rename_scope.rs": [0, 0, 1],
  "crates/vize_maestro/src/ide/diagnostics/corsa/relative_import_tests.rs": [0, 2, 0],
  "crates/vize_maestro/src/ide/file_rename/manual.rs": [1, 0, 0],
  "crates/vize_maestro/src/server/state/global_components.rs": [1, 0, 0],
  "crates/vize_maestro/src/server/state/global_tag_names.rs": [1, 0, 0],
  "crates/vize_maestro/src/server/state/workspace_project_files.rs": [2, 0, 0],
  "crates/vize_maestro/src/server/state/workspace_vue_files.rs": [4, 0, 0],
};
