import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const accessibilityFamilyRoot = "src/families/accessibility/";
const announcerFamilyRoot = `${accessibilityFamilyRoot}announcer/`;
const focusFamilyRoot = `${accessibilityFamilyRoot}focus/`;
const focusGuardsFamilyRoot = `${accessibilityFamilyRoot}focus-guards/`;
const focusScopeFamilyRoot = `${accessibilityFamilyRoot}focus-scope/`;
const inertOutsideFamilyRoot = `${accessibilityFamilyRoot}inert-outside/`;
const interactionModalityFamilyRoot = `${accessibilityFamilyRoot}interaction-modality/`;
const liveRegionFamilyRoot = `${accessibilityFamilyRoot}live-region/`;
const scrollLockFamilyRoot = `${accessibilityFamilyRoot}scroll-lock/`;
const visuallyHiddenFamilyRoot = `${accessibilityFamilyRoot}visually-hidden/`;

export const accessibilityFamilyCatalog = [
  {
    canonicalName: "announcer",
    title: "Announcer",
    packageSubpath: "./announcer",
    entryFile: `${announcerFamilyRoot}announcer.ts`,
    sourceFiles: [
      `${announcerFamilyRoot}announcer-provider.vue`,
      `${announcerFamilyRoot}announcer.ts`,
      `${announcerFamilyRoot}announcer-busy.ts`,
      `${announcerFamilyRoot}announcer-runtime.ts`,
      `${announcerFamilyRoot}announcer-types.ts`,
    ],
    behaviorContract: `${announcerFamilyRoot}announcer.behavior.md`,
    tests: [
      `${announcerFamilyRoot}announcer.test.ts`,
      `${announcerFamilyRoot}announcer-ssr.test.ts`,
    ],
    typeTests: [`${announcerFamilyRoot}announcer.types.test-d.ts`],
    rendererFixture: "families/accessibility/announcer/announcer-provider.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "AnnouncerProvider",
      retainedSignature: "VIZE_UI_ANNOUNCER_DISPOSED",
      allowedRetainedFamilies: ["context", "live-region"],
      maximumJavaScriptGzipBytes: 2_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["announcement queue", "status announcer", "busy announcements"],
    upstreamCoverage: ["ARIA live regions", "coalesced announcement queues"],
    dependencies: ["context", "live-region"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "focus",
    title: "Focus Interactions",
    packageSubpath: "./focus",
    entryFile: `${focusFamilyRoot}focus.ts`,
    sourceFiles: [
      `${focusFamilyRoot}focus.ts`,
      `${focusFamilyRoot}focus-internal.ts`,
      `${focusFamilyRoot}focus-types.ts`,
    ],
    behaviorContract: `${focusFamilyRoot}focus.behavior.md`,
    tests: [
      `${focusFamilyRoot}focus.test.ts`,
      `${focusFamilyRoot}focus-lifecycle.test.ts`,
      `${focusFamilyRoot}focus-ssr.test.ts`,
    ],
    typeTests: [`${focusFamilyRoot}focus.types.test-d.ts`],
    rendererFixture: "FocusConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createFocus",
      retainedSignature: "VIZE_UI_FOCUS_DISPOSED",
      allowedRetainedFamilies: ["interaction-modality"],
      maximumJavaScriptGzipBytes: 3_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["focus ring", "focus within", "focus visible"],
    upstreamCoverage: ["React Aria useFocus", "React Aria useFocusRing", "WICG focus-visible"],
    dependencies: ["interaction-modality"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "focus-guards",
    title: "Focus Guards",
    packageSubpath: "./focus-guards",
    entryFile: `${focusGuardsFamilyRoot}focus-guards.ts`,
    sourceFiles: [
      `${focusGuardsFamilyRoot}focus-guards.ts`,
      `${focusGuardsFamilyRoot}focus-guards-internal.ts`,
      `${focusGuardsFamilyRoot}focus-guards-stack.ts`,
      `${focusGuardsFamilyRoot}focus-guards-types.ts`,
    ],
    behaviorContract: `${focusGuardsFamilyRoot}focus-guards.behavior.md`,
    tests: [
      `${focusGuardsFamilyRoot}focus-guards.test.ts`,
      `${focusGuardsFamilyRoot}focus-guards-ssr.test.ts`,
    ],
    typeTests: [`${focusGuardsFamilyRoot}focus-guards.types.test-d.ts`],
    rendererFixture: "FocusGuardsConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createFocusGuards",
      retainedSignature: "VIZE_UI_FOCUS_GUARDS_DISPOSED",
      maximumJavaScriptGzipBytes: 3_525,
      maximumCssGzipBytes: 0,
    },
    aliases: ["focus sentinels", "tab guards", "focus trap guards"],
    upstreamCoverage: ["Radix FocusGuards", "React Aria FocusScope sentinels"],
    dependencies: ["focus-scope"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "focus-scope",
    title: "Focus Scope",
    packageSubpath: "./focus-scope",
    entryFile: `${focusScopeFamilyRoot}focus-scope.ts`,
    sourceFiles: [
      `${focusScopeFamilyRoot}focus-scope.ts`,
      `${focusScopeFamilyRoot}focus-scope-dom.ts`,
      `${focusScopeFamilyRoot}focus-scope-internal.ts`,
      `${focusScopeFamilyRoot}focus-scope-manager.ts`,
      `${focusScopeFamilyRoot}focus-scope-stack.ts`,
      `${focusScopeFamilyRoot}focus-scope-types.ts`,
      `${focusScopeFamilyRoot}use-focus-scope.ts`,
    ],
    behaviorContract: `${focusScopeFamilyRoot}focus-scope.behavior.md`,
    tests: [
      `${focusScopeFamilyRoot}focus-scope.test.ts`,
      `${focusScopeFamilyRoot}focus-scope-lifecycle.test.ts`,
      `${focusScopeFamilyRoot}focus-scope-ssr.test.ts`,
    ],
    typeTests: [`${focusScopeFamilyRoot}focus-scope.types.test-d.ts`],
    rendererFixture: "FocusScopeConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createFocusScope",
      retainedSignature: "VIZE_UI_FOCUS_SCOPE_DISPOSED",
      maximumJavaScriptGzipBytes: 4_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["focus trap", "focus containment", "focus restoration"],
    upstreamCoverage: ["React Aria FocusScope", "Radix FocusScope", "Ariakit FocusTrap"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "inert-outside",
    title: "Outside Inerting",
    packageSubpath: "./inert-outside",
    entryFile: `${inertOutsideFamilyRoot}inert-outside.ts`,
    sourceFiles: [
      `${inertOutsideFamilyRoot}inert-outside.ts`,
      `${inertOutsideFamilyRoot}inert-outside-dom.ts`,
      `${inertOutsideFamilyRoot}inert-outside-internal.ts`,
      `${inertOutsideFamilyRoot}inert-outside-stack.ts`,
      `${inertOutsideFamilyRoot}inert-outside-types.ts`,
    ],
    behaviorContract: `${inertOutsideFamilyRoot}inert-outside.behavior.md`,
    tests: [
      `${inertOutsideFamilyRoot}inert-outside.test.ts`,
      `${inertOutsideFamilyRoot}inert-outside-ssr.test.ts`,
    ],
    typeTests: [`${inertOutsideFamilyRoot}inert-outside.types.test-d.ts`],
    rendererFixture: "InertOutsideConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createInertOutside",
      retainedSignature: "VIZE_UI_INERT_OUTSIDE_DISPOSED",
      maximumJavaScriptGzipBytes: 2_175,
      maximumCssGzipBytes: 0,
    },
    aliases: ["aria hidden outside", "outside inerting", "overlay inerting"],
    upstreamCoverage: ["Radix overlay inerting", "Adobe Spectrum overlay provider"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "interaction-modality",
    title: "Interaction Modality",
    packageSubpath: "./interaction-modality",
    entryFile: `${interactionModalityFamilyRoot}interaction-modality.ts`,
    sourceFiles: [
      `${interactionModalityFamilyRoot}interaction-modality.ts`,
      `${interactionModalityFamilyRoot}interaction-modality-events.ts`,
      `${interactionModalityFamilyRoot}interaction-modality-hub.ts`,
      `${interactionModalityFamilyRoot}interaction-modality-types.ts`,
    ],
    behaviorContract: `${interactionModalityFamilyRoot}interaction-modality.behavior.md`,
    tests: [
      `${interactionModalityFamilyRoot}interaction-modality.test.ts`,
      `${interactionModalityFamilyRoot}interaction-modality-lifecycle.test.ts`,
      `${interactionModalityFamilyRoot}interaction-modality-ssr.test.ts`,
    ],
    typeTests: [`${interactionModalityFamilyRoot}interaction-modality.types.test-d.ts`],
    qualityGates: [
      "behavior-contract",
      "mounted-dom",
      "type-inference",
      "ssr",
      "tree-shaking",
      "bundle-size",
    ],
    bundleBudget: {
      exportName: "createInteractionModalityTracker",
      retainedSignature: "VIZE_UI_INTERACTION_MODALITY_DISPOSED",
      maximumJavaScriptGzipBytes: 1_650,
      maximumCssGzipBytes: 0,
    },
    aliases: ["focus modality", "input modality", "focus visible modality"],
    upstreamCoverage: ["React Aria useFocusVisible", "WICG focus-visible"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "live-region",
    title: "Live Region",
    packageSubpath: "./live-region",
    entryFile: `${liveRegionFamilyRoot}live-region.ts`,
    sourceFiles: [
      `${liveRegionFamilyRoot}live-region.vue`,
      `${liveRegionFamilyRoot}live-region.ts`,
      `${liveRegionFamilyRoot}live-region-runtime.ts`,
      `${liveRegionFamilyRoot}live-region-types.ts`,
    ],
    behaviorContract: `${liveRegionFamilyRoot}live-region.behavior.md`,
    tests: [
      `${liveRegionFamilyRoot}live-region.test.ts`,
      `${liveRegionFamilyRoot}live-region-ssr.test.ts`,
    ],
    typeTests: [`${liveRegionFamilyRoot}live-region.types.test-d.ts`],
    rendererFixture: "families/accessibility/live-region/live-region.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "createLiveRegion",
      retainedSignature: "VIZE_UI_LIVE_REGION_DISPOSED",
      maximumJavaScriptGzipBytes: 1_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["announcer", "aria live", "status region"],
    upstreamCoverage: ["ARIA live regions", "WAI-ARIA status and alert"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "scroll-lock",
    title: "Scroll Lock",
    packageSubpath: "./scroll-lock",
    entryFile: `${scrollLockFamilyRoot}scroll-lock.ts`,
    sourceFiles: [
      `${scrollLockFamilyRoot}scroll-lock.ts`,
      `${scrollLockFamilyRoot}scroll-lock-dom.ts`,
      `${scrollLockFamilyRoot}scroll-lock-internal.ts`,
      `${scrollLockFamilyRoot}scroll-lock-stack.ts`,
      `${scrollLockFamilyRoot}scroll-lock-types.ts`,
    ],
    behaviorContract: `${scrollLockFamilyRoot}scroll-lock.behavior.md`,
    tests: [
      `${scrollLockFamilyRoot}scroll-lock.test.ts`,
      `${scrollLockFamilyRoot}scroll-lock-ssr.test.ts`,
    ],
    typeTests: [`${scrollLockFamilyRoot}scroll-lock.types.test-d.ts`],
    rendererFixture: "ScrollLockConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createScrollLock",
      retainedSignature: "VIZE_UI_SCROLL_LOCK_DISPOSED",
      maximumJavaScriptGzipBytes: 2_150,
      maximumCssGzipBytes: 0,
    },
    aliases: ["body scroll lock", "document scroll lock", "overlay scroll lock"],
    upstreamCoverage: ["React Aria usePreventScroll", "Radix RemoveScroll"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "visually-hidden",
    title: "Visually Hidden",
    packageSubpath: "./visually-hidden",
    entryFile: `${visuallyHiddenFamilyRoot}visually-hidden.ts`,
    sourceFiles: [
      `${visuallyHiddenFamilyRoot}visually-hidden.vue`,
      `${visuallyHiddenFamilyRoot}visually-hidden.ts`,
    ],
    behaviorContract: `${visuallyHiddenFamilyRoot}visually-hidden.behavior.md`,
    tests: [`${visuallyHiddenFamilyRoot}visually-hidden.test.ts`],
    rendererFixture: "families/accessibility/visually-hidden/visually-hidden.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "VisuallyHidden",
      retainedSignature: "visually-hidden",
      maximumJavaScriptGzipBytes: 400,
      // Covers the shared packaged stylesheet and motion tokens shipped with styled families.
      maximumCssGzipBytes: 7_600,
    },
    aliases: ["screen reader only", "sr-only", "visually hidden"],
    upstreamCoverage: ["React Aria VisuallyHidden", "Radix VisuallyHidden"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
