import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const breadcrumbFamilyRoot = "src/families/navigation/breadcrumb/";
const paginationFamilyRoot = "src/families/navigation/pagination/";
const stepperFamilyRoot = "src/families/navigation/stepper/";
const tabsFamilyRoot = "src/families/navigation/tabs/";

export const navigationFamilyCatalog = [
  {
    canonicalName: "breadcrumb",
    title: "Breadcrumb",
    packageSubpath: "./breadcrumb",
    entryFile: `${breadcrumbFamilyRoot}breadcrumb.ts`,
    sourceFiles: [
      `${breadcrumbFamilyRoot}breadcrumb.vue`,
      `${breadcrumbFamilyRoot}breadcrumb-item.vue`,
      `${breadcrumbFamilyRoot}breadcrumb-link.vue`,
      `${breadcrumbFamilyRoot}breadcrumb-list.vue`,
      `${breadcrumbFamilyRoot}breadcrumb-separator.vue`,
      `${breadcrumbFamilyRoot}breadcrumb.ts`,
      `${breadcrumbFamilyRoot}breadcrumb-types.ts`,
    ],
    behaviorContract: `${breadcrumbFamilyRoot}breadcrumb.behavior.md`,
    tests: [
      `${breadcrumbFamilyRoot}breadcrumb.test.ts`,
      `${breadcrumbFamilyRoot}breadcrumb-ssr.test.ts`,
    ],
    typeTests: [`${breadcrumbFamilyRoot}breadcrumb.types.test-d.ts`],
    rendererFixture: "BreadcrumbConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Breadcrumb",
      retainedSignature: 'data-vize-ui":(?:`breadcrumb`|"breadcrumb"|\'breadcrumb\')',
      maximumJavaScriptGzipBytes: 1_725,
      maximumCssGzipBytes: 0,
    },
    aliases: ["breadcrumb navigation", "route breadcrumb", "path trail", "hierarchy trail"],
    upstreamCoverage: [
      "HTML nav landmark",
      "WAI-ARIA breadcrumb pattern",
      "React Aria Breadcrumbs",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "skip-link",
    title: "Skip Link",
    packageSubpath: "./skip-link",
    entryFile: "src/families/navigation/skip-link/skip-link.ts",
    sourceFiles: [
      "src/families/navigation/skip-link/skip-link.vue",
      "src/families/navigation/skip-link/skip-link.ts",
      "src/families/navigation/skip-link/skip-link-types.ts",
    ],
    behaviorContract: "src/families/navigation/skip-link/skip-link.behavior.md",
    tests: [
      "src/families/navigation/skip-link/skip-link.test.ts",
      "src/families/navigation/skip-link/skip-link-ssr.test.ts",
    ],
    typeTests: ["src/families/navigation/skip-link/skip-link.types.test-d.ts"],
    rendererFixture: "SkipLinkConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "SkipLink",
      retainedSignature: 'data-vize-ui":(?:`skip-link`|"skip-link"|\'skip-link\')',
      maximumJavaScriptGzipBytes: 1_850,
      maximumCssGzipBytes: 0,
    },
    aliases: ["skip link", "skip navigation", "skip to content", "bypass block"],
    upstreamCoverage: [
      "WCAG bypass blocks",
      "HTML same-document fragment navigation",
      "WebAIM skip navigation links",
    ],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "tabs",
    title: "Tabs",
    packageSubpath: "./tabs",
    entryFile: `${tabsFamilyRoot}tabs.ts`,
    sourceFiles: [
      `${tabsFamilyRoot}tabs-content.vue`,
      `${tabsFamilyRoot}tabs-list.vue`,
      `${tabsFamilyRoot}tabs-root.vue`,
      `${tabsFamilyRoot}tabs-trigger.vue`,
      `${tabsFamilyRoot}tabs.ts`,
      `${tabsFamilyRoot}tabs-context.ts`,
      `${tabsFamilyRoot}tabs-types.ts`,
      `${tabsFamilyRoot}tabs-value.ts`,
    ],
    behaviorContract: `${tabsFamilyRoot}tabs.behavior.md`,
    tests: [`${tabsFamilyRoot}tabs.test.ts`, `${tabsFamilyRoot}tabs-ssr.test.ts`],
    typeTests: [`${tabsFamilyRoot}tabs.types.test-d.ts`],
    rendererFixture: "TabsConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "TabsRoot",
      retainedSignature: 'data-vize-ui":(?:`tabs-root`|"tabs-root"|\'tabs-root\')',
      allowedRetainedFamilies: [
        "collection",
        "composite-navigation",
        "context",
        "controllable-state",
        "typeahead",
      ],
      maximumJavaScriptGzipBytes: 8_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["tablist", "tab panels", "segmented navigation", "application sections"],
    upstreamCoverage: ["WAI-ARIA tabs pattern", "React Aria Tabs", "Radix Tabs", "Reka UI Tabs"],
    dependencies: [
      "collection",
      "composite-navigation",
      "context",
      "controllable-state",
      "typeahead",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "stepper",
    title: "Stepper",
    packageSubpath: "./stepper",
    entryFile: `${stepperFamilyRoot}stepper.ts`,
    sourceFiles: [
      `${stepperFamilyRoot}stepper-content.vue`,
      `${stepperFamilyRoot}stepper-item.vue`,
      `${stepperFamilyRoot}stepper-list.vue`,
      `${stepperFamilyRoot}stepper-root.vue`,
      `${stepperFamilyRoot}stepper-trigger.vue`,
      `${stepperFamilyRoot}stepper.ts`,
      `${stepperFamilyRoot}stepper-context.ts`,
      `${stepperFamilyRoot}stepper-navigation.ts`,
      `${stepperFamilyRoot}stepper-types.ts`,
      `${stepperFamilyRoot}stepper-value.ts`,
    ],
    behaviorContract: `${stepperFamilyRoot}stepper.behavior.md`,
    tests: [
      `${stepperFamilyRoot}stepper.test.ts`,
      `${stepperFamilyRoot}stepper-expose.test.ts`,
      `${stepperFamilyRoot}stepper-ssr.test.ts`,
    ],
    typeTests: [`${stepperFamilyRoot}stepper.types.test-d.ts`],
    rendererFixture: "StepperConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "StepperRoot",
      retainedSignature: 'data-vize-ui":(?:`stepper-root`|"stepper-root"|\'stepper-root\')',
      allowedRetainedFamilies: [
        "collection",
        "composite-navigation",
        "context",
        "controllable-state",
        "typeahead",
      ],
      maximumJavaScriptGzipBytes: 9_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["stepper", "wizard", "multi-step flow", "checkout steps"],
    upstreamCoverage: [
      "WAI-ARIA aria-current step",
      "MUI Stepper",
      "Vuetify Stepper",
      "Reka UI Stepper",
    ],
    dependencies: [
      "collection",
      "composite-navigation",
      "context",
      "controllable-state",
      "id",
      "typeahead",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "pagination",
    title: "Pagination",
    packageSubpath: "./pagination",
    entryFile: `${paginationFamilyRoot}pagination.ts`,
    sourceFiles: [
      `${paginationFamilyRoot}pagination.vue`,
      `${paginationFamilyRoot}pagination-list.vue`,
      `${paginationFamilyRoot}pagination-item.vue`,
      `${paginationFamilyRoot}pagination-page.vue`,
      `${paginationFamilyRoot}pagination-previous.vue`,
      `${paginationFamilyRoot}pagination-next.vue`,
      `${paginationFamilyRoot}pagination-ellipsis.vue`,
      `${paginationFamilyRoot}pagination.ts`,
      `${paginationFamilyRoot}pagination-context.ts`,
      `${paginationFamilyRoot}pagination-range.ts`,
      `${paginationFamilyRoot}pagination-types.ts`,
    ],
    behaviorContract: `${paginationFamilyRoot}pagination.behavior.md`,
    tests: [
      `${paginationFamilyRoot}pagination.test.ts`,
      `${paginationFamilyRoot}pagination-edge.test.ts`,
      `${paginationFamilyRoot}pagination-ssr.test.ts`,
    ],
    typeTests: [`${paginationFamilyRoot}pagination.types.test-d.ts`],
    rendererFixture: "PaginationConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Pagination",
      retainedSignature: 'data-vize-ui":(?:`pagination`|"pagination"|\'pagination\')',
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 2_750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["pagination", "pager", "page navigation", "page controls"],
    upstreamCoverage: [
      "HTML nav landmark",
      "WAI-ARIA aria-current page",
      "MUI Pagination",
      "Vuetify Pagination",
      "Reka UI Pagination",
    ],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
