import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const menuRoot = "src/families/menus/menu/";
const dropdownMenuRoot = "src/families/menus/dropdown-menu/";
const contextMenuRoot = "src/families/menus/context-menu/";
const menubarRoot = "src/families/menus/menubar/";

const menuCoreDependencies = [
  "collection",
  "context",
  "controllable-state",
  "dismissable-layer",
  "focus-scope",
  "id",
  "inert-outside",
  "pointer-grace",
  "portal",
  "positioner",
  "presence",
  "scroll-lock",
  "typeahead",
] as const;

/** Menu, DropdownMenu, ContextMenu, and Menubar share one menu core. */
export const menuFamilyCatalog = [
  {
    canonicalName: "context-menu",
    title: "Context Menu",
    packageSubpath: "./context-menu",
    entryFile: `${contextMenuRoot}context-menu.ts`,
    sourceFiles: [
      `${contextMenuRoot}context-menu.ts`,
      `${contextMenuRoot}context-menu-context.ts`,
      `${contextMenuRoot}context-menu-root.vue`,
      `${contextMenuRoot}context-menu-trigger.vue`,
      `${contextMenuRoot}context-menu-types.ts`,
    ],
    behaviorContract: `${contextMenuRoot}context-menu.behavior.md`,
    tests: [`${contextMenuRoot}context-menu.test.ts`, `${contextMenuRoot}context-menu-ssr.test.ts`],
    typeTests: [`${contextMenuRoot}context-menu.types.test-d.ts`],
    rendererFixture: "ContextMenuConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ContextMenuTrigger",
      retainedSignature: "data-vize-ui[\"'`:=\\s]{1,4}context-menu-trigger",
      allowedRetainedFamilies: ["context", "long-press", "press"],
      maximumJavaScriptGzipBytes: 6_600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["right-click menu", "contextual menu", "long-press menu", "shortcut menu"],
    upstreamCoverage: ["WAI-ARIA menu pattern", "Radix Context Menu", "Reka UI Context Menu"],
    dependencies: ["long-press", "menu", "press", ...menuCoreDependencies],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "dropdown-menu",
    title: "Dropdown Menu",
    packageSubpath: "./dropdown-menu",
    entryFile: `${dropdownMenuRoot}dropdown-menu.ts`,
    sourceFiles: [
      `${dropdownMenuRoot}dropdown-menu.ts`,
      `${dropdownMenuRoot}dropdown-menu-root.vue`,
      `${dropdownMenuRoot}dropdown-menu-trigger.vue`,
    ],
    behaviorContract: `${dropdownMenuRoot}dropdown-menu.behavior.md`,
    tests: [
      `${dropdownMenuRoot}dropdown-menu.test.ts`,
      `${dropdownMenuRoot}dropdown-menu-ssr.test.ts`,
    ],
    typeTests: [`${dropdownMenuRoot}dropdown-menu.types.test-d.ts`],
    rendererFixture: "DropdownMenuConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "DropdownMenuTrigger",
      retainedSignature: "data-vize-ui[\"'`:=\\s]{1,4}dropdown-menu-trigger",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 1_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["menu button", "actions menu", "overflow menu", "kebab menu"],
    upstreamCoverage: [
      "WAI-ARIA menu button pattern",
      "Radix Dropdown Menu",
      "Reka UI Dropdown Menu",
    ],
    dependencies: ["menu", ...menuCoreDependencies],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "menu",
    title: "Menu",
    packageSubpath: "./menu",
    entryFile: `${menuRoot}menu.ts`,
    sourceFiles: [
      `${menuRoot}menu.ts`,
      `${menuRoot}menu-arrow.vue`,
      `${menuRoot}menu-checkbox-item.vue`,
      `${menuRoot}menu-content.vue`,
      `${menuRoot}menu-content-runtime.ts`,
      `${menuRoot}menu-context.ts`,
      `${menuRoot}menu-dom.ts`,
      `${menuRoot}menu-group.vue`,
      `${menuRoot}menu-item.vue`,
      `${menuRoot}menu-item-indicator.vue`,
      `${menuRoot}menu-item-runtime.ts`,
      `${menuRoot}menu-label.vue`,
      `${menuRoot}menu-radio-group.vue`,
      `${menuRoot}menu-radio-item.vue`,
      `${menuRoot}menu-root.vue`,
      `${menuRoot}menu-root-runtime.ts`,
      `${menuRoot}menu-separator.vue`,
      `${menuRoot}menu-sub.vue`,
      `${menuRoot}menu-sub-content.vue`,
      `${menuRoot}menu-sub-trigger.vue`,
      `${menuRoot}menu-trigger.vue`,
      `${menuRoot}menu-types.ts`,
    ],
    behaviorContract: `${menuRoot}menu.behavior.md`,
    tests: [
      `${menuRoot}menu.test.ts`,
      `${menuRoot}menu-keyboard.test.ts`,
      `${menuRoot}menu-pointer.test.ts`,
      `${menuRoot}menu-ssr.test.ts`,
    ],
    typeTests: [`${menuRoot}menu.types.test-d.ts`],
    rendererFixture: "MenuConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "MenuItem",
      retainedSignature: "data-vize-ui[\"'`:=\\s]{1,4}menu-item[\"'`]",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 2_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["menu", "action menu", "submenu", "menuitemcheckbox", "menuitemradio"],
    upstreamCoverage: ["WAI-ARIA menu pattern", "Radix Menu", "Reka UI Menu", "React Aria Menu"],
    dependencies: menuCoreDependencies,
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "menubar",
    title: "Menubar",
    packageSubpath: "./menubar",
    entryFile: `${menubarRoot}menubar.ts`,
    sourceFiles: [
      `${menubarRoot}menubar.ts`,
      `${menubarRoot}menubar-context.ts`,
      `${menubarRoot}menubar-menu.vue`,
      `${menubarRoot}menubar-root.vue`,
      `${menubarRoot}menubar-trigger.vue`,
      `${menubarRoot}menubar-types.ts`,
    ],
    behaviorContract: `${menubarRoot}menubar.behavior.md`,
    tests: [`${menubarRoot}menubar.test.ts`, `${menubarRoot}menubar-ssr.test.ts`],
    typeTests: [`${menubarRoot}menubar.types.test-d.ts`],
    rendererFixture: "MenubarConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "MenubarRoot",
      retainedSignature: "data-vize-ui[\"'`:=\\s]{1,4}menubar[\"'`]",
      allowedRetainedFamilies: ["collection", "context", "controllable-state", "typeahead"],
      maximumJavaScriptGzipBytes: 6_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["application menu bar", "menu bar", "top menu"],
    upstreamCoverage: ["WAI-ARIA menubar pattern", "Radix Menubar", "Reka UI Menubar"],
    dependencies: ["menu", ...menuCoreDependencies],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
