import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";
const actionSheetRoot = "src/families/overlays/action-sheet/";
const bottomNavigationRoot = "src/families/navigation/bottom-navigation/";
const pagerRoot = "src/families/navigation/pager/";
const pullToRefreshRoot = "src/families/interaction/pull-to-refresh/";
const safeAreaRoot = "src/families/layout/safe-area/";
const swipeActionsRoot = "src/families/interaction/swipe-actions/";

/** Catalog entries for mobile-first patterns (sheets, gestures, tab bars, pagers, safe areas). */
export const mobileFamilyCatalog = [
  {
    canonicalName: "safe-area",
    title: "Safe Area",
    packageSubpath: "./safe-area",
    entryFile: `${safeAreaRoot}safe-area.ts`,
    sourceFiles: [
      `${safeAreaRoot}safe-area.vue`,
      `${safeAreaRoot}safe-area.ts`,
      `${safeAreaRoot}safe-area-runtime.ts`,
    ],
    behaviorContract: `${safeAreaRoot}safe-area.behavior.md`,
    tests: [`${safeAreaRoot}safe-area.test.ts`, `${safeAreaRoot}safe-area-ssr.test.ts`],
    typeTests: [`${safeAreaRoot}safe-area.types.test-d.ts`],
    rendererFixture: "SafeAreaConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "SafeArea",
      retainedSignature: 'data-vize-ui":(?:`safe-area`|"safe-area"|\'safe-area\')',
      allowedRetainedFamilies: [],
      maximumJavaScriptGzipBytes: 1_600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["safe area", "notch insets", "env safe-area-inset", "home indicator padding"],
    upstreamCoverage: [
      "CSS env(safe-area-inset-*)",
      "Ionic safe area",
      "react-native-safe-area-context",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "bottom-navigation",
    title: "Bottom Navigation",
    packageSubpath: "./bottom-navigation",
    entryFile: `${bottomNavigationRoot}bottom-navigation.ts`,
    sourceFiles: [
      `${bottomNavigationRoot}bottom-navigation.vue`,
      `${bottomNavigationRoot}bottom-navigation-item.vue`,
      `${bottomNavigationRoot}bottom-navigation.ts`,
      `${bottomNavigationRoot}bottom-navigation-context.ts`,
    ],
    behaviorContract: `${bottomNavigationRoot}bottom-navigation.behavior.md`,
    tests: [
      `${bottomNavigationRoot}bottom-navigation.test.ts`,
      `${bottomNavigationRoot}bottom-navigation-ssr.test.ts`,
    ],
    typeTests: [`${bottomNavigationRoot}bottom-navigation.types.test-d.ts`],
    rendererFixture: "BottomNavigationConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "BottomNavigation",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}bottom-navigation",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 1_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["tab bar", "bottom tabs", "bottom nav", "app navigation bar"],
    upstreamCoverage: ["HTML nav landmark", "aria-current=page", "Material bottom navigation"],
    dependencies: ["context", "controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "action-sheet",
    title: "Action Sheet",
    packageSubpath: "./action-sheet",
    entryFile: `${actionSheetRoot}action-sheet.ts`,
    sourceFiles: [
      `${actionSheetRoot}action-sheet-menu.vue`,
      `${actionSheetRoot}action-sheet-item.vue`,
      `${actionSheetRoot}action-sheet.ts`,
      `${actionSheetRoot}action-sheet-context.ts`,
      `${actionSheetRoot}action-sheet-types.ts`,
    ],
    behaviorContract: `${actionSheetRoot}action-sheet.behavior.md`,
    tests: [`${actionSheetRoot}action-sheet.test.ts`, `${actionSheetRoot}action-sheet-ssr.test.ts`],
    typeTests: [`${actionSheetRoot}action-sheet.types.test-d.ts`],
    rendererFixture: "ActionSheetConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ActionSheetMenu",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}action-sheet",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 3_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["action sheet", "bottom menu", "share sheet", "iOS action sheet"],
    upstreamCoverage: ["WAI-ARIA Menu", "UIKit UIAlertController actionSheet", "Ionic ActionSheet"],
    dependencies: ["context", "dialog", "drawer", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "pull-to-refresh",
    title: "Pull to Refresh",
    packageSubpath: "./pull-to-refresh",
    entryFile: `${pullToRefreshRoot}pull-to-refresh.ts`,
    sourceFiles: [
      `${pullToRefreshRoot}pull-to-refresh.vue`,
      `${pullToRefreshRoot}pull-to-refresh-trigger.vue`,
      `${pullToRefreshRoot}pull-to-refresh.ts`,
      `${pullToRefreshRoot}pull-to-refresh-context.ts`,
      `${pullToRefreshRoot}pull-to-refresh-types.ts`,
    ],
    behaviorContract: `${pullToRefreshRoot}pull-to-refresh.behavior.md`,
    tests: [
      `${pullToRefreshRoot}pull-to-refresh.test.ts`,
      `${pullToRefreshRoot}pull-to-refresh-ssr.test.ts`,
    ],
    typeTests: [`${pullToRefreshRoot}pull-to-refresh.types.test-d.ts`],
    rendererFixture: "PullToRefreshConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "PullToRefresh",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}pull-to-refresh",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 3_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["pull to refresh", "swipe to refresh", "refresh gesture", "overscroll refresh"],
    upstreamCoverage: ["iOS UIRefreshControl", "Android SwipeRefreshLayout", "Ionic Refresher"],
    dependencies: ["context", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "swipe-actions",
    title: "Swipe Actions",
    packageSubpath: "./swipe-actions",
    entryFile: `${swipeActionsRoot}swipe-actions.ts`,
    sourceFiles: [
      `${swipeActionsRoot}swipe-actions.vue`,
      `${swipeActionsRoot}swipe-actions-content.vue`,
      `${swipeActionsRoot}swipe-actions-tray.vue`,
      `${swipeActionsRoot}swipe-actions-action.vue`,
      `${swipeActionsRoot}swipe-actions.ts`,
      `${swipeActionsRoot}swipe-actions-context.ts`,
      `${swipeActionsRoot}swipe-actions-types.ts`,
    ],
    behaviorContract: `${swipeActionsRoot}swipe-actions.behavior.md`,
    tests: [
      `${swipeActionsRoot}swipe-actions.test.ts`,
      `${swipeActionsRoot}swipe-actions-ssr.test.ts`,
    ],
    typeTests: [`${swipeActionsRoot}swipe-actions.types.test-d.ts`],
    rendererFixture: "SwipeActionsConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "SwipeActions",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}swipe-actions",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["swipe to delete", "swipeable list item", "leading trailing actions", "row actions"],
    upstreamCoverage: ["iOS UIContextualAction", "Material swipe to dismiss", "Ionic ItemSliding"],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "pager",
    title: "Pager",
    packageSubpath: "./pager",
    entryFile: `${pagerRoot}pager.ts`,
    sourceFiles: [
      `${pagerRoot}pager.vue`,
      `${pagerRoot}pager-tab-list.vue`,
      `${pagerRoot}pager-tab.vue`,
      `${pagerRoot}pager-viewport.vue`,
      `${pagerRoot}pager-page.vue`,
      `${pagerRoot}pager.ts`,
      `${pagerRoot}pager-context.ts`,
      `${pagerRoot}pager-types.ts`,
    ],
    behaviorContract: `${pagerRoot}pager.behavior.md`,
    tests: [`${pagerRoot}pager.test.ts`, `${pagerRoot}pager-ssr.test.ts`],
    typeTests: [`${pagerRoot}pager.types.test-d.ts`],
    rendererFixture: "PagerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Pager",
      retainedSignature: 'data-vize-ui":(?:`pager`|"pager"|\'pager\')',
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["view pager", "swipe tabs", "segmented pager", "page view", "swipeable views"],
    upstreamCoverage: [
      "WAI-ARIA Tabs",
      "CSS scroll snap",
      "Android ViewPager2",
      "UIPageViewController",
    ],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
