import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const inputMaskRoot = "src/families/form/input-mask/";
const numberFieldRoot = "src/families/form/number-field/";
const rangeSliderRoot = "src/families/form/range-slider/";

/** Catalog entries for the extended form-input family (numeric, masked, and composite inputs). */
export const formInputFamilyCatalog = [
  {
    canonicalName: "input-mask",
    title: "Input Mask",
    packageSubpath: "./input-mask",
    entryFile: `${inputMaskRoot}input-mask.ts`,
    sourceFiles: [
      `${inputMaskRoot}masked-input.vue`,
      `${inputMaskRoot}input-mask.ts`,
      `${inputMaskRoot}input-mask-engine.ts`,
      `${inputMaskRoot}input-mask-runtime.ts`,
      `${inputMaskRoot}input-mask-types.ts`,
    ],
    behaviorContract: `${inputMaskRoot}input-mask.behavior.md`,
    tests: [`${inputMaskRoot}input-mask.test.ts`, `${inputMaskRoot}input-mask-ssr.test.ts`],
    typeTests: [`${inputMaskRoot}input-mask.types.test-d.ts`],
    rendererFixture: "MaskedInputConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "MaskedInput",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}masked-input",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["masked input", "input mask", "phone input", "pattern input", "formatted input"],
    upstreamCoverage: ["HTML pattern attribute", "imask", "maska", "vue-the-mask"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "number-field",
    title: "Number Field",
    packageSubpath: "./number-field",
    entryFile: `${numberFieldRoot}number-field.ts`,
    sourceFiles: [
      `${numberFieldRoot}number-field.vue`,
      `${numberFieldRoot}number-field-input.vue`,
      `${numberFieldRoot}number-field-increment.vue`,
      `${numberFieldRoot}number-field-decrement.vue`,
      `${numberFieldRoot}number-field.ts`,
      `${numberFieldRoot}number-field-context.ts`,
      `${numberFieldRoot}number-field-parser.ts`,
      `${numberFieldRoot}number-field-state.ts`,
      `${numberFieldRoot}number-field-trigger.ts`,
      `${numberFieldRoot}number-field-types.ts`,
    ],
    behaviorContract: `${numberFieldRoot}number-field.behavior.md`,
    tests: [
      `${numberFieldRoot}number-field.test.ts`,
      `${numberFieldRoot}number-field-parser.test.ts`,
      `${numberFieldRoot}number-field-ssr.test.ts`,
    ],
    typeTests: [`${numberFieldRoot}number-field.types.test-d.ts`],
    rendererFixture: "NumberFieldConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "NumberField",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}number-field",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 6_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["number input", "spinbutton", "stepper input", "currency input", "numeric field"],
    upstreamCoverage: [
      "HTML number input",
      "WAI-ARIA Spinbutton",
      "React Aria NumberField",
      "Radix/Reka NumberField",
    ],
    dependencies: ["context", "controllable-state", "id", "locale"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "range-slider",
    title: "Range Slider",
    packageSubpath: "./range-slider",
    entryFile: `${rangeSliderRoot}range-slider.ts`,
    sourceFiles: [
      `${rangeSliderRoot}range-slider.vue`,
      `${rangeSliderRoot}range-slider-track.vue`,
      `${rangeSliderRoot}range-slider-range.vue`,
      `${rangeSliderRoot}range-slider-thumb.vue`,
      `${rangeSliderRoot}range-slider.ts`,
      `${rangeSliderRoot}range-slider-context.ts`,
      `${rangeSliderRoot}range-slider-state.ts`,
      `${rangeSliderRoot}range-slider-types.ts`,
    ],
    behaviorContract: `${rangeSliderRoot}range-slider.behavior.md`,
    tests: [`${rangeSliderRoot}range-slider.test.ts`, `${rangeSliderRoot}range-slider-ssr.test.ts`],
    typeTests: [`${rangeSliderRoot}range-slider.types.test-d.ts`],
    rendererFixture: "RangeSliderConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "RangeSlider",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}range-slider",
      // The root reuses Slider's bound normalization, and its own markup matches Slider's signature.
      allowedRetainedFamilies: ["context", "controllable-state", "slider"],
      maximumJavaScriptGzipBytes: 4_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["multi-thumb slider", "dual slider", "price range", "range input"],
    upstreamCoverage: [
      "WAI-ARIA Multi-Thumb Slider",
      "React Aria RangeSlider",
      "Radix/Reka Slider (multiple thumbs)",
    ],
    dependencies: ["context", "controllable-state", "slider"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
