import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const dataGridRoot = "src/families/data/data-grid/";
const gridListRoot = "src/families/data/grid-list/";
const kanbanRoot = "src/families/data/kanban/";

/** Interactive data views: DataGrid, GridList, and Kanban. */
export const dataViewFamilyCatalog = [
  {
    canonicalName: "data-grid",
    title: "Data Grid",
    packageSubpath: "./data-grid",
    entryFile: `${dataGridRoot}data-grid.ts`,
    sourceFiles: [
      `${dataGridRoot}data-grid.ts`,
      `${dataGridRoot}data-grid.vue`,
      `${dataGridRoot}data-grid-cell.vue`,
      `${dataGridRoot}data-grid-cell-editor.vue`,
      `${dataGridRoot}data-grid-column-header.vue`,
      `${dataGridRoot}data-grid-columns.ts`,
      `${dataGridRoot}data-grid-context.ts`,
      `${dataGridRoot}data-grid-model.ts`,
      `${dataGridRoot}data-grid-resize-handle.vue`,
      `${dataGridRoot}data-grid-row.vue`,
      `${dataGridRoot}data-grid-rows.ts`,
      `${dataGridRoot}data-grid-types.ts`,
    ],
    behaviorContract: `${dataGridRoot}data-grid.behavior.md`,
    tests: [
      `${dataGridRoot}data-grid.test.ts`,
      `${dataGridRoot}data-grid-model.test.ts`,
      `${dataGridRoot}data-grid-ssr.test.ts`,
    ],
    typeTests: [`${dataGridRoot}data-grid.types.test-d.ts`],
    rendererFixture: "DataGridConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "DataGrid",
      retainedSignature: "data-vize-ui[\"'`:=\\s]{1,4}data-grid[\"'`]",
      // `measure` ships inside the virtualizer; `separator` matches the resize
      // handle's `role="separator"` markup rather than the Separator family.
      allowedRetainedFamilies: [
        "context",
        "controllable-state",
        "measure",
        "separator",
        "virtualizer",
      ],
      maximumJavaScriptGzipBytes: 14_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["data table", "spreadsheet grid", "tree grid", "editable table"],
    upstreamCoverage: [
      "WAI-ARIA grid pattern",
      "WAI-ARIA treegrid pattern",
      "TanStack Table",
      "AG Grid",
      "React Aria Table",
    ],
    dependencies: ["context", "controllable-state", "id", "virtualizer"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "grid-list",
    title: "Grid List",
    packageSubpath: "./grid-list",
    entryFile: `${gridListRoot}grid-list.ts`,
    sourceFiles: [
      `${gridListRoot}grid-list.ts`,
      `${gridListRoot}grid-list.vue`,
      `${gridListRoot}grid-list-context.ts`,
      `${gridListRoot}grid-list-item.vue`,
      `${gridListRoot}grid-list-types.ts`,
    ],
    behaviorContract: `${gridListRoot}grid-list.behavior.md`,
    tests: [`${gridListRoot}grid-list.test.ts`, `${gridListRoot}grid-list-ssr.test.ts`],
    typeTests: [`${gridListRoot}grid-list.types.test-d.ts`],
    rendererFixture: "GridListConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "GridList",
      retainedSignature: "data-vize-ui[\"'`:=\\s]{1,4}grid-list[\"'`]",
      allowedRetainedFamilies: [
        "collection",
        "context",
        "controllable-state",
        "drag-and-drop",
        "sortable",
        "typeahead",
      ],
      maximumJavaScriptGzipBytes: 15_600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["selectable list", "reorderable list", "card grid", "gallery grid"],
    upstreamCoverage: ["WAI-ARIA grid pattern", "React Aria GridList", "Reka UI Listbox"],
    dependencies: [
      "collection",
      "context",
      "controllable-state",
      "drag-and-drop",
      "id",
      "sortable",
      "typeahead",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "kanban",
    title: "Kanban",
    packageSubpath: "./kanban",
    entryFile: `${kanbanRoot}kanban.ts`,
    sourceFiles: [
      `${kanbanRoot}kanban.ts`,
      `${kanbanRoot}kanban.vue`,
      `${kanbanRoot}kanban-card.vue`,
      `${kanbanRoot}kanban-column.vue`,
      `${kanbanRoot}kanban-context.ts`,
      `${kanbanRoot}kanban-types.ts`,
    ],
    behaviorContract: `${kanbanRoot}kanban.behavior.md`,
    tests: [`${kanbanRoot}kanban.test.ts`, `${kanbanRoot}kanban-ssr.test.ts`],
    typeTests: [`${kanbanRoot}kanban.types.test-d.ts`],
    rendererFixture: "KanbanConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Kanban",
      retainedSignature: "data-vize-ui[\"'`:=\\s]{1,4}kanban[\"'`]",
      allowedRetainedFamilies: ["context", "drag-and-drop"],
      maximumJavaScriptGzipBytes: 9_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["task board", "kanban board", "swimlanes", "card board"],
    upstreamCoverage: [
      "WAI-ARIA drag-and-drop guidance",
      "dnd-kit sortable board",
      "Atlassian board",
    ],
    dependencies: ["context", "drag-and-drop", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
