import assert from "node:assert/strict";

import { focusFamilyCatalog } from "./family-catalog-focus.ts";
import { foundationFamilyCatalog } from "./family-catalog-foundations.ts";
import { interactionFamilyCatalog } from "./family-catalog-interactions.ts";
import { overlayFamilyCatalog } from "./family-catalog-overlays.ts";
import type { UiFamilyCatalogEntry } from "./family-catalog-types.ts";

type FamilyCatalog = readonly UiFamilyCatalogEntry[];

type RehomedFlatFamily = {
  readonly catalog: FamilyCatalog;
  readonly familyName: string;
  readonly familyRoot: string;
};

export const rehomedFoundationUtilities = ["context", "controllable-state"] as const;

export const rehomedFlatFamilies: readonly RehomedFlatFamily[] = [
  {
    catalog: foundationFamilyCatalog,
    familyName: "collection",
    familyRoot: "src/families/foundations/collection/",
  },
  {
    catalog: foundationFamilyCatalog,
    familyName: "composite-navigation",
    familyRoot: "src/families/foundations/composite-navigation/",
  },
  {
    catalog: focusFamilyCatalog,
    familyName: "drag-and-drop",
    familyRoot: "src/families/interaction/drag-and-drop/",
  },
  {
    catalog: focusFamilyCatalog,
    familyName: "dismissable-layer",
    familyRoot: "src/families/overlays/dismissable-layer/",
  },
  {
    catalog: interactionFamilyCatalog,
    familyName: "primitive",
    familyRoot: "src/families/foundations/primitive/",
  },
  {
    catalog: interactionFamilyCatalog,
    familyName: "shortcut",
    familyRoot: "src/families/interaction/shortcut/",
  },
  {
    catalog: interactionFamilyCatalog,
    familyName: "sortable",
    familyRoot: "src/families/interaction/sortable/",
  },
  {
    catalog: interactionFamilyCatalog,
    familyName: "spatial-navigation",
    familyRoot: "src/families/interaction/spatial-navigation/",
  },
  {
    catalog: interactionFamilyCatalog,
    familyName: "virtualizer",
    familyRoot: "src/families/interaction/virtualizer/",
  },
  {
    catalog: overlayFamilyCatalog,
    familyName: "motion",
    familyRoot: "src/families/overlays/motion/",
  },
];

export const uiFamilyRoots = new Map<string, string>([
  ["a11y-audit", "src/families/accessibility/a11y-audit/"],
  ["action-sheet", "src/families/overlays/action-sheet/"],
  ["alert", "src/families/feedback/alert/"],
  ["alert-dialog", "src/families/overlays/alert-dialog/"],
  ["accordion", "src/families/disclosure/accordion/"],
  ["angle-picker", "src/families/form/angle-picker/"],
  ["announcer", "src/families/accessibility/announcer/"],
  ["aspect-ratio", "src/families/layout/aspect-ratio/"],
  ["audio-player", "src/families/media/audio-player/"],
  ["audio-visualizer", "src/families/media/audio-visualizer/"],
  ["autocomplete", "src/families/selection/autocomplete/"],
  ["avatar", "src/families/layout/avatar/"],
  ["back-to-top", "src/families/actions/back-to-top/"],
  ["banner", "src/families/feedback/banner/"],
  ["avatar-group", "src/families/layout/avatar-group/"],
  ["badge", "src/families/feedback/badge/"],
  ["bottom-navigation", "src/families/navigation/bottom-navigation/"],
  ["breadcrumb", "src/families/navigation/breadcrumb/"],
  ["blockquote", "src/families/typography/blockquote/"],
  ["block-ui", "src/families/feedback/block-ui/"],
  ["button", "src/families/actions/button/"],
  ["button-group", "src/families/actions/button-group/"],
  ["calendar", "src/families/date-time/calendar/"],
  ["callout", "src/families/feedback/callout/"],
  ["card", "src/families/layout/card/"],
  ["carousel", "src/families/media/carousel/"],
  ["cascader", "src/families/selection/cascader/"],
  ["chart", "src/families/charts/chart/"],
  ["chart-scale", "src/families/charts/chart-scale/"],
  ["chart-shape", "src/families/charts/chart-shape/"],
  ["checkbox", "src/families/selection/checkbox/"],
  ["checkbox-group", "src/families/selection/checkbox-group/"],
  ["cluster", "src/families/layout/cluster/"],
  ["confirm", "src/families/overlays/confirm/"],
  ["code", "src/families/typography/code/"],
  ["collection", "src/families/foundations/collection/"],
  ["color-picker", "src/families/form/color-picker/"],
  ["combobox", "src/families/selection/combobox/"],
  ["command-palette", "src/families/overlays/command-palette/"],
  ["composite-navigation", "src/families/foundations/composite-navigation/"],
  ["container", "src/families/layout/container/"],
  ["context-menu", "src/families/menus/context-menu/"],
  ["data-grid", "src/families/data/data-grid/"],
  ["date-field", "src/families/date-time/date-field/"],
  ["date-picker", "src/families/date-time/date-picker/"],
  ["date-range-picker", "src/families/date-time/date-range-picker/"],
  ["datetime-field", "src/families/date-time/datetime-field/"],
  ["dialog", "src/families/overlays/dialog/"],
  ["direction", "src/families/i18n/direction/"],
  ["dismissable-layer", "src/families/overlays/dismissable-layer/"],
  ["drag-and-drop", "src/families/interaction/drag-and-drop/"],
  ["dropdown-menu", "src/families/menus/dropdown-menu/"],
  ["editable", "src/families/form/editable/"],
  ["duration-field", "src/families/date-time/duration-field/"],
  ["emoji-picker", "src/families/selection/emoji-picker/"],
  ["empty-state", "src/families/feedback/empty-state/"],
  ["error-summary", "src/families/form/error-summary/"],
  ["fieldset", "src/families/form/fieldset/"],
  ["file-upload", "src/families/form/file-upload/"],
  ["floating-action-button", "src/families/actions/floating-action-button/"],
  ["focus", "src/families/accessibility/focus/"],
  ["focus-guards", "src/families/accessibility/focus-guards/"],
  ["drawer", "src/families/overlays/drawer/"],
  ["focus-scope", "src/families/accessibility/focus-scope/"],
  ["focus-visible", "src/families/accessibility/focus-visible/"],
  ["form-wizard", "src/families/form/form-wizard/"],
  ["fullscreen-button", "src/families/actions/fullscreen-button/"],
  ["grid", "src/families/layout/grid/"],
  ["grid-list", "src/families/data/grid-list/"],
  ["heading", "src/families/typography/heading/"],
  ["hotspot", "src/families/media/hotspot/"],
  ["hover", "src/families/interaction/hover/"],
  ["hover-card", "src/families/overlays/hover-card/"],
  ["icon", "src/families/layout/icon/"],
  ["icon-button", "src/families/layout/icon/"],
  ["image", "src/families/media/image/"],
  ["image-compare", "src/families/media/image-compare/"],
  ["image-cropper", "src/families/media/image-cropper/"],
  ["inert-outside", "src/families/accessibility/inert-outside/"],
  ["input-mask", "src/families/form/input-mask/"],
  ["interaction-modality", "src/families/accessibility/interaction-modality/"],
  ["infinite-scroll", "src/families/data/infinite-scroll/"],
  ["interaction-hooks", "src/families/interaction/interaction-hooks/"],
  ["kanban", "src/families/data/kanban/"],
  ["kbd", "src/families/typography/kbd/"],
  ["knob", "src/families/form/knob/"],
  ["landmark", "src/families/accessibility/landmark/"],
  ["lightbox", "src/families/media/lightbox/"],
  ["link", "src/families/navigation/link/"],
  ["list", "src/families/layout/list/"],
  ["listbox", "src/families/selection/listbox/"],
  ["listbox-grid", "src/families/selection/listbox-grid/"],
  ["live-region", "src/families/accessibility/live-region/"],
  ["locale", "src/families/i18n/locale/"],
  ["long-press", "src/families/interaction/long-press/"],
  ["media-preferences", "src/families/accessibility/media-preferences/"],
  ["menu", "src/families/menus/menu/"],
  ["menubar", "src/families/menus/menubar/"],
  ["marquee", "src/families/media/marquee/"],
  ["media-player", "src/families/media/media-player/"],
  ["mention", "src/families/form/mention/"],
  ["meter", "src/families/feedback/meter/"],
  ["month-picker", "src/families/date-time/month-picker/"],
  ["motion", "src/families/overlays/motion/"],
  ["move", "src/families/interaction/move/"],
  ["native-select", "src/families/selection/native-select/"],
  ["navigation-menu", "src/families/navigation/navigation-menu/"],
  ["number-field", "src/families/form/number-field/"],
  ["notification-center", "src/families/feedback/notification-center/"],
  ["pager", "src/families/navigation/pager/"],
  ["pagination", "src/families/navigation/pagination/"],
  ["pan-zoom", "src/families/media/pan-zoom/"],
  ["password-field", "src/families/form/password-field/"],
  ["pin-input", "src/families/form/pin-input/"],
  ["phone-field", "src/families/form/phone-field/"],
  ["pointer-grace", "src/families/interaction/pointer-grace/"],
  ["popconfirm", "src/families/overlays/popconfirm/"],
  ["popover", "src/families/overlays/popover/"],
  ["portal", "src/families/overlays/portal/"],
  ["positioner", "src/families/overlays/positioner/"],
  ["presence", "src/families/overlays/presence/"],
  ["press", "src/families/interaction/press/"],
  ["primitive", "src/families/foundations/primitive/"],
  ["print-button", "src/families/actions/print-button/"],
  ["progress", "src/families/feedback/progress/"],
  ["progress-bar", "src/families/feedback/progress-bar/"],
  ["pull-to-refresh", "src/families/interaction/pull-to-refresh/"],
  ["qr-code", "src/families/media/qr-code/"],
  ["radio-group", "src/families/selection/radio-group/"],
  ["range-calendar", "src/families/date-time/range-calendar/"],
  ["range-slider", "src/families/form/range-slider/"],
  ["rating", "src/families/form/rating/"],
  ["resizable", "src/families/layout/resizable/"],
  ["safe-area", "src/families/layout/safe-area/"],
  ["scroll-area", "src/families/layout/scroll-area/"],
  ["scroll-lock", "src/families/accessibility/scroll-lock/"],
  ["scroll-spy", "src/families/interaction/scroll-spy/"],
  ["scrubber-preview", "src/families/media/scrubber-preview/"],
  ["select", "src/families/selection/select/"],
  ["separator", "src/families/layout/separator/"],
  ["share-button", "src/families/actions/share-button/"],
  ["shortcut", "src/families/interaction/shortcut/"],
  ["sidebar", "src/families/layout/sidebar/"],
  ["signature-pad", "src/families/media/signature-pad/"],
  ["skeleton", "src/families/feedback/skeleton/"],
  ["skip-link", "src/families/navigation/skip-link/"],
  ["sortable", "src/families/interaction/sortable/"],
  ["spacer", "src/families/layout/spacer/"],
  ["spatial-navigation", "src/families/interaction/spatial-navigation/"],
  ["spinner", "src/families/feedback/spinner/"],
  ["splitter", "src/families/layout/splitter/"],
  ["stack", "src/families/layout/stack/"],
  ["status-light", "src/families/feedback/status-light/"],
  ["stepper", "src/families/navigation/stepper/"],
  ["sticky", "src/families/layout/sticky/"],
  ["surface", "src/families/layout/surface/"],
  ["swipe-actions", "src/families/interaction/swipe-actions/"],
  ["switch", "src/families/selection/switch/"],
  ["table", "src/families/data/table/"],
  ["tabs", "src/families/navigation/tabs/"],
  ["tags-input", "src/families/form/tags-input/"],
  ["text", "src/families/typography/text/"],
  ["timeline", "src/families/data/timeline/"],
  ["toc", "src/families/navigation/toc/"],
  ["toast", "src/families/feedback/toast/"],
  ["time-field", "src/families/date-time/time-field/"],
  ["time-picker", "src/families/date-time/time-picker/"],
  ["toggle", "src/families/selection/toggle/"],
  ["toggle-group", "src/families/selection/toggle-group/"],
  ["toolbar", "src/families/actions/toolbar/"],
  ["tooltip", "src/families/overlays/tooltip/"],
  ["tour", "src/families/overlays/tour/"],
  ["transfer-list", "src/families/selection/transfer-list/"],
  ["transition", "src/families/overlays/transition/"],
  ["tree", "src/families/data/tree/"],
  ["video-player", "src/families/media/video-player/"],
  ["virtualizer", "src/families/interaction/virtualizer/"],
  ["visually-hidden", "src/families/accessibility/visually-hidden/"],
  ["webcam-capture", "src/families/media/webcam-capture/"],
  ["week-picker", "src/families/date-time/week-picker/"],
  ["year-picker", "src/families/date-time/year-picker/"],
]);

export function assertFamilyPaths(
  canonicalName: string,
  familyRoot: string,
  label: string,
  files: readonly string[],
): void {
  assert.ok(
    files.every((file) => file.startsWith(familyRoot)),
    `${canonicalName} ${label} must stay beside the family source`,
  );
}
