import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const checkboxGroupRoot = "src/families/selection/checkbox-group/";
const editableRoot = "src/families/form/editable/";
const passwordFieldRoot = "src/families/form/password-field/";
const pinInputRoot = "src/families/form/pin-input/";

/** Catalog entries for composite form inputs (grouped, segmented, and inline-edit controls). */
export const formCompositeFamilyCatalog = [
  {
    canonicalName: "checkbox-group",
    title: "Checkbox Group",
    packageSubpath: "./checkbox-group",
    entryFile: `${checkboxGroupRoot}checkbox-group.ts`,
    sourceFiles: [
      `${checkboxGroupRoot}checkbox-group.vue`,
      `${checkboxGroupRoot}checkbox-group-item.vue`,
      `${checkboxGroupRoot}checkbox-group-select-all.vue`,
      `${checkboxGroupRoot}checkbox-group.ts`,
      `${checkboxGroupRoot}checkbox-group-context.ts`,
      `${checkboxGroupRoot}checkbox-group-types.ts`,
    ],
    behaviorContract: `${checkboxGroupRoot}checkbox-group.behavior.md`,
    tests: [
      `${checkboxGroupRoot}checkbox-group.test.ts`,
      `${checkboxGroupRoot}checkbox-group-ssr.test.ts`,
    ],
    typeTests: [`${checkboxGroupRoot}checkbox-group.types.test-d.ts`],
    rendererFixture: "CheckboxGroupConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "CheckboxGroup",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}checkbox-group",
      // `checkbox-group` also matches the Checkbox signature by name.
      allowedRetainedFamilies: ["checkbox", "context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["checkbox list", "multi-select checkboxes", "select all", "tri-state checkbox"],
    upstreamCoverage: [
      "HTML checkbox",
      "WAI-ARIA Checkbox (tri-state)",
      "React Aria CheckboxGroup",
      "Reka UI CheckboxGroup",
    ],
    dependencies: ["context", "controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "password-field",
    title: "Password Field",
    packageSubpath: "./password-field",
    entryFile: `${passwordFieldRoot}password-field.ts`,
    sourceFiles: [
      `${passwordFieldRoot}password-field.vue`,
      `${passwordFieldRoot}password-field-input.vue`,
      `${passwordFieldRoot}password-field-toggle.vue`,
      `${passwordFieldRoot}password-field.ts`,
      `${passwordFieldRoot}password-field-context.ts`,
      `${passwordFieldRoot}password-field-strength.ts`,
      `${passwordFieldRoot}password-field-types.ts`,
    ],
    behaviorContract: `${passwordFieldRoot}password-field.behavior.md`,
    tests: [
      `${passwordFieldRoot}password-field.test.ts`,
      `${passwordFieldRoot}password-field-ssr.test.ts`,
    ],
    typeTests: [`${passwordFieldRoot}password-field.types.test-d.ts`],
    rendererFixture: "PasswordFieldConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "PasswordField",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}password-field",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: [
      "password input",
      "show password",
      "reveal password",
      "caps lock warning",
      "password strength",
    ],
    upstreamCoverage: ["HTML password input", "WAI-ARIA Button (pressed)", "Chakra PasswordInput"],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "pin-input",
    title: "PIN Input",
    packageSubpath: "./pin-input",
    entryFile: `${pinInputRoot}pin-input.ts`,
    sourceFiles: [
      `${pinInputRoot}pin-input.vue`,
      `${pinInputRoot}pin-input-field.vue`,
      `${pinInputRoot}pin-input.ts`,
      `${pinInputRoot}pin-input-context.ts`,
      `${pinInputRoot}pin-input-state.ts`,
      `${pinInputRoot}pin-input-types.ts`,
    ],
    behaviorContract: `${pinInputRoot}pin-input.behavior.md`,
    tests: [`${pinInputRoot}pin-input.test.ts`, `${pinInputRoot}pin-input-ssr.test.ts`],
    typeTests: [`${pinInputRoot}pin-input.types.test-d.ts`],
    rendererFixture: "PinInputConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "PinInput",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}pin-input",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["otp input", "one-time code", "verification code", "pin code", "segmented input"],
    upstreamCoverage: ["HTML autocomplete one-time-code", "Chakra PinInput", "Reka UI PinInput"],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "editable",
    title: "Editable",
    packageSubpath: "./editable",
    entryFile: `${editableRoot}editable.ts`,
    sourceFiles: [
      `${editableRoot}editable.vue`,
      `${editableRoot}editable-preview.vue`,
      `${editableRoot}editable-input.vue`,
      `${editableRoot}editable-trigger.vue`,
      `${editableRoot}editable.ts`,
      `${editableRoot}editable-context.ts`,
      `${editableRoot}editable-types.ts`,
    ],
    behaviorContract: `${editableRoot}editable.behavior.md`,
    tests: [`${editableRoot}editable.test.ts`, `${editableRoot}editable-ssr.test.ts`],
    typeTests: [`${editableRoot}editable.types.test-d.ts`],
    rendererFixture: "EditableConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Editable",
      retainedSignature: 'data-vize-ui":(?:`editable`|"editable"|\'editable\')',
      // "editable" contains "table", so the Table signature matches by name.
      allowedRetainedFamilies: ["context", "controllable-state", "table"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["inline edit", "click to edit", "editable text", "in-place editor"],
    upstreamCoverage: ["Chakra Editable", "Ark UI Editable", "Reka UI Editable"],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
