import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const splitterFamilyRoot = "src/families/layout/splitter/";
const treeFamilyRoot = "src/families/data/tree/";

export const structureFamilyCatalog = [
  {
    canonicalName: "splitter",
    title: "Splitter",
    packageSubpath: "./splitter",
    entryFile: `${splitterFamilyRoot}splitter.ts`,
    sourceFiles: [
      `${splitterFamilyRoot}splitter-group.vue`,
      `${splitterFamilyRoot}splitter-handle.vue`,
      `${splitterFamilyRoot}splitter-panel.vue`,
      `${splitterFamilyRoot}splitter.ts`,
      `${splitterFamilyRoot}splitter-context.ts`,
      `${splitterFamilyRoot}splitter-layout.ts`,
      `${splitterFamilyRoot}splitter-persistence.ts`,
      `${splitterFamilyRoot}splitter-types.ts`,
    ],
    behaviorContract: `${splitterFamilyRoot}splitter.behavior.md`,
    tests: [
      `${splitterFamilyRoot}splitter.test.ts`,
      `${splitterFamilyRoot}splitter-layout.test.ts`,
      `${splitterFamilyRoot}splitter-ssr.test.ts`,
    ],
    typeTests: [`${splitterFamilyRoot}splitter.types.test-d.ts`],
    rendererFixture: "SplitterConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "SplitterGroup",
      retainedSignature: 'data-vize-ui":(?:`splitter-group`|"splitter-group"|\'splitter-group\')',
      allowedRetainedFamilies: ["collection", "context", "controllable-state"],
      maximumJavaScriptGzipBytes: 6_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["resizable panels", "split view", "split pane", "window splitter", "panel group"],
    upstreamCoverage: [
      "WAI-ARIA window splitter pattern",
      "react-resizable-panels",
      "Reka UI Splitter",
      "Ark UI Splitter",
    ],
    dependencies: ["collection", "context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "tree",
    title: "Tree",
    packageSubpath: "./tree",
    entryFile: `${treeFamilyRoot}tree.ts`,
    sourceFiles: [
      `${treeFamilyRoot}tree-item-checkbox.vue`,
      `${treeFamilyRoot}tree-item-toggle.vue`,
      `${treeFamilyRoot}tree-item.vue`,
      `${treeFamilyRoot}tree-root.vue`,
      `${treeFamilyRoot}tree.ts`,
      `${treeFamilyRoot}tree-context.ts`,
      `${treeFamilyRoot}tree-model.ts`,
      `${treeFamilyRoot}tree-reorder.ts`,
      `${treeFamilyRoot}tree-types.ts`,
      `${treeFamilyRoot}tree-virtualizer.ts`,
    ],
    behaviorContract: `${treeFamilyRoot}tree.behavior.md`,
    tests: [
      `${treeFamilyRoot}tree.test.ts`,
      `${treeFamilyRoot}tree-adapters.test.ts`,
      `${treeFamilyRoot}tree-model.test.ts`,
      `${treeFamilyRoot}tree-ssr.test.ts`,
    ],
    typeTests: [`${treeFamilyRoot}tree.types.test-d.ts`],
    rendererFixture: "TreeConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "TreeRoot",
      retainedSignature: 'data-vize-ui":(?:`tree`|"tree"|\'tree\')',
      allowedRetainedFamilies: ["collection", "context", "controllable-state", "typeahead"],
      maximumJavaScriptGzipBytes: 9_750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["tree view", "treeview", "file tree", "hierarchy", "outline", "nested list"],
    upstreamCoverage: [
      "WAI-ARIA tree view pattern",
      "React Aria Tree",
      "Ark UI Tree View",
      "Reka UI Tree",
      "MUI Tree View",
    ],
    dependencies: [
      "collection",
      "context",
      "controllable-state",
      "id",
      "sortable",
      "typeahead",
      "virtualizer",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
