import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const dateTimeRoot = "src/families/date-time/";

/** Date and time families: calendar grids, segmented fields, and popover pickers. */
export const dateTimeFamilyCatalog = [
  {
    canonicalName: "calendar",
    title: "Calendar",
    packageSubpath: "./calendar",
    entryFile: `${dateTimeRoot}calendar/calendar.ts`,
    sourceFiles: [
      `${dateTimeRoot}calendar/calendar-context.ts`,
      `${dateTimeRoot}calendar/calendar-grid.vue`,
      `${dateTimeRoot}calendar/calendar-heading.vue`,
      `${dateTimeRoot}calendar/calendar-locale.ts`,
      `${dateTimeRoot}calendar/calendar-month-select.vue`,
      `${dateTimeRoot}calendar/calendar-next.vue`,
      `${dateTimeRoot}calendar/calendar-prev.vue`,
      `${dateTimeRoot}calendar/calendar-root.vue`,
      `${dateTimeRoot}calendar/calendar-runtime.ts`,
      `${dateTimeRoot}calendar/calendar-selection.ts`,
      `${dateTimeRoot}calendar/calendar-today.ts`,
      `${dateTimeRoot}calendar/calendar-types.ts`,
      `${dateTimeRoot}calendar/calendar-year-select.vue`,
      `${dateTimeRoot}calendar/calendar.ts`,
      `${dateTimeRoot}calendar/plain-date.ts`,
    ],
    behaviorContract: `${dateTimeRoot}calendar/calendar.behavior.md`,
    tests: [
      `${dateTimeRoot}calendar/calendar-ssr.test.ts`,
      `${dateTimeRoot}calendar/calendar.test.ts`,
      `${dateTimeRoot}calendar/plain-date.test.ts`,
    ],
    typeTests: [`${dateTimeRoot}calendar/calendar.types.test-d.ts`],
    rendererFixture: "families/date-time/calendar/calendar-root.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "CalendarRoot",
      retainedSignature: 'data-vize-ui":(?:`calendar`|"calendar"|\'calendar\')',
      allowedRetainedFamilies: ["context", "controllable-state", "locale"],
      maximumJavaScriptGzipBytes: 8_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["calendar", "date grid", "month view", "mini calendar", "day picker"],
    upstreamCoverage: [
      "WAI-ARIA APG date picker dialog grid",
      "React Aria Calendar",
      "Reka UI Calendar",
      "Radix-style calendar composition",
    ],
    dependencies: ["context", "controllable-state", "id", "locale"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "date-field",
    title: "Date Field",
    packageSubpath: "./date-field",
    entryFile: `${dateTimeRoot}date-field/date-field.ts`,
    sourceFiles: [
      `${dateTimeRoot}date-field/date-field-runtime.ts`,
      `${dateTimeRoot}date-field/date-field-types.ts`,
      `${dateTimeRoot}date-field/date-field.ts`,
      `${dateTimeRoot}date-field/date-field.vue`,
      `${dateTimeRoot}date-field/field-segment-runtime.ts`,
      `${dateTimeRoot}date-field/field-segments.ts`,
    ],
    behaviorContract: `${dateTimeRoot}date-field/date-field.behavior.md`,
    tests: [
      `${dateTimeRoot}date-field/date-field-ssr.test.ts`,
      `${dateTimeRoot}date-field/date-field.test.ts`,
    ],
    typeTests: [`${dateTimeRoot}date-field/date-field.types.test-d.ts`],
    rendererFixture: "families/date-time/date-field/date-field.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "DateField",
      retainedSignature: "data-vize-ui[\\s\\S]{0,16}date-field-segment",
      allowedRetainedFamilies: ["context", "controllable-state", "locale"],
      maximumJavaScriptGzipBytes: 7_350,
      maximumCssGzipBytes: 0,
    },
    aliases: ["date input", "segmented date", "date segments", "masked date"],
    upstreamCoverage: [
      "WAI-ARIA spinbutton",
      "React Aria DateField",
      "Reka UI DateField",
      "HTML input type=date",
    ],
    dependencies: ["controllable-state", "id", "locale"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "date-picker",
    title: "Date Picker",
    packageSubpath: "./date-picker",
    entryFile: `${dateTimeRoot}date-picker/date-picker.ts`,
    sourceFiles: [
      `${dateTimeRoot}date-picker/date-picker-calendar.vue`,
      `${dateTimeRoot}date-picker/date-picker-content.vue`,
      `${dateTimeRoot}date-picker/date-picker-context.ts`,
      `${dateTimeRoot}date-picker/date-picker-field.vue`,
      `${dateTimeRoot}date-picker/date-picker-root.vue`,
      `${dateTimeRoot}date-picker/date-picker-runtime.ts`,
      `${dateTimeRoot}date-picker/date-picker-types.ts`,
      `${dateTimeRoot}date-picker/date-picker.ts`,
    ],
    behaviorContract: `${dateTimeRoot}date-picker/date-picker.behavior.md`,
    tests: [
      `${dateTimeRoot}date-picker/date-picker-ssr.test.ts`,
      `${dateTimeRoot}date-picker/date-picker.test.ts`,
    ],
    typeTests: [`${dateTimeRoot}date-picker/date-picker.types.test-d.ts`],
    rendererFixture: "families/date-time/date-picker/date-picker-root.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "DatePickerRoot",
      retainedSignature: 'data-vize-ui":(?:`date-picker`|"date-picker"|\'date-picker\')',
      allowedRetainedFamilies: ["context", "controllable-state", "locale", "popover"],
      maximumJavaScriptGzipBytes: 3_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["datepicker", "date popover", "calendar input"],
    upstreamCoverage: [
      "WAI-ARIA APG date picker dialog",
      "React Aria DatePicker",
      "Reka UI DatePicker",
      "HTML input type=date",
    ],
    dependencies: ["calendar", "context", "controllable-state", "date-field", "id", "popover"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "date-range-picker",
    title: "Date Range Picker",
    packageSubpath: "./date-range-picker",
    entryFile: `${dateTimeRoot}date-range-picker/date-range-picker.ts`,
    sourceFiles: [
      `${dateTimeRoot}date-range-picker/date-range-picker-calendar.vue`,
      `${dateTimeRoot}date-range-picker/date-range-picker-content.vue`,
      `${dateTimeRoot}date-range-picker/date-range-picker-context.ts`,
      `${dateTimeRoot}date-range-picker/date-range-picker-field.vue`,
      `${dateTimeRoot}date-range-picker/date-range-picker-root.vue`,
      `${dateTimeRoot}date-range-picker/date-range-picker-runtime.ts`,
      `${dateTimeRoot}date-range-picker/date-range-picker-types.ts`,
      `${dateTimeRoot}date-range-picker/date-range-picker.ts`,
    ],
    behaviorContract: `${dateTimeRoot}date-range-picker/date-range-picker.behavior.md`,
    tests: [
      `${dateTimeRoot}date-range-picker/date-range-picker-ssr.test.ts`,
      `${dateTimeRoot}date-range-picker/date-range-picker.test.ts`,
    ],
    typeTests: [`${dateTimeRoot}date-range-picker/date-range-picker.types.test-d.ts`],
    rendererFixture: "families/date-time/date-range-picker/date-range-picker-root.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "DateRangePickerRoot",
      retainedSignature:
        'data-vize-ui":(?:`date-range-picker`|"date-range-picker"|\'date-range-picker\')',
      allowedRetainedFamilies: ["context", "controllable-state", "locale", "popover"],
      maximumJavaScriptGzipBytes: 3_750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["range picker", "booking dates", "check-in check-out"],
    upstreamCoverage: [
      "React Aria DateRangePicker",
      "Reka UI DateRangePicker",
      "WAI-ARIA APG date picker dialog",
    ],
    dependencies: [
      "context",
      "controllable-state",
      "date-field",
      "id",
      "popover",
      "range-calendar",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "range-calendar",
    title: "Range Calendar",
    packageSubpath: "./range-calendar",
    entryFile: `${dateTimeRoot}range-calendar/range-calendar.ts`,
    sourceFiles: [
      `${dateTimeRoot}range-calendar/range-calendar-root.vue`,
      `${dateTimeRoot}range-calendar/range-calendar-selection.ts`,
      `${dateTimeRoot}range-calendar/range-calendar-types.ts`,
      `${dateTimeRoot}range-calendar/range-calendar.ts`,
    ],
    behaviorContract: `${dateTimeRoot}range-calendar/range-calendar.behavior.md`,
    tests: [
      `${dateTimeRoot}range-calendar/range-calendar-ssr.test.ts`,
      `${dateTimeRoot}range-calendar/range-calendar.test.ts`,
    ],
    typeTests: [`${dateTimeRoot}range-calendar/range-calendar.types.test-d.ts`],
    rendererFixture: "families/date-time/range-calendar/range-calendar-root.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "RangeCalendarRoot",
      retainedSignature: "data-mode[\\s\\S]{0,16}range",
      allowedRetainedFamilies: ["calendar", "context", "controllable-state", "locale"],
      maximumJavaScriptGzipBytes: 8_600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["date range calendar", "booking calendar", "two-click range"],
    upstreamCoverage: ["React Aria RangeCalendar", "Reka UI RangeCalendar", "WAI-ARIA APG grid"],
    dependencies: ["calendar", "context", "controllable-state", "id", "locale"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "time-field",
    title: "Time Field",
    packageSubpath: "./time-field",
    entryFile: `${dateTimeRoot}time-field/time-field.ts`,
    sourceFiles: [
      `${dateTimeRoot}time-field/plain-time.ts`,
      `${dateTimeRoot}time-field/time-field-runtime.ts`,
      `${dateTimeRoot}time-field/time-field-types.ts`,
      `${dateTimeRoot}time-field/time-field.ts`,
      `${dateTimeRoot}time-field/time-field.vue`,
    ],
    behaviorContract: `${dateTimeRoot}time-field/time-field.behavior.md`,
    tests: [
      `${dateTimeRoot}time-field/time-field-ssr.test.ts`,
      `${dateTimeRoot}time-field/time-field.test.ts`,
    ],
    typeTests: [`${dateTimeRoot}time-field/time-field.types.test-d.ts`],
    rendererFixture: "families/date-time/time-field/time-field.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "TimeField",
      retainedSignature: "data-vize-ui[\\s\\S]{0,16}time-field-segment",
      allowedRetainedFamilies: ["context", "controllable-state", "locale"],
      maximumJavaScriptGzipBytes: 6_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["time input", "segmented time", "clock input", "hh:mm"],
    upstreamCoverage: [
      "WAI-ARIA spinbutton",
      "React Aria TimeField",
      "Reka UI TimeField",
      "HTML input type=time",
    ],
    dependencies: ["controllable-state", "date-field", "id", "locale"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
