import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const checkboxFamilyRoot = "src/families/selection/checkbox/";
const listboxFamilyRoot = "src/families/selection/listbox/";
const nativeSelectFamilyRoot = "src/families/selection/native-select/";
const radioGroupFamilyRoot = "src/families/selection/radio-group/";
const switchFamilyRoot = "src/families/selection/switch/";
const toggleFamilyRoot = "src/families/selection/toggle/";
const toggleGroupFamilyRoot = "src/families/selection/toggle-group/";

export const selectionFamilyCatalog = [
  {
    canonicalName: "checkbox",
    title: "Checkbox",
    packageSubpath: "./checkbox",
    entryFile: `${checkboxFamilyRoot}checkbox.ts`,
    sourceFiles: [
      `${checkboxFamilyRoot}checkbox-control.vue`,
      `${checkboxFamilyRoot}checkbox.ts`,
      `${checkboxFamilyRoot}checkbox-state.ts`,
    ],
    behaviorContract: `${checkboxFamilyRoot}checkbox.behavior.md`,
    tests: [`${checkboxFamilyRoot}checkbox.test.ts`],
    rendererFixture: "families/selection/checkbox/checkbox-control.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Checkbox",
      retainedSignature: "data-vize-ui[\\s\\S]{0,24}checkbox",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 1_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["checkbox control", "mixed checkbox"],
    upstreamCoverage: ["shadcn/ui Checkbox", "Reka UI Checkbox", "React Aria Checkbox"],
    dependencies: ["controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "listbox",
    title: "Listbox",
    packageSubpath: "./listbox",
    entryFile: `${listboxFamilyRoot}listbox.ts`,
    sourceFiles: [
      `${listboxFamilyRoot}listbox.vue`,
      `${listboxFamilyRoot}listbox-item.vue`,
      `${listboxFamilyRoot}listbox.ts`,
      `${listboxFamilyRoot}listbox-context.ts`,
      `${listboxFamilyRoot}listbox-types.ts`,
      `${listboxFamilyRoot}listbox-value.ts`,
    ],
    behaviorContract: `${listboxFamilyRoot}listbox.behavior.md`,
    tests: [`${listboxFamilyRoot}listbox.test.ts`, `${listboxFamilyRoot}listbox-ssr.test.ts`],
    typeTests: [`${listboxFamilyRoot}listbox.types.test-d.ts`],
    rendererFixture: "ListboxConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Listbox",
      retainedSignature: 'data-vize-ui":(?:`listbox`|"listbox"|\'listbox\')',
      allowedRetainedFamilies: [
        "collection",
        "composite-navigation",
        "context",
        "controllable-state",
        "typeahead",
      ],
      maximumJavaScriptGzipBytes: 9_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["listbox", "option list", "single select", "multi select"],
    upstreamCoverage: [
      "WAI-ARIA listbox pattern",
      "React Aria ListBox",
      "Ariakit Select",
      "Reka UI Listbox",
    ],
    dependencies: [
      "collection",
      "composite-navigation",
      "context",
      "controllable-state",
      "id",
      "typeahead",
    ],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "native-select",
    title: "Native Select",
    packageSubpath: "./native-select",
    entryFile: `${nativeSelectFamilyRoot}native-select.ts`,
    sourceFiles: [
      `${nativeSelectFamilyRoot}native-select.vue`,
      `${nativeSelectFamilyRoot}native-select.ts`,
      `${nativeSelectFamilyRoot}native-select-types.ts`,
      `${nativeSelectFamilyRoot}native-select-value.ts`,
    ],
    behaviorContract: `${nativeSelectFamilyRoot}native-select.behavior.md`,
    tests: [
      `${nativeSelectFamilyRoot}native-select.test.ts`,
      `${nativeSelectFamilyRoot}native-select-ssr.test.ts`,
    ],
    typeTests: [`${nativeSelectFamilyRoot}native-select.types.test-d.ts`],
    rendererFixture: "families/selection/native-select/native-select.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "NativeSelect",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}native-select",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 4_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["native select", "select", "form select", "html select"],
    upstreamCoverage: [
      "HTML select element",
      "React Aria Select native escape hatch",
      "Radix Select native form fallback",
      "Reka UI Select hidden native select interop",
    ],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "radio-group",
    title: "Radio Group",
    packageSubpath: "./radio-group",
    entryFile: `${radioGroupFamilyRoot}radio-group.ts`,
    sourceFiles: [
      `${radioGroupFamilyRoot}radio-group.vue`,
      `${radioGroupFamilyRoot}radio-group-item.vue`,
      `${radioGroupFamilyRoot}radio-group.ts`,
      `${radioGroupFamilyRoot}radio-group-context.ts`,
      `${radioGroupFamilyRoot}radio-group-types.ts`,
    ],
    behaviorContract: `${radioGroupFamilyRoot}radio-group.behavior.md`,
    tests: [
      `${radioGroupFamilyRoot}radio-group.test.ts`,
      `${radioGroupFamilyRoot}radio-group-ssr.test.ts`,
    ],
    typeTests: [`${radioGroupFamilyRoot}radio-group.types.test-d.ts`],
    rendererFixture: "RadioGroupConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "RadioGroup",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}radio-group",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 2_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["radio group", "choice group", "single choice"],
    upstreamCoverage: [
      "HTML radio",
      "WAI-ARIA Radio Group",
      "React Aria RadioGroup",
      "Reka UI Radio Group",
    ],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "switch",
    title: "Switch",
    packageSubpath: "./switch",
    entryFile: `${switchFamilyRoot}switch.ts`,
    sourceFiles: [
      `${switchFamilyRoot}switch-control.vue`,
      `${switchFamilyRoot}switch.ts`,
      `${switchFamilyRoot}switch-types.ts`,
    ],
    behaviorContract: `${switchFamilyRoot}switch.behavior.md`,
    tests: [`${switchFamilyRoot}switch.test.ts`],
    typeTests: [`${switchFamilyRoot}switch.types.test-d.ts`],
    rendererFixture: "families/selection/switch/switch-control.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Switch",
      retainedSignature: "role[\\s\\S]{0,24}switch",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 3_200,
      maximumCssGzipBytes: 0,
    },
    aliases: ["switch control", "on off switch", "form switch"],
    upstreamCoverage: ["WAI-ARIA Switch", "React Aria Switch", "Reka UI Switch"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "toggle",
    title: "Toggle",
    packageSubpath: "./toggle",
    entryFile: `${toggleFamilyRoot}toggle.ts`,
    sourceFiles: [
      `${toggleFamilyRoot}toggle-button.vue`,
      `${toggleFamilyRoot}toggle.ts`,
      `${toggleFamilyRoot}toggle-types.ts`,
    ],
    behaviorContract: `${toggleFamilyRoot}toggle.behavior.md`,
    tests: [`${toggleFamilyRoot}toggle.test.ts`],
    typeTests: [`${toggleFamilyRoot}toggle.types.test-d.ts`],
    rendererFixture: "families/selection/toggle/toggle-button.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Toggle",
      retainedSignature: "aria-pressed",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 1_700,
      maximumCssGzipBytes: 0,
    },
    aliases: ["toggle button", "pressed button", "on off button"],
    upstreamCoverage: ["WAI-ARIA toggle button", "React Aria ToggleButton", "Reka UI Toggle"],
    dependencies: ["controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "toggle-group",
    title: "Toggle Group",
    packageSubpath: "./toggle-group",
    entryFile: `${toggleGroupFamilyRoot}toggle-group.ts`,
    sourceFiles: [
      `${toggleGroupFamilyRoot}toggle-group.vue`,
      `${toggleGroupFamilyRoot}toggle-group-item.vue`,
      `${toggleGroupFamilyRoot}toggle-group.ts`,
      `${toggleGroupFamilyRoot}toggle-group-context.ts`,
      `${toggleGroupFamilyRoot}toggle-group-types.ts`,
      `${toggleGroupFamilyRoot}toggle-group-value.ts`,
    ],
    behaviorContract: `${toggleGroupFamilyRoot}toggle-group.behavior.md`,
    tests: [
      `${toggleGroupFamilyRoot}toggle-group.test.ts`,
      `${toggleGroupFamilyRoot}toggle-group-ssr.test.ts`,
    ],
    typeTests: [`${toggleGroupFamilyRoot}toggle-group.types.test-d.ts`],
    rendererFixture: "ToggleGroupConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ToggleGroup",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}toggle-group",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 4_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["toggle button group", "pressed button group", "segmented control"],
    upstreamCoverage: [
      "WAI-ARIA toggle button group",
      "Radix UI ToggleGroup",
      "Reka UI ToggleGroup",
    ],
    dependencies: ["context", "controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
