import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const layoutFamilyRoot = "src/families/layout/";
const dashboardGridFamilyRoot = `${layoutFamilyRoot}dashboard-grid/`;
const windowManagerFamilyRoot = `${layoutFamilyRoot}window-manager/`;
const masonryFamilyRoot = `${layoutFamilyRoot}masonry/`;
const masterDetailFamilyRoot = `${layoutFamilyRoot}master-detail/`;
const responsiveFamilyRoot = `${layoutFamilyRoot}responsive/`;
const stickyStackFamilyRoot = `${layoutFamilyRoot}sticky-stack/`;

/** Niche layout patterns: dashboards, masonry, master-detail, responsive rendering, sticky stacks, and windows. */
export const layoutPatternFamilyCatalog = [
  {
    canonicalName: "dashboard-grid",
    title: "Dashboard Grid",
    packageSubpath: "./dashboard-grid",
    entryFile: `${dashboardGridFamilyRoot}dashboard-grid.ts`,
    sourceFiles: [
      `${dashboardGridFamilyRoot}dashboard-grid-item.vue`,
      `${dashboardGridFamilyRoot}dashboard-grid.vue`,
      `${dashboardGridFamilyRoot}dashboard-grid.ts`,
      `${dashboardGridFamilyRoot}dashboard-grid-context.ts`,
      `${dashboardGridFamilyRoot}dashboard-grid-layout.ts`,
      `${dashboardGridFamilyRoot}dashboard-grid-types.ts`,
    ],
    behaviorContract: `${dashboardGridFamilyRoot}dashboard-grid.behavior.md`,
    tests: [
      `${dashboardGridFamilyRoot}dashboard-grid.test.ts`,
      `${dashboardGridFamilyRoot}dashboard-grid-layout.test.ts`,
      `${dashboardGridFamilyRoot}dashboard-grid-ssr.test.ts`,
    ],
    typeTests: [`${dashboardGridFamilyRoot}dashboard-grid.types.test-d.ts`],
    rendererFixture: "DashboardGridConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "DashboardGrid",
      retainedSignature: 'data-vize-ui":(?:`dashboard-grid`|"dashboard-grid"|\'dashboard-grid\')',
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 2_600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["grid layout", "draggable dashboard", "widget grid", "resizable widgets"],
    upstreamCoverage: ["react-grid-layout", "gridstack.js", "vue-grid-layout"],
    dependencies: ["context", "controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "masonry",
    title: "Masonry",
    packageSubpath: "./masonry",
    entryFile: `${masonryFamilyRoot}masonry.ts`,
    sourceFiles: [
      `${masonryFamilyRoot}masonry.vue`,
      `${masonryFamilyRoot}masonry.ts`,
      `${masonryFamilyRoot}masonry-layout.ts`,
      `${masonryFamilyRoot}masonry-types.ts`,
    ],
    behaviorContract: `${masonryFamilyRoot}masonry.behavior.md`,
    tests: [
      `${masonryFamilyRoot}masonry.test.ts`,
      `${masonryFamilyRoot}masonry-layout.test.ts`,
      `${masonryFamilyRoot}masonry-ssr.test.ts`,
    ],
    typeTests: [`${masonryFamilyRoot}masonry.types.test-d.ts`],
    rendererFixture: "MasonryConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Masonry",
      retainedSignature: "VIZE_UI_MASONRY_COLUMNS",
      maximumJavaScriptGzipBytes: 2_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["masonry grid", "pinterest layout", "waterfall layout", "column balancing"],
    upstreamCoverage: ["Masonry.js", "react-masonry-css", "Mantine Masonry", "CSS grid-lanes"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "master-detail",
    title: "Master Detail",
    packageSubpath: "./master-detail",
    entryFile: `${masterDetailFamilyRoot}master-detail.ts`,
    sourceFiles: [
      `${masterDetailFamilyRoot}master-detail.vue`,
      `${masterDetailFamilyRoot}master-detail.ts`,
      `${masterDetailFamilyRoot}master-detail-types.ts`,
      `${masterDetailFamilyRoot}master-detail-viewport.ts`,
    ],
    behaviorContract: `${masterDetailFamilyRoot}master-detail.behavior.md`,
    tests: [
      `${masterDetailFamilyRoot}master-detail.test.ts`,
      `${masterDetailFamilyRoot}master-detail-ssr.test.ts`,
    ],
    typeTests: [`${masterDetailFamilyRoot}master-detail.types.test-d.ts`],
    rendererFixture: "MasterDetailConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "MasterDetail",
      retainedSignature: 'data-vize-ui":(?:`master-detail`|"master-detail"|\'master-detail\')',
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 2_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["list detail", "split view", "two pane layout", "adaptive list"],
    upstreamCoverage: [
      "Material list-detail canonical layout",
      "Apple split view",
      "Fluent master-detail pattern",
    ],
    dependencies: ["controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "responsive",
    title: "Responsive Rendering",
    packageSubpath: "./responsive",
    entryFile: `${responsiveFamilyRoot}responsive.ts`,
    sourceFiles: [
      `${responsiveFamilyRoot}responsive-show.vue`,
      `${responsiveFamilyRoot}responsive-switch.vue`,
      `${responsiveFamilyRoot}responsive.ts`,
      `${responsiveFamilyRoot}breakpoint.ts`,
      `${responsiveFamilyRoot}responsive-types.ts`,
    ],
    behaviorContract: `${responsiveFamilyRoot}responsive.behavior.md`,
    tests: [
      `${responsiveFamilyRoot}responsive.test.ts`,
      `${responsiveFamilyRoot}responsive-ssr.test.ts`,
    ],
    typeTests: [`${responsiveFamilyRoot}responsive.types.test-d.ts`],
    rendererFixture: "ResponsiveConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ResponsiveSwitch",
      retainedSignature: "VIZE_UI_RESPONSIVE_SETUP",
      maximumJavaScriptGzipBytes: 1_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["breakpoints", "use breakpoint", "show hide", "media query rendering"],
    upstreamCoverage: ["Chakra Show/Hide", "Vuetify useDisplay", "VueUse useBreakpoints"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "sticky-stack",
    title: "Sticky Stack",
    packageSubpath: "./sticky-stack",
    entryFile: `${stickyStackFamilyRoot}sticky-stack.ts`,
    sourceFiles: [
      `${stickyStackFamilyRoot}sticky-stack-item.vue`,
      `${stickyStackFamilyRoot}sticky-stack.vue`,
      `${stickyStackFamilyRoot}sticky-stack.ts`,
      `${stickyStackFamilyRoot}sticky-stack-context.ts`,
      `${stickyStackFamilyRoot}sticky-stack-layout.ts`,
      `${stickyStackFamilyRoot}sticky-stack-types.ts`,
    ],
    behaviorContract: `${stickyStackFamilyRoot}sticky-stack.behavior.md`,
    tests: [
      `${stickyStackFamilyRoot}sticky-stack.test.ts`,
      `${stickyStackFamilyRoot}sticky-stack-ssr.test.ts`,
    ],
    typeTests: [`${stickyStackFamilyRoot}sticky-stack.types.test-d.ts`],
    rendererFixture: "StickyStackConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "StickyStack",
      retainedSignature: "--vize-ui-sticky-stack-height",
      allowedRetainedFamilies: ["context"],
      maximumJavaScriptGzipBytes: 1_600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["sticky header", "stacked sticky", "sticky toolbar", "sticky offsets"],
    upstreamCoverage: ["position: sticky", "react-sticky", "Material top app bar stacking"],
    dependencies: ["context"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "window-manager",
    title: "Window Manager",
    packageSubpath: "./window-manager",
    entryFile: `${windowManagerFamilyRoot}window-manager.ts`,
    sourceFiles: [
      `${windowManagerFamilyRoot}floating-window.vue`,
      `${windowManagerFamilyRoot}window-dock.vue`,
      `${windowManagerFamilyRoot}window-manager.vue`,
      `${windowManagerFamilyRoot}window-manager.ts`,
      `${windowManagerFamilyRoot}window-manager-context.ts`,
      `${windowManagerFamilyRoot}window-manager-model.ts`,
      `${windowManagerFamilyRoot}window-manager-persistence.ts`,
      `${windowManagerFamilyRoot}window-manager-types.ts`,
    ],
    behaviorContract: `${windowManagerFamilyRoot}window-manager.behavior.md`,
    tests: [
      `${windowManagerFamilyRoot}window-manager.test.ts`,
      `${windowManagerFamilyRoot}window-manager-model.test.ts`,
      `${windowManagerFamilyRoot}window-manager-ssr.test.ts`,
    ],
    typeTests: [`${windowManagerFamilyRoot}window-manager.types.test-d.ts`],
    rendererFixture: "WindowManagerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "WindowManager",
      retainedSignature: 'data-vize-ui":(?:`window-manager`|"window-manager"|\'window-manager\')',
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["floating windows", "dock", "mdi", "desktop windows", "taskbar"],
    upstreamCoverage: [
      "WinBox.js",
      "react-rnd",
      "Golden Layout floating windows",
      "macOS window management",
    ],
    dependencies: ["context", "controllable-state"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
