import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";
const anglePickerRoot = "src/families/form/angle-picker/";
const fieldsetRoot = "src/families/form/fieldset/";
const formWizardRoot = "src/families/form/form-wizard/";
const knobRoot = "src/families/form/knob/";
const phoneFieldRoot = "src/families/form/phone-field/";

/** Catalog entries for form structure and specialised inputs (fieldsets, wizards, dials, phone numbers). */
export const formStructureFamilyCatalog = [
  {
    canonicalName: "fieldset",
    title: "Fieldset",
    packageSubpath: "./fieldset",
    entryFile: `${fieldsetRoot}fieldset.ts`,
    sourceFiles: [
      `${fieldsetRoot}fieldset.vue`,
      `${fieldsetRoot}fieldset-legend.vue`,
      `${fieldsetRoot}fieldset-description.vue`,
      `${fieldsetRoot}fieldset-error-message.vue`,
      `${fieldsetRoot}fieldset.ts`,
      `${fieldsetRoot}fieldset-context.ts`,
      `${fieldsetRoot}fieldset-types.ts`,
    ],
    behaviorContract: `${fieldsetRoot}fieldset.behavior.md`,
    tests: [`${fieldsetRoot}fieldset.test.ts`, `${fieldsetRoot}fieldset-ssr.test.ts`],
    typeTests: [`${fieldsetRoot}fieldset.types.test-d.ts`],
    rendererFixture: "FieldsetConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Fieldset",
      retainedSignature: 'data-vize-ui":(?:`fieldset`|"fieldset"|\'fieldset\')',
      allowedRetainedFamilies: ["context", "field-wiring"],
      maximumJavaScriptGzipBytes: 2_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["fieldset", "field group", "legend", "radio group wrapper", "form section"],
    upstreamCoverage: ["HTML fieldset/legend", "WAI-ARIA group", "React Aria Fieldset"],
    dependencies: ["context", "field-wiring", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "form-wizard",
    title: "Form Wizard",
    packageSubpath: "./form-wizard",
    entryFile: `${formWizardRoot}form-wizard.ts`,
    sourceFiles: [
      `${formWizardRoot}form-wizard.vue`,
      `${formWizardRoot}form-wizard-step.vue`,
      `${formWizardRoot}form-wizard-next.vue`,
      `${formWizardRoot}form-wizard-back.vue`,
      `${formWizardRoot}form-wizard-progress.vue`,
      `${formWizardRoot}form-wizard.ts`,
      `${formWizardRoot}form-wizard-context.ts`,
      `${formWizardRoot}form-wizard-types.ts`,
    ],
    behaviorContract: `${formWizardRoot}form-wizard.behavior.md`,
    tests: [`${formWizardRoot}form-wizard.test.ts`, `${formWizardRoot}form-wizard-ssr.test.ts`],
    typeTests: [`${formWizardRoot}form-wizard.types.test-d.ts`],
    rendererFixture: "FormWizardConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "FormWizard",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}form-wizard",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["multi-step form", "wizard", "checkout steps", "onboarding flow"],
    upstreamCoverage: ["WAI-ARIA aria-current=step", "Chakra Steps", "Ark UI Steps"],
    dependencies: ["context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "knob",
    title: "Knob",
    packageSubpath: "./knob",
    entryFile: `${knobRoot}knob.ts`,
    sourceFiles: [
      `${knobRoot}knob.vue`,
      `${knobRoot}knob.ts`,
      `${knobRoot}knob-geometry.ts`,
      `${knobRoot}knob-pointer.ts`,
      `${knobRoot}knob-types.ts`,
    ],
    behaviorContract: `${knobRoot}knob.behavior.md`,
    tests: [`${knobRoot}knob.test.ts`, `${knobRoot}knob-ssr.test.ts`],
    typeTests: [`${knobRoot}knob.types.test-d.ts`],
    rendererFixture: "KnobConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Knob",
      retainedSignature: 'data-vize-ui":(?:`knob`|"knob"|\'knob\')',
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["knob", "dial", "rotary input", "potentiometer"],
    upstreamCoverage: ["WAI-ARIA Slider", "React Aria useSlider (rotary)", "Web Audio UI knobs"],
    dependencies: ["controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "angle-picker",
    title: "Angle Picker",
    packageSubpath: "./angle-picker",
    entryFile: `${anglePickerRoot}angle-picker.ts`,
    sourceFiles: [
      `${anglePickerRoot}angle-picker.vue`,
      `${anglePickerRoot}angle-picker.ts`,
      `${anglePickerRoot}angle-picker-types.ts`,
    ],
    behaviorContract: `${anglePickerRoot}angle-picker.behavior.md`,
    tests: [`${anglePickerRoot}angle-picker.test.ts`],
    typeTests: [`${anglePickerRoot}angle-picker.types.test-d.ts`],
    rendererFixture: "KnobConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "AnglePicker",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}angle-picker",
      allowedRetainedFamilies: ["controllable-state"],
      maximumJavaScriptGzipBytes: 3_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["angle input", "rotation picker", "hue wheel", "direction picker"],
    upstreamCoverage: ["WAI-ARIA Slider", "Figma angle input", "Mantine AngleSlider"],
    dependencies: ["controllable-state", "id", "knob"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "phone-field",
    title: "Phone Field",
    packageSubpath: "./phone-field",
    entryFile: `${phoneFieldRoot}phone-field.ts`,
    sourceFiles: [
      `${phoneFieldRoot}phone-field.vue`,
      `${phoneFieldRoot}phone-field-input.vue`,
      `${phoneFieldRoot}phone-field-country-select.vue`,
      `${phoneFieldRoot}phone-field.ts`,
      `${phoneFieldRoot}phone-field-context.ts`,
      `${phoneFieldRoot}phone-field-country.ts`,
      `${phoneFieldRoot}phone-field-types.ts`,
    ],
    behaviorContract: `${phoneFieldRoot}phone-field.behavior.md`,
    tests: [`${phoneFieldRoot}phone-field.test.ts`, `${phoneFieldRoot}phone-field-ssr.test.ts`],
    typeTests: [`${phoneFieldRoot}phone-field.types.test-d.ts`],
    rendererFixture: "PhoneFieldConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "PhoneField",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}phone-field",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 6_500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["phone input", "telephone field", "international phone", "e164 input"],
    upstreamCoverage: [
      "HTML tel input",
      "libphonenumber (metadata supplied by consumer)",
      "react-phone-number-input",
    ],
    dependencies: ["context", "controllable-state", "id", "input-mask", "native-select"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
