import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const navigationMenuFamilyRoot = "src/families/navigation/navigation-menu/";
const scrollSpyFamilyRoot = "src/families/interaction/scroll-spy/";
const timelineFamilyRoot = "src/families/data/timeline/";
const tocFamilyRoot = "src/families/navigation/toc/";

export const wayfindingFamilyCatalog = [
  {
    canonicalName: "navigation-menu",
    title: "Navigation Menu",
    packageSubpath: "./navigation-menu",
    entryFile: `${navigationMenuFamilyRoot}navigation-menu.ts`,
    sourceFiles: [
      `${navigationMenuFamilyRoot}navigation-menu-content.vue`,
      `${navigationMenuFamilyRoot}navigation-menu-indicator.vue`,
      `${navigationMenuFamilyRoot}navigation-menu-item.vue`,
      `${navigationMenuFamilyRoot}navigation-menu-link.vue`,
      `${navigationMenuFamilyRoot}navigation-menu-list.vue`,
      `${navigationMenuFamilyRoot}navigation-menu-root.vue`,
      `${navigationMenuFamilyRoot}navigation-menu-trigger.vue`,
      `${navigationMenuFamilyRoot}navigation-menu-viewport.vue`,
      `${navigationMenuFamilyRoot}navigation-menu.ts`,
      `${navigationMenuFamilyRoot}navigation-menu-context.ts`,
      `${navigationMenuFamilyRoot}navigation-menu-id.ts`,
      `${navigationMenuFamilyRoot}navigation-menu-types.ts`,
    ],
    behaviorContract: `${navigationMenuFamilyRoot}navigation-menu.behavior.md`,
    tests: [
      `${navigationMenuFamilyRoot}navigation-menu.test.ts`,
      `${navigationMenuFamilyRoot}navigation-menu-ssr.test.ts`,
    ],
    typeTests: [`${navigationMenuFamilyRoot}navigation-menu.types.test-d.ts`],
    rendererFixture: "NavigationMenuConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "NavigationMenuRoot",
      retainedSignature:
        'data-vize-ui":(?:`navigation-menu`|"navigation-menu"|\'navigation-menu\')',
      allowedRetainedFamilies: ["collection", "context", "controllable-state"],
      maximumJavaScriptGzipBytes: 6_000,
      maximumCssGzipBytes: 0,
    },
    aliases: [
      "site navigation",
      "mega menu",
      "navbar",
      "flyout navigation",
      "disclosure navigation",
    ],
    upstreamCoverage: [
      "WAI-ARIA disclosure navigation pattern",
      "Radix Navigation Menu",
      "Reka UI Navigation Menu",
      "Ark UI Navigation Menu",
    ],
    dependencies: ["collection", "context", "controllable-state", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "scroll-spy",
    title: "Scroll Spy",
    packageSubpath: "./scroll-spy",
    entryFile: `${scrollSpyFamilyRoot}scroll-spy.ts`,
    sourceFiles: [
      `${scrollSpyFamilyRoot}scroll-spy.ts`,
      `${scrollSpyFamilyRoot}scroll-spy-types.ts`,
    ],
    behaviorContract: `${scrollSpyFamilyRoot}scroll-spy.behavior.md`,
    tests: [
      `${scrollSpyFamilyRoot}scroll-spy.test.ts`,
      `${scrollSpyFamilyRoot}scroll-spy-ssr.test.ts`,
    ],
    typeTests: [`${scrollSpyFamilyRoot}scroll-spy.types.test-d.ts`],
    rendererFixture: "ScrollSpyConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "useScrollSpy",
      retainedSignature: "VIZE_UI_SCROLL_SPY_SETUP",
      maximumJavaScriptGzipBytes: 1_300,
      maximumCssGzipBytes: 0,
    },
    aliases: ["scroll spy", "active section", "section observer", "reading position"],
    upstreamCoverage: [
      "Bootstrap Scrollspy",
      "VueUse useIntersectionObserver",
      "IntersectionObserver",
    ],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "timeline",
    title: "Timeline",
    packageSubpath: "./timeline",
    entryFile: `${timelineFamilyRoot}timeline.ts`,
    sourceFiles: [
      `${timelineFamilyRoot}timeline-connector.vue`,
      `${timelineFamilyRoot}timeline-content.vue`,
      `${timelineFamilyRoot}timeline-indicator.vue`,
      `${timelineFamilyRoot}timeline-item.vue`,
      `${timelineFamilyRoot}timeline-root.vue`,
      `${timelineFamilyRoot}timeline-time.vue`,
      `${timelineFamilyRoot}timeline.ts`,
      `${timelineFamilyRoot}timeline-context.ts`,
      `${timelineFamilyRoot}timeline-types.ts`,
    ],
    behaviorContract: `${timelineFamilyRoot}timeline.behavior.md`,
    tests: [`${timelineFamilyRoot}timeline.test.ts`, `${timelineFamilyRoot}timeline-ssr.test.ts`],
    typeTests: [`${timelineFamilyRoot}timeline.types.test-d.ts`],
    rendererFixture: "TimelineConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "TimelineRoot",
      retainedSignature: 'data-vize-ui":(?:`timeline`|"timeline"|\'timeline\')',
      allowedRetainedFamilies: ["collection", "context"],
      maximumJavaScriptGzipBytes: 4_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["timeline", "activity feed", "history", "event log", "progress steps"],
    upstreamCoverage: [
      "HTML ordered list",
      "HTML time element",
      "MUI Timeline",
      "Mantine Timeline",
    ],
    dependencies: ["collection", "context", "id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "toc",
    title: "Table of Contents",
    packageSubpath: "./toc",
    entryFile: `${tocFamilyRoot}toc.ts`,
    sourceFiles: [
      `${tocFamilyRoot}toc-item.vue`,
      `${tocFamilyRoot}toc-link.vue`,
      `${tocFamilyRoot}toc-list.vue`,
      `${tocFamilyRoot}toc-root.vue`,
      `${tocFamilyRoot}toc.ts`,
      `${tocFamilyRoot}toc-collect.ts`,
      `${tocFamilyRoot}toc-context.ts`,
      `${tocFamilyRoot}toc-types.ts`,
    ],
    behaviorContract: `${tocFamilyRoot}toc.behavior.md`,
    tests: [`${tocFamilyRoot}toc.test.ts`, `${tocFamilyRoot}toc-ssr.test.ts`],
    typeTests: [`${tocFamilyRoot}toc.types.test-d.ts`],
    rendererFixture: "TocConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "TocRoot",
      retainedSignature: 'data-vize-ui":(?:`toc`|"toc"|\'toc\')',
      allowedRetainedFamilies: ["collection", "context", "controllable-state", "scroll-spy"],
      maximumJavaScriptGzipBytes: 5_300,
      maximumCssGzipBytes: 0,
    },
    aliases: [
      "table of contents",
      "toc",
      "on this page",
      "outline navigation",
      "anchor navigation",
    ],
    upstreamCoverage: [
      "HTML nav landmark",
      "aria-current location",
      "Docusaurus TOC",
      "Nuxt UI ContentToc",
    ],
    dependencies: ["collection", "context", "controllable-state", "id", "scroll-spy"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
