import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "./family-catalog-types.ts";

const carouselFamilyRoot = "src/families/media/carousel/";
const imageFamilyRoot = "src/families/media/image/";

export const mediaFamilyCatalog = [
  {
    canonicalName: "carousel",
    title: "Carousel",
    packageSubpath: "./carousel",
    entryFile: `${carouselFamilyRoot}carousel.ts`,
    sourceFiles: [
      `${carouselFamilyRoot}carousel-autoplay-toggle.vue`,
      `${carouselFamilyRoot}carousel-context.ts`,
      `${carouselFamilyRoot}carousel-geometry.ts`,
      `${carouselFamilyRoot}carousel-indicator-group.vue`,
      `${carouselFamilyRoot}carousel-indicator.vue`,
      `${carouselFamilyRoot}carousel-next.vue`,
      `${carouselFamilyRoot}carousel-previous.vue`,
      `${carouselFamilyRoot}carousel-root.vue`,
      `${carouselFamilyRoot}carousel-slide.vue`,
      `${carouselFamilyRoot}carousel-types.ts`,
      `${carouselFamilyRoot}carousel-viewport.vue`,
      `${carouselFamilyRoot}carousel.ts`,
    ],
    behaviorContract: `${carouselFamilyRoot}carousel.behavior.md`,
    tests: [
      `${carouselFamilyRoot}carousel.test.ts`,
      `${carouselFamilyRoot}carousel-ssr.test.ts`,
      `${carouselFamilyRoot}carousel-geometry.test.ts`,
    ],
    typeTests: [`${carouselFamilyRoot}carousel.types.test-d.ts`],
    rendererFixture: "CarouselConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "CarouselRoot",
      retainedSignature: "data-vize-ui[\\s\\S]{0,8}carousel-root",
      allowedRetainedFamilies: ["context", "controllable-state"],
      maximumJavaScriptGzipBytes: 3_450,
      maximumCssGzipBytes: 0,
    },
    aliases: ["carousel", "slider gallery", "slideshow", "image carousel", "content rotator"],
    upstreamCoverage: [
      "WAI-ARIA Carousel",
      "CSS Scroll Snap",
      "Ark UI Carousel",
      "Embla Carousel",
      "shadcn/ui Carousel",
    ],
    dependencies: ["context", "controllable-state", "id", "measure"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "image",
    title: "Image",
    packageSubpath: "./image",
    entryFile: `${imageFamilyRoot}image.ts`,
    sourceFiles: [
      `${imageFamilyRoot}image-content.vue`,
      `${imageFamilyRoot}image-context.ts`,
      `${imageFamilyRoot}image-fallback.vue`,
      `${imageFamilyRoot}image-placeholder.vue`,
      `${imageFamilyRoot}image-root.vue`,
      `${imageFamilyRoot}image-source.ts`,
      `${imageFamilyRoot}image-types.ts`,
      `${imageFamilyRoot}image.ts`,
    ],
    behaviorContract: `${imageFamilyRoot}image.behavior.md`,
    tests: [`${imageFamilyRoot}image.test.ts`, `${imageFamilyRoot}image-ssr.test.ts`],
    typeTests: [`${imageFamilyRoot}image.types.test-d.ts`],
    rendererFixture: "ImageConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ImageRoot",
      retainedSignature: "data-vize-ui[\\s\\S]{0,8}image-root",
      allowedRetainedFamilies: ["context", "measure"],
      maximumJavaScriptGzipBytes: 2_850,
      maximumCssGzipBytes: 0,
    },
    aliases: ["image", "img", "picture", "lazy image", "image fallback"],
    upstreamCoverage: [
      "HTML img",
      "Radix Avatar image loading status",
      "Chakra UI Image",
      "Next.js Image placeholder",
    ],
    dependencies: ["context", "measure"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
