/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Art descriptor for NAPI */
export interface ArtDescriptorNapi {
  filename: string;
  metadata: ArtMetadataNapi;
  variants: Array<ArtVariantNapi>;
  hasScriptSetup: boolean;
  hasScript: boolean;
  styleCount: number;
}

/** Art metadata for NAPI */
export interface ArtMetadataNapi {
  title: string;
  description?: string;
  component?: string;
  category?: string;
  tags: Array<string>;
  status: string;
  order?: number;
}

/** Art parse options for NAPI */
export interface ArtParseOptionsNapi {
  filename?: string;
}

/** Transform Art to Storybook CSF 3.0 */
export declare function artToCsf(
  source: string,
  options?: ArtParseOptionsNapi | undefined | null,
): CsfOutputNapi;

/** Art variant for NAPI */
export interface ArtVariantNapi {
  name: string;
  template: string;
  isDefault: boolean;
  skipVrt: boolean;
}

export interface AutogenConfigNapi {
  maxVariants?: number;
  includeDefault?: boolean;
  includeBooleanToggles?: boolean;
  includeEnumVariants?: boolean;
  includeBoundaryValues?: boolean;
  includeEmptyStrings?: boolean;
}

export interface AutogenOutputNapi {
  variants: Array<GeneratedVariantNapi>;
  artFileContent: string;
  componentName: string;
}

/** Batch compile options for NAPI */
export interface BatchCompileOptionsNapi {
  ssr?: boolean;
  vapor?: boolean;
  customRenderer?: boolean;
  /** Preserve TypeScript in output when true */
  isTs?: boolean;
  threads?: number;
}

/** Batch compile result for NAPI */
export interface BatchCompileResultNapi {
  /** Number of files compiled successfully */
  success: number;
  /** Number of files that failed */
  failed: number;
  /** Total input bytes */
  inputBytes: number;
  /** Total output bytes */
  outputBytes: number;
  /** Compilation time in milliseconds */
  timeMs: number;
}

/** Batch compile result with per-file results */
export interface BatchCompileResultWithFilesNapi {
  /** Per-file compilation results */
  results: Array<BatchFileResultNapi>;
  /** Number of files compiled successfully */
  successCount: number;
  /** Number of files that failed */
  failedCount: number;
  /** Compilation time in milliseconds */
  timeMs: number;
}

/** Input file for batch compilation with results */
export interface BatchFileInputNapi {
  /** File path */
  path: string;
  /** Source code */
  source: string;
}

/** Per-file result from batch compilation */
export interface BatchFileResultNapi {
  /** File path */
  path: string;
  /** Generated JavaScript code */
  code: string;
  /** Generated CSS (if any) */
  css?: string;
  /** Scope ID for scoped styles */
  scopeId: string;
  /** Whether the file has scoped styles */
  hasScoped: boolean;
  /** Compilation errors */
  errors: Array<string>;
  /** Compilation warnings */
  warnings: Array<string>;
  /** Hash of template content (for HMR) */
  templateHash?: string;
  /** Hash of style content (for HMR) */
  styleHash?: string;
  /** Hash of script content (for HMR) */
  scriptHash?: string;
  /** Compile-time macro artifacts */
  macroArtifacts: Array<MacroArtifactNapi>;
}

/** Batch type check result for NAPI */
export interface BatchTypeCheckResultNapi {
  filesChecked: number;
  filesWithErrors: number;
  totalErrors: number;
  totalWarnings: number;
  timeMs: number;
}

/** Catalog entry for NAPI */
export interface CatalogEntryNapi {
  title: string;
  description?: string;
  category?: string;
  tags: Array<string>;
  status: string;
  variantCount: number;
  docPath: string;
  sourcePath: string;
}

/** Catalog output for NAPI */
export interface CatalogOutputNapi {
  markdown: string;
  filename: string;
  componentCount: number;
  categories: Array<string>;
  tags: Array<string>;
}

/** Compile Vue template to VDom render function */
export declare function compile(
  template: string,
  options?: CompilerOptions | undefined | null,
): CompileResult;

/**
 * Compile a CSS string with scoped CSS, v-bind() extraction, and optional minification.
 * Unlike `compileSfc`, the `scopeId` is used as-is without stripping the "data-v-" prefix.
 * Callers must pass the full attribute name (e.g., "data-v-abc123").
 */
export declare function compileCss(
  source: string,
  options?: CssCompileOptionsNapi | undefined | null,
): CssCompileResultNapi;

/** Compile result */
export interface CompileResult {
  /** Generated code */
  code: string;
  /** Preamble code (imports) */
  preamble: string;
  /** AST (serialized as JSON) */
  ast: any;
  /** Source map */
  map?: any;
  /** Used helpers */
  helpers: Array<string>;
  /** Template strings for Vapor mode static parts */
  templates?: Array<string>;
}

/** Compiler options for bindings */
export interface CompilerOptions {
  /** Output mode: "module" or "function" */
  mode?: string;
  /** Whether to prefix identifiers */
  prefixIdentifiers?: boolean;
  /** Whether to hoist static nodes */
  hoistStatic?: boolean;
  /** Whether to cache event handlers */
  cacheHandlers?: boolean;
  /** Scope ID for scoped CSS */
  scopeId?: string;
  /** Whether in SSR mode */
  ssr?: boolean;
  /** Whether to generate source map */
  sourceMap?: boolean;
  /** Filename for source map */
  filename?: string;
  /** Output mode: "vdom" or "vapor" */
  outputMode?: string;
  /** Whether the template contains TypeScript */
  isTs?: boolean;
  /** Whether the template targets a custom renderer instead of the DOM. */
  customRenderer?: boolean;
  /**
   * Script extension handling: "preserve" (keep TypeScript) or "downcompile" (transpile to JS)
   * Defaults to "downcompile"
   */
  scriptExt?: string;
}

/** Compile SFC (.vue file) to JavaScript - main use case */
export declare function compileSfc(
  source: string,
  options?: SfcCompileOptionsNapi | undefined | null,
): SfcCompileResultNapi;

/** Batch compile SFC files matching a glob pattern (native multithreading) */
export declare function compileSfcBatch(
  pattern: string,
  options?: BatchCompileOptionsNapi | undefined | null,
): BatchCompileResultNapi;

/** Batch compile SFC files with per-file results (in-memory, native multithreading) */
export declare function compileSfcBatchWithResults(
  files: Array<BatchFileInputNapi>,
  options?: BatchCompileOptionsNapi | undefined | null,
): BatchCompileResultWithFilesNapi;

/** Compile Vue template to Vapor mode */
export declare function compileVapor(
  template: string,
  options?: CompilerOptions | undefined | null,
): CompileResult;

/** CSF output for NAPI */
export interface CsfOutputNapi {
  code: string;
  filename: string;
}

/** CSS compile options for NAPI */
export interface CssCompileOptionsNapi {
  /** Filename for error reporting */
  filename?: string;
  /** Whether to apply scoped CSS transformation */
  scoped?: boolean;
  /** Scope ID for scoped CSS (e.g., "data-v-abc123"). Must be the full attribute name. */
  scopeId?: string;
  /** Whether to generate source maps */
  sourceMap?: boolean;
  /** Whether to minify the output */
  minify?: boolean;
  /** Whether to enable CSS Modules transforms */
  cssModules?: boolean;
  /** Whether to enable custom media query resolution */
  customMedia?: boolean;
  /** Browser targets for autoprefixing */
  targets?: CssTargetsNapi;
}

/** CSS compile result for NAPI */
export interface CssCompileResultNapi {
  /** Compiled CSS code */
  code: string;
  /** Source map (if requested) */
  map?: string;
  /** CSS variables found (from v-bind()) */
  cssVars: Array<string>;
  /** Errors during compilation */
  errors: Array<string>;
  /** Warnings during compilation */
  warnings: Array<string>;
}

/** Browser targets for CSS autoprefixing */
export interface CssTargetsNapi {
  chrome?: number;
  firefox?: number;
  safari?: number;
  edge?: number;
  ios?: number;
  android?: number;
}

/** Declaration generation options for NAPI */
export interface DeclarationOptionsNapi {
  filename?: string;
}

/** Declaration generation result for NAPI */
export interface DeclarationResultNapi {
  code: string;
}

/** Doc options for NAPI */
export interface DocOptionsNapi {
  includeSource?: boolean;
  includeTemplates?: boolean;
  includeMetadata?: boolean;
  includeToc?: boolean;
  tocThreshold?: number;
  basePath?: string;
  title?: string;
}

/** Doc output for NAPI */
export interface DocOutputNapi {
  markdown: string;
  filename: string;
  title: string;
  category?: string;
  variantCount: number;
}

/** Format options for NAPI. */
export interface FormatOptionsNapi {
  printWidth?: number;
  tabWidth?: number;
  useTabs?: boolean;
  semi?: boolean;
  singleQuote?: boolean;
  sortAttributes?: boolean;
  singleAttributePerLine?: boolean;
  maxAttributesPerLine?: number;
  normalizeDirectiveShorthands?: boolean;
}

/** Format result for NAPI. */
export interface FormatResultNapi {
  code: string;
  changed: boolean;
}

/** Format a Vue SFC source string. */
export declare function formatSfc(
  source: string,
  options?: FormatOptionsNapi | undefined | null,
): FormatResultNapi;

/** Generate catalog from multiple Art sources (high-performance batch) */
export declare function generateArtCatalog(
  sources: Array<string>,
  docOptions?: DocOptionsNapi | undefined | null,
): CatalogOutputNapi;

/** Generate component documentation from Art source */
export declare function generateArtDoc(
  source: string,
  artOptions?: ArtParseOptionsNapi | undefined | null,
  docOptions?: DocOptionsNapi | undefined | null,
): DocOutputNapi;

/** Batch generate docs with parallel processing */
export declare function generateArtDocsBatch(
  sources: Array<string>,
  docOptions?: DocOptionsNapi | undefined | null,
): Array<DocOutputNapi>;

/** Generate props palette from Art source */
export declare function generateArtPalette(
  source: string,
  artOptions?: ArtParseOptionsNapi | undefined | null,
  paletteOptions?: PaletteOptionsNapi | undefined | null,
): PaletteOutputNapi;

/** Generate a Vue SFC `.d.ts` declaration from Croquis analysis. */
export declare function generateDeclaration(
  source: string,
  options?: DeclarationOptionsNapi | undefined | null,
): DeclarationResultNapi;

export interface GeneratedVariantNapi {
  name: string;
  isDefault: boolean;
  props: any;
  description?: string;
}

/** Generate .art.vue variants from component prop definitions */
export declare function generateVariants(
  componentPath: string,
  props: Array<PropDefinitionNapi>,
  config?: AutogenConfigNapi | undefined | null,
): AutogenOutputNapi;

/** Get Patina's currently registered rule metadata. */
export declare function getPatinaRules(): any;

/** Get type checking capabilities info */
export declare function getTypeCheckCapabilities(): TypeCheckCapabilitiesNapi;

/** Lint Vue SFC files matching patterns (native multithreading, .gitignore-aware) */
export declare function lint(
  patterns: Array<string>,
  options?: LintOptionsNapi | undefined | null,
): LintResultNapi;

/** Lint options for NAPI */
export interface LintOptionsNapi {
  /** Output format: "text" or "json" */
  format?: string;
  /** Maximum number of warnings before failing */
  maxWarnings?: number;
  /** Quiet mode - only show summary */
  quiet?: boolean;
  /** Automatically fix problems (not yet implemented) */
  fix?: boolean;
  /** Help display level: "full", "short", "none" */
  helpLevel?: string;
  /** Lint preset: "general-recommended", "essential", "incremental", "opinionated", or "nuxt" */
  preset?: string;
}

/** Lint a single Vue SFC with Patina and return structured diagnostics. */
export declare function lintPatinaSfc(
  source: string,
  options?: PatinaLintOptionsNapi | undefined | null,
): any;

/** Lint result for NAPI */
export interface LintResultNapi {
  /** Formatted output string */
  output: string;
  /** Total number of errors */
  errorCount: number;
  /** Total number of warnings */
  warningCount: number;
  /** Number of files linted */
  fileCount: number;
  /** Time in milliseconds */
  timeMs: number;
}

export interface MacroArtifactNapi {
  kind: string;
  name: string;
  source: string;
  content: string;
  moduleCode?: string;
  start: number;
  end: number;
}

/** Palette options for NAPI */
export interface PaletteOptionsNapi {
  inferOptions?: boolean;
  minSelectValues?: number;
  maxSelectValues?: number;
  groupByType?: boolean;
}

/** Palette output for NAPI */
export interface PaletteOutputNapi {
  title: string;
  controls: Array<PropControlNapi>;
  groups: Array<string>;
  json: string;
  typescript: string;
}

/** Parse Art file (*.art.vue) */
export declare function parseArt(
  source: string,
  options?: ArtParseOptionsNapi | undefined | null,
): ArtDescriptorNapi;

/** Parse SFC (.vue file) - returns lightweight result for speed */
export declare function parseSfc(
  source: string,
  options?: SfcParseOptionsNapi | undefined | null,
): any;

/** Parse template to AST only */
export declare function parseTemplate(
  template: string,
  options?: CompilerOptions | undefined | null,
): any;

/** Single-file Patina lint options for NAPI */
export interface PatinaLintOptionsNapi {
  /** Filename used for diagnostics */
  filename?: string;
  /** Locale code: "en", "ja", or "zh" */
  locale?: string;
  /** Help display level: "full", "short", or "none" */
  helpLevel?: string;
  /** Lint preset: "general-recommended", "essential", "incremental", "opinionated", or "nuxt" */
  preset?: string;
  /** Optional list of Patina rule names to enable */
  enabledRules?: Array<string>;
}

/** Prop control for NAPI */
export interface PropControlNapi {
  name: string;
  control: string;
  defaultValue?: any;
  description?: string;
  required: boolean;
  options: Array<SelectOptionNapi>;
  range?: RangeConfigNapi;
  group?: string;
}

export interface PropDefinitionNapi {
  name: string;
  propType: string;
  required: boolean;
  defaultValue?: any;
}

/** Range config for NAPI */
export interface RangeConfigNapi {
  min: number;
  max: number;
  step?: number;
}

/** Related location for diagnostic (NAPI) */
export interface RelatedLocationNapi {
  message: string;
  start: number;
  end: number;
  filename?: string;
}

/** Select option for NAPI */
export interface SelectOptionNapi {
  label: string;
  value: any;
}

/** SFC compile options for NAPI */
export interface SfcCompileOptionsNapi {
  filename?: string;
  sourceMap?: boolean;
  ssr?: boolean;
  vapor?: boolean;
  customRenderer?: boolean;
  /** Preserve TypeScript in output when true */
  isTs?: boolean;
  /** Scope ID for scoped CSS (e.g., "data-v-abc123") */
  scopeId?: string;
}

/** SFC compile result for NAPI */
export interface SfcCompileResultNapi {
  /** Generated JavaScript code */
  code: string;
  /** Generated CSS (if any) */
  css?: string;
  /** Compilation errors */
  errors: Array<string>;
  /** Compilation warnings */
  warnings: Array<string>;
  /** Hash of template content (for HMR) */
  templateHash?: string;
  /** Hash of style content (for HMR) */
  styleHash?: string;
  /** Hash of script content (for HMR) */
  scriptHash?: string;
  /** Compile-time macro artifacts */
  macroArtifacts: Array<MacroArtifactNapi>;
}

/** SFC parse options for NAPI */
export interface SfcParseOptionsNapi {
  filename?: string;
}

/**
 * Perform type checking on a Vue SFC
 *
 * This performs AST-based type analysis without requiring a TypeScript compiler.
 * For full type checking, use the CLI with Corsa integration.
 */
export declare function typeCheck(
  source: string,
  options?: TypeCheckOptionsNapi | undefined | null,
): TypeCheckResultNapi;

/** Batch type check SFC files matching a glob pattern (native multithreading) */
export declare function typeCheckBatch(
  pattern: string,
  options?: TypeCheckOptionsNapi | undefined | null,
): BatchTypeCheckResultNapi;

/** Type check capabilities result */
export interface TypeCheckCapabilitiesNapi {
  mode: string;
  description: string;
  checks: Array<TypeCheckCapabilityNapi>;
  notes: Array<string>;
}

/** Type check capabilities info */
export interface TypeCheckCapabilityNapi {
  name: string;
  description: string;
  severity: string;
}

/** Type check options for NAPI */
export interface TypeCheckOptionsNapi {
  filename?: string;
  strict?: boolean;
  includeVirtualTs?: boolean;
  checkProps?: boolean;
  checkEmits?: boolean;
  checkTemplateBindings?: boolean;
  checkReactivity?: boolean;
  checkSetupContext?: boolean;
  checkInvalidExports?: boolean;
  checkFallthroughAttrs?: boolean;
}

/** Type check result for NAPI */
export interface TypeCheckResultNapi {
  diagnostics: Array<TypeDiagnosticNapi>;
  virtualTs?: string;
  errorCount: number;
  warningCount: number;
  analysisTimeMs?: number;
}

/** Type diagnostic for NAPI */
export interface TypeDiagnosticNapi {
  severity: string;
  message: string;
  start: number;
  end: number;
  code?: string;
  help?: string;
  related: Array<RelatedLocationNapi>;
}
