import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "../../../family-catalog-types.ts";

export const feedbackCoreCatalog = [
  {
    canonicalName: "alert",
    title: "Alert",
    packageSubpath: "./alert",
    entryFile: "src/families/feedback/alert/alert.ts",
    sourceFiles: [
      "src/families/feedback/alert/alert.vue",
      "src/families/feedback/alert/alert.ts",
      "src/families/feedback/alert/alert-types.ts",
    ],
    behaviorContract: "src/families/feedback/alert/alert.behavior.md",
    tests: ["src/families/feedback/alert/alert.test.ts"],
    typeTests: ["src/families/feedback/alert/alert.types.test-d.ts"],
    rendererFixture: "families/feedback/alert/alert.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Alert",
      retainedSignature: 'data-vize-ui":(?:`alert`|"alert"|\'alert\')',
      maximumJavaScriptGzipBytes: 750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["inline alert", "status alert", "callout primitive"],
    upstreamCoverage: ["WAI-ARIA alert role", "WAI-ARIA status role", "shadcn/ui Alert"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "badge",
    title: "Badge",
    packageSubpath: "./badge",
    entryFile: "src/families/feedback/badge/badge.ts",
    sourceFiles: [
      "src/families/feedback/badge/badge.vue",
      "src/families/feedback/badge/badge.ts",
      "src/families/feedback/badge/badge-types.ts",
    ],
    behaviorContract: "src/families/feedback/badge/badge.behavior.md",
    tests: [
      "src/families/feedback/badge/badge.test.ts",
      "src/families/feedback/badge/badge-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/badge/badge.types.test-d.ts"],
    rendererFixture: "BadgeConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Badge",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}badge",
      maximumJavaScriptGzipBytes: 600,
      maximumCssGzipBytes: 0,
    },
    aliases: ["tag", "chip", "status badge", "count badge", "unread indicator"],
    upstreamCoverage: ["HTML span", "shadcn/ui Badge", "Radix Themes Badge", "Reka UI Primitive"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "banner",
    title: "Banner",
    packageSubpath: "./banner",
    entryFile: "src/families/feedback/banner/banner.ts",
    sourceFiles: [
      "src/families/feedback/banner/banner.vue",
      "src/families/feedback/banner/banner.ts",
      "src/families/feedback/banner/banner-aria.ts",
      "src/families/feedback/banner/banner-types.ts",
    ],
    behaviorContract: "src/families/feedback/banner/banner.behavior.md",
    tests: [
      "src/families/feedback/banner/banner.test.ts",
      "src/families/feedback/banner/banner-aria.test.ts",
      "src/families/feedback/banner/banner-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/banner/banner.types.test-d.ts"],
    rendererFixture: "BannerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Banner",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}banner",
      maximumJavaScriptGzipBytes: 4_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["announcement banner", "dismissible notice", "page notice", "status banner"],
    upstreamCoverage: [
      "WAI-ARIA region role",
      "WAI-ARIA status role",
      "WAI-ARIA alert role",
      "shadcn/ui Alert",
      "Vuetify Alert",
      "React Aria live regions",
    ],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "block-ui",
    title: "BlockUI",
    packageSubpath: "./block-ui",
    entryFile: "src/families/feedback/block-ui/block-ui.ts",
    sourceFiles: [
      "src/families/feedback/block-ui/block-ui.vue",
      "src/families/feedback/block-ui/block-ui.ts",
      "src/families/feedback/block-ui/block-ui-types.ts",
    ],
    behaviorContract: "src/families/feedback/block-ui/block-ui.behavior.md",
    tests: [
      "src/families/feedback/block-ui/block-ui.test.ts",
      "src/families/feedback/block-ui/block-ui-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/block-ui/block-ui.types.test-d.ts"],
    rendererFixture: "BlockUIConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "BlockUI",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}block-ui",
      maximumJavaScriptGzipBytes: 975,
      maximumCssGzipBytes: 0,
    },
    aliases: ["blocking overlay", "busy region", "pending region", "stale content", "offline gate"],
    upstreamCoverage: ["HTML inert attribute", "WAI-ARIA aria-busy", "WAI-ARIA status role"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
