#!/usr/bin/env rust-script
//! ```cargo
//! [package]
//! edition = "2024"
//!
//! [dependencies]
//! serde = { version = "1", features = ["derive"] }
//! serde_json = "1"
//! ```

use serde_json::Value;
use std::{collections::BTreeSet, process::ExitCode};

#[path = "../../support/common.rs"]
mod common;

const LINT_RULE_SNAPSHOT_REL: &str =
    "crates/vize_patina/src/preset/snapshots/vize_patina__preset__tests__lint_preset_rule_membership.snap";
const LINT_RULE_TYPES_REL: &str = "npm/cli/src/types/rules.ts";

fn main() -> ExitCode {
    common::main_result(run())
}

fn run() -> Result<(), String> {
    let root = common::repo_root()?;
    let snapshot = common::read_text(root.join(LINT_RULE_SNAPSHOT_REL))?;
    let json_body = snapshot_json_body(&snapshot)?;
    let parsed = serde_json::from_str(&json_body)
        .map_err(|_| "Failed to parse lint preset snapshot JSON".to_string())?;
    let rule_names = collect_rule_names(&parsed)?;
    common::write_text(
        root.join(LINT_RULE_TYPES_REL),
        &generate_output(&rule_names),
    )
}

fn snapshot_json_body(snapshot: &str) -> Result<String, String> {
    if !snapshot.starts_with("---\n") {
        return Err("Invalid insta snapshot format for lint preset rule membership".to_string());
    }

    let Some(frontmatter_end) = snapshot[4..].find("\n---\n").map(|index| index + 4) else {
        return Err("Invalid insta snapshot format for lint preset rule membership".to_string());
    };

    Ok(snapshot[frontmatter_end + "\n---\n".len()..].to_string())
}

fn collect_rule_names(value: &Value) -> Result<Vec<String>, String> {
    let presets = value
        .as_object()
        .ok_or_else(|| "Expected lint preset snapshot root to be an object".to_string())?;
    let mut rule_names = BTreeSet::new();

    for (preset, entries) in presets {
        let entries = entries
            .as_array()
            .ok_or_else(|| format!("Expected {preset} rules to be an array"))?;
        for entry in entries {
            let rule_name = entry
                .as_str()
                .ok_or_else(|| format!("Expected {preset} rule name to be a string"))?;
            rule_names.insert(rule_name.to_string());
        }
    }

    Ok(rule_names.into_iter().collect())
}

fn generate_output(rule_names: &[String]) -> String {
    let rule_entries = rule_names
        .iter()
        .map(|name| {
            format!(
                "  {},",
                serde_json::to_string(name).expect("string serialization")
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "// This file is generated by `rust-script tools/commands/generate/rule-types.rs`.\n\
         // Do not edit it by hand.\n\n\
         import type {{ RuleSeverity }} from \"./generated.js\";\n\n\
         export const LINT_RULE_NAMES = [\n\
         {rule_entries}\n\
         ] as const;\n\n\
         export type LintRuleName = (typeof LINT_RULE_NAMES)[number];\n\n\
         export type LintRulesConfig = Partial<Record<LintRuleName, RuleSeverity>>;\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_invalid_snapshot_frontmatter() {
        assert!(snapshot_json_body("{}").is_err());
        assert!(snapshot_json_body("---\nsource: test\n{}").is_err());
    }

    #[test]
    fn collects_sorted_unique_rule_names() {
        let value = serde_json::json!({
            "recommended": ["v-for-key", "no-unused-vars"],
            "strict": ["no-unused-vars", "valid-v-slot"]
        });

        assert_eq!(
            collect_rule_names(&value).unwrap(),
            vec![
                "no-unused-vars".to_string(),
                "v-for-key".to_string(),
                "valid-v-slot".to_string()
            ]
        );
    }
}
