import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { setupNuxtLintConfigGeneration } from "./generation.ts";

const dependencies = { hasTypeScript: () => false, resolvePluginSpecifier: () => "./plugin.mjs" };

function nuxt(rootDir: string) {
  return {
    options: { rootDir, buildDir: path.join(rootDir, ".nuxt"), srcDir: path.join(rootDir, "app") },
    hook() {},
  };
}

void test("explicit spellings of the reserved path preserve an authored collision", async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), "vize-nuxt-reserved-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const reserved = path.join(root, ".oxlint.vize.json");
  const authored = '{"rules":{"no-console":"off"}}\n';
  await writeFile(reserved, authored);
  for (const configFile of [undefined, ".oxlint.vize.json", "./.oxlint.vize.json", reserved]) {
    await assert.rejects(
      setupNuxtLintConfigGeneration({ configFile, autoInit: false }, nuxt(root), dependencies),
      { message: `Refusing to replace authored ${reserved}; choose a different lint.configFile` },
    );
    assert.equal(await readFile(reserved, "utf8"), authored);
  }
  await assert.rejects(readFile(path.join(root, "oxlint.config.mts")), { code: "ENOENT" });
});

void test("unsupported nested and sibling config placements leave all authored paths intact", async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), "vize-nuxt-placement-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const nested = path.join(root, ".nuxt/oxlint.config.json");
  await mkdir(path.dirname(nested));
  await writeFile(nested, "authored\n");
  for (const options of [
    { configFile: ".nuxt/oxlint.config.json" },
    { configFile: "generated/custom.json", rootDir: "packages/web" },
  ]) {
    await assert.rejects(
      setupNuxtLintConfigGeneration({ ...options, autoInit: false }, nuxt(root), dependencies),
      { message: "Generated oxlint config must be in the lint root or an ancestor directory" },
    );
  }
  assert.equal(await readFile(nested, "utf8"), "authored\n");
  await assert.rejects(readFile(path.join(root, "generated/custom.json")), { code: "ENOENT" });
  await assert.rejects(readFile(path.join(root, "oxlint.config.mts")), { code: "ENOENT" });
});

void test("only the exact previous generated loader migrates to the corrected root config", async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), "vize-nuxt-loader-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const wrapper = path.join(root, "oxlint.config.mts");
  const former = `// Generated by @vizejs/nuxt.
import { readFileSync } from "node:fs";

type OxlintJsPlugin = string | { name?: string; specifier: string };

const generatedUrl = new URL("./.nuxt/oxlint.config.json", import.meta.url);
const config = JSON.parse(readFileSync(generatedUrl, "utf8"));
config.jsPlugins = config.jsPlugins.map((plugin: OxlintJsPlugin) =>
  typeof plugin === "string"
    ? new URL(plugin, generatedUrl).href
    : { ...plugin, specifier: new URL(plugin.specifier, generatedUrl).href },
);

export default config;
`;
  await writeFile(wrapper, former);
  await setupNuxtLintConfigGeneration(true, nuxt(root), dependencies);
  assert.equal(
    await readFile(wrapper, "utf8"),
    former.replace("./.nuxt/oxlint.config.json", "./.oxlint.vize.json"),
  );
  const authored = former + "// authored extension\n";
  await writeFile(wrapper, authored);
  await setupNuxtLintConfigGeneration(true, nuxt(root), dependencies);
  assert.equal(await readFile(wrapper, "utf8"), authored);
});
