import assert from "node:assert/strict";
import { constants } from "node:fs";
import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  stat,
  symlink,
  utimes,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import type { TestContext } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  ROOT_OXLINT_CONFIG_NAMES,
  setupNuxtLintConfigGeneration,
  writeFileIfChanged,
} from "./generation.ts";

type Hook = (...args: unknown[]) => unknown;

function createNuxt(rootDir: string) {
  const hooks = new Map<string, Hook[]>();
  return {
    hooks,
    nuxt: {
      options: {
        rootDir,
        srcDir: path.join(rootDir, "app"),
        buildDir: path.join(rootDir, ".nuxt"),
        dir: {},
        _layers: [{ config: { srcDir: path.join(rootDir, "app") } }],
      },
      hook(name: string, callback: Hook) {
        const registered = hooks.get(name) ?? [];
        registered.push(callback);
        hooks.set(name, registered);
      },
    },
  };
}

async function callHooks(hooks: Map<string, Hook[]>, name: string): Promise<void> {
  for (const hook of hooks.get(name) ?? []) await hook();
}

async function absent(file: string): Promise<boolean> {
  try {
    await access(file, constants.F_OK);
    return false;
  } catch {
    return true;
  }
}

async function temporaryRoot(t: TestContext, prefix: string): Promise<string> {
  const root = await mkdtemp(path.join(os.tmpdir(), prefix));
  t.after(() => rm(root, { force: true, recursive: true }));
  return root;
}

void test("generation writes the whole artifact, auto-inits once, and skips unchanged rewrites", async (t) => {
  const root = await temporaryRoot(t, "vize-nuxt-lint-");
  const { hooks, nuxt } = createNuxt(root);

  await setupNuxtLintConfigGeneration(true, nuxt, {
    hasTypeScript: () => true,
    resolvePluginSpecifier: () => "../plugin.mjs",
  });

  const generated = path.join(root, ".nuxt", "oxlint.config.json");
  const rootConfig = path.join(root, "oxlint.config.mts");
  const initial = await readFile(generated, "utf8");
  assert.equal(initial, expectedDefaultArtifact());
  assert.equal(
    await readFile(rootConfig, "utf8"),
    `// Generated by @vizejs/nuxt.
import { readFileSync } from "node:fs";

type OxlintJsPlugin = string | { name?: string; specifier: string };

const generatedUrl = new URL("./.nuxt/oxlint.config.json", import.meta.url);
const config = JSON.parse(readFileSync(generatedUrl, "utf8"));
config.jsPlugins = config.jsPlugins.map((plugin: OxlintJsPlugin) =>
  typeof plugin === "string"
    ? new URL(plugin, generatedUrl).href
    : { ...plugin, specifier: new URL(plugin.specifier, generatedUrl).href },
);

export default config;
`,
  );

  const pinned = new Date("2001-02-03T04:05:06.000Z");
  await utimes(generated, pinned, pinned);
  await callHooks(hooks, "builder:generateApp");
  assert.equal((await stat(generated)).mtimeMs, pinned.getTime());
  assert.equal(await readFile(generated, "utf8"), initial);
  assert.equal(hooks.get("builder:generateApp")?.length, 1);
});

void test("regeneration resolves addons afresh and rewrites same-length changes", async (t) => {
  const root = await temporaryRoot(t, "vize-nuxt-lint-addons-");
  const { hooks, nuxt } = createNuxt(root);
  let globalName = "first1";

  await setupNuxtLintConfigGeneration({ autoInit: false }, nuxt, {
    hasTypeScript: () => false,
    resolvePluginSpecifier: () => "../plugin.mjs",
    resolveAddons: async () => [{ name: "nuxt/test-addon", globals: { [globalName]: "readonly" } }],
  });

  const generated = path.join(root, ".nuxt", "oxlint.config.json");
  const before = await readFile(generated, "utf8");
  globalName = "second";
  await callHooks(hooks, "builder:generateApp");
  const after = await readFile(generated, "utf8");

  assert.equal(before.length, after.length);
  assert.notEqual(after, before);
  assert.match(after, /"second": "readonly"/);
  assert.equal(await absent(path.join(root, "oxlint.config.mts")), true);
});

void test("resolved plans stay cached until an inspector requests a fresh plan", async (t) => {
  const root = await temporaryRoot(t, "vize-nuxt-lint-inspector-");
  const { nuxt } = createNuxt(root);
  let addonName = "nuxt/initial-addon";
  let resolutions = 0;
  const generation = await setupNuxtLintConfigGeneration({ autoInit: false }, nuxt, {
    resolvePluginSpecifier: () => "../plugin.mjs",
    resolveAddons() {
      resolutions += 1;
      return [{ name: addonName }];
    },
  });
  assert.ok(generation);

  addonName = "nuxt/fresh-addon";
  assert.equal((await generation.resolvePlan()).at(-1)?.name, "nuxt/initial-addon");
  assert.equal(resolutions, 1);
  assert.equal((await generation.resolvePlan(true)).at(-1)?.name, "nuxt/fresh-addon");
  assert.equal(resolutions, 2);
});

void test("auto-init preserves every supported existing root or ancestor config", async (t) => {
  for (const name of ROOT_OXLINT_CONFIG_NAMES) {
    const parent = await temporaryRoot(t, "vize-nuxt-lint-existing-");
    const root = path.join(parent, "project");
    await mkdir(root);
    const existing = path.join(parent, name);
    await writeFile(existing, "keep\n");
    const { nuxt } = createNuxt(root);

    await setupNuxtLintConfigGeneration(true, nuxt, {
      resolvePluginSpecifier: () => "../plugin.mjs",
    });

    assert.equal(await readFile(existing, "utf8"), "keep\n");
    assert.equal(await absent(path.join(root, "oxlint.config.mts")), true);
  }
});

void test("custom configFile and rootDir are resolved from the Nuxt root", async (t) => {
  const root = await temporaryRoot(t, "vize-nuxt-lint-custom-");
  const alternateRoot = path.join(root, "packages", "web");
  await mkdir(path.join(alternateRoot, "app"), { recursive: true });
  const { nuxt } = createNuxt(root);

  const result = await setupNuxtLintConfigGeneration(
    {
      autoInit: false,
      configFile: "generated/custom.json",
      rootDir: "packages/web",
    },
    nuxt,
    { resolvePluginSpecifier: () => "../plugin.mjs" },
  );

  assert.equal(result?.configFile, path.join(root, "generated", "custom.json"));
  assert.match(await readFile(result?.configFile ?? "", "utf8"), /"\.\.\/\.\.\/app\/pages/);
});

void test("default plugin resolution remains relative to the generated artifact", async (t) => {
  const root = await temporaryRoot(t, "vize-nuxt-lint-plugin-");
  const { nuxt } = createNuxt(root);
  const result = await setupNuxtLintConfigGeneration({ autoInit: false }, nuxt);
  const artifact = JSON.parse(await readFile(result?.configFile ?? "", "utf8")) as {
    jsPlugins: Array<{ specifier: string }>;
  };
  const resolvedEntry = fileURLToPath(
    new URL(artifact.jsPlugins[0].specifier, pathToFileURL(result?.configFile ?? "")),
  );

  assert.equal(resolvedEntry, fileURLToPath(import.meta.resolve("oxlint-plugin-vize")));
});

void test("write-if-changed refuses to follow a generated-file symlink", async (t) => {
  const root = await temporaryRoot(t, "vize-nuxt-lint-link-");
  const target = path.join(root, "target.json");
  const generated = path.join(root, "generated.json");
  await writeFile(target, "keep\n");
  await symlink(target, generated);

  await assert.rejects(writeFileIfChanged(generated, "replace\n"), /regular file/);
  assert.equal(await readFile(target, "utf8"), "keep\n");
});

function expectedDefaultArtifact(): string {
  return `{
  "plugins": [
    "vue"
  ],
  "jsPlugins": [
    {
      "name": "vize",
      "specifier": "../plugin.mjs"
    }
  ],
  "settings": {
    "vize": {
      "preset": "incremental"
    }
  },
  "ignorePatterns": [
    "**/dist",
    "**/node_modules",
    "**/.nuxt",
    "**/.output",
    "**/.vercel",
    "**/.netlify",
    "**/public"
  ],
  "globals": {
    "$fetch": "readonly"
  },
  "rules": {
    "vize/nuxt/prefer-import-meta": "error"
  },
  "overrides": [
    {
      "files": [
        "app/components/**/*.server.{js,ts,jsx,tsx,vue}",
        "app/layouts/**/*.{js,ts,jsx,tsx,vue}",
        "app/pages/**/*.{js,ts,jsx,tsx,vue}"
      ],
      "rules": {
        "vize/vue/no-multiple-template-root": "error"
      }
    },
    {
      "files": [
        "app/pages/**/*.{js,ts,jsx,tsx,vue}"
      ],
      "rules": {
        "vize/nuxt/no-page-meta-runtime-values": "error"
      }
    },
    {
      "files": [
        "**/.config/nuxt.?([cm])[jt]s?(x)",
        "**/nuxt.config.?([cm])[jt]s?(x)"
      ],
      "rules": {
        "vize/nuxt/no-nuxt-config-test-key": "error"
      }
    },
    {
      "files": [
        "app/app.{js,ts,jsx,tsx,vue}",
        "app/components/*/**/*.{js,ts,jsx,tsx,vue}",
        "app/error.{js,ts,jsx,tsx,vue}",
        "app/layouts/**/*.{js,ts,jsx,tsx,vue}",
        "app/pages/**/*.{js,ts,jsx,tsx,vue}"
      ],
      "rules": {
        "vize/vue/multi-word-component-names": "off"
      }
    }
  ]
}
`;
}
