//! Span-carrying text for emitters that assemble code off-buffer (P3-9, S4).
//!
//! The DOM codegen writes straight into its code buffer and records spans as it
//! goes. SSR and Vapor build pieces of code (template-literal parts, prop
//! objects, template strings) before they know where those pieces will land.
//! [`SpannedText`] carries those pieces together with the authored spans of
//! the tokens they copy; when a piece is finally written, its anchors are
//! rebased onto the generated offset and handed to the shared
//! [`SourceMapBuilder`]. The text itself is exactly what a plain string would
//! hold, so emitted bytes never depend on whether maps are requested.

use vize_s0::{Span, String};

use super::rewrite_spans::rewritten_identifier_spans;
use super::source_map::SourceMapBuilder;

/// One authored anchor inside a piece of generated text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpanAnchor {
    /// Byte offset inside the generated text.
    pub offset: usize,
    /// Authored byte offset the generated bytes at `offset` come from.
    pub source: u32,
    /// Authored symbol, for identifier anchors.
    pub name: Option<String>,
}

/// Generated text plus the authored anchors of the tokens it copies.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SpannedText {
    text: String,
    anchors: Vec<SpanAnchor>,
}

impl SpannedText {
    /// Text with no authored anchors.
    pub fn plain(text: &str) -> Self {
        Self {
            text: String::new(text),
            anchors: Vec::new(),
        }
    }

    /// Text copied from the authored byte `source`.
    pub fn mapped(text: &str, source: u32) -> Self {
        let mut spanned = Self::default();
        spanned.push_mapped(text, source);
        spanned
    }

    pub fn as_str(&self) -> &str {
        &self.text
    }

    /// The generated text, dropping the anchors.
    pub fn into_string(self) -> String {
        self.text
    }

    pub fn anchors(&self) -> &[SpanAnchor] {
        &self.anchors
    }

    /// Append unanchored text.
    pub fn push_str(&mut self, text: &str) {
        self.text.push_str(text);
    }

    /// Append text whose first byte comes from the authored byte `source`.
    pub fn push_mapped(&mut self, text: &str, source: u32) {
        self.anchors.push(SpanAnchor {
            offset: self.text.len(),
            source,
            name: None,
        });
        self.text.push_str(text);
    }

    /// Append an emitted expression authored at `span` of `source_text`, with
    /// its whole-expression and rewritten-identifier anchors.
    pub fn push_expression(&mut self, code: &str, span: Span, source_text: &str) {
        let base = self.text.len();
        self.anchors
            .extend(
                expression_anchors(code, span, source_text)
                    .into_iter()
                    .map(|anchor| SpanAnchor {
                        offset: base + anchor.offset,
                        ..anchor
                    }),
            );
        self.text.push_str(code);
    }

    /// Append another piece, rebasing its anchors.
    pub fn push_spanned(&mut self, other: &SpannedText) {
        let base = self.text.len();
        self.anchors
            .extend(other.anchors.iter().map(|anchor| SpanAnchor {
                offset: base + anchor.offset,
                ..anchor.clone()
            }));
        self.text.push_str(&other.text);
    }
}

/// A text sink that may record authored anchors.
///
/// Emitters write through this trait once: a plain [`String`] sink ignores the
/// anchors (the no-map path pays nothing), and a [`SpannedText`] sink keeps
/// them, so both produce the same bytes by construction.
pub trait SpanSink {
    /// Append unanchored text.
    fn push_plain(&mut self, text: &str);
    /// Append text whose first byte comes from the authored byte `source`.
    fn push_at(&mut self, text: &str, source: u32);
}

impl SpanSink for String {
    #[inline]
    fn push_plain(&mut self, text: &str) {
        self.push_str(text);
    }

    #[inline]
    fn push_at(&mut self, text: &str, _source: u32) {
        self.push_str(text);
    }
}

impl SpanSink for SpannedText {
    #[inline]
    fn push_plain(&mut self, text: &str) {
        self.push_str(text);
    }

    #[inline]
    fn push_at(&mut self, text: &str, source: u32) {
        self.push_mapped(text, source);
    }
}

impl From<String> for SpannedText {
    fn from(text: String) -> Self {
        Self {
            text,
            anchors: Vec::new(),
        }
    }
}

/// Anchors for an emitted expression authored at `span`: every identifier
/// the context rewrite scoped (named, see [`rewritten_identifier_spans`]) plus
/// the whole-expression anchor unless an identifier already covers its first
/// byte. An expression without an authored span (the empty stub location of a
/// synthesized node) has no anchors.
pub fn expression_anchors(code: &str, span: Span, source_text: &str) -> Vec<SpanAnchor> {
    if span.start >= span.end {
        return Vec::new();
    }
    let mut anchors = Vec::new();
    let authored = source_text.get(span.start as usize..span.end as usize);
    if let Some(identifiers) =
        authored.and_then(|authored| rewritten_identifier_spans(authored, code))
    {
        anchors.extend(identifiers.into_iter().map(|identifier| SpanAnchor {
            offset: identifier.emitted,
            source: span.start + identifier.authored as u32,
            name: Some(String::new(identifier.name)),
        }));
    }
    let covers_start = anchors
        .first()
        .is_some_and(|anchor| anchor.offset == 0 && anchor.source == span.start);
    if !covers_start {
        anchors.insert(
            0,
            SpanAnchor {
                offset: 0,
                source: span.start,
                name: None,
            },
        );
    }
    anchors
}

impl SourceMapBuilder {
    /// Record `anchors` for text written at the generated byte offset `base`.
    pub fn add_anchors(&mut self, base: usize, anchors: &[SpanAnchor]) {
        for anchor in anchors {
            match &anchor.name {
                Some(name) => self.add_named(base + anchor.offset, anchor.source, name),
                None => self.add_raw(base + anchor.offset, anchor.source),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{SpanAnchor, SpannedText, expression_anchors};
    use vize_s0::{Span, String};

    fn anchor(offset: usize, source: u32, name: Option<&str>) -> SpanAnchor {
        SpanAnchor {
            offset,
            source,
            name: name.map(String::new),
        }
    }

    #[test]
    fn expression_anchors_name_rewrites_and_keep_the_expression_start() {
        let source = "{{ a + b }} {{ 1 + c }}";
        assert_eq!(
            expression_anchors("_ctx.a + _ctx.b", Span::new(3, 8), source),
            vec![anchor(0, 3, Some("a")), anchor(9, 7, Some("b"))]
        );
        assert_eq!(
            expression_anchors("1 + _ctx.c", Span::new(15, 20), source),
            vec![anchor(0, 15, None), anchor(4, 19, Some("c"))]
        );
        assert_eq!(expression_anchors("x", Span::new(0, 0), source), vec![]);
    }

    #[test]
    fn spanned_pieces_rebase_their_anchors() {
        let source = "<p :title=\"t\">";
        let mut value = SpannedText::plain("_ssrRenderAttr(\"");
        value.push_mapped("title", 4);
        value.push_str("\", ");
        value.push_expression("_ctx.t", Span::new(11, 12), source);
        value.push_str(")");
        let mut part = SpannedText::plain("<p");
        part.push_spanned(&value);
        assert_eq!(part.as_str(), "<p_ssrRenderAttr(\"title\", _ctx.t)");
        assert_eq!(
            part.anchors(),
            [anchor(18, 4, None), anchor(26, 11, Some("t"))]
        );
    }
}
