import type { ComposableProbeMap } from "./probe-types.ts";

/** Conformance probes for catalog entries in group A (test-only). */
export const probesGroupA: ComposableProbeMap = {
  "./abort-signal": {
    kind: "component",
    setup: [
      'import { anyAbortSignal, deadlineAbortSignal, timeoutAbortSignal } from "@/abort-signal.ts";',
      "const controller = new AbortController();",
      "const any = anyAbortSignal([controller.signal]);",
      "const timeout = timeoutAbortSignal(60_000);",
      "const deadline = deadlineAbortSignal(Date.now() + 60_000);",
      "const aborted = { any: any.aborted, timeout: timeout.aborted, deadline: deadline.aborted };",
    ].join("\n"),
    state: "aborted",
    server: { any: false, timeout: false, deadline: false },
    client: { any: false, timeout: false, deadline: false },
  },
  "./active-element": {
    kind: "component",
    setup: [
      'import { computed } from "vue";',
      'import { useActiveElement } from "@/active-element.ts";',
      "const active = useActiveElement();",
      "const tag = computed(() => active.value?.tagName.toLowerCase() ?? null);",
    ].join("\n"),
    state: "{ tag }",
    server: { tag: null },
    client: { tag: "body" },
  },
  "./animate": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useAnimate } from "@/animate.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { isSupported, playbackRate } = useAnimate(target, [{ opacity: 0 }, { opacity: 1 }], {",
      "  duration: 1000,",
      "  immediate: false,",
      "});",
    ].join("\n"),
    state: "{ isSupported, playbackRate }",
    markup: '<div ref="target"></div>',
    server: { isSupported: false, playbackRate: 1 },
  },
  "./async-resource": {
    kind: "component",
    setup: [
      'import { useAsyncResource } from "@/async-resource.ts";',
      "const { data, status } = useAsyncResource(async () => 42, { initialData: 0 });",
    ].join("\n"),
    state: "{ data, status }",
    server: { data: 0, status: "idle" },
    client: { data: 0, status: "idle" },
  },
  "./battery": {
    kind: "component",
    setup: [
      'import { useBattery } from "@/battery.ts";',
      "const { isSupported, charging, level } = useBattery();",
    ].join("\n"),
    state: "{ isSupported, charging, level }",
    server: { isSupported: false, charging: true, level: 1 },
  },
  "./breakpoints": {
    kind: "component",
    setup: [
      'import { breakpointsTailwind, toPixels, useBreakpoints } from "@/breakpoints.ts";',
      "const breakpoints = useBreakpoints(breakpointsTailwind);",
      'const md = breakpoints.greaterOrEqual("md");',
      "const current = breakpoints.current;",
      'const pixels = toPixels("2rem");',
    ].join("\n"),
    state: "{ md, current, pixels }",
    server: { md: false, current: [], pixels: 32 },
    client: { md: true, current: ["sm", "md", "lg"], pixels: 32 },
  },
  "./capability": {
    kind: "component",
    setup: [
      'import { availableCapability, isCapabilityAvailable, isCapabilityUnavailable, unavailableCapability } from "@/capability.ts";',
      "const available = availableCapability(1);",
      'const missing = unavailableCapability("unsupported");',
      "const flags = [isCapabilityAvailable(available), isCapabilityUnavailable(missing)];",
    ].join("\n"),
    state: "{ available, missing, flags }",
    server: {
      available: { status: "available", available: true, value: 1, source: "runtime" },
      missing: { status: "unavailable", available: false, reason: "unsupported", details: null },
      flags: [true, true],
    },
  },
  "./catalog": {
    kind: "exempt",
    reason: "Serializable package metadata only; it has no reactive or host behavior to mount.",
  },
  "./color-mode": {
    kind: "component",
    setup: [
      'import { useColorMode, useDark } from "@/color-mode.ts";',
      'if (typeof window !== "undefined") window.localStorage.setItem("probe-color-mode", "dark");',
      "const { mode, state, stored } = useColorMode({",
      '  storageKey: "probe-color-mode",',
      '  attribute: "data-probe-mode",',
      "});",
      "const dark = useDark({ storageKey: null });",
    ].join("\n"),
    state: "{ mode, state, stored, dark }",
    server: { mode: "auto", state: "light", stored: "auto", dark: false },
    client: { mode: "dark", state: "dark", stored: "dark", dark: false },
  },
  "./computed-async": {
    kind: "component",
    setup: [
      'import { computedAsync } from "@/computed-async.ts";',
      "const value = computedAsync(async () => 2, 1);",
    ].join("\n"),
    state: "{ value }",
    server: { value: 1 },
    client: { value: 2 },
  },
  "./computed-with-control": {
    kind: "component",
    setup: [
      'import { ref } from "vue";',
      'import { computedWithControl } from "@/computed-with-control.ts";',
      "const source = ref(1);",
      "const doubled = computedWithControl(source, () => source.value * 2);",
    ].join("\n"),
    state: "{ doubled }",
    server: { doubled: 2 },
    client: { doubled: 2 },
  },
  "./create-event-hook": {
    kind: "component",
    setup: [
      'import { ref } from "vue";',
      'import { createEventHook } from "@/create-event-hook.ts";',
      "const hook = createEventHook<[number]>();",
      "const received = ref(0);",
      "hook.on((value) => {",
      "  received.value = value;",
      "});",
      "const size = hook.size();",
    ].join("\n"),
    state: "{ size, received }",
    server: { size: 1, received: 0 },
    client: { size: 1, received: 0 },
  },
  "./create-global-state": {
    kind: "component",
    setup: [
      'import { ref } from "vue";',
      'import { createGlobalState } from "@/create-global-state.ts";',
      "const useShared = createGlobalState(() => ref(7));",
      "const same = useShared() === useShared();",
      "const value = useShared();",
    ].join("\n"),
    state: "{ same, value }",
    server: { same: true, value: 7 },
    client: { same: true, value: 7 },
  },
  "./create-injection-state": {
    kind: "component",
    setup: [
      'import { ref } from "vue";',
      'import { createInjectionState } from "@/create-injection-state.ts";',
      "const [useProvide, useInjected] = createInjectionState((initial: number) => ref(initial));",
      "const provided = useProvide(3);",
      "// A component cannot inject its own provide; the consumer half is only type-checked here.",
      "void useInjected;",
    ].join("\n"),
    state: "{ provided }",
    server: { provided: 3 },
    client: { provided: 3 },
  },
  "./create-shared-composable": {
    kind: "component",
    setup: [
      'import { ref } from "vue";',
      'import { createSharedComposable } from "@/create-shared-composable.ts";',
      "let calls = 0;",
      "const useShared = createSharedComposable(() => {",
      "  calls += 1;",
      "  return ref(calls);",
      "});",
      "// The server never shares state between calls (it would leak across requests),",
      "// so only the first call's value is rendered.",
      "const first = useShared();",
    ].join("\n"),
    state: "{ first }",
    server: { first: 1 },
    client: { first: 1 },
  },
  "./device-motion": {
    kind: "component",
    setup: [
      'import { useDeviceMotion } from "@/device-motion.ts";',
      "const { isSupported, acceleration, interval } = useDeviceMotion();",
    ].join("\n"),
    state: "{ isSupported, acceleration, interval }",
    server: { isSupported: false, acceleration: null, interval: 0 },
    client: { isSupported: true, acceleration: null, interval: 0 },
  },
  "./device-orientation": {
    kind: "component",
    setup: [
      'import { useDeviceOrientation } from "@/device-orientation.ts";',
      "const { isSupported, alpha, beta, gamma } = useDeviceOrientation();",
    ].join("\n"),
    state: "{ isSupported, alpha, beta, gamma }",
    server: { isSupported: false, alpha: null, beta: null, gamma: null },
    client: { isSupported: true, alpha: null, beta: null, gamma: null },
  },
  "./device-pixel-ratio": {
    kind: "component",
    setup: [
      'import { useDevicePixelRatio } from "@/device-pixel-ratio.ts";',
      "const { pixelRatio, isSupported } = useDevicePixelRatio({ ssrPixelRatio: 2 });",
    ].join("\n"),
    state: "{ pixelRatio, isSupported }",
    server: { pixelRatio: 2, isSupported: false },
    client: { pixelRatio: 1, isSupported: true },
  },
  "./disposal-scope": {
    kind: "component",
    setup: [
      'import { createDisposalScope } from "@/disposal-scope.ts";',
      "const scope = createDisposalScope();",
      "scope.add(() => undefined);",
      "const size = scope.size;",
      "const disposed = scope.disposed;",
    ].join("\n"),
    state: "{ size, disposed }",
    server: { size: 1, disposed: false },
    client: { size: 1, disposed: false },
  },
  "./document-visibility": {
    kind: "component",
    setup: [
      'import { useDocumentVisibility } from "@/document-visibility.ts";',
      "const { state, supported } = useDocumentVisibility();",
    ].join("\n"),
    state: "{ state, supported }",
    server: { state: "visible", supported: false },
    client: { state: "visible", supported: true },
  },
  "./draggable": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useDraggable } from "@/draggable.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { x, y, isDragging, style } = useDraggable(target, { initialValue: { x: 10, y: 20 } });",
    ].join("\n"),
    state: "{ x, y, isDragging, style }",
    markup: '<div ref="target"></div>',
    server: { x: 10, y: 20, isDragging: false, style: "left:10px;top:20px;" },
    client: { x: 10, y: 20, isDragging: false, style: "left:10px;top:20px;" },
  },
  "./element-bounding": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useElementBounding } from "@/element-bounding.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { width, height, top } = useElementBounding(target);",
    ].join("\n"),
    state: "{ width, height, top }",
    markup: '<div ref="target"></div>',
    server: { width: 0, height: 0, top: 0 },
    client: { width: 0, height: 0, top: 0 },
  },
  "./element-by-point": {
    kind: "component",
    setup: [
      'import { computed } from "vue";',
      'import { useElementByPoint } from "@/element-by-point.ts";',
      "const { isSupported, element } = useElementByPoint({ x: 0, y: 0 });",
      "const found = computed(() => element.value !== null);",
    ].join("\n"),
    state: "{ isSupported, found }",
    server: { isSupported: false, found: false },
    // happy-dom performs no layout, so no element is ever hit at a point.
    client: { isSupported: true, found: false },
  },
  "./element-hover": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useElementHover } from "@/element-hover.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const hovered = useElementHover(target);",
    ].join("\n"),
    state: "{ hovered }",
    markup: '<div ref="target"></div>',
    server: { hovered: false },
    client: { hovered: false },
  },
  "./element-ref": {
    kind: "component",
    setup: [
      'import { computed } from "vue";',
      'import { useElementRef } from "@/element-ref.ts";',
      "const { element, setRef } = useElementRef();",
      "const tag = computed(() => element.value?.tagName.toLowerCase() ?? null);",
    ].join("\n"),
    state: "{ tag }",
    markup: '<span :ref="setRef"></span>',
    server: { tag: null },
    client: { tag: "span" },
  },
  "./element-target": {
    kind: "component",
    setup: [
      'import { computed, useTemplateRef } from "vue";',
      'import { isElementNode, resolveElement, resolveElements } from "@/element-target.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const resolved = computed(() => ({",
      "  single: resolveElement(target)?.tagName.toLowerCase() ?? null,",
      "  count: resolveElements(target).length,",
      "  node: isElementNode(target.value),",
      "}));",
    ].join("\n"),
    state: "resolved",
    markup: '<p ref="target"></p>',
    server: { single: null, count: 0, node: false },
    client: { single: "p", count: 1, node: true },
  },
  "./event-listener": {
    kind: "component",
    setup: [
      'import { useEventListener } from "@/event-listener.ts";',
      'const target = typeof window === "undefined" ? null : window;',
      'const { isListening } = useEventListener(() => (typeof window === "undefined" ? null : window), "resize", () => undefined);',
      "void target;",
    ].join("\n"),
    state: "{ isListening }",
    server: { isListening: false },
    client: { isListening: true },
  },
  "./focus": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useFocus, useFocusWithin } from "@/focus.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { focused } = useFocus(target);",
      "const { focused: within } = useFocusWithin(target);",
    ].join("\n"),
    state: "{ focused, within }",
    markup: '<button ref="target" type="button">Focus</button>',
    server: { focused: false, within: false },
    client: { focused: false, within: false },
  },
  "./fps": {
    kind: "component",
    setup: [
      'import { computed } from "vue";',
      'import { useFps } from "@/fps.ts";',
      "const { fps, isSupported, isActive } = useFps();",
      "// The measured rate depends on the host clock; only its sign is rendered.",
      "const measuring = computed(() => fps.value >= 0);",
    ].join("\n"),
    state: "{ measuring, isSupported, isActive }",
    server: { measuring: true, isSupported: false, isActive: true },
    client: { measuring: true, isSupported: true, isActive: true },
  },
  "./geolocation": {
    kind: "component",
    setup: [
      'import { useGeolocation } from "@/geolocation.ts";',
      "const { isSupported, latitude, longitude } = useGeolocation();",
    ].join("\n"),
    state: "{ isSupported, latitude, longitude }",
    server: { isSupported: false, latitude: null, longitude: null },
    client: { isSupported: true, latitude: null, longitude: null },
  },
  "./idle": {
    kind: "component",
    setup: [
      'import { useIdle } from "@/idle.ts";',
      "const { idle, lastActive } = useIdle(60_000, { now: () => 1_000 });",
    ].join("\n"),
    state: "{ idle, lastActive }",
    server: { idle: false, lastActive: null },
    client: { idle: false, lastActive: 1000 },
  },
  "./infinite-scroll": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useInfiniteScroll } from "@/infinite-scroll.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { isLoading } = useInfiniteScroll(target, () => undefined, { distance: 10 });",
    ].join("\n"),
    state: "{ isLoading }",
    markup: '<div ref="target"></div>',
    server: { isLoading: false },
  },
  "./intersection-observer": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useElementVisibility, useIntersectionObserver } from "@/intersection-observer.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { isSupported, isActive } = useIntersectionObserver(target, () => undefined);",
      "const { isVisible } = useElementVisibility(target);",
    ].join("\n"),
    state: "{ isSupported, isActive, isVisible }",
    markup: '<div ref="target"></div>',
    server: { isSupported: false, isActive: true, isVisible: false },
    client: { isSupported: true, isActive: true, isVisible: false },
  },
  "./locale": {
    kind: "component",
    setup: [
      'import { useLocale } from "@/locale.ts";',
      'const { locale, direction } = useLocale("ar-EG");',
      'const number = useLocale("en-US").number().format(1234.5);',
    ].join("\n"),
    state: "{ locale, direction, number }",
    server: { locale: "ar-EG", direction: "rtl", number: "1,234.5" },
    client: { locale: "ar-EG", direction: "rtl", number: "1,234.5" },
  },
  "./magic-keys": {
    kind: "component",
    setup: [
      'import { computed } from "vue";',
      'import { normalizeKeyName, useKeyPressed, useMagicKeys } from "@/magic-keys.ts";',
      "const keys = useMagicKeys();",
      'const shift = useKeyPressed("shift");',
      "const current = computed(() => [...keys.current]);",
      'const normalized = normalizeKeyName("Control");',
    ].join("\n"),
    state: "{ current, shift, normalized }",
    server: { current: [], shift: false, normalized: "control" },
    client: { current: [], shift: false, normalized: "control" },
  },
  "./math": {
    kind: "component",
    setup: [
      'import { useClamp, useProjection, useRound } from "@/math.ts";',
      "const clamped = useClamp(15, 0, 10);",
      "const rounded = useRound(1.25, { precision: 1 });",
      "const projected = useProjection(5, [0, 10], [0, 100]);",
    ].join("\n"),
    state: "{ clamped, rounded, projected }",
    server: { clamped: 10, rounded: 1.3, projected: 50 },
    client: { clamped: 10, rounded: 1.3, projected: 50 },
  },
  "./mouse": {
    kind: "component",
    setup: [
      'import { useMouse } from "@/mouse.ts";',
      "const { x, y, sourceType } = useMouse({ initialValue: { x: 1, y: 2 } });",
    ].join("\n"),
    state: "{ x, y, sourceType }",
    server: { x: 1, y: 2, sourceType: null },
    client: { x: 1, y: 2, sourceType: null },
  },
  "./mouse-in-element": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useMouseInElement } from "@/mouse-in-element.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { isOutside, elementWidth } = useMouseInElement(target);",
    ].join("\n"),
    state: "{ isOutside, elementWidth }",
    markup: '<div ref="target"></div>',
    server: { isOutside: true, elementWidth: 0 },
    client: { isOutside: true, elementWidth: 0 },
  },
  "./mutation-observer": {
    kind: "component",
    setup: [
      'import { useTemplateRef } from "vue";',
      'import { useMutationObserver } from "@/mutation-observer.ts";',
      'const target = useTemplateRef<HTMLElement>("target");',
      "const { isSupported } = useMutationObserver(target, () => undefined, { attributes: true });",
    ].join("\n"),
    state: "{ isSupported }",
    markup: '<div ref="target"></div>',
    server: { isSupported: false },
    client: { isSupported: true },
  },
};
