//! Assemble prepared script and target fragments into one SFC module.
//!
//! The script lane rewrites its default export and supplies a component binding.
//! The target supplies hoists/cache declarations and either a declared render
//! function or an inline render expression. This module never parses or rewrites
//! JavaScript. It joins their writers, preserving every authored link, then
//! builds helper imports from the complete used-helper set. Runtime vocabulary
//! tables and target generation remain separate providers (#6840).

use crate::runtime::{Helper, Vocabulary};
use crate::write::{Emitted, LinkSink, Writer};

/// The component field a declared render function implements.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RenderProperty {
    Render,
    SsrRender,
}

impl RenderProperty {
    const fn name(self) -> &'static str {
        match self {
            Self::Render => "render",
            Self::SsrRender => "ssrRender",
        }
    }
}

/// How the target's prepared render fragment joins the component.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RenderPlacement<'a> {
    /// No template; there must be no render fragment.
    None,
    /// A complete function declaration, attached to the component afterwards.
    /// `binding` is the generated JavaScript identifier of that declaration.
    Function {
        binding: &'a str,
        property: RenderProperty,
    },
    /// An expression inserted between the script lane's prepared fragments.
    /// The script lane owns `setup()`, `return` and all surrounding punctuation.
    Inline,
}

/// The authored script, already rewritten and linked by the script lane.
#[derive(Debug)]
pub enum ScriptPart<L: LinkSink> {
    /// A script defining the component binding, with no default export.
    Body(Writer<L>),
    /// Script output around the inline render expression. These fragments are
    /// concatenated without added whitespace, so `return` semantics are kept.
    Inline {
        before_render: Writer<L>,
        after_render: Writer<L>,
    },
}

/// Prepared pieces of one module, in their final emission order.
#[derive(Debug)]
pub struct ModuleParts<'a, L: LinkSink> {
    /// The vocabulary used by every fragment. Helpers are imported as `_name`.
    /// Names must be distinct JavaScript identifiers; fragments use that alias.
    pub vocabulary: &'a Vocabulary,
    /// Linked hoists and cache declarations, already generated by the target.
    pub prelude: Option<Writer<L>>,
    /// Rewritten script. Without one, assembly declares `const component = {}`.
    pub script: Option<ScriptPart<L>>,
    /// A complete declared function or an inline expression, as specified below.
    pub render: Option<Writer<L>>,
    pub placement: RenderPlacement<'a>,
    /// The generated JavaScript identifier defined by the script lane.
    pub component: &'a str,
}

/// A mismatch between prepared fragments and their declared contracts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssemblyError {
    MissingRender,
    UnexpectedRender,
    MissingInlineScript,
    UnexpectedInlineScript,
    UnknownHelper(Helper),
    InvalidModuleSpecifier,
}

/// Assemble one module without inserting text into any fragment.
///
/// Generated identifiers and fragment syntax belong to their providers. The
/// assembler checks placement and helper membership; it does not admit targets
/// or claim native product coverage. Its returned links cover the whole module.
pub fn assemble<L: LinkSink>(parts: ModuleParts<'_, L>) -> Result<Emitted<L>, AssemblyError> {
    let ModuleParts {
        vocabulary,
        prelude,
        script,
        render,
        placement,
        component,
    } = parts;
    let mut body = prelude.unwrap_or_default();
    separate_statement(&mut body);
    match (placement, script, render) {
        (RenderPlacement::None, _, Some(_)) => return Err(AssemblyError::UnexpectedRender),
        (RenderPlacement::None, Some(ScriptPart::Inline { .. }), None) => {
            return Err(AssemblyError::UnexpectedInlineScript);
        }
        (RenderPlacement::None, script, None) => append_script(&mut body, script, component),
        (RenderPlacement::Function { .. } | RenderPlacement::Inline, _, None) => {
            return Err(AssemblyError::MissingRender);
        }
        (RenderPlacement::Function { .. }, Some(ScriptPart::Inline { .. }), Some(_)) => {
            return Err(AssemblyError::UnexpectedInlineScript);
        }
        (RenderPlacement::Function { binding, property }, script, Some(render)) => {
            append_script(&mut body, script, component);
            separate_statement(&mut body);
            body.append(render);
            end_line(&mut body);
            body.push(component);
            body.push(".");
            body.push(property.name());
            body.push(" = ");
            body.push(binding);
            body.push("\n");
        }
        (
            RenderPlacement::Inline,
            Some(ScriptPart::Inline {
                before_render,
                after_render,
            }),
            Some(render),
        ) => {
            body.append(before_render);
            body.append(render);
            body.append(after_render);
            end_line(&mut body);
        }
        (RenderPlacement::Inline, _, Some(_)) => return Err(AssemblyError::MissingInlineScript),
    }
    body.push("export default ");
    body.push(component);
    body.push("\n");

    let mut preamble = Writer::default();
    if !body.helpers().is_empty() {
        preamble.push("import { ");
        for (index, &helper) in body.helpers().in_use_order().iter().enumerate() {
            let name = vocabulary
                .name(helper)
                .ok_or(AssemblyError::UnknownHelper(helper))?;
            if index != 0 {
                preamble.push(", ");
            }
            preamble.push(name);
            preamble.push(" as _");
            preamble.push(name);
        }
        preamble.push(" } from ");
        let specifier = serde_json::to_string(vocabulary.module)
            .map_err(|_| AssemblyError::InvalidModuleSpecifier)?;
        preamble.push(&specifier);
        preamble.push("\n");
    }
    Ok(body.finish_with_preamble(preamble))
}

fn append_script<L: LinkSink>(
    body: &mut Writer<L>,
    script: Option<ScriptPart<L>>,
    component: &str,
) {
    if let Some(ScriptPart::Body(script)) = script {
        body.append(script);
    } else {
        body.push("const ");
        body.push(component);
        body.push(" = {}\n");
    }
    end_line(body);
}

fn end_line<L: LinkSink>(writer: &mut Writer<L>) {
    if !writer.is_empty() && !writer.as_str().ends_with('\n') {
        writer.push("\n");
    }
}

// A newline alone can continue a preceding initializer when the next prepared
// fragment starts with `(`, `[` or a template literal. Put the delimiter on its
// own line so a trailing authored line comment cannot consume it. Inline
// expression insertion deliberately does not use this statement boundary.
fn separate_statement<L: LinkSink>(writer: &mut Writer<L>) {
    if !writer.is_empty() {
        end_line(writer);
        writer.push(";\n");
    }
}

#[cfg(test)]
mod tests;
