import {
  catalogOwner,
  componentQualityGates,
  type UiFamilyCatalogEntry,
} from "../../../catalog/family-catalog-types.ts";

export const feedbackLoadingCatalog = [
  {
    canonicalName: "progress",
    title: "Progress",
    packageSubpath: "./progress",
    entryFile: "src/families/feedback/progress/progress.ts",
    sourceFiles: [
      "src/families/feedback/progress/progress.vue",
      "src/families/feedback/progress/progress.ts",
      "src/families/feedback/progress/progress-state.ts",
      "src/families/feedback/progress/progress-types.ts",
    ],
    behaviorContract: "src/families/feedback/progress/progress.behavior.md",
    tests: [
      "src/families/feedback/progress/progress.test.ts",
      "src/families/feedback/progress/progress-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/progress/progress.types.test-d.ts"],
    rendererFixture: "ProgressConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Progress",
      retainedSignature: 'data-vize-ui":(?:`progress`|"progress"|\'progress\')',
      maximumJavaScriptGzipBytes: 1_550,
      maximumCssGzipBytes: 0,
    },
    aliases: ["native progress", "loading progress", "task progress"],
    upstreamCoverage: ["HTML progress", "WAI-ARIA progressbar", "React Aria ProgressBar"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "progress-bar",
    title: "ProgressBar",
    packageSubpath: "./progress-bar",
    entryFile: "src/families/feedback/progress-bar/progress-bar.ts",
    sourceFiles: [
      "src/families/feedback/progress-bar/progress-bar.vue",
      "src/families/feedback/progress-bar/progress-bar.ts",
      "src/families/feedback/progress-bar/progress-bar.css",
      "src/families/feedback/progress-bar/progress-bar-state.ts",
      "src/families/feedback/progress-bar/progress-bar-types.ts",
    ],
    behaviorContract: "src/families/feedback/progress-bar/progress-bar.behavior.md",
    tests: [
      "src/families/feedback/progress-bar/progress-bar.test.ts",
      "src/families/feedback/progress-bar/progress-bar-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/progress-bar/progress-bar.types.test-d.ts"],
    rendererFixture: "ProgressBarConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "ProgressBar",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}progress-bar",
      maximumJavaScriptGzipBytes: 2_550,
      // Covers the shared packaged stylesheet used by styled families.
      maximumCssGzipBytes: 7_600,
    },
    aliases: ["progress", "loading progress", "task progress", "upload progress"],
    upstreamCoverage: ["WAI-ARIA progressbar role", "React Aria ProgressBar", "HTML progress"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "skeleton",
    title: "Skeleton",
    packageSubpath: "./skeleton",
    entryFile: "src/families/feedback/skeleton/skeleton.ts",
    sourceFiles: [
      "src/families/feedback/skeleton/skeleton.vue",
      "src/families/feedback/skeleton/skeleton.ts",
      "src/families/feedback/skeleton/skeleton-types.ts",
    ],
    behaviorContract: "src/families/feedback/skeleton/skeleton.behavior.md",
    tests: [
      "src/families/feedback/skeleton/skeleton.test.ts",
      "src/families/feedback/skeleton/skeleton-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/skeleton/skeleton.types.test-d.ts"],
    rendererFixture: "SkeletonConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Skeleton",
      retainedSignature: "data-vize-ui[\\s\\S]{0,32}skeleton",
      maximumJavaScriptGzipBytes: 1_250,
      maximumCssGzipBytes: 0,
    },
    aliases: ["placeholder", "loading skeleton", "deferred content", "suspense fallback"],
    upstreamCoverage: ["WAI-ARIA status role", "shadcn/ui Skeleton", "React Aria ProgressBar"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "spinner",
    title: "Spinner",
    packageSubpath: "./spinner",
    entryFile: "src/families/feedback/spinner/spinner.ts",
    sourceFiles: [
      "src/families/feedback/spinner/spinner.vue",
      "src/families/feedback/spinner/spinner.ts",
      "src/families/feedback/spinner/spinner-types.ts",
    ],
    behaviorContract: "src/families/feedback/spinner/spinner.behavior.md",
    tests: [
      "src/families/feedback/spinner/spinner.test.ts",
      "src/families/feedback/spinner/spinner-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/spinner/spinner.types.test-d.ts"],
    rendererFixture: "SpinnerConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Spinner",
      retainedSignature: 'data-vize-ui":(?:`spinner`|"spinner"|\'spinner\')',
      maximumJavaScriptGzipBytes: 1_900,
      maximumCssGzipBytes: 0,
    },
    aliases: ["spinner", "loading indicator", "progress spinner", "activity indicator"],
    upstreamCoverage: ["WAI-ARIA status role", "WAI-ARIA progressbar role", "MUI CircularProgress"],
    dependencies: ["id"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "status-light",
    title: "StatusLight",
    packageSubpath: "./status-light",
    entryFile: "src/families/feedback/status-light/status-light.ts",
    sourceFiles: [
      "src/families/feedback/status-light/status-light.vue",
      "src/families/feedback/status-light/status-light.ts",
      "src/families/feedback/status-light/status-light-types.ts",
    ],
    behaviorContract: "src/families/feedback/status-light/status-light.behavior.md",
    tests: [
      "src/families/feedback/status-light/status-light.test.ts",
      "src/families/feedback/status-light/status-light-ssr.test.ts",
    ],
    typeTests: ["src/families/feedback/status-light/status-light.types.test-d.ts"],
    rendererFixture: "StatusLightConsumer.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "StatusLight",
      retainedSignature: "data-vize-ui[\\s\\S]{0,40}status-light",
      maximumJavaScriptGzipBytes: 1_400,
      maximumCssGzipBytes: 0,
    },
    aliases: ["presence indicator", "health indicator", "status dot", "traffic light"],
    upstreamCoverage: ["WAI-ARIA img role", "WAI-ARIA status role", "Radix Themes Badge"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
