/**
 * Fresco App - Application instance management
 */

import {
  defineComponent,
  h,
  ref,
  shallowRef,
  type App as VueApp,
  type Component,
  type Ref,
  type VNode,
} from "@vue/runtime-core";
import type { InputEventNapi } from "@vizejs/fresco-native";
import {
  SCREEN_READER_KEY,
  isScreenReaderEnabledByDefault,
  treeToScreenReaderRenderNodes,
} from "./accessibility.js";
import { APP_KEY, createAppContext, type UseAppReturn } from "./composables/useApp.js";
import { createFocusManager, FOCUS_KEY, type FocusManager } from "./composables/useFocus.js";
import { createStreamsContext, STREAMS_KEY } from "./composables/useStreams.js";
import { updateLastRenderLayouts } from "./layoutMetrics.js";
import type { KittyKeyboardOptions } from "./kittyKeyboard.js";
import {
  createRenderer,
  treeToRenderNodes,
  type FrescoElement,
  type FrescoNode,
} from "./renderer.js";

export type KeyEventType = "press" | "repeat" | "release";

// Event types
export interface KeyEvent {
  type: "key";
  key?: string;
  char?: string;
  ctrl: boolean;
  alt: boolean;
  shift: boolean;
  meta: boolean;
  super: boolean;
  hyper: boolean;
  capsLock: boolean;
  numLock: boolean;
  eventType?: KeyEventType;
}

export interface PasteEvent {
  type: "paste";
  text: string;
}

export interface ResizeEvent {
  type: "resize";
  width: number;
  height: number;
}

export interface MouseEvent {
  type: "mouse";
  button?: string;
  x: number;
  y: number;
}

export interface FocusEvent {
  type: "focus";
  focused: boolean;
}

export interface CompositionEvent {
  type: "compositionstart" | "compositionupdate" | "compositionend";
  text: string;
  cursor: number;
}

export type InputEvent =
  | KeyEvent
  | PasteEvent
  | ResizeEvent
  | MouseEvent
  | FocusEvent
  | CompositionEvent;

// Global event state
export const lastKeyEvent: Ref<KeyEvent | null> = ref(null);
export const lastPasteEvent: Ref<PasteEvent | null> = ref(null);
export const lastResizeEvent: Ref<ResizeEvent | null> = ref(null);
export const lastMouseEvent: Ref<MouseEvent | null> = ref(null);
export const lastFocusEvent: Ref<FocusEvent | null> = ref(null);
export const lastCompositionEvent: Ref<CompositionEvent | null> = ref(null);

// Import native bindings
// eslint-disable-next-line typescript-eslint/no-redundant-type-constituents -- index.d.ts is generated by napi
let native: typeof import("@vizejs/fresco-native") | null = null;

async function loadNative() {
  if (!native) {
    native = await import("@vizejs/fresco-native");
  }
  return native;
}

/**
 * App options
 */
export interface AppOptions {
  /** Enable mouse support */
  mouse?: boolean;
  /** Exit on Ctrl+C */
  exitOnCtrlC?: boolean;
  /** Custom error handler */
  onError?: (error: Error) => void;
  /** Debug mode - logs render tree */
  debug?: boolean;
  /** Ink-compatible option, accepted for API parity */
  stdout?: NodeJS.WriteStream;
  /** Ink-compatible option, accepted for API parity */
  stdin?: NodeJS.ReadStream;
  /** Ink-compatible option, accepted for API parity */
  stderr?: NodeJS.WriteStream;
  /** Ink-compatible option, accepted for API parity */
  patchConsole?: boolean;
  /** Called after a frame is rendered */
  onRender?: (metrics: { renderTime: number }) => void;
  /** Enable screen reader rendering hints */
  isScreenReaderEnabled?: boolean;
  /** Maximum render frames per second */
  maxFps?: number;
  /** Use alternate screen buffer */
  alternateScreen?: boolean;
  /** Ink-compatible option, accepted for API parity */
  incrementalRendering?: boolean;
  /** Ink-compatible option, accepted for API parity */
  concurrent?: boolean;
  /** Override interactive mode detection */
  interactive?: boolean;
  /** Configure Kitty keyboard protocol support */
  kittyKeyboard?: KittyKeyboardOptions;
}

export type RenderOptions = AppOptions;

export type AppRoot = Component | VNode;

/**
 * Fresco App instance
 */
export interface App {
  /** Mount the app */
  mount(): Promise<void>;
  /** Unmount the app */
  unmount(errorOrResult?: unknown): Promise<void>;
  /** Wait for exit */
  waitUntilExit(): Promise<unknown>;
  /** Wait for pending render output */
  waitUntilRenderFlush(): Promise<void>;
  /** Render the app */
  render(): void;
  /** Clear the screen */
  clear(): void;
  /** Get terminal info */
  getTerminalInfo(): Promise<{ width: number; height: number }>;
}

export interface RenderInstance {
  rerender(root: AppRoot): void;
  unmount(errorOrResult?: unknown): Promise<void>;
  waitUntilExit(): Promise<unknown>;
  waitUntilRenderFlush(): Promise<void>;
  cleanup(): Promise<void>;
  clear(): void;
}

export interface RenderToStringOptions {
  /** Width of the virtual terminal in columns */
  columns?: number;
}

export interface WritableStreamLike {
  write(...args: unknown[]): unknown;
}

function isWritableStream(value: unknown): value is WritableStreamLike {
  return (
    typeof value === "object" &&
    value !== null &&
    "write" in value &&
    typeof (value as { write?: unknown }).write === "function"
  );
}

function normalizeRenderOptions(options: AppOptions | WritableStreamLike): AppOptions {
  return isWritableStream(options) ? { stdout: options as NodeJS.WriteStream } : options;
}

function isVNodeRoot(root: AppRoot): root is VNode {
  return typeof root === "object" && root !== null && "__v_isVNode" in root;
}

function componentFromRoot(root: AppRoot): Component {
  if (!isVNodeRoot(root)) return root;

  return defineComponent({
    name: "FrescoVNodeRoot",
    setup() {
      return () => root;
    },
  });
}

function createRootElement(width = "100%", height = "100%"): FrescoElement {
  return {
    id: -1,
    type: "root",
    props: {
      style: {
        width,
        height,
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        alignContent: "flex-start",
      },
    },
    children: [],
    parent: null,
  };
}

function nodeText(node: FrescoNode): string {
  if (node.text !== undefined) return node.text;
  const propText = node.props.text ?? node.props.content;
  if (typeof propText === "string" || typeof propText === "number") return String(propText);
  if (node.type === "input") {
    const value = node.props.value;
    const placeholder = node.props.placeholder;
    if (typeof value === "string" || typeof value === "number") return String(value);
    if (typeof placeholder === "string" || typeof placeholder === "number")
      return String(placeholder);
  }
  return "";
}

function treeToString(node: FrescoNode): string {
  const ownText = nodeText(node);
  const childOutput = node.children.map((child) => treeToString(child));

  if (node.type === "text" || node.type === "input") {
    return `${ownText}${childOutput.join("")}`;
  }

  const style = (node.props.style ?? {}) as Record<string, unknown>;
  const flexDirection = style.flexDirection ?? style.flex_direction;
  const separator = flexDirection === "column" ? "\n" : "";
  return childOutput.filter(Boolean).join(separator);
}

function updateAppSize(context: UseAppReturn | null, width: number, height: number) {
  if (!context) return;
  context.width.value = width;
  context.height.value = height;
}

/**
 * Create a Fresco TUI app
 */
export function createApp(rootComponent: AppRoot, options: AppOptions = {}): App {
  const { mouse = false, exitOnCtrlC = true, onError } = options;
  const screenReaderEnabled = ref(
    options.isScreenReaderEnabled ?? isScreenReaderEnabledByDefault(),
  );
  const frameDelay = Math.max(1, Math.floor(1000 / Math.max(1, options.maxFps ?? 30)));
  const streamsContext = createStreamsContext({
    stdin: options.stdin,
    stdout: options.stdout,
    stderr: options.stderr,
    exitOnCtrlC,
    interactive: options.interactive ?? true,
  });

  let vueApp: VueApp | null = null;
  let rootElement: FrescoElement | null = null;
  let mounted = false;
  let running = false;
  let needsRender = true;
  let appContext: UseAppReturn | null = null;
  let focusManager: FocusManager | null = null;

  let exitSettled = false;
  let resolveExit: ((value?: unknown) => void) | null = null;
  let rejectExit: ((reason?: unknown) => void) | null = null;
  const exitPromise = new Promise<unknown>((resolve, reject) => {
    resolveExit = resolve;
    rejectExit = reject;
  });

  const { createApp: createVueApp } = createRenderer();

  async function mount() {
    if (mounted) return;

    const n = await loadNative();

    // Initialize terminal
    if (mouse) {
      n.initTerminalWithMouse();
    } else {
      n.initTerminal();
    }

    n.enableIme?.();

    // Initialize layout engine
    n.initLayout();

    // Create Vue app with custom renderer
    const app = createVueApp(componentFromRoot(rootComponent));

    const info = n.getTerminalInfo();
    appContext = createAppContext({
      width: info.width,
      height: info.height,
      exit: (value) => {
        void unmount(value);
      },
      render,
      clear,
      waitUntilRenderFlush,
      stdout: streamsContext.stdout,
    });
    focusManager = createFocusManager();
    app.provide(APP_KEY, appContext);
    app.provide(FOCUS_KEY, focusManager);
    app.provide(SCREEN_READER_KEY, screenReaderEnabled);
    app.provide(STREAMS_KEY, streamsContext);

    // Create a root element for mounting
    rootElement = createRootElement();

    app.mount(rootElement);
    vueApp = app;

    mounted = true;
    running = true;
    needsRender = true;

    // Start event loop
    void eventLoop();
  }

  async function unmount(errorOrResult?: unknown) {
    if (!mounted) return;

    running = false;

    const n = await loadNative();
    n.disableIme?.();
    n.restoreTerminal();

    if (vueApp) {
      vueApp.unmount();
      vueApp = null;
    }

    rootElement = null;
    mounted = false;
    appContext = null;
    focusManager = null;

    if (!exitSettled) {
      exitSettled = true;
      if (errorOrResult instanceof Error) {
        rejectExit?.(errorOrResult);
      } else {
        resolveExit?.(errorOrResult);
      }
    }
  }

  async function waitUntilExit(): Promise<unknown> {
    return exitPromise;
  }

  async function waitUntilRenderFlush(): Promise<void> {
    return Promise.resolve();
  }

  function clear() {
    if (!native || !mounted) return;
    native.clearScreen();
    native.flushTerminal();
  }

  function render() {
    if (!native || !mounted || !rootElement) {
      return;
    }

    const start = performance.now();

    try {
      const renderNodes = screenReaderEnabled.value
        ? treeToScreenReaderRenderNodes(rootElement)
        : treeToRenderNodes(rootElement);

      // Send to native for rendering
      if (renderNodes.length > 0) {
        if (options.debug) {
          streamsContext.stderr.write(`${JSON.stringify(renderNodes, null, 2)}\n`);
        }

        // Use renderTree which handles layout and painting
        native.renderTree(renderNodes);
        if ("getLastRenderLayouts" in native) {
          updateLastRenderLayouts(native.getLastRenderLayouts());
        }

        // Flush to display
        native.flushTerminal();
        options.onRender?.({ renderTime: performance.now() - start });
      }
    } catch (error) {
      if (onError) {
        onError(error as Error);
      } else {
        console.error("Render error:", error);
      }
    }
  }

  async function getTerminalInfo() {
    const n = await loadNative();
    const info = n.getTerminalInfo();
    return { width: info.width, height: info.height };
  }

  function dispatchEvent(event: InputEventNapi) {
    if (event.eventType === "resize") {
      const resizeEvent = {
        type: "resize" as const,
        width: event.width ?? 0,
        height: event.height ?? 0,
      };
      lastResizeEvent.value = resizeEvent;
      updateAppSize(appContext, resizeEvent.width, resizeEvent.height);
      return;
    }

    if (event.eventType === "paste") {
      lastPasteEvent.value = {
        type: "paste",
        text: event.text ?? "",
      };
      return;
    }

    if (event.eventType === "mouse") {
      lastMouseEvent.value = {
        type: "mouse",
        button: event.button ?? undefined,
        x: event.x ?? 0,
        y: event.y ?? 0,
      };
      return;
    }

    if (event.eventType === "focus") {
      lastFocusEvent.value = {
        type: "focus",
        focused: event.key === "gained",
      };
      return;
    }

    if (
      event.eventType === "compositionstart" ||
      event.eventType === "compositionupdate" ||
      event.eventType === "compositionend"
    ) {
      const type = event.eventType as CompositionEvent["type"];
      lastCompositionEvent.value = {
        type,
        text: event.text ?? "",
        cursor: event.cursor ?? 0,
      };
      return;
    }

    if (event.eventType === "key") {
      const modifiers = event.modifiers ?? {};
      lastKeyEvent.value = {
        type: "key",
        key: event.key ?? undefined,
        char: event.char ?? undefined,
        ctrl: modifiers.ctrl ?? false,
        alt: modifiers.alt ?? false,
        shift: modifiers.shift ?? false,
        meta: modifiers.meta ?? false,
        super: modifiers.super ?? false,
        hyper: modifiers.hyper ?? false,
        capsLock: modifiers.capsLock ?? false,
        numLock: modifiers.numLock ?? false,
        eventType: event.keyEventType ?? undefined,
      };
    }
  }

  async function eventLoop() {
    const n = await loadNative();

    while (running) {
      try {
        const event = n.pollEvent(16); // ~60fps

        if (event) {
          // Handle resize
          if (event.eventType === "resize") {
            n.syncTerminalSize();
            n.clearScreen();
            needsRender = true;
          }

          dispatchEvent(event);

          // Handle focus traversal
          if (event.eventType === "key" && event.key === "tab") {
            focusManager?.focusNext();
            needsRender = true;
          } else if (event.eventType === "key" && event.key === "backtab") {
            focusManager?.focusPrevious();
            needsRender = true;
          }

          // Handle Ctrl+C
          if (
            exitOnCtrlC &&
            event.eventType === "key" &&
            event.char === "c" &&
            event.modifiers?.ctrl
          ) {
            await unmount();
            break;
          }
        }

        // Render frame if needed
        if (needsRender) {
          render();
          needsRender = false;
        }

        // Schedule re-render (Vue reactivity will trigger updates)
        needsRender = true;
      } catch (error) {
        if (onError) {
          onError(error as Error);
        }
      }

      // Small delay to prevent busy loop
      await new Promise((resolve) => setTimeout(resolve, frameDelay));
    }
  }

  return {
    mount,
    unmount,
    waitUntilExit,
    waitUntilRenderFlush,
    render,
    clear,
    getTerminalInfo,
  };
}

/**
 * Ink-compatible helper that mounts immediately.
 */
export function render(
  root: AppRoot,
  options: AppOptions | WritableStreamLike = {},
): RenderInstance {
  const renderOptions = normalizeRenderOptions(options);
  const rootRef = shallowRef(root);
  const Root = defineComponent({
    name: "FrescoRenderRoot",
    setup() {
      return () => {
        const current = rootRef.value;
        return isVNodeRoot(current) ? current : h(current);
      };
    },
  });

  const app = createApp(Root, renderOptions);
  void app.mount();

  return {
    rerender(nextRoot: AppRoot) {
      rootRef.value = nextRoot;
      app.render();
    },
    unmount: (value?: unknown) => app.unmount(value),
    waitUntilExit: () => app.waitUntilExit(),
    waitUntilRenderFlush: () => app.waitUntilRenderFlush(),
    cleanup: () => app.unmount(),
    clear: () => app.clear(),
  };
}

/**
 * Render a Fresco component to a plain string without starting a terminal app.
 */
export function renderToString(root: AppRoot, options: RenderToStringOptions = {}): string {
  const { createApp: createVueApp } = createRenderer();
  const app = createVueApp(componentFromRoot(root));
  const rootElement = createRootElement(String(options.columns ?? 80), "auto");

  app.provide(
    APP_KEY,
    createAppContext({
      width: options.columns ?? 80,
      height: 24,
    }),
  );
  app.provide(FOCUS_KEY, createFocusManager());
  app.provide(SCREEN_READER_KEY, ref(false));
  app.provide(STREAMS_KEY, createStreamsContext({ interactive: false }));
  app.mount(rootElement);

  const output = treeToString(rootElement);
  app.unmount();
  return output;
}
