/**
 * Fresco App - Application instance management
 */

import { format } from "node:util";
import {
  defineComponent,
  h,
  ref,
  shallowRef,
  type App as VueApp,
  type Component,
  type Ref,
  type VNode,
} from "@vue/runtime-core";
import type { InputEventNapi } from "@vizejs/fresco-native";
import {
  SCREEN_READER_KEY,
  isScreenReaderEnabledByDefault,
  treeToScreenReaderRenderNodes,
} from "./accessibility.js";
import { APP_KEY, createAppContext, type UseAppReturn } from "./composables/useApp.js";
import { createFocusManager, FOCUS_KEY, type FocusManager } from "./composables/useFocus.js";
import {
  createStreamsContext,
  STREAMS_KEY,
  type StreamsContext,
} from "./composables/useStreams.js";
import { createCursorContext, CURSOR_KEY, type CursorPosition } from "./composables/useCursor.js";
import { updateLastRenderLayouts } from "./layoutMetrics.js";
import type { KittyKeyboardOptions } from "./kittyKeyboard.js";
import {
  createRenderer,
  treeToRenderNodes,
  type FrescoElement,
  type FrescoNode,
} from "./renderer.js";

export type KeyEventType = "press" | "repeat" | "release";

// Event types
export interface KeyEvent {
  type: "key";
  key?: string;
  char?: string;
  ctrl: boolean;
  alt: boolean;
  shift: boolean;
  meta: boolean;
  super: boolean;
  hyper: boolean;
  capsLock: boolean;
  numLock: boolean;
  eventType?: KeyEventType;
}

export interface PasteEvent {
  type: "paste";
  text: string;
}

export interface ResizeEvent {
  type: "resize";
  width: number;
  height: number;
}

export interface MouseEvent {
  type: "mouse";
  button?: string;
  x: number;
  y: number;
}

export interface FocusEvent {
  type: "focus";
  focused: boolean;
}

export interface CompositionEvent {
  type: "compositionstart" | "compositionupdate" | "compositionend";
  text: string;
  cursor: number;
}

export type InputEvent =
  | KeyEvent
  | PasteEvent
  | ResizeEvent
  | MouseEvent
  | FocusEvent
  | CompositionEvent;

// Global event state
export const lastKeyEvent: Ref<KeyEvent | null> = ref(null);
export const lastPasteEvent: Ref<PasteEvent | null> = ref(null);
export const lastResizeEvent: Ref<ResizeEvent | null> = ref(null);
export const lastMouseEvent: Ref<MouseEvent | null> = ref(null);
export const lastFocusEvent: Ref<FocusEvent | null> = ref(null);
export const lastCompositionEvent: Ref<CompositionEvent | null> = ref(null);

// Import native bindings
// eslint-disable-next-line typescript-eslint/no-redundant-type-constituents -- index.d.ts is generated by napi
let native: typeof import("@vizejs/fresco-native") | null = null;

type ConsoleMethod = "debug" | "error" | "info" | "log" | "warn";
const consoleMethods: ConsoleMethod[] = ["debug", "error", "info", "log", "warn"];

async function loadNative() {
  if (!native) {
    native = await import("@vizejs/fresco-native");
  }
  return native;
}

/**
 * App options
 */
export interface AppOptions {
  /** Enable mouse support */
  mouse?: boolean;
  /** Exit on Ctrl+C */
  exitOnCtrlC?: boolean;
  /** Custom error handler */
  onError?: (error: Error) => void;
  /** Debug mode - logs render tree */
  debug?: boolean;
  /** Ink-compatible option, accepted for API parity */
  stdout?: NodeJS.WriteStream;
  /** Ink-compatible option, accepted for API parity */
  stdin?: NodeJS.ReadStream;
  /** Ink-compatible option, accepted for API parity */
  stderr?: NodeJS.WriteStream;
  /** Ink-compatible option, accepted for API parity */
  patchConsole?: boolean;
  /** Called after a frame is rendered */
  onRender?: (metrics: RenderMetrics) => void;
  /** Enable screen reader rendering hints */
  isScreenReaderEnabled?: boolean;
  /** Maximum render frames per second */
  maxFps?: number;
  /** Use alternate screen buffer */
  alternateScreen?: boolean;
  /** Ink-compatible option, accepted for API parity */
  incrementalRendering?: boolean;
  /** Ink-compatible option, accepted for API parity */
  concurrent?: boolean;
  /** Override interactive mode detection */
  interactive?: boolean;
  /** Configure Kitty keyboard protocol support */
  kittyKeyboard?: KittyKeyboardOptions;
}

export type RenderOptions = AppOptions;

export type AppRoot = Component | VNode;

/**
 * Performance metrics for a render operation.
 */
export interface RenderMetrics {
  /** Time spent rendering in milliseconds */
  renderTime: number;
}

/**
 * Fresco App instance
 */
export interface App {
  /** Mount the app */
  mount(): Promise<void>;
  /** Unmount the app */
  unmount(errorOrResult?: unknown): Promise<void>;
  /** Wait for exit */
  waitUntilExit(): Promise<unknown>;
  /** Wait for pending render output */
  waitUntilRenderFlush(): Promise<void>;
  /** Render the app */
  render(): void;
  /** Clear the screen */
  clear(): void;
  /** Get terminal info */
  getTerminalInfo(): Promise<{ width: number; height: number }>;
}

export interface RenderInstance {
  rerender(root: AppRoot): void;
  unmount(errorOrResult?: unknown): Promise<void>;
  waitUntilExit(): Promise<unknown>;
  waitUntilRenderFlush(): Promise<void>;
  cleanup(): Promise<void>;
  clear(): void;
}

export type Instance = RenderInstance;

export interface RenderToStringOptions {
  /** Width of the virtual terminal in columns */
  columns?: number;
}

export interface WritableStreamLike {
  write(...args: unknown[]): unknown;
}

type Listener = (...args: unknown[]) => void;

function createNoopWriteStream(columns: number, rows: number): NodeJS.WriteStream {
  const stream = {
    isTTY: false,
    columns,
    rows,
    write: () => true,
    on: (_event: string, _listener: Listener) => stream,
    off: (_event: string, _listener: Listener) => stream,
    once: (_event: string, _listener: Listener) => stream,
    removeListener: (_event: string, _listener: Listener) => stream,
  };

  return stream as unknown as NodeJS.WriteStream;
}

function createNoopReadStream(): NodeJS.ReadStream {
  const stream = {
    isTTY: false,
    isPaused: () => true,
    pause: () => stream,
    resume: () => stream,
    ref: () => stream,
    unref: () => stream,
    setEncoding: () => stream,
    setRawMode: () => stream,
    on: (_event: string, _listener: Listener) => stream,
    off: (_event: string, _listener: Listener) => stream,
    once: (_event: string, _listener: Listener) => stream,
    removeListener: (_event: string, _listener: Listener) => stream,
  };

  return stream as unknown as NodeJS.ReadStream;
}

function isWritableStream(value: unknown): value is WritableStreamLike {
  return (
    typeof value === "object" &&
    value !== null &&
    "write" in value &&
    typeof (value as { write?: unknown }).write === "function"
  );
}

function normalizeRenderOptions(options: AppOptions | WritableStreamLike): AppOptions {
  return isWritableStream(options) ? { stdout: options as NodeJS.WriteStream } : options;
}

function isVNodeRoot(root: AppRoot): root is VNode {
  return typeof root === "object" && root !== null && "__v_isVNode" in root;
}

function componentFromRoot(root: AppRoot): Component {
  if (!isVNodeRoot(root)) return root;

  return defineComponent({
    name: "FrescoVNodeRoot",
    setup() {
      return () => root;
    },
  });
}

function createRootElement(width = "100%", height = "100%"): FrescoElement {
  return {
    id: -1,
    type: "root",
    props: {
      style: {
        width,
        height,
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        alignContent: "flex-start",
      },
    },
    children: [],
    parent: null,
  };
}

function nodeText(node: FrescoNode): string {
  if (node.text !== undefined) return node.text;
  const propText = node.props.text ?? node.props.content;
  if (typeof propText === "string" || typeof propText === "number") return String(propText);
  if (node.type === "input") {
    const value = node.props.value;
    const placeholder = node.props.placeholder;
    if (typeof value === "string" || typeof value === "number") return String(value);
    if (typeof placeholder === "string" || typeof placeholder === "number")
      return String(placeholder);
  }
  return "";
}

function isStaticNode(node: FrescoNode): boolean {
  return node.props.internal_static === true || node.props.internalStatic === true;
}

function joinOutput(parts: string[], separator = "\n"): string {
  return parts.filter(Boolean).join(separator);
}

function treeToString(node: FrescoNode, options: { skipStatic?: boolean } = {}): string {
  if (options.skipStatic && isStaticNode(node)) return "";

  const ownText = nodeText(node);
  const childOutput = node.children.map((child) => treeToString(child, options));

  if (node.type === "text" || node.type === "input") {
    return `${ownText}${childOutput.join("")}`;
  }

  const style = (node.props.style ?? {}) as Record<string, unknown>;
  const flexDirection = style.flexDirection ?? style.flex_direction;
  const separator = flexDirection === "column" ? "\n" : "";
  return joinOutput(childOutput, separator);
}

function normalizeOutput(output: string): string {
  return output.endsWith("\n") ? output.slice(0, -1) : output;
}

function appendOutput(previous: string, next: string): string {
  const normalized = normalizeOutput(next);
  if (!normalized) return previous;
  return previous ? `${previous}\n${normalized}` : normalized;
}

function captureStaticOutput(node: FrescoNode, renderedStaticItems: Map<number, number>): string {
  const output: string[] = [];

  function visit(current: FrescoNode) {
    if (isStaticNode(current)) {
      const renderedItems = renderedStaticItems.get(current.id) ?? 0;
      const nextItems = current.children.slice(renderedItems);
      const nextOutput = joinOutput(
        nextItems.map((child) => treeToString(child)),
        "\n",
      );
      if (nextOutput) output.push(nextOutput);
      renderedStaticItems.set(current.id, current.children.length);
      return;
    }

    for (const child of current.children) {
      visit(child);
    }
  }

  visit(node);
  return joinOutput(output, "\n");
}

function createStaticOutputNode(output: string): FrescoElement | null {
  const normalized = normalizeOutput(output);
  if (!normalized) return null;

  const staticRoot: FrescoElement = {
    id: -1,
    type: "box",
    props: {
      style: {
        flexDirection: "column",
      },
    },
    children: [],
    parent: null,
  };

  staticRoot.children = normalized.split("\n").map((line, index) => ({
    id: -2 - index,
    type: "text",
    props: {
      text: line,
    },
    children: [],
    parent: staticRoot,
  }));

  return staticRoot;
}

function cloneDynamicTree(node: FrescoNode): FrescoElement | null {
  if (isStaticNode(node)) return null;

  const clone: FrescoElement = {
    id: node.id,
    type: node.type,
    props: node.props,
    children: [],
    parent: null,
    text: node.text,
  };

  clone.children = node.children
    .map((child) => cloneDynamicTree(child))
    .filter((child): child is FrescoElement => child !== null);
  for (const child of clone.children) {
    child.parent = clone;
  }

  return clone;
}

function createRenderTree(root: FrescoElement, staticOutput: string): FrescoElement {
  const dynamicRoot = cloneDynamicTree(root) ?? createRootElement();
  const staticOutputNode = createStaticOutputNode(staticOutput);

  if (staticOutputNode) {
    staticOutputNode.parent = dynamicRoot;
    dynamicRoot.children = [staticOutputNode, ...dynamicRoot.children];
  }

  return dynamicRoot;
}

function renderPlainOutput(root: FrescoNode, staticOutput: string): string {
  return joinOutput([staticOutput, treeToString(root, { skipStatic: true })], "\n");
}

function updateAppSize(context: UseAppReturn | null, width: number, height: number) {
  if (!context) return;
  context.width.value = width;
  context.height.value = height;
}

const CI_ENVIRONMENT_KEYS = ["CI", "CONTINUOUS_INTEGRATION", "BUILD_NUMBER", "RUN_ID"] as const;

function isTruthyEnvironmentValue(value: string | undefined): boolean {
  if (!value) return false;
  return !["0", "false", "no"].includes(value.toLowerCase());
}

function isCiEnvironment(env: NodeJS.ProcessEnv = process.env): boolean {
  return CI_ENVIRONMENT_KEYS.some((key) => isTruthyEnvironmentValue(env[key]));
}

function detectInteractiveMode(options: AppOptions): boolean {
  const stdout = options.stdout ?? process.stdout;
  return options.interactive ?? (stdout.isTTY === true && !isCiEnvironment());
}

/**
 * Create a Fresco TUI app
 */
export function createApp(rootComponent: AppRoot, options: AppOptions = {}): App {
  const { mouse = false, exitOnCtrlC = true, onError } = options;
  const interactive = detectInteractiveMode(options);
  const screenReaderEnabled = ref(
    options.isScreenReaderEnabled ?? isScreenReaderEnabledByDefault(),
  );
  const frameDelay = Math.max(1, Math.floor(1000 / Math.max(1, options.maxFps ?? 30)));
  let streamsContext: StreamsContext;
  const writeToStdout = (data: string) => {
    writeExternalOutput(streamsContext.stdout, data);
  };
  const writeToStderr = (data: string) => {
    writeExternalOutput(streamsContext.stderr, data);
  };
  streamsContext = createStreamsContext({
    stdin: options.stdin,
    stdout: options.stdout,
    stderr: options.stderr,
    exitOnCtrlC,
    interactive,
    writeToStdout,
    writeToStderr,
  });

  let vueApp: VueApp | null = null;
  let rootElement: FrescoElement | null = null;
  let mounted = false;
  let running = false;
  let needsRender = true;
  let appContext: UseAppReturn | null = null;
  let focusManager: FocusManager | null = null;
  let consoleRestore: (() => void) | null = null;
  let isWritingExternalOutput = false;
  let nonInteractiveOutput = "";
  let staticOutput = "";
  const renderedStaticItems = new Map<number, number>();
  let cursorPosition: CursorPosition | undefined;
  let hasCursorOverride = false;

  let exitSettled = false;
  let resolveExit: ((value?: unknown) => void) | null = null;
  let rejectExit: ((reason?: unknown) => void) | null = null;
  const exitPromise = new Promise<unknown>((resolve, reject) => {
    resolveExit = resolve;
    rejectExit = reject;
  });

  const { createApp: createVueApp } = createRenderer();

  async function mount() {
    if (mounted) return;

    const n = interactive ? await loadNative() : null;

    if (n) {
      if (typeof n.initTerminalWithOptions === "function") {
        n.initTerminalWithOptions({
          alternateScreen: options.alternateScreen === true,
          bracketedPaste: true,
          hideCursor: true,
          mouse,
          rawMode: true,
        });
      } else if (mouse) {
        n.initTerminalWithMouse();
      } else {
        n.initTerminal();
      }

      n.enableIme?.();

      // Initialize layout engine
      n.initLayout();
    }

    // Create Vue app with custom renderer
    const app = createVueApp(componentFromRoot(rootComponent));

    const info = n?.getTerminalInfo() ?? {
      width: streamsContext.stdout.columns ?? 80,
      height: streamsContext.stdout.rows ?? 24,
    };
    appContext = createAppContext({
      width: info.width,
      height: info.height,
      exit: (value) => {
        void unmount(value);
      },
      render,
      clear,
      waitUntilRenderFlush,
      stdout: streamsContext.stdout,
    });
    focusManager = createFocusManager();
    app.provide(APP_KEY, appContext);
    app.provide(FOCUS_KEY, focusManager);
    app.provide(SCREEN_READER_KEY, screenReaderEnabled);
    app.provide(STREAMS_KEY, streamsContext);
    app.provide(
      CURSOR_KEY,
      createCursorContext((position) => {
        hasCursorOverride = true;
        cursorPosition = position;
        needsRender = true;
      }),
    );

    // Create a root element for mounting
    rootElement = createRootElement();

    patchConsoleMethods();
    try {
      app.mount(rootElement);
    } catch (error) {
      restoreConsoleMethods();
      throw error;
    }
    vueApp = app;

    mounted = true;
    running = true;
    needsRender = true;

    // Start event loop
    void eventLoop();
  }

  async function unmount(errorOrResult?: unknown) {
    if (!mounted) return;

    running = false;

    if (!interactive && rootElement) {
      staticOutput = appendOutput(
        staticOutput,
        captureStaticOutput(rootElement, renderedStaticItems),
      );
      nonInteractiveOutput = renderPlainOutput(rootElement, staticOutput);
    }

    if (native && interactive) {
      native.disableIme?.();
      native.restoreTerminal();
    }

    restoreConsoleMethods();

    if (vueApp) {
      vueApp.unmount();
      vueApp = null;
    }

    if (!interactive && nonInteractiveOutput) {
      streamsContext.stdout.write(
        nonInteractiveOutput.endsWith("\n") ? nonInteractiveOutput : `${nonInteractiveOutput}\n`,
      );
      nonInteractiveOutput = "";
    }

    rootElement = null;
    mounted = false;
    appContext = null;
    focusManager = null;
    cursorPosition = undefined;
    hasCursorOverride = false;

    if (!exitSettled) {
      exitSettled = true;
      if (errorOrResult instanceof Error) {
        rejectExit?.(errorOrResult);
      } else {
        resolveExit?.(errorOrResult);
      }
    }
  }

  async function waitUntilExit(): Promise<unknown> {
    return exitPromise;
  }

  async function waitUntilRenderFlush(): Promise<void> {
    return Promise.resolve();
  }

  function clear() {
    if (!mounted) return;
    staticOutput = "";
    if (!interactive) {
      nonInteractiveOutput = "";
      return;
    }
    if (!native) return;
    native.clearScreen();
    native.flushTerminal();
  }

  function writeExternalOutput(stream: NodeJS.WriteStream, data: string) {
    if (!mounted || !interactive || !native || isWritingExternalOutput) {
      stream.write(data);
      return;
    }

    try {
      isWritingExternalOutput = true;
      native.clearScreen();
      native.flushTerminal();
      stream.write(data);
      needsRender = true;
      render();
    } finally {
      isWritingExternalOutput = false;
    }
  }

  function patchConsoleMethods() {
    if (options.patchConsole === false || consoleRestore) return;

    const target = console as unknown as Record<ConsoleMethod, (...data: unknown[]) => void>;
    const original: Partial<Record<ConsoleMethod, (...data: unknown[]) => void>> = {};
    const patch = (method: ConsoleMethod, writer: (data: string) => void) => {
      original[method] = target[method];
      target[method] = (...args: unknown[]) => {
        writer(`${format(...args)}\n`);
      };
    };

    patch("debug", writeToStdout);
    patch("info", writeToStdout);
    patch("log", writeToStdout);
    patch("warn", writeToStderr);
    patch("error", writeToStderr);

    consoleRestore = () => {
      for (const method of consoleMethods) {
        const originalMethod = original[method];
        if (originalMethod) target[method] = originalMethod;
      }
      consoleRestore = null;
    };
  }

  function restoreConsoleMethods() {
    consoleRestore?.();
  }

  function applyCursorOverride() {
    if (!hasCursorOverride || !native) return;

    if (cursorPosition) {
      native.setCursor(cursorPosition.x, cursorPosition.y);
      native.showCursor();
    } else {
      native.hideCursor();
    }
  }

  function render() {
    if (!mounted || !rootElement) {
      return;
    }

    const start = performance.now();

    try {
      if (!interactive) {
        staticOutput = appendOutput(
          staticOutput,
          captureStaticOutput(rootElement, renderedStaticItems),
        );
        nonInteractiveOutput = renderPlainOutput(rootElement, staticOutput);
        options.onRender?.({ renderTime: performance.now() - start });
        return;
      }

      if (!native) {
        return;
      }

      staticOutput = appendOutput(
        staticOutput,
        captureStaticOutput(rootElement, renderedStaticItems),
      );
      const renderRoot = createRenderTree(rootElement, staticOutput);
      const renderNodes = screenReaderEnabled.value
        ? treeToScreenReaderRenderNodes(renderRoot)
        : treeToRenderNodes(renderRoot);

      // Send to native for rendering
      if (renderNodes.length > 0) {
        if (options.debug) {
          streamsContext.stderr.write(`${JSON.stringify(renderNodes, null, 2)}\n`);
        }

        // Use renderTree which handles layout and painting
        native.renderTree(renderNodes);
        if ("getLastRenderLayouts" in native) {
          updateLastRenderLayouts(native.getLastRenderLayouts());
        }

        applyCursorOverride();

        // Flush to display
        native.flushTerminal();
        options.onRender?.({ renderTime: performance.now() - start });
      }
    } catch (error) {
      if (onError) {
        onError(error as Error);
      } else {
        console.error("Render error:", error);
      }
    }
  }

  async function getTerminalInfo() {
    const n = await loadNative();
    const info = n.getTerminalInfo();
    return { width: info.width, height: info.height };
  }

  function dispatchEvent(event: InputEventNapi) {
    if (event.eventType === "resize") {
      const resizeEvent = {
        type: "resize" as const,
        width: event.width ?? 0,
        height: event.height ?? 0,
      };
      lastResizeEvent.value = resizeEvent;
      updateAppSize(appContext, resizeEvent.width, resizeEvent.height);
      return;
    }

    if (event.eventType === "paste") {
      lastPasteEvent.value = {
        type: "paste",
        text: event.text ?? "",
      };
      return;
    }

    if (event.eventType === "mouse") {
      lastMouseEvent.value = {
        type: "mouse",
        button: event.button ?? undefined,
        x: event.x ?? 0,
        y: event.y ?? 0,
      };
      return;
    }

    if (event.eventType === "focus") {
      lastFocusEvent.value = {
        type: "focus",
        focused: event.key === "gained",
      };
      return;
    }

    if (
      event.eventType === "compositionstart" ||
      event.eventType === "compositionupdate" ||
      event.eventType === "compositionend"
    ) {
      const type = event.eventType as CompositionEvent["type"];
      lastCompositionEvent.value = {
        type,
        text: event.text ?? "",
        cursor: event.cursor ?? 0,
      };
      return;
    }

    if (event.eventType === "key") {
      const modifiers = event.modifiers ?? {};
      lastKeyEvent.value = {
        type: "key",
        key: event.key ?? undefined,
        char: event.char ?? undefined,
        ctrl: modifiers.ctrl ?? false,
        alt: modifiers.alt ?? false,
        shift: modifiers.shift ?? false,
        meta: modifiers.meta ?? false,
        super: modifiers.super ?? false,
        hyper: modifiers.hyper ?? false,
        capsLock: modifiers.capsLock ?? false,
        numLock: modifiers.numLock ?? false,
        eventType: event.keyEventType ?? undefined,
      };
    }
  }

  async function eventLoop() {
    const n = interactive ? await loadNative() : null;

    while (running) {
      try {
        const event = n?.pollEvent(16); // ~60fps

        if (event) {
          // Handle resize
          if (event.eventType === "resize") {
            n?.syncTerminalSize();
            n?.clearScreen();
            needsRender = true;
          }

          dispatchEvent(event);

          // Handle focus traversal
          if (event.eventType === "key" && event.key === "tab") {
            focusManager?.focusNext();
            needsRender = true;
          } else if (event.eventType === "key" && event.key === "backtab") {
            focusManager?.focusPrevious();
            needsRender = true;
          }

          // Handle Ctrl+C
          if (
            exitOnCtrlC &&
            event.eventType === "key" &&
            event.char === "c" &&
            event.modifiers?.ctrl
          ) {
            await unmount();
            break;
          }
        }

        // Render frame if needed
        if (needsRender) {
          render();
          needsRender = false;
        }

        // Schedule re-render (Vue reactivity will trigger updates)
        needsRender = true;
      } catch (error) {
        if (onError) {
          onError(error as Error);
        }
      }

      // Small delay to prevent busy loop
      await new Promise((resolve) => setTimeout(resolve, frameDelay));
    }
  }

  return {
    mount,
    unmount,
    waitUntilExit,
    waitUntilRenderFlush,
    render,
    clear,
    getTerminalInfo,
  };
}

/**
 * Ink-compatible helper that mounts immediately.
 */
export function render(
  root: AppRoot,
  options: AppOptions | WritableStreamLike = {},
): RenderInstance {
  const renderOptions = normalizeRenderOptions(options);
  const rootRef = shallowRef(root);
  const Root = defineComponent({
    name: "FrescoRenderRoot",
    setup() {
      return () => {
        const current = rootRef.value;
        return isVNodeRoot(current) ? current : h(current);
      };
    },
  });

  const app = createApp(Root, renderOptions);
  void app.mount();

  return {
    rerender(nextRoot: AppRoot) {
      rootRef.value = nextRoot;
      app.render();
    },
    unmount: (value?: unknown) => app.unmount(value),
    waitUntilExit: () => app.waitUntilExit(),
    waitUntilRenderFlush: () => app.waitUntilRenderFlush(),
    cleanup: () => app.unmount(),
    clear: () => app.clear(),
  };
}

/**
 * Render a Fresco component to a plain string without starting a terminal app.
 */
export function renderToString(root: AppRoot, options: RenderToStringOptions = {}): string {
  const { createApp: createVueApp } = createRenderer();
  const app = createVueApp(componentFromRoot(root));
  const columns = options.columns ?? 80;
  const stdout = createNoopWriteStream(columns, 24);
  const stderr = createNoopWriteStream(columns, 24);
  const stdin = createNoopReadStream();
  const rootElement = createRootElement(String(columns), "auto");

  app.provide(
    APP_KEY,
    createAppContext({
      width: columns,
      height: 24,
      stdout,
    }),
  );
  app.provide(FOCUS_KEY, createFocusManager());
  app.provide(SCREEN_READER_KEY, ref(false));
  app.provide(
    CURSOR_KEY,
    createCursorContext(() => {}),
  );
  app.provide(
    STREAMS_KEY,
    createStreamsContext({
      stdin,
      stdout,
      stderr,
      interactive: false,
      writeToStdout: () => {},
      writeToStderr: () => {},
    }),
  );
  app.mount(rootElement);

  const renderedStaticItems = new Map<number, number>();
  const staticOutput = captureStaticOutput(rootElement, renderedStaticItems);
  const output = renderPlainOutput(rootElement, staticOutput);
  app.unmount();
  return output;
}
