//! The contract table: the declared domains and one row per rule.

use vize_davinci::diagnostic::{Domain, RuleContract, Severity, Tier};

use super::RuleEntry;

const A11Y: Domain = Domain::new(
    "native elements with static attributes and roles in SFC templates; components and dynamic bindings are outside",
);
const BINDINGS: Domain = Domain::new(
    "bindings croquis resolves across <script setup> and the template; values reached through unresolved imports are outside",
);
const BLOCKS: Domain = Domain::new("the SFC's top-level blocks, their order and their attributes");
const CSS_TEXT: Domain =
    Domain::new("declarations and selectors of <style> blocks as parsed by lightningcss");
const DIRECTIVES: Domain = Domain::new(
    "elements and Vue directive syntax of SFC templates as parsed: names, arguments, modifiers, expressions and placement",
);
const ECOSYSTEM: Domain = Domain::new(
    "Vue Router, Nuxt, Pinia, vue-i18n, Void and Vue Test Utils APIs used with literal arguments",
);
const HTML: Domain =
    Domain::new("HTML conformance of native elements with static attributes in SFC templates");
const MACROS: Domain = Domain::new(
    "Vue compiler macro calls in <script setup> (defineProps, defineEmits, defineOptions, defineSlots)",
);
const MUSEA: Domain = Domain::new("<art> and <variant> blocks of .art.vue files");
const NUXT: Domain =
    Domain::new("Nuxt configuration objects and definePageMeta calls written as literals");
const OPTIONS: Domain = Domain::new("Options API component definitions written as object literals");
const SCRIPT: Domain =
    Domain::new("the syntax of <script> and <script setup> programs, without type information");
const STYLE: Domain = Domain::new(
    "the authored text of SFC templates and declarations: casing, quoting, spacing, order and shorthand",
);
const TEMPLATE_FLOW: Domain = Domain::new(
    "control flow of HTML SFC templates as lowered to S2: branches, loops, scoped slots and the operators of parsed expressions; pug and src templates are outside",
);
const TYPES: Domain =
    Domain::new("types the Corsa session resolves for the component; unresolved types are outside");

/// Every Patina rule, sorted by name.
#[rustfmt::skip]
pub static RULE_CONTRACTS: &[RuleEntry] = &[
    row!("a11y/alt-text", Exact, A11Y, Warning),
    row!("a11y/anchor-has-content", Complete, A11Y, Warning),
    row!("a11y/anchor-is-valid", Exact, A11Y, Warning),
    row!("a11y/aria-props", Exact, A11Y, Error),
    row!("a11y/aria-role", Exact, A11Y, Error),
    row!("a11y/aria-unsupported-elements", Exact, A11Y, Error),
    row!("a11y/click-events-have-key-events", Exact, A11Y, Warning),
    row!("a11y/form-control-has-label", Complete, A11Y, Warning),
    row!("a11y/heading-has-content", Exact, A11Y, Warning),
    row!("a11y/heading-levels", Exact, A11Y, Warning),
    row!("a11y/iframe-has-title", Exact, A11Y, Warning),
    row!("a11y/img-alt", Exact, A11Y, Warning),
    row!("a11y/interactive-supports-focus", Exact, A11Y, Warning),
    row!("a11y/label-has-for", Complete, A11Y, Warning),
    row!("a11y/landmark-roles", Complete, A11Y, Warning),
    row!("a11y/media-has-caption", Exact, A11Y, Warning),
    row!("a11y/mouse-events-have-key-events", Exact, A11Y, Warning),
    row!("a11y/no-access-key", Exact, A11Y, Warning),
    row!("a11y/no-aria-hidden-on-focusable", Exact, A11Y, Error),
    row!("a11y/no-autofocus", Exact, A11Y, Warning),
    row!("a11y/no-distracting-elements", Exact, A11Y, Warning),
    row!("a11y/no-i-for-icon", Heuristic, A11Y, Warning),
    row!("a11y/no-redundant-roles", Exact, A11Y, Warning),
    row!("a11y/no-refer-to-non-existent-id", Heuristic, A11Y, Warning),
    row!("a11y/no-role-presentation-on-focusable", Exact, A11Y, Error),
    row!("a11y/no-static-element-interactions", Exact, A11Y, Warning),
    row!("a11y/placeholder-label-option", Exact, A11Y, Warning),
    row!("a11y/role-has-required-aria-props", Exact, A11Y, Warning),
    row!("a11y/tabindex-no-positive", Exact, A11Y, Warning),
    row!("a11y/use-list", Heuristic, A11Y, Warning),
    row!("css/no-display-none", Heuristic, CSS_TEXT, Warning),
    row!("css/no-hardcoded-values", Heuristic, CSS_TEXT, Warning),
    row!("css/no-id-selectors", Exact, CSS_TEXT, Warning),
    row!("css/no-important", Exact, CSS_TEXT, Warning),
    row!("css/no-utility-classes", Heuristic, CSS_TEXT, Warning),
    row!("css/no-v-bind-performance", Exact, CSS_TEXT, Warning),
    row!("css/prefer-logical-properties", Exact, CSS_TEXT, Warning),
    row!("css/prefer-nested-selectors", Heuristic, CSS_TEXT, Warning),
    row!("css/prefer-slotted", Heuristic, CSS_TEXT, Warning),
    row!("css/require-font-display", Exact, CSS_TEXT, Warning),
    row!("ecosystem/nuxt-prefer-nuxt-link", Exact, ECOSYSTEM, Warning),
    row!("ecosystem/pinia-prefer-store-to-refs", Complete, ECOSYSTEM, Warning),
    row!("ecosystem/router-link-require-to", Exact, ECOSYSTEM, Error),
    row!("ecosystem/void-link-require-href", Exact, ECOSYSTEM, Error),
    row!("ecosystem/void-link-valid-method", Exact, ECOSYSTEM, Warning),
    row!("ecosystem/vue-i18n-no-missing-key", Complete, ECOSYSTEM, Warning),
    row!("ecosystem/vue-router-prefer-named-link", Exact, ECOSYSTEM, Warning),
    row!("ecosystem/vue-router-prefer-named-push", Exact, ECOSYSTEM, Warning),
    row!("ecosystem/vue-test-utils-no-html-snapshot", Exact, ECOSYSTEM, Warning),
    row!("html/deprecated-attr", Exact, HTML, Warning),
    row!("html/deprecated-element", Exact, HTML, Warning),
    row!("html/id-duplication", Exact, HTML, Error),
    row!("html/no-consecutive-br", Exact, HTML, Warning),
    row!("html/no-dupe-style-properties", Exact, HTML, Warning),
    row!("html/no-duplicate-class", Exact, HTML, Warning),
    row!("html/no-duplicate-dt", Exact, HTML, Warning),
    row!("html/no-empty-palpable-content", Exact, HTML, Warning),
    row!("html/require-datetime", Exact, HTML, Warning),
    row!("musea/no-empty-variant", Exact, MUSEA, Warning),
    row!("musea/prefer-design-tokens", Heuristic, MUSEA, Warning),
    row!("musea/require-component", Exact, MUSEA, Warning),
    row!("musea/require-title", Exact, MUSEA, Error),
    row!("musea/unique-variant-names", Exact, MUSEA, Error),
    row!("musea/valid-variant", Exact, MUSEA, Error),
    row!("nuxt/no-nuxt-config-test-key", Exact, NUXT, Error),
    row!("nuxt/no-page-meta-runtime-values", Complete, NUXT, Error),
    row!("nuxt/nuxt-config-keys-order", Exact, NUXT, Error),
    row!("nuxt/prefer-import-meta", Exact, NUXT, Error),
    row!("petite-vue/no-unsupported-directive", Exact, DIRECTIVES, Error),
    row!("petite-vue/valid-v-effect", Exact, DIRECTIVES, Error),
    row!("petite-vue/valid-v-scope", Exact, DIRECTIVES, Error),
    row!("script/component-options-name-casing", Exact, OPTIONS, Error),
    row!("script/custom-event-name-casing", Complete, MACROS, Error),
    row!("script/define-emits-declaration", Exact, MACROS, Warning),
    row!("script/define-macros-order", Exact, MACROS, Warning),
    row!("script/define-props-declaration", Exact, MACROS, Warning),
    row!("script/define-props-destructuring", Exact, MACROS, Warning),
    row!("script/no-arrow-functions-in-watch", Exact, OPTIONS, Error),
    row!("script/no-async-in-computed", Exact, OPTIONS, Error),
    row!("script/no-boolean-default", Exact, OPTIONS, Warning),
    row!("script/no-deep-destructure-in-props", Exact, MACROS, Warning),
    row!("script/no-deprecated-data-object-declaration", Exact, OPTIONS, Error),
    row!("script/no-deprecated-destroyed-lifecycle", Exact, OPTIONS, Error),
    row!("script/no-deprecated-dollar-listeners-api", Exact, OPTIONS, Error),
    row!("script/no-deprecated-dollar-scopedslots-api", Exact, OPTIONS, Error),
    row!("script/no-deprecated-events-api", Exact, OPTIONS, Error),
    row!("script/no-deprecated-props-default-this", Exact, OPTIONS, Error),
    row!("script/no-dupe-keys", Exact, OPTIONS, Error),
    row!("script/no-duplicate-attr-inheritance", Complete, BINDINGS, Warning),
    row!("script/no-export-in-script-setup", Exact, SCRIPT, Error),
    row!("script/no-get-current-instance", Exact, SCRIPT, Error),
    row!("script/no-import-compiler-macros", Exact, SCRIPT, Error),
    row!("script/no-internal-imports", Exact, SCRIPT, Error),
    row!("script/no-multiple-slot-args", Exact, SCRIPT, Warning),
    row!("script/no-next-tick", Exact, SCRIPT, Error),
    row!("script/no-options-api", Exact, OPTIONS, Error),
    row!("script/no-potential-component-option-typo", Heuristic, OPTIONS, Warning),
    row!("script/no-reactive-destructure", Complete, BINDINGS, Warning),
    row!("script/no-ref-as-operand", Complete, BINDINGS, Error),
    row!("script/no-required-prop-with-default", Exact, OPTIONS, Error),
    row!("script/no-reserved-identifiers", Exact, SCRIPT, Error),
    row!("script/no-reserved-keys", Exact, OPTIONS, Error),
    row!("script/no-reserved-props", Exact, OPTIONS, Error),
    row!("script/no-restricted-globals", Exact, SCRIPT, Error),
    row!("script/no-restricted-members", Exact, SCRIPT, Error),
    row!("script/no-side-effects-in-computed-properties", Complete, OPTIONS, Error),
    row!("script/no-top-level-ref-in-script", Exact, SCRIPT, Error),
    row!("script/no-unstable-nested-components", Complete, BINDINGS, Warning),
    row!("script/no-unused-emit-declarations", Complete, MACROS, Warning),
    row!("script/no-use-computed-property-like-method", Complete, OPTIONS, Error),
    row!("script/no-with-defaults", Exact, MACROS, Warning),
    row!("script/prefer-computed", Heuristic, SCRIPT, Warning),
    row!("script/prefer-define-options", Exact, MACROS, Warning),
    row!("script/prefer-import-from-vue", Exact, SCRIPT, Warning),
    row!("script/prefer-ref-over-reactive", Heuristic, SCRIPT, Warning),
    row!("script/prefer-use-attrs", Exact, SCRIPT, Warning),
    row!("script/prefer-use-id", Heuristic, SCRIPT, Warning),
    row!("script/prefer-use-slots", Exact, SCRIPT, Warning),
    row!("script/prefer-use-template-ref", Complete, BINDINGS, Warning),
    row!("script/require-default-prop", Exact, OPTIONS, Error),
    row!("script/require-explicit-emits", Complete, MACROS, Warning),
    row!("script/require-explicit-slots", Complete, MACROS, Warning),
    row!("script/require-function-return-type", Exact, SCRIPT, Warning),
    row!("script/require-prop-type-constructor", Exact, OPTIONS, Error),
    row!("script/require-prop-types", Exact, OPTIONS, Error),
    row!("script/require-symbol-provide", Exact, SCRIPT, Warning),
    row!("script/require-typed-object-prop", Exact, OPTIONS, Warning),
    row!("script/require-typed-ref", Exact, SCRIPT, Warning),
    row!("script/require-valid-default-prop", Complete, OPTIONS, Error),
    row!("script/return-in-computed-property", Complete, OPTIONS, Error),
    row!("script/return-in-emits-validator", Complete, OPTIONS, Error),
    row!("script/valid-define-emits", Exact, MACROS, Error),
    row!("script/valid-define-options", Exact, MACROS, Error),
    row!("script/valid-define-props", Exact, MACROS, Error),
    row!("script/valid-next-tick", Complete, BINDINGS, Warning),
    row!("ssr/no-browser-globals-in-ssr", Heuristic, SCRIPT, Warning),
    row!("ssr/no-hydration-mismatch", Heuristic, SCRIPT, Warning),
    row!("type/no-floating-promises", Complete, TYPES, Warning),
    row!("type/no-reactivity-loss", Complete, TYPES, Warning),
    row!("type/no-unsafe-template-binding", Complete, TYPES, Warning),
    row!("type/require-typed-emits", Exact, MACROS, Warning),
    row!("type/require-typed-props", Exact, MACROS, Warning),
    row!("vapor/no-inline-template", Exact, DIRECTIVES, Error),
    row!("vapor/no-vue-lifecycle-events", Exact, DIRECTIVES, Error),
    row!("vapor/prefer-static-class", Exact, DIRECTIVES, Warning),
    row!("vapor/require-vapor-attribute", Exact, BLOCKS, Warning),
    row!("vue/a11y-img-alt", Exact, A11Y, Warning),
    row!("vue/attribute-hyphenation", Exact, STYLE, Warning),
    row!("vue/attribute-order", Exact, STYLE, Warning),
    row!("vue/component-definition-name-casing", Exact, STYLE, Warning),
    row!("vue/component-name-in-template-casing", Exact, STYLE, Warning),
    row!("vue/html-button-has-type", Exact, HTML, Warning),
    row!("vue/html-quotes", Exact, STYLE, Warning),
    row!("vue/html-self-closing", Exact, STYLE, Warning),
    row!("vue/max-template-complexity", Exact, TEMPLATE_FLOW, Warning),
    row!("vue/multi-word-component-names", Exact, STYLE, Error),
    row!("vue/mustache-interpolation-spacing", Exact, STYLE, Warning),
    row!("vue/no-array-index-key", Exact, DIRECTIVES, Warning),
    row!("vue/no-bare-strings-in-template", Heuristic, DIRECTIVES, Warning),
    row!("vue/no-boolean-attr-value", Exact, STYLE, Warning),
    row!("vue/no-child-content", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-filter", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-functional-template", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-html-element-is", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-inline-template", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-router-link-tag-prop", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-scope-attribute", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-slot-attribute", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-slot-scope-attribute", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-v-bind-sync", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-v-on-native-modifier", Exact, DIRECTIVES, Error),
    row!("vue/no-deprecated-v-on-number-modifiers", Exact, DIRECTIVES, Error),
    row!("vue/no-dupe-v-else-if", Complete, DIRECTIVES, Error),
    row!("vue/no-duplicate-attributes", Exact, DIRECTIVES, Error),
    row!("vue/no-empty-component-block", Exact, BLOCKS, Warning),
    row!("vue/no-inline-style", Exact, STYLE, Warning),
    row!("vue/no-invalid-html-attribute", Exact, HTML, Warning),
    row!("vue/no-lone-template", Exact, DIRECTIVES, Warning),
    row!("vue/no-multi-spaces", Exact, STYLE, Warning),
    row!("vue/no-multiple-objects-in-class", Exact, DIRECTIVES, Warning),
    row!("vue/no-multiple-template-root", Exact, DIRECTIVES, Error),
    row!("vue/no-mutating-props", Complete, BINDINGS, Error),
    row!("vue/no-negated-v-if-condition", Exact, DIRECTIVES, Warning),
    row!("vue/no-non-component-keep-alive-child", Exact, DIRECTIVES, Warning),
    row!("vue/no-preprocessor-lang", Exact, BLOCKS, Warning),
    row!("vue/no-reserved-component-names", Exact, STYLE, Error),
    row!("vue/no-root-v-if", Exact, DIRECTIVES, Warning),
    row!("vue/no-script-non-standard-lang", Exact, BLOCKS, Warning),
    row!("vue/no-src-attribute", Exact, BLOCKS, Warning),
    row!("vue/no-static-inline-styles", Exact, STYLE, Warning),
    row!("vue/no-template-key", Exact, DIRECTIVES, Error),
    row!("vue/no-template-lang", Exact, BLOCKS, Warning),
    row!("vue/no-template-shadow", Exact, DIRECTIVES, Warning),
    row!("vue/no-template-target-blank", Exact, HTML, Warning),
    row!("vue/no-textarea-mustache", Exact, DIRECTIVES, Error),
    row!("vue/no-undefined-refs", Complete, BINDINGS, Warning),
    row!("vue/no-unsafe-url", Heuristic, DIRECTIVES, Warning),
    row!("vue/no-unsandboxed-iframe", Exact, HTML, Warning),
    row!("vue/no-unused-components", Complete, BINDINGS, Warning),
    row!("vue/no-unused-properties", Complete, BINDINGS, Warning),
    row!("vue/no-unused-refs", Complete, BINDINGS, Warning),
    row!("vue/no-unused-vars", Exact, DIRECTIVES, Warning),
    row!("vue/no-use-v-else-with-v-for", Exact, DIRECTIVES, Warning),
    row!("vue/no-use-v-if-with-v-for", Exact, DIRECTIVES, Warning),
    row!("vue/no-useless-mustaches", Exact, DIRECTIVES, Warning),
    row!("vue/no-useless-template-attributes", Exact, DIRECTIVES, Error),
    row!("vue/no-useless-v-bind", Exact, DIRECTIVES, Warning),
    row!("vue/no-v-for-template-key-on-child", Exact, DIRECTIVES, Error),
    row!("vue/no-v-html", Exact, DIRECTIVES, Warning),
    row!("vue/no-v-text", Exact, DIRECTIVES, Warning),
    row!("vue/no-v-text-v-html-on-component", Exact, DIRECTIVES, Error),
    row!("vue/permitted-contents", Exact, HTML, Error),
    row!("vue/prefer-props-shorthand", Exact, STYLE, Warning),
    row!("vue/prefer-true-attribute-shorthand", Exact, STYLE, Warning),
    row!("vue/prop-name-casing", Exact, STYLE, Warning),
    row!("vue/require-component-is", Exact, DIRECTIVES, Error),
    row!("vue/require-component-registration", Complete, BINDINGS, Warning),
    row!("vue/require-scoped-style", Exact, BLOCKS, Warning),
    row!("vue/require-toggle-inside-transition", Exact, DIRECTIVES, Error),
    row!("vue/require-v-for-key", Exact, DIRECTIVES, Error),
    row!("vue/scoped-event-names", Exact, STYLE, Warning),
    row!("vue/sfc-element-order", Exact, BLOCKS, Warning),
    row!("vue/single-style-block", Exact, BLOCKS, Warning),
    row!("vue/slot-name-casing", Exact, STYLE, Warning),
    row!("vue/this-in-template", Exact, DIRECTIVES, Warning),
    row!("vue/use-unique-element-ids", Exact, DIRECTIVES, Warning),
    row!("vue/use-v-on-exact", Exact, DIRECTIVES, Warning),
    row!("vue/v-bind-style", Exact, STYLE, Warning),
    row!("vue/v-on-event-hyphenation", Exact, STYLE, Warning),
    row!("vue/v-on-handler-style", Exact, STYLE, Warning),
    row!("vue/v-on-style", Exact, STYLE, Warning),
    row!("vue/v-slot-style", Exact, STYLE, Warning),
    row!("vue/valid-attribute-name", Exact, DIRECTIVES, Error),
    row!("vue/valid-template-root", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-bind", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-cloak", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-else", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-for", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-html", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-if", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-memo", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-model", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-on", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-once", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-show", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-slot", Exact, DIRECTIVES, Error),
    row!("vue/valid-v-text", Exact, DIRECTIVES, Error),
    row!("vue/warn-custom-block", Exact, BLOCKS, Warning),
    row!("vue/warn-custom-directive", Exact, DIRECTIVES, Warning),
];
