//! Row types of the one projection mapping model.
//!
//! A [`VizeMapping`] is one span link — a generated byte range paired with the
//! authored byte range it projects, optionally refined by exact sub-spans.
//! [`ProjectionMeta`] is the per-row metadata the editor needs on top of the
//! link: which language features the row serves and which authored construct
//! it maps. Rows keep the names the generators already emit, so the model
//! absorbs them without a second row vocabulary.

use core::fmt;
use std::ops::Range;

/// A mapping from generated virtual TS position to SFC source position.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VizeMapping {
    /// Byte range in the generated virtual TypeScript.
    pub gen_range: Range<usize>,
    /// Byte range in the original SFC source.
    pub src_range: Range<usize>,
    /// Sub-token spans inside `gen_range`, paired with the matching SFC
    /// sub-range. Used to map TypeScript diagnostics that point at a
    /// specific identifier inside a template expression back to its exact
    /// position in the Vue source.
    ///
    /// Empty by default. Populated by template-expression generators that
    /// know the inner positions (e.g. property access inside an
    /// interpolation). Consumers fall back to `gen_range` / `src_range`
    /// when no sub-span covers the diagnostic.
    pub sub_spans: Vec<VizeSubSpan>,
}

/// A sub-token span inside a `VizeMapping`'s generated/source ranges.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VizeSubSpan {
    pub gen_range: Range<usize>,
    pub src_range: Range<usize>,
}

impl VizeMapping {
    /// A span link without sub-spans.
    #[inline]
    pub const fn new(gen_range: Range<usize>, src_range: Range<usize>) -> Self {
        Self {
            gen_range,
            src_range,
            sub_spans: Vec::new(),
        }
    }

    /// Look up the SFC sub-range that contains `gen_offset`. Returns `None`
    /// when no sub-span covers it — callers should fall back to `src_range`.
    pub fn sub_span_for_gen(&self, gen_offset: usize) -> Option<&VizeSubSpan> {
        self.sub_spans
            .iter()
            .find(|span| span.gen_range.contains(&gen_offset))
    }
}

/// Language features one projection row serves, packed into one byte.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct ProjectionFeatures(u8);

impl ProjectionFeatures {
    pub const NONE: Self = Self(0);
    pub const HOVER: Self = Self(1 << 0);
    pub const COMPLETION: Self = Self(1 << 1);
    pub const SIGNATURE_HELP: Self = Self(1 << 2);
    pub const DEFINITION: Self = Self(1 << 3);
    pub const REFERENCES: Self = Self(1 << 4);
    pub const RENAME: Self = Self(1 << 5);
    pub const DIAGNOSTICS: Self = Self(1 << 6);
    pub const SEMANTIC_TOKENS: Self = Self(1 << 7);
    pub const ALL: Self = Self(u8::MAX);

    /// Every flag in declaration order with its name, for dumps and oracles.
    pub const NAMED: [(Self, &'static str); 8] = [
        (Self::HOVER, "hover"),
        (Self::COMPLETION, "completion"),
        (Self::SIGNATURE_HELP, "signature_help"),
        (Self::DEFINITION, "definition"),
        (Self::REFERENCES, "references"),
        (Self::RENAME, "rename"),
        (Self::DIAGNOSTICS, "diagnostics"),
        (Self::SEMANTIC_TOKENS, "semantic_tokens"),
    ];

    /// The flags present in either set.
    #[inline]
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    /// Whether every flag of `other` is present.
    #[inline]
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }

    /// The packed representation.
    #[inline]
    pub const fn bits(self) -> u8 {
        self.0
    }
}

impl Default for ProjectionFeatures {
    /// A row serves every feature unless its producer narrows it.
    fn default() -> Self {
        Self::ALL
    }
}

impl fmt::Debug for ProjectionFeatures {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.0 == 0 {
            return formatter.write_str("NONE");
        }
        let mut first = true;
        for (flag, name) in Self::NAMED {
            if !self.contains(flag) {
                continue;
            }
            if !first {
                formatter.write_str(" | ")?;
            }
            formatter.write_str(name)?;
            first = false;
        }
        Ok(())
    }
}

/// The authored construct a projection row maps.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ProjectionSpanKind {
    /// The producer does not classify the row.
    #[default]
    Unknown,
    /// Script content projected byte for byte.
    Script,
    /// Template interpolation `{{ expr }}`.
    Interpolation,
    /// Directive expression `v-if="expr"`.
    DirectiveExpr,
    /// Directive argument `:prop` / `v-bind:prop`.
    DirectiveArg,
    /// Event handler `@click="handler"`.
    EventHandler,
    /// `v-for` alias.
    VForVar,
    /// `v-slot` binding.
    SlotBinding,
    /// Component tag reference.
    ComponentRef,
    /// A template expression whose producer does not distinguish the
    /// interpolation and directive cases.
    TemplateExpression,
}

/// Per-row metadata of a [`super::ProjectionMapping`].
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct ProjectionMeta {
    pub features: ProjectionFeatures,
    pub kind: ProjectionSpanKind,
}

impl ProjectionMeta {
    /// Every feature, classified as `kind`.
    #[inline]
    pub const fn of_kind(kind: ProjectionSpanKind) -> Self {
        Self {
            features: ProjectionFeatures::ALL,
            kind,
        }
    }
}

/// One row of a [`super::ProjectionMapping`]: the span link and its metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProjectionRow<'a> {
    pub span: &'a VizeMapping,
    pub meta: ProjectionMeta,
}
