import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "../../../family-catalog-types.ts";

const measureFamilyRoot = "src/families/interaction/measure/";

export const interactionSupportFamilyCatalog = [
  {
    canonicalName: "measure",
    title: "Measure",
    packageSubpath: "./measure",
    entryFile: `${measureFamilyRoot}measure.ts`,
    sourceFiles: [
      `${measureFamilyRoot}measure.ts`,
      `${measureFamilyRoot}measure-runtime.ts`,
      `${measureFamilyRoot}measure-types.ts`,
    ],
    behaviorContract: `${measureFamilyRoot}measure.behavior.md`,
    tests: [`${measureFamilyRoot}measure.test.ts`, `${measureFamilyRoot}measure-ssr.test.ts`],
    typeTests: [`${measureFamilyRoot}measure.types.test-d.ts`],
    rendererFixture: "MeasureConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSizeObserver",
      retainedSignature: "VIZE_UI_MEASURE_DISPOSED",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["resize observer", "intersection observer", "element size", "visibility"],
    upstreamCoverage: ["ResizeObserver", "IntersectionObserver"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "primitive",
    title: "Primitive",
    packageSubpath: "./primitive",
    entryFile: "src/primitive.ts",
    sourceFiles: ["src/primitive-element.vue", "src/primitive.ts"],
    behaviorContract: "src/primitive.behavior.md",
    tests: ["src/primitive.test.ts"],
    rendererFixture: "primitive-element.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Primitive",
      retainedSignature: "data-vize-ui.+primitive",
      maximumJavaScriptGzipBytes: 500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["as child", "polymorphic primitive", "slot forwarding primitive"],
    upstreamCoverage: ["Reka UI Primitive", "Radix Slot", "shadcn/ui Slot"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "shortcut",
    title: "Shortcut",
    packageSubpath: "./shortcut",
    entryFile: "src/shortcut.ts",
    sourceFiles: [
      "src/shortcut.ts",
      "src/shortcut-format.ts",
      "src/shortcut-parse.ts",
      "src/shortcut-registry.ts",
      "src/shortcut-types.ts",
    ],
    behaviorContract: "src/shortcut.behavior.md",
    tests: [
      "src/shortcut.test.ts",
      "src/shortcut-format.test.ts",
      "src/shortcut-lifecycle.test.ts",
      "src/shortcut-ssr.test.ts",
    ],
    typeTests: ["src/shortcut.types.test-d.ts"],
    rendererFixture: "ShortcutConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createShortcutRegistry",
      retainedSignature: "VIZE_UI_SHORTCUT_DISPOSED",
      maximumJavaScriptGzipBytes: 4_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["keyboard shortcuts", "hotkeys", "keybindings", "kbd formatting"],
    upstreamCoverage: ["VS Code keybindings", "React Aria useKeyboard", "GitHub Hotkey"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "sortable",
    title: "Sortable",
    packageSubpath: "./sortable",
    entryFile: "src/sortable.ts",
    sourceFiles: [
      "src/sortable.ts",
      "src/sortable-internal.ts",
      "src/sortable-keyboard.ts",
      "src/sortable-types.ts",
    ],
    behaviorContract: "src/sortable.behavior.md",
    tests: ["src/sortable.test.ts", "src/sortable-ssr.test.ts"],
    typeTests: ["src/sortable.types.test-d.ts"],
    rendererFixture: "SortableConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSortable",
      retainedSignature: "VIZE_UI_SORTABLE_DISPOSED",
      allowedRetainedFamilies: ["drag-and-drop"],
      maximumJavaScriptGzipBytes: 9_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["sortable list", "reorder", "sortable grid", "sortable tree"],
    upstreamCoverage: ["React Aria useDraggableCollection", "ARIA APG drag reordering"],
    dependencies: ["drag-and-drop"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "spatial-navigation",
    title: "Spatial Navigation",
    packageSubpath: "./spatial-navigation",
    entryFile: "src/spatial-navigation.ts",
    sourceFiles: [
      "src/spatial-navigation.ts",
      "src/spatial-navigation-internal.ts",
      "src/spatial-navigation-types.ts",
    ],
    behaviorContract: "src/spatial-navigation.behavior.md",
    tests: [
      "src/spatial-navigation.test.ts",
      "src/spatial-navigation-lifecycle.test.ts",
      "src/spatial-navigation-ssr.test.ts",
    ],
    typeTests: ["src/spatial-navigation.types.test-d.ts"],
    rendererFixture: "SpatialNavigationConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSpatialNavigation",
      retainedSignature: "VIZE_UI_SPATIAL_NAVIGATION_DISPOSED",
      maximumJavaScriptGzipBytes: 4_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["spatial navigation", "grid navigation", "geometry navigation"],
    upstreamCoverage: ["CSS Spatial Navigation", "ARIA grid navigation"],
    dependencies: ["collection"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "typeahead",
    title: "Typeahead",
    packageSubpath: "./typeahead",
    entryFile: "src/typeahead.ts",
    sourceFiles: ["src/typeahead.ts", "src/typeahead-internal.ts", "src/typeahead-types.ts"],
    behaviorContract: "src/typeahead.behavior.md",
    tests: ["src/typeahead.test.ts", "src/typeahead-ssr.test.ts"],
    typeTests: ["src/typeahead.types.test-d.ts"],
    rendererFixture: "TypeaheadConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createTypeahead",
      retainedSignature: "VIZE_UI_TYPEAHEAD_DISPOSED",
      maximumJavaScriptGzipBytes: 1_375,
      maximumCssGzipBytes: 0,
    },
    aliases: ["typeahead", "collection search", "keyboard search"],
    upstreamCoverage: ["React Aria useTypeSelect", "Ariakit composite typeahead"],
    dependencies: ["collection"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "virtualizer",
    title: "Virtualizer",
    packageSubpath: "./virtualizer",
    entryFile: "src/virtualizer.ts",
    sourceFiles: [
      "src/virtualizer.ts",
      "src/virtualizer-grid.ts",
      "src/virtualizer-infinite.ts",
      "src/virtualizer-measure-cache.ts",
      "src/virtualizer-options.ts",
      "src/virtualizer-runtime.ts",
      "src/virtualizer-types.ts",
      "src/virtualizer-viewport.ts",
      "src/virtualizer-window.ts",
    ],
    behaviorContract: "src/virtualizer.behavior.md",
    tests: [
      "src/virtualizer.test.ts",
      "src/virtualizer-grid.test.ts",
      "src/virtualizer-infinite.test.ts",
      "src/virtualizer-measure-cache.test.ts",
      "src/virtualizer-ssr.test.ts",
    ],
    typeTests: ["src/virtualizer.types.test-d.ts"],
    rendererFixture: "VirtualizerConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createVirtualizer",
      retainedSignature: "VIZE_UI_VIRTUALIZER_DISPOSED",
      allowedRetainedFamilies: ["measure"],
      maximumJavaScriptGzipBytes: 4_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["virtual list", "virtual scroll", "windowing", "infinite scroll"],
    upstreamCoverage: ["windowed rendering", "scroll anchoring", "scroll restoration"],
    dependencies: ["measure"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
