// Generated by `nuxi prepare`. Registers project components globally so
// templates can use them without an explicit import.
declare module "vue" {
  export interface GlobalComponents {
    TheGreeting: typeof import("../components/TheGreeting.vue")["default"];
  }
}

export {};
