// Generated by `nuxi prepare` (committed so `vize check` runs without a
// Nuxt install). Re-exports the project's auto-imported composables and
// declares the framework auto-imports as globals.
export { useCounter } from "../composables/useCounter";

declare global {
  const useCounter: typeof import("../composables/useCounter")["useCounter"];
  const navigateTo: (to: string) => Promise<void>;
  const useRoute: () => { path: string; params: Record<string, string> };
}

export {};
