//! Template-related generation for virtual TypeScript.
//!
//! Handles template AST traversal, expression emission, v-for/v-if scoping,
//! and source mapping for template expressions.
#![allow(clippy::disallowed_macros)] // format! used for generating TypeScript code strings

use super::{
    BindingMetadata, BindingType, DirectiveNode, ElementNode, ExpressionNode, ForNode, IfNode,
    InterpolationNode, MappingData, PropNode, RootNode, SourceMapping, SourceRange,
    TemplateChildNode, VirtualTsGenerator, VirtualTsOutput,
};
use crate::analyzer::{VForScopeAliases, parse_v_for_scope_expression};
use vize_carton::{String, ToCompactString, append, profile};

impl VirtualTsGenerator {
    /// Generate virtual TypeScript from template AST (legacy API).
    pub fn generate_template(
        &mut self,
        ast: &RootNode,
        bindings: &BindingMetadata,
        block_offset: u32,
        emit_context: bool,
    ) -> VirtualTsOutput {
        self.reset();
        self.block_offset = block_offset;

        if emit_context {
            self.write_line("// Virtual TypeScript for template type checking");
            self.write_line("// Generated by vize_croquis");
            self.write_line("");

            // Generate context type from bindings
            self.write_line("// Context from script setup");
            self.write("declare const __ctx: { ");

            let binding_entries: Vec<_> = bindings.bindings.iter().collect();
            for (i, (name, _)) in binding_entries.iter().enumerate() {
                if i > 0 {
                    self.write(", ");
                }
                self.write(&format!("{}: any", name));
            }
            self.write_line(" };");

            // Destructure context variables for direct use in expressions
            if !binding_entries.is_empty() {
                self.write("const { ");
                for (i, (name, _)) in binding_entries.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.write(name);
                }
                self.write_line(" } = __ctx;");
            }
            self.write_line("");
        }

        // Profile the full child walk as one span. This keeps virtual TS
        // generation observable without wrapping every recursive template node
        // and paying guard overhead proportional to AST size.
        self.write_line("// Template expressions");
        profile!(
            "croquis.virtual_ts.template.visit_children",
            self.visit_children(&ast.children)
        );

        profile!("croquis.virtual_ts.create_output", self.create_output())
    }

    /// Emit template scope nested inside setup.
    pub(crate) fn emit_template_scope(&mut self, ast: &RootNode, bindings: &BindingMetadata) {
        self.emit_line("");
        self.emit_line("// Template scope (inherits from setup)");
        // Keep the template IIFE from being parsed as a call on the last setup expression.
        self.emit_line(";(function __template() {");
        self.indent_level += 1;

        // Declare refs for template ref access
        profile!(
            "croquis.virtual_ts.template.emit_ref_declarations",
            self.emit_template_ref_declarations(bindings)
        );

        // Same coarse span as the standalone path: the emitted code is built by
        // the recursive walk, but profiling each child would dominate small
        // templates and add noise to large ones.
        self.emit_line("// Template expressions");
        profile!(
            "croquis.virtual_ts.template.visit_children",
            self.visit_children(&ast.children)
        );

        self.indent_level = self.indent_level.saturating_sub(1);
        self.emit_line("})();");
    }

    /// Emit template ref declarations.
    fn emit_template_ref_declarations(&mut self, bindings: &BindingMetadata) {
        let template_refs: Vec<_> = bindings
            .bindings
            .iter()
            .filter(|(_, t)| matches!(t, BindingType::SetupRef))
            .collect();

        if !template_refs.is_empty() {
            self.emit_line("// Template refs (auto-unwrapped)");
            for (name, _) in template_refs {
                // Template refs are auto-unwrapped in templates
                self.emit_line(&format!("const __unwrapped_{} = {}.value;", name, name));
            }
            self.emit_line("");
        }
    }

    /// Visit template children.
    pub(crate) fn visit_children(&mut self, children: &[TemplateChildNode]) {
        for child in children {
            self.visit_child(child);
        }
    }

    /// Visit a single template child.
    fn visit_child(&mut self, node: &TemplateChildNode) {
        match node {
            TemplateChildNode::Element(el) => {
                profile!(
                    "croquis.virtual_ts.template.element",
                    self.visit_element(el)
                )
            }
            TemplateChildNode::Interpolation(interp) => profile!(
                "croquis.virtual_ts.template.interpolation",
                self.visit_interpolation(interp)
            ),
            TemplateChildNode::If(if_node) => {
                profile!("croquis.virtual_ts.template.if", self.visit_if(if_node))
            }
            TemplateChildNode::For(for_node) => {
                profile!("croquis.virtual_ts.template.for", self.visit_for(for_node))
            }
            TemplateChildNode::IfBranch(branch) => {
                if let Some(ref cond) = branch.condition {
                    self.emit_expression(cond, "v-if");
                }
                self.visit_children(&branch.children);
            }
            _ => {}
        }
    }

    /// Visit an element node.
    fn visit_element(&mut self, element: &ElementNode) {
        if let Some(condition) = element_control_flow_condition(element)
            && self.emit_mapped_expression_line(condition, "if (", ") {")
        {
            self.indent_level += 1;
            self.visit_element_inner(element);
            self.indent_level = self.indent_level.saturating_sub(1);
            self.emit_line("}");
            return;
        }

        self.visit_element_inner(element);
    }

    fn visit_element_inner(&mut self, element: &ElementNode) {
        // Check if this element has a v-for directive
        let v_for_exp = element.props.iter().find_map(|prop| {
            if let PropNode::Directive(dir) = prop
                && dir.name == "for"
            {
                return dir.exp.as_ref();
            }
            None
        });

        // If v-for directive exists, handle it with proper scoping
        if let Some(exp) = v_for_exp {
            self.emit_v_for_scope(exp, |this| {
                for prop in &element.props {
                    if let PropNode::Directive(dir) = prop
                        && dir.name != "for"
                        && !is_control_flow_directive(&dir.name)
                    {
                        profile!(
                            "croquis.virtual_ts.template.directive",
                            this.visit_directive(dir)
                        );
                    }
                }
                profile!(
                    "croquis.virtual_ts.template.element_children",
                    this.visit_children(&element.children)
                );
            });
        } else {
            for prop in &element.props {
                if let PropNode::Directive(dir) = prop
                    && !is_control_flow_directive(&dir.name)
                {
                    profile!(
                        "croquis.virtual_ts.template.directive",
                        self.visit_directive(dir)
                    );
                }
            }
            profile!(
                "croquis.virtual_ts.template.element_children",
                self.visit_children(&element.children)
            );
        }
    }

    /// Emit v-for scope with loop variables.
    fn emit_v_for_scope<F>(&mut self, exp: &ExpressionNode, body: F)
    where
        F: FnOnce(&mut Self),
    {
        let content = expression_source(exp);

        // Parse v-for expression: "item in items" or "(item, index) in items"
        if let Some(aliases) = parse_v_for_scope_expression(content) {
            self.emit_line("// v-for scope");
            self.emit_line("{");
            self.indent_level += 1;

            // Emit the source expression (right side)
            let var_name = format!("__expr_{}", self.expr_counter);
            self.expr_counter += 1;
            self.emit_line(&format!("const {} = {};", var_name, aliases.source));

            let loop_emitted = self.emit_v_for_scope_loop_open(&aliases, &var_name);
            profile!("croquis.virtual_ts.template.v_for_body", body(self));
            if loop_emitted {
                self.indent_level = self.indent_level.saturating_sub(1);
                self.emit_line("}");
            }

            self.indent_level = self.indent_level.saturating_sub(1);
            self.emit_line("}");
        } else {
            self.emit_expression(exp, "v-for");
            body(self);
        }
    }

    /// Visit a directive.
    fn visit_directive(&mut self, directive: &DirectiveNode) {
        if let Some(ref exp) = directive.exp {
            self.emit_expression(exp, &directive.name);
        }
    }

    /// Visit an interpolation.
    fn visit_interpolation(&mut self, interp: &InterpolationNode) {
        self.emit_expression(&interp.content, "interpolation");
    }

    /// Visit an if node.
    fn visit_if(&mut self, if_node: &IfNode) {
        let mut control_flow_open = false;
        for branch in &if_node.branches {
            if let Some(ref cond) = branch.condition {
                if control_flow_open {
                    self.indent_level = self.indent_level.saturating_sub(1);
                }

                let prefix = if control_flow_open {
                    "} else if ("
                } else {
                    "if ("
                };
                if self.emit_mapped_expression_line(cond, prefix, ") {") {
                    control_flow_open = true;
                    self.indent_level += 1;
                } else {
                    if control_flow_open {
                        self.emit_line("}");
                        control_flow_open = false;
                    }
                    self.emit_expression(cond, "v-if");
                }
            } else if control_flow_open {
                self.indent_level = self.indent_level.saturating_sub(1);
                self.emit_line("} else {");
                self.indent_level += 1;
            }
            self.visit_children(&branch.children);
        }
        if control_flow_open {
            self.indent_level = self.indent_level.saturating_sub(1);
            self.emit_line("}");
        }
    }

    /// Visit a for node.
    fn visit_for(&mut self, for_node: &ForNode) {
        let parse_result = &for_node.parse_result;

        self.emit_line("// v-for scope");
        self.emit_line("{");
        self.indent_level += 1;

        let value_pattern = parse_result
            .value
            .as_ref()
            .or(for_node.value_alias.as_ref())
            .map(expression_source);
        let key_alias = parse_result
            .key
            .as_ref()
            .or(for_node.key_alias.as_ref())
            .and_then(extract_var_name);
        let index_alias = parse_result
            .index
            .as_ref()
            .or(for_node.object_index_alias.as_ref())
            .and_then(extract_var_name);

        // Emit the source expression
        let source_expr = &parse_result.source;
        let source_var_name = match source_expr {
            ExpressionNode::Simple(simple) => {
                if !simple.content.is_empty() {
                    let expr_index = self.expr_counter;
                    self.expr_counter += 1;
                    self.emit_generated_line(|output| {
                        append!(*output, "const __expr_{expr_index} = {};", simple.content);
                    });
                    Some(format!("__expr_{expr_index}"))
                } else {
                    None
                }
            }
            ExpressionNode::Compound(_) => {
                self.emit_expression(source_expr, "v-for source");
                Some(format!("__expr_{}", self.expr_counter.saturating_sub(1)))
            }
        };

        let loop_emitted = source_var_name.as_deref().is_some_and(|source_var_name| {
            value_pattern.is_some_and(|value_pattern| {
                self.emit_v_for_loop_open(
                    value_pattern.trim(),
                    key_alias.as_deref(),
                    index_alias.as_deref(),
                    source_var_name,
                )
            })
        });
        profile!(
            "croquis.virtual_ts.template.for_children",
            self.visit_children(&for_node.children)
        );
        if loop_emitted {
            self.indent_level = self.indent_level.saturating_sub(1);
            self.emit_line("}");
        }

        self.indent_level = self.indent_level.saturating_sub(1);
        self.emit_line("}");
    }

    fn emit_v_for_scope_loop_open(
        &mut self,
        aliases: &VForScopeAliases,
        source_var_name: &str,
    ) -> bool {
        self.emit_v_for_loop_open(
            aliases.value_pattern.as_str(),
            aliases
                .key_alias
                .as_ref()
                .map(|alias: &vize_carton::CompactString| alias.as_str()),
            aliases
                .index_alias
                .as_ref()
                .map(|alias: &vize_carton::CompactString| alias.as_str()),
            source_var_name,
        )
    }

    fn emit_v_for_loop_open(
        &mut self,
        value_pattern: &str,
        key_alias: Option<&str>,
        index_alias: Option<&str>,
        source_var_name: &str,
    ) -> bool {
        if value_pattern.is_empty() {
            return false;
        }

        match (key_alias, index_alias) {
            (None, None) => {
                self.emit_line(&format!(
                    "for (const {} of {}) {{",
                    value_pattern, source_var_name
                ));
                self.indent_level += 1;
                true
            }
            (Some(index), None) => {
                self.emit_line(&format!(
                    "for (const [{}, {}] of Array.from({}).entries()) {{",
                    index, value_pattern, source_var_name
                ));
                self.indent_level += 1;
                true
            }
            (Some(key), Some(index)) => {
                self.emit_line(&format!(
                    "for (const [{}, {}] of Array.from({}).entries()) {{",
                    index, value_pattern, source_var_name
                ));
                self.indent_level += 1;
                self.emit_line(&format!("const {} = {};", key, index));
                true
            }
            (None, Some(index)) => {
                self.emit_line(&format!(
                    "for (const [{}, {}] of Array.from({}).entries()) {{",
                    index, value_pattern, source_var_name
                ));
                self.indent_level += 1;
                true
            }
        }
    }

    /// Emit a TypeScript expression with source mapping.
    pub(crate) fn emit_expression(&mut self, expr: &ExpressionNode, context: &str) {
        profile!("croquis.virtual_ts.emit_expression", {
            match expr {
                ExpressionNode::Simple(simple) => {
                    if simple.content.is_empty() {
                        return;
                    }

                    let expr_index = self.expr_counter;
                    self.expr_counter += 1;

                    // Calculate positions for mapping
                    let prefix_len = self.indent_level * 2
                        + "const ".len()
                        + "__expr_".len()
                        + decimal_len(expr_index)
                        + " = ".len();
                    let expr_start = self.gen_offset + prefix_len as u32;
                    let expr_end = expr_start + simple.content.len() as u32;

                    let source_start = simple.loc.start.offset + self.block_offset;
                    let source_end = simple.loc.end.offset + self.block_offset;

                    // Create mapping
                    self.mappings.push(SourceMapping::with_data(
                        SourceRange::new(source_start, source_end),
                        SourceRange::new(expr_start, expr_end),
                        MappingData::Expression {
                            text: simple.content.to_compact_string(),
                        },
                    ));

                    self.emit_generated_line(|output| {
                        append!(*output, "const __expr_{expr_index} = {};", simple.content);
                    });
                }
                ExpressionNode::Compound(_) => {
                    let expr_index = self.expr_counter;
                    self.expr_counter += 1;
                    self.emit_generated_line(|output| {
                        append!(
                            *output,
                            "const __expr_{expr_index} = void 0 as any; // {context} compound"
                        );
                    });
                }
            }
        });
    }

    fn emit_mapped_expression_line(
        &mut self,
        expr: &ExpressionNode,
        prefix: &str,
        suffix: &str,
    ) -> bool {
        let ExpressionNode::Simple(simple) = expr else {
            return false;
        };
        if simple.content.is_empty() {
            return false;
        }

        let expr_start = self.gen_offset + (self.indent_level * 2 + prefix.len()) as u32;
        let expr_end = expr_start + simple.content.len() as u32;
        let source_start = simple.loc.start.offset + self.block_offset;
        let source_end = simple.loc.end.offset + self.block_offset;

        self.mappings.push(SourceMapping::with_data(
            SourceRange::new(source_start, source_end),
            SourceRange::new(expr_start, expr_end),
            MappingData::Expression {
                text: simple.content.to_compact_string(),
            },
        ));

        self.emit_generated_line(|output| {
            output.push_str(prefix);
            output.push_str(simple.content.as_str());
            output.push_str(suffix);
        });
        true
    }
}

fn decimal_len(mut value: u32) -> usize {
    let mut len = 1;
    while value >= 10 {
        value /= 10;
        len += 1;
    }
    len
}

fn element_control_flow_condition<'a>(
    element: &'a ElementNode<'a>,
) -> Option<&'a ExpressionNode<'a>> {
    element.props.iter().find_map(|prop| {
        let PropNode::Directive(dir) = prop else {
            return None;
        };
        matches!(dir.name.as_str(), "if" | "else-if")
            .then_some(dir.exp.as_ref())
            .flatten()
    })
}

fn is_control_flow_directive(name: &str) -> bool {
    matches!(name, "if" | "else-if" | "else")
}

fn extract_var_name(expr: &ExpressionNode) -> Option<String> {
    match expr {
        ExpressionNode::Simple(simple) => {
            let name = simple.content.trim();
            is_simple_identifier(name).then_some(name.to_compact_string())
        }
        ExpressionNode::Compound(compound) => {
            use vize_relief::ast::CompoundExpressionChild;
            if let Some(CompoundExpressionChild::Simple(simple)) = compound.children.first() {
                let name = simple.content.trim();
                return is_simple_identifier(name).then_some(name.to_compact_string());
            }
            None
        }
    }
}

fn is_simple_identifier(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_alphanumeric() || c == '_' || c == '$')
}

fn expression_source<'a>(expr: &'a ExpressionNode<'a>) -> &'a str {
    match expr {
        ExpressionNode::Simple(simple) => simple.content.as_str(),
        ExpressionNode::Compound(compound) => compound.loc.source.as_str(),
    }
}
