/** Offline, deterministic Rust metadata from the complete pinned Microsoft CSS data. */
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const INPUT = new URL("../../data/css/fixtures/web-custom-data.json.txt", import.meta.url);
const COLORS = new URL("../../data/css/named-colors.json", import.meta.url);
const OUTPUT = new URL("../../../crates/vize_maestro/src/ide/style/data/", import.meta.url);
const SNAPSHOT_SHA = "7f228ab474664fe2a565fd88a2835fb6dda57a31da03aead96b14b965a5e205f";
const COLORS_SHA = "af6ce64a9eab7e00dbd09a104ee3e4d79477e3a05f5db88e75ac1e2dc74389e0";
const CHUNK_SIZE = 225;
const FAMILIES = [
  ["properties", "properties", 888],
  ["atDirectives", "at_rules", 25],
  ["pseudoClasses", "pseudo_classes", 111],
  ["pseudoElements", "pseudo_elements", 90],
] as const;
const ENTRY_FIELDS = new Set([
  "name",
  "description",
  "syntax",
  "references",
  "values",
  "atRule",
  "status",
  "restrictions",
  "browsers",
  "baseline",
  "relevance",
  "descriptors",
  "type",
]);
const VALUE_FIELDS = new Set(["name", "description", "browsers", "baseline"]);
const HEADER = [
  "// Generated by tools/commands/fixtures/generate-css-catalog.ts; do not edit.",
  "// Microsoft vscode-css-languageservice 2a253759802c9aba0d71b30e369fb65f1f062b5c.",
  "// Copyright (c) Microsoft. MIT: tools/data/css/LICENSE.microsoft.txt.",
].join("\n");

function record(value: unknown): asserts value is Record<string, unknown> {
  assert.ok(value !== null && typeof value === "object" && !Array.isArray(value));
}

function array(value: unknown): readonly unknown[] {
  assert.ok(Array.isArray(value));
  return value;
}

function text(value: unknown): string {
  assert.equal(typeof value, "string");
  assert.ok(typeof value === "string");
  return value;
}

function named(value: unknown): string {
  record(value);
  const name = text(value.name);
  assert.ok(name.length > 0 && /^[\x20-\x7e]+$/.test(name), "Catalog names must be ASCII");
  return name;
}

function fields(value: Record<string, unknown>, allowed: ReadonlySet<string>): void {
  for (const key of Object.keys(value)) assert.ok(allowed.has(key), `Unpreserved field: ${key}`);
}

function quote(value: unknown): string {
  let result = '"';
  for (const character of text(value)) {
    const point = character.codePointAt(0);
    assert.ok(point !== undefined && (point < 0xd800 || point > 0xdfff));
    if (character === "\\") result += "\\\\";
    else if (character === '"') result += '\\"';
    else if (character === "\n") result += "\\n";
    else if (character === "\r") result += "\\r";
    else if (character === "\t") result += "\\t";
    else if (point < 0x20 || point === 0x7f) result += `\\u{${point.toString(16)}}`;
    else result += character;
  }
  return result + '"';
}

function optional(value: unknown): string {
  return value === undefined ? "None" : `Some(${quote(value)})`;
}

function strings(value: unknown): string {
  return value === undefined ? "&[]" : `&[${array(value).map(quote).join(", ")}]`;
}

function baseline(value: unknown): string {
  if (value === undefined) return "None";
  record(value);
  fields(value, new Set(["status", "baseline_low_date", "baseline_high_date"]));
  assert.ok(["high", "low", "false"].includes(text(value.status)));
  return `Some(CssBaseline { status: ${quote(value.status)}, low_date: ${optional(value.baseline_low_date)}, high_date: ${optional(value.baseline_high_date)} })`;
}

function references(value: unknown): string {
  if (value === undefined) return "&[]";
  return `&[${array(value)
    .map((reference) => {
      record(reference);
      fields(reference, new Set(["name", "url"]));
      assert.ok(text(reference.url).startsWith("https://"), "Reference must retain an HTTPS URL");
      return `CssReference { name: ${quote(reference.name)}, url: ${quote(reference.url)} }`;
    })
    .join(", ")}]`;
}

function values(value: unknown): string {
  if (value === undefined) return "&[]";
  // Every owned value stays in original order, including original duplicate rows.
  return `&[${array(value)
    .map((item) => {
      record(item);
      fields(item, VALUE_FIELDS);
      return `CssValue { name: ${quote(named(item))}, description: ${optional(item.description)}, browsers: ${strings(item.browsers)}, baseline: ${baseline(item.baseline)} }`;
    })
    .join(", ")}]`;
}

function relevance(value: unknown): string {
  if (value === undefined) return "None";
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0 || value > 65535) {
    throw new Error("Relevance must be an unsigned 16-bit integer");
  }
  return `Some(${value.toString()})`;
}

function entry(value: unknown): string {
  record(value);
  fields(value, ENTRY_FIELDS);
  const name = named(value);
  assert.equal(name, name.toLowerCase(), "Index keys must be lowercase ASCII");
  const descriptors =
    value.descriptors === undefined
      ? "&[]"
      : `&[${array(value.descriptors).map(entry).join(", ")}]`;
  return `CssEntry { name: ${quote(name)}, description: ${optional(value.description)}, syntax: ${optional(value.syntax)}, references: ${references(value.references)}, values: ${values(value.values)}, at_rule: ${optional(value.atRule)}, status: ${optional(value.status)}, restrictions: ${strings(value.restrictions)}, browsers: ${strings(value.browsers)}, baseline: ${baseline(value.baseline)}, relevance: ${relevance(value.relevance)}, descriptors: ${descriptors}, entry_type: ${optional(value.type)} }`;
}

function uniqueOriginal(entries: readonly unknown[]): readonly unknown[] {
  const seen = new Set<string>();
  return entries.filter((item) => {
    const name = named(item);
    if (seen.has(name)) return false;
    seen.add(name);
    return true;
  });
}

function colorTable(): string {
  const raw = readFileSync(COLORS);
  assert.equal(createHash("sha256").update(raw).digest("hex"), COLORS_SHA);
  const source: unknown = JSON.parse(raw.toString("utf8"));
  record(source);
  fields(source, new Set(["colors", "colorKeywords"]));
  record(source.colors);
  record(source.colorKeywords);
  const namedColors = source.colors;
  assert.equal(Object.keys(namedColors).length, 148);
  assert.equal(Object.keys(source.colorKeywords).length, 2);
  const colors = [...Object.entries(namedColors), ...Object.entries(source.colorKeywords)]
    .map(([name, description]) => {
      assert.ok(/^[a-zA-Z]+$/.test(name));
      if (name in namedColors) assert.ok(/^#[0-9a-f]{6}$/.test(text(description)));
      return { name, description: text(description) };
    })
    .sort((a, b) => (a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1));
  assert.equal(new Set(colors.map(({ name }) => name.toLowerCase())).size, 150);
  const body = colors
    .map(
      ({ name, description }) =>
        `    CssValue { name: ${quote(name)}, description: Some(${quote(description)}), browsers: &[], baseline: None },`,
    )
    .join("\n");
  return `${HEADER}\nuse super::CssValue;\n\n#[rustfmt::skip]\npub(super) static VALUES: [CssValue; 150] = [\n${body}\n];\n`;
}

export function generatedCatalogFiles(): Map<string, string> {
  const raw = readFileSync(INPUT);
  assert.equal(createHash("sha256").update(raw).digest("hex"), SNAPSHOT_SHA);
  const source: unknown = JSON.parse(raw.toString("utf8"));
  record(source);
  fields(source, new Set(["version", ...FAMILIES.map(([sourceName]) => sourceName)]));
  assert.equal(source.version, 1.1);
  const generated = new Map<string, string>();
  let ownedValueCount = 0;
  for (const [sourceName, outputName, expectedCount] of FAMILIES) {
    const original = array(source[sourceName]);
    assert.equal(original.length, expectedCount);
    // Validate even rows shadowed by the upstream first-name-wins policy.
    for (const item of original) entry(item);
    if (sourceName === "properties") {
      for (const item of original) {
        record(item);
        ownedValueCount += item.values === undefined ? 0 : array(item.values).length;
      }
    }
    const effective = [...uniqueOriginal(original)].sort((left, right) => {
      const a = named(left),
        b = named(right);
      return a < b ? -1 : a > b ? 1 : 0;
    });
    const count =
      sourceName === "pseudoClasses" ? 110 : sourceName === "pseudoElements" ? 88 : expectedCount;
    assert.equal(effective.length, count);
    const index: string[] = [];
    for (let start = 0; start < effective.length; start += CHUNK_SIZE) {
      const chunk = effective.slice(start, start + CHUNK_SIZE);
      const chunkName = `${outputName}_${Math.floor(start / CHUNK_SIZE)}`;
      const body = chunk.map((item) => `    ${entry(item)},`).join("\n");
      const imports = ["CssBaseline", "CssEntry", "CssReference", "CssValue"]
        .filter((name) => body.includes(`${name} {`))
        .join(", ");
      generated.set(
        `${chunkName}.rs`,
        `${HEADER}\nuse super::{${imports}};\n\n#[rustfmt::skip]\npub(super) static ENTRIES: [CssEntry; ${chunk.length}] = [\n${body}\n];\n`,
      );
      for (let offset = 0; offset < chunk.length; offset++) {
        index.push(`&super::${chunkName}::ENTRIES[${offset}]`);
      }
    }
    const lines: string[] = [];
    for (let i = 0; i < index.length; i += 8)
      lines.push(`    ${index.slice(i, i + 8).join(", ")},`);
    generated.set(
      `${outputName}_index.rs`,
      `${HEADER}\nuse super::CssEntry;\n\n#[rustfmt::skip]\npub(super) static ENTRIES: [&CssEntry; ${effective.length}] = [\n${lines.join("\n")}\n];\n`,
    );
  }
  assert.equal(ownedValueCount, 2148);
  generated.set("colors.rs", colorTable());
  for (const [name, content] of generated) assert.ok(content.split("\n").length <= 350, name);
  return generated;
}

export function generate(check: boolean): void {
  const files = generatedCatalogFiles();
  if (check) {
    assert.deepEqual(
      readdirSync(OUTPUT)
        .filter((name) => name.endsWith(".rs"))
        .sort(),
      [...files.keys()].sort(),
    );
    for (const [name, expected] of files)
      assert.equal(readFileSync(new URL(name, OUTPUT), "utf8"), expected, name);
  } else {
    mkdirSync(OUTPUT, { recursive: true });
    for (const [name, content] of files) writeFileSync(new URL(name, OUTPUT), content);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  assert.ok(process.argv.slice(2).every((argument) => argument === "--check"));
  generate(process.argv.includes("--check"));
  console.log(
    "CSS static catalog: 888 properties, 2148 authored values, 25 at-rules, 110 pseudo classes, 88 pseudo elements, 150 color values; complete pinned source, first-name-wins indexes.",
  );
}
