// Runtime scenarios are retained in the full T1 suite. This is an explicit
// inventory of tests using the real tsgo requirement or LspSession launch
// capability, not a filename-prefix exclusion. Pure helper gates remain in T0.
export const mergeOnlyToolingTests = [
  "tests/tooling/canon-external-contracts.test.ts",
  "tests/tooling/canon-functional-slot-contracts.test.ts",
  "tests/tooling/canon-jsx-module-contracts.test.ts",
  "tests/tooling/canon-model-macro-contracts.test.ts",
  "tests/tooling/canon-options-binding-contracts.test.ts",
  "tests/tooling/canon-own-attrs-contracts.test.ts",
  "tests/tooling/canon-own-slot-contracts.test.ts",
  "tests/tooling/canon-script-syntax-ownership.test.ts",
  "tests/tooling/canon-self-component-contracts.test.ts",
  "tests/tooling/canon-template-directives.test.ts",
  "tests/tooling/canon-vfor-scope-contracts.test.ts",
  "tests/tooling/check-bench-gate.test.ts",
  "tests/tooling/cli-check-collection.test.ts",
  "tests/tooling/cli-check-diagnostics.test.ts",
  "tests/tooling/cli-check-json-shape.test.ts",
  "tests/tooling/cli-check-sub-package-dependency.test.ts",
  "tests/tooling/lsp-alias-barrel-definition.test.ts",
  "tests/tooling/lsp-aliased-dependency-revalidation.test.ts",
  "tests/tooling/lsp-authored-script-diagnostics.test.ts",
  "tests/tooling/lsp-authoring-core.test.ts",
  "tests/tooling/lsp-auto-insert-capabilities.test.ts",
  "tests/tooling/lsp-auto-insertion.test.ts",
  "tests/tooling/lsp-broken-file.test.ts",
  "tests/tooling/lsp-call-hierarchy-capability.test.ts",
  "tests/tooling/lsp-call-hierarchy-project.test.ts",
  "tests/tooling/lsp-call-hierarchy-vue-exports.test.ts",
  "tests/tooling/lsp-capabilities.test.ts",
  "tests/tooling/lsp-code-action-kinds.test.ts",
  "tests/tooling/lsp-completion-resolve.test.ts",
  "tests/tooling/lsp-completion-triggers.test.ts",
  "tests/tooling/lsp-component-documentation.test.ts",
  "tests/tooling/lsp-component-event-callback-diagnostics.test.ts",
  "tests/tooling/lsp-component-event-hover-type-backed.test.ts",
  "tests/tooling/lsp-component-reexport-navigation.test.ts",
  "tests/tooling/lsp-component-v-model-type-backed.test.ts",
  "tests/tooling/lsp-concurrent-edit-deadlock.test.ts",
  "tests/tooling/lsp-corsa-crash-recovery.test.ts",
  "tests/tooling/lsp-css-module-contracts.test.ts",
  "tests/tooling/lsp-davinci-ts40-projection-diagnostics.test.ts",
  "tests/tooling/lsp-declaration-capability.test.ts",
  "tests/tooling/lsp-definition-navigation.test.ts",
  "tests/tooling/lsp-diagnostics-lifecycle.test.ts",
  "tests/tooling/lsp-document-color.test.ts",
  "tests/tooling/lsp-document-features.test.ts",
  "tests/tooling/lsp-document-highlight.test.ts",
  "tests/tooling/lsp-document-link.test.ts",
  "tests/tooling/lsp-editor-feature-isolation.test.ts",
  "tests/tooling/lsp-editor-feature-routing.test.ts",
  "tests/tooling/lsp-editor-production-gates.test.ts",
  "tests/tooling/lsp-fallthrough-attrs.test.ts",
  "tests/tooling/lsp-file-create-delete.test.ts",
  "tests/tooling/lsp-file-rename-workspace.test.ts",
  "tests/tooling/lsp-folding-range.test.ts",
  "tests/tooling/lsp-hover-template.test.ts",
  "tests/tooling/lsp-hover-type-backed.test.ts",
  "tests/tooling/lsp-implementation-capability.test.ts",
  "tests/tooling/lsp-imported-component-hover-type-backed.test.ts",
  "tests/tooling/lsp-imported-component-reexport-hover-type-backed.test.ts",
  "tests/tooling/lsp-initial-diagnostics-version.test.ts",
  "tests/tooling/lsp-inlay-codelens.test.ts",
  "tests/tooling/lsp-inline-code-actions.test.ts",
  "tests/tooling/lsp-invalid-params.test.ts",
  "tests/tooling/lsp-jsx-component-lifecycle.test.ts",
  "tests/tooling/lsp-linked-editing.test.ts",
  "tests/tooling/lsp-multi-root-workspace.test.ts",
  "tests/tooling/lsp-native-code-actions.test.ts",
  "tests/tooling/lsp-native-event-authoring.test.ts",
  "tests/tooling/lsp-on-type-formatting.test.ts",
  "tests/tooling/lsp-own-attrs-authoring.test.ts",
  "tests/tooling/lsp-own-slot-authoring.test.ts",
  "tests/tooling/lsp-pattern-reference.test.ts",
  "tests/tooling/lsp-protocol-resilience.test.ts",
  "tests/tooling/lsp-publish-supersession.test.ts",
  "tests/tooling/lsp-range-formatting.test.ts",
  "tests/tooling/lsp-reactive-hover-type-backed.test.ts",
  "tests/tooling/lsp-rename-guards.test.ts",
  "tests/tooling/lsp-request-cancellation.test.ts",
  "tests/tooling/lsp-rich-authoring.test.ts",
  "tests/tooling/lsp-roadmap-completion.test.ts",
  "tests/tooling/lsp-script-completion-boundary.test.ts",
  "tests/tooling/lsp-selection-range.test.ts",
  "tests/tooling/lsp-server-restart.test.ts",
  "tests/tooling/lsp-sfc-tsx-script-typecheck.test.ts",
  "tests/tooling/lsp-signature-help-capability.test.ts",
  "tests/tooling/lsp-smoke.test.ts",
  "tests/tooling/lsp-structural-identity.test.ts",
  "tests/tooling/lsp-symlinked-node-modules.test.ts",
  "tests/tooling/lsp-template-completion.test.ts",
  "tests/tooling/lsp-template-scope-hover-navigation.test.ts",
  "tests/tooling/lsp-type-definition-capability.test.ts",
  "tests/tooling/lsp-typecheck-jsx-component.test.ts",
  "tests/tooling/lsp-typecheck-template.test.ts",
  "tests/tooling/lsp-untitled-lifecycle.test.ts",
  "tests/tooling/lsp-vue-file-lifecycle.test.ts",
  "tests/tooling/lsp-vue-language-tools-oracles.test.ts",
  "tests/tooling/lsp-watched-refresh.test.ts",
  "tests/tooling/lsp-watcher-revalidation.test.ts",
  "tests/tooling/lsp-workspace-folder-changes.test.ts",
  "tests/tooling/lsp-workspace-semantic.test.ts",
  "tests/tooling/lsp-workspace-symbol-emits.test.ts",
  "tests/tooling/production-readiness.test.ts",
  "tests/tooling/real-project-lsp.test.ts",
  "tests/tooling/typecheck-baseline-isolation.test.ts",
  "tests/tooling/typecheck-baseline-project-composite.test.ts",
  "tests/tooling/typecheck-baseline-project.test.ts",
] as const;

// Audited contracts read plan/ledger files or synthetic fixture trees. Their
// imported modules are added by the selector, including transitive helpers.
// Unlisted tests retain the broad tooling inputs until separately audited.
export const toolingTestScopes = [
  {
    input: "toolingRustCorpus",
    tests: [
      "tests/tooling/davinci-fact-spec-corpus.test.ts",
      "tests/tooling/davinci-complexity-corpus.test.ts",
      "tests/tooling/davinci-metamorphic-corpus.test.ts",
    ],
  },
  {
    input: "toolingMoonBuild",
    tests: ["tests/tooling/moonbit-warnings.test.ts"],
  },
  {
    input: "toolingBenchCompare",
    tests: ["tests/tooling/davinci-bench-compare.test.ts"],
  },
  {
    input: "toolingPlans",
    tests: [
      "tests/tooling/davinci-phase2-contract-status.test.ts",
      "tests/tooling/davinci-phase3-contract-status.test.ts",
      "tests/tooling/davinci-phase4-contract-status.test.ts",
      "tests/tooling/davinci-phase5-contract-status.test.ts",
      "tests/tooling/davinci-phase6-contract-status.test.ts",
      "tests/tooling/davinci-storage-summary.test.ts",
    ],
  },
  {
    input: "toolingLedgers",
    tests: ["tests/tooling/davinci-phase2-ledger.test.ts"],
  },
  {
    input: "toolingFixtureUnits",
    tests: [
      "tests/tooling/typecheck-baseline-ambient.test.ts",
      "tests/tooling/typecheck-baseline-isolation-*.test.ts",
      "tests/tooling/typecheck-baseline-outside-*.test.ts",
      "tests/tooling/typecheck-divergence.test.ts",
    ],
  },
] as const;
