// Generated by `nuxi prepare` for a plugin that returns `provide: { shout }`.
// A generated declaration file lives inside the project, so the virtual project
// mirrors it — and the mirrored copy has to keep resolving `"vue"` to the same
// module the generated template code imports.
declare module "vue" {
  interface ComponentCustomProperties {
    $shout: (label: string) => string;
  }
}

export {};
