//! TS-31 fixture battery: authored anchors resolved against fixture sources.
//!
//! The oracle is the fixture file. Every anchor names the authored token by
//! text and occurrence, so its byte span is computed from the authored source
//! alone and never from the map under measurement.

use std::path::Path;

use serde::Deserialize;

/// A TS-31 mapping category, spelled as in `budgets.toml`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Category {
    StaticTemplate,
    RewrittenIdentifier,
    SectionBoundary,
    TextMatchingRecovery,
    RewrittenStatement,
}

impl Category {
    fn parse(text: &str) -> Category {
        match text {
            "static-template" => Category::StaticTemplate,
            "rewritten-identifier" => Category::RewrittenIdentifier,
            "section-boundary" => Category::SectionBoundary,
            "text-matching-recovery" => Category::TextMatchingRecovery,
            "rewritten-statement" => Category::RewrittenStatement,
            other => panic!("unknown TS-31 category `{other}`"),
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Category::StaticTemplate => "static-template",
            Category::RewrittenIdentifier => "rewritten-identifier",
            Category::SectionBoundary => "section-boundary",
            Category::TextMatchingRecovery => "text-matching-recovery",
            Category::RewrittenStatement => "rewritten-statement",
        }
    }
}

/// A compiler backend whose map is measured.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Backend {
    Dom,
    Vapor,
    Ssr,
    /// The structured SFC module map `compile_sfc` attaches.
    Sfc,
}

impl Backend {
    pub fn as_str(self) -> &'static str {
        match self {
            Backend::Dom => "dom",
            Backend::Vapor => "vapor",
            Backend::Ssr => "ssr",
            Backend::Sfc => "sfc",
        }
    }
}

/// What the generated side must look like at a byte-exact mapping.
#[derive(Debug, Clone)]
pub enum Emitted {
    /// The generated bytes at the mapping start with this text.
    Verbatim(std::string::String),
    /// The generated bytes start with this identifier, optionally behind one
    /// context rewrite prefix, and the identifier ends at a word boundary.
    Identifier(std::string::String),
    /// The generated bytes start with the backend's structural construct.
    PerBackend {
        dom: std::string::String,
        vapor: std::string::String,
        ssr: std::string::String,
    },
}

/// One authored anchor with its resolved byte span.
#[derive(Debug, Clone)]
pub struct Anchor {
    /// Stable report key: `<fixture>:<token>@<line>:<column>` (1-based).
    pub id: std::string::String,
    pub category: Category,
    pub start: usize,
    pub len: usize,
    pub emitted: Emitted,
    /// Backends that by design emit no code for this authored token (SSR
    /// drops event listeners). The harness verifies the absence instead of
    /// measuring a mapping.
    pub absent: Vec<Backend>,
}

/// One fixture source and its anchors.
#[derive(Debug)]
pub struct Fixture {
    pub name: std::string::String,
    pub source: std::string::String,
    pub anchors: Vec<Anchor>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct BatteryFile {
    fixture: Vec<FixtureSpec>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct FixtureSpec {
    name: std::string::String,
    source: std::string::String,
    anchor: Vec<AnchorSpec>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct AnchorSpec {
    category: std::string::String,
    find: std::string::String,
    #[serde(default)]
    nth: usize,
    token: Option<std::string::String>,
    generated: Option<std::string::String>,
    dom: Option<std::string::String>,
    vapor: Option<std::string::String>,
    ssr: Option<std::string::String>,
    #[serde(default)]
    absent: Vec<std::string::String>,
}

/// Load a battery file relative to the crate's `tests/fixtures/ts31`.
pub fn load(file: &str) -> Vec<Fixture> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/ts31")
        .join(file);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    let battery: BatteryFile =
        toml::from_str(&text).unwrap_or_else(|error| panic!("parse {}: {error}", path.display()));
    battery.fixture.into_iter().map(resolve_fixture).collect()
}

fn resolve_fixture(spec: FixtureSpec) -> Fixture {
    let anchors = spec
        .anchor
        .iter()
        .map(|anchor| resolve_anchor(&spec.name, &spec.source, anchor))
        .collect::<Vec<_>>();
    let mut ids = anchors.iter().map(|a| a.id.as_str()).collect::<Vec<_>>();
    ids.sort_unstable();
    let before = ids.len();
    ids.dedup();
    assert_eq!(
        ids.len(),
        before,
        "fixture `{}` repeats an anchor",
        spec.name
    );
    Fixture {
        name: spec.name,
        source: spec.source,
        anchors,
    }
}

fn resolve_anchor(fixture: &str, source: &str, spec: &AnchorSpec) -> Anchor {
    let category = Category::parse(&spec.category);
    let context = source
        .match_indices(spec.find.as_str())
        .nth(spec.nth)
        .unwrap_or_else(|| panic!("{fixture}: `{}` #{} not in source", spec.find, spec.nth))
        .0;
    let token = spec.token.as_deref().unwrap_or(spec.find.as_str());
    let start = context
        + spec
            .find
            .find(token)
            .unwrap_or_else(|| panic!("{fixture}: token `{token}` not inside `{}`", spec.find));
    let emitted = match category {
        Category::StaticTemplate
        | Category::TextMatchingRecovery
        | Category::RewrittenStatement => {
            Emitted::Verbatim(spec.generated.clone().unwrap_or_else(|| token.into()))
        }
        Category::RewrittenIdentifier => {
            assert_identifier_token(fixture, source, start, token);
            assert_eq!(
                spec.generated, None,
                "{fixture}: identifiers derive `generated`"
            );
            Emitted::Identifier(token.into())
        }
        Category::SectionBoundary => {
            assert_eq!(
                token, "<",
                "{fixture}: a section boundary anchors its opening `<`"
            );
            let backend = |value: &Option<std::string::String>, name: &str| {
                value
                    .clone()
                    .unwrap_or_else(|| panic!("{fixture}: boundary `{}` needs `{name}`", spec.find))
            };
            Emitted::PerBackend {
                dom: backend(&spec.dom, "dom"),
                vapor: backend(&spec.vapor, "vapor"),
                ssr: backend(&spec.ssr, "ssr"),
            }
        }
    };
    if category != Category::SectionBoundary {
        assert_eq!(
            (&spec.dom, &spec.vapor, &spec.ssr),
            (&None, &None, &None),
            "{fixture}: only section boundaries carry per-backend constructs"
        );
    }
    let absent = spec
        .absent
        .iter()
        .map(|name| match name.as_str() {
            "dom" => Backend::Dom,
            "vapor" => Backend::Vapor,
            "ssr" => Backend::Ssr,
            other => panic!("{fixture}: unknown backend `{other}` in `absent`"),
        })
        .collect();
    let (line, column) = line_column(source, start);
    Anchor {
        id: std::format!("{fixture}:{token}@{line}:{column}"),
        category,
        start,
        len: token.len(),
        emitted,
        absent,
    }
}

/// An identifier anchor must be a whole identifier in the authored source.
fn assert_identifier_token(fixture: &str, source: &str, start: usize, token: &str) {
    let before = source[..start].chars().next_back();
    let after = source[start + token.len()..].chars().next();
    let bounded = !before.is_some_and(is_identifier_char) && !after.is_some_and(is_identifier_char);
    let shaped = token.chars().all(is_identifier_char);
    assert_eq!(
        (bounded, shaped),
        (true, true),
        "{fixture}: `{token}` is not a whole identifier"
    );
}

pub fn is_identifier_char(ch: char) -> bool {
    ch.is_alphanumeric() || ch == '_' || ch == '$'
}

/// 1-based line and column (in chars) of `offset` in `source`.
fn line_column(source: &str, offset: usize) -> (usize, usize) {
    let before = &source[..offset];
    let line = before.matches('\n').count() + 1;
    let line_start = before.rfind('\n').map_or(0, |index| index + 1);
    (line, source[line_start..offset].chars().count() + 1)
}
