#!/usr/bin/env node --experimental-strip-types

import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export const lintRuleSnapshotPath = path.join(
  root,
  "crates/vize_patina/src/snapshots/vize_patina__preset__tests__lint_preset_rule_membership.snap",
);

export const lintRuleTypesPath = path.join(root, "npm/vize/src/types/rules.ts");

export function collectLintRuleNames(snapshotContent: string): string[] {
  const frontmatterEnd = snapshotContent.indexOf("\n---\n", 4);

  if (!snapshotContent.startsWith("---\n") || frontmatterEnd === -1) {
    throw new Error("Invalid insta snapshot format for lint preset rule membership");
  }

  const json = JSON.parse(snapshotContent.slice(frontmatterEnd + "\n---\n".length)) as unknown;

  if (json == null || typeof json !== "object" || Array.isArray(json)) {
    throw new Error("Expected lint preset snapshot to contain an object");
  }

  const ruleNames = new Set<string>();
  for (const [preset, names] of Object.entries(json)) {
    assert(Array.isArray(names), `Expected ${preset} rules to be an array`);

    for (const name of names) {
      assert.equal(typeof name, "string", `Expected ${preset} rule name to be a string`);
      ruleNames.add(name);
    }
  }

  return [...ruleNames].sort();
}

export function generateLintRuleTypes(ruleNames: readonly string[]): string {
  const ruleEntries = ruleNames.map((name) => `  ${JSON.stringify(name)},`).join("\n");

  return `// This file is generated by scripts/generate-vize-rule-types.ts.
// Do not edit it by hand.

import type { RuleSeverity } from "./core.js";

export const LINT_RULE_NAMES = [
${ruleEntries}
] as const;

export type LintRuleName = (typeof LINT_RULE_NAMES)[number];

export type LintRulesConfig = Partial<Record<LintRuleName, RuleSeverity>>;
`;
}

export function generateLintRuleTypesFromSnapshot(): string {
  return generateLintRuleTypes(
    collectLintRuleNames(fs.readFileSync(lintRuleSnapshotPath, "utf-8")),
  );
}

export function writeLintRuleTypes(): void {
  fs.writeFileSync(lintRuleTypesPath, generateLintRuleTypesFromSnapshot());
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeLintRuleTypes();
}
