/** Existing English subgroup routes and their actual source-rule membership. */
export const catalogueSubgroups: Record<string, { title: string; rules: readonly string[] }> = {
  "accessibility-core": {
    title: "Accessibility core",
    rules: [
      "a11y/alt-text",
      "a11y/anchor-has-content",
      "a11y/anchor-is-valid",
      "a11y/aria-props",
      "a11y/aria-role",
      "a11y/aria-unsupported-elements",
      "a11y/click-events-have-key-events",
      "a11y/form-control-has-label",
    ],
  },
  "accessibility-integrity": {
    title: "Accessibility integrity",
    rules: [
      "a11y/no-role-presentation-on-focusable",
      "a11y/no-static-element-interactions",
      "a11y/placeholder-label-option",
      "a11y/role-has-required-aria-props",
      "a11y/tabindex-no-positive",
      "a11y/use-list",
      "vue/use-unique-element-ids",
    ],
  },
  "accessibility-interactions": {
    title: "Accessibility interactions",
    rules: [
      "a11y/mouse-events-have-key-events",
      "a11y/no-access-key",
      "a11y/no-aria-hidden-on-focusable",
      "a11y/no-autofocus",
      "a11y/no-distracting-elements",
      "a11y/no-i-for-icon",
      "a11y/no-redundant-roles",
      "a11y/no-refer-to-non-existent-id",
    ],
  },
  "accessibility-structure": {
    title: "Accessibility structure",
    rules: [
      "a11y/heading-has-content",
      "a11y/heading-levels",
      "a11y/iframe-has-title",
      "a11y/img-alt",
      "a11y/interactive-supports-focus",
      "a11y/label-has-for",
      "a11y/landmark-roles",
      "a11y/media-has-caption",
    ],
  },
  "vue-components": {
    title: "Vue Rules: Components and Props",
    rules: [
      "vue/no-mutating-props",
      "vue/no-unused-components",
      "vue/no-unused-properties",
      "vue/require-component-is",
      "vue/component-definition-name-casing",
      "vue/component-name-in-template-casing",
      "vue/multi-word-component-names",
      "vue/no-non-component-keep-alive-child",
      "vue/no-reserved-component-names",
      "vue/require-component-registration",
    ],
  },
  "vue-directive-validity": {
    title: "Vue Rules: Directive Validity",
    rules: [
      "vue/valid-v-bind",
      "vue/valid-v-else",
      "vue/valid-v-for",
      "vue/valid-v-if",
      "vue/valid-v-memo",
      "vue/valid-v-model",
      "vue/valid-v-on",
      "vue/valid-v-show",
      "vue/valid-v-slot",
    ],
  },
  "vue-directives": {
    title: "Vue Rules: Directive Conventions",
    rules: [
      "vue/scoped-event-names",
      "vue/use-v-on-exact",
      "vue/v-bind-style",
      "vue/v-on-style",
      "vue/v-slot-style",
      "vue/warn-custom-directive",
    ],
  },
  "vue-formatting": {
    title: "Vue Rules: Template Formatting",
    rules: [
      "vue/attribute-hyphenation",
      "vue/attribute-order",
      "vue/html-quotes",
      "vue/html-self-closing",
      "vue/mustache-interpolation-spacing",
      "vue/no-boolean-attr-value",
      "vue/no-inline-style",
      "vue/no-multi-spaces",
      "vue/prefer-props-shorthand",
      "vue/prop-name-casing",
      "vue/valid-attribute-name",
    ],
  },
  "vue-sfc": {
    title: "Vue Rules: SFC Blocks",
    rules: [
      "vue/no-preprocessor-lang",
      "vue/no-script-non-standard-lang",
      "vue/no-src-attribute",
      "vue/no-template-lang",
      "vue/require-scoped-style",
      "vue/sfc-element-order",
      "vue/single-style-block",
      "vue/warn-custom-block",
    ],
  },
  "vue-template-safety": {
    title: "Vue Rules: Template Safety",
    rules: [
      "vue/no-v-html",
      "vue/no-duplicate-attributes",
      "vue/no-unsafe-url",
      "vue/use-unique-element-ids",
      "vue/no-textarea-mustache",
      "vue/no-v-text-v-html-on-component",
      "vue/permitted-contents",
    ],
  },
  "vue-template-structure": {
    title: "Vue Rules: Template Structure",
    rules: [
      "vue/require-v-for-key",
      "vue/no-use-v-if-with-v-for",
      "vue/no-child-content",
      "vue/no-dupe-v-else-if",
      "vue/no-template-shadow",
      "vue/no-lone-template",
      "vue/no-template-key",
      "vue/no-unused-vars",
      "vue/no-useless-template-attributes",
    ],
  },
};
