/** Existing native category fragments, captured before replacing stale reader pages. */
export const legacyfr: Record<string, readonly string[]> = {
  accessibility: [
    "règles-d-accessibilité",
    "a11y-img-alt",
    "a11y-alt-text",
    "a11y-click-events-have-key-events",
    "a11y-interactive-supports-focus",
    "a11y-label-has-for",
    "a11y-form-control-has-label",
    "a11y-no-aria-hidden-on-focusable",
    "a11y-no-static-element-interactions",
    "a11y-tabindex-no-positive",
    "a11y-anchor-is-valid",
    "règles-supplémentaires-d-accessibilité",
  ],
  all: [
    "toutes-les-règles-de-patine",
    "catégories",
    "essentiel-48",
    "fortement-recommandé-12",
    "recommandé-42",
    "accessibilité-31",
    "conformité-html-9",
    "type-aware-5",
    "vapeur-7",
    "écosystème-9",
    "css-10",
    "musea-6",
    "script-60",
    "essential-48",
    "strongly-recommended-12",
    "recommended-42",
    "accessibility-31",
    "html-conformance-9",
    "vapor-7",
    "ecosystem-9",
  ],
  "cross-file": [
    "règles-croisées",
    "vize-croquis-cf-unmatched-inject",
    "vize-croquis-cf-unused-provide",
    "vize-croquis-cf-provide-without-symbol",
    "vize-croquis-cf-inject-without-symbol",
    "vize-croquis-cf-non-reactive-provide",
    "vize-croquis-cf-duplicate-id",
    "vize-croquis-cf-non-unique-id",
    "vize-croquis-cf-spread-breaks-reactivity",
    "vize-croquis-cf-reassignment-breaks-reactivity",
    "vize-croquis-cf-value-extraction-breaks-reactivity",
    "vize-croquis-cf-destructuring-breaks-reactivity",
    "vize-croquis-cf-hydration-risk",
    "vize-croquis-cf-async-boundary",
    "vize-croquis-cf-watcheffect-async",
    "vize-croquis-cf-injected-async-mutation-race",
    "orientation-de-mise-en-œuvre",
  ],
  ecosystem: [
    "règles-de-l-écosystème",
    "ecosystem-router-link-require-to",
    "ecosystem-vue-router-prefer-named-link",
    "ecosystem-vue-router-prefer-named-push",
    "ecosystem-nuxt-prefer-nuxt-link",
    "ecosystem-pinia-prefer-store-to-refs",
    "ecosystem-vue-i18n-no-missing-key",
    "ecosystem-void-link-require-href",
    "ecosystem-void-link-valid-method",
    "ecosystem-vue-test-utils-no-html-snapshot",
  ],
  html: [
    "règles-html",
    "html-id-duplication",
    "html-deprecated-element",
    "html-deprecated-attr",
    "html-no-consecutive-br",
    "html-require-datetime",
    "html-no-duplicate-dt",
    "html-no-empty-palpable-content",
  ],
  "musea-and-css": [
    "règles-de-la-musea-et-du-css",
    "musea-require-title",
    "musea-require-component",
    "musea-valid-variant",
    "musea-unique-variant-names",
    "musea-no-empty-variant",
    "musea-prefer-design-tokens",
    "css-no-important",
    "css-no-hardcoded-values",
    "css-no-id-selectors",
    "css-no-display-none",
    "css-no-v-bind-performance",
    "css-prefer-logical-properties",
    "css-prefer-slotted",
    "css-require-font-display",
    "règles-css-supplémentaires",
  ],
  ssr: ["règles-ssr", "ssr-no-browser-globals-in-ssr", "ssr-no-hydration-mismatch"],
  "type-and-script": [
    "règles-de-type-et-de-script",
    "type-require-typed-props",
    "type-require-typed-emits",
    "type-no-unsafe-template-binding",
    "type-no-floating-promises",
    "type-no-reactivity-loss",
    "checker-configuration",
    "script-no-options-api",
    "script-no-next-tick",
    "script-no-get-current-instance",
  ],
  vapor: [
    "règles-de-la-vapeur",
    "vapor-no-vue-lifecycle-events",
    "vapor-require-vapor-attribute",
    "vapor-no-inline-template",
    "vapor-prefer-static-class",
  ],
};
