/** Existing native category fragments, captured before replacing stale reader pages. */
export const legacyen: Record<string, readonly string[]> = {
  "accessibility-core": ["accessibility-core"],
  "accessibility-integrity": ["accessibility-integrity"],
  "accessibility-interactions": ["accessibility-interactions"],
  "accessibility-structure": ["accessibility-structure"],
  accessibility: ["accessibility-rules"],
  all: ["all-lint-rules", "single-file-rules-251", "project-rules-and-analyzer-contracts-66"],
  "cross-file": ["cross-file-rules", "project-specific-lint-ids", "published-analyzer-codes"],
  ecosystem: ["ecosystem-rules"],
  html: ["html-rules"],
  "musea-and-css": ["musea-and-css-rules"],
  "petite-vue": ["petite-vue-rules"],
  ssr: ["ssr-rules"],
  "type-and-script": ["type-and-script-rules"],
  vapor: ["vapor-rules"],
  "vue-components": [
    "vue-rules-components-and-props",
    "vue-no-mutating-props",
    "vue-no-unused-components",
    "vue-no-unused-properties",
    "vue-require-component-is",
    "vue-component-definition-name-casing",
    "vue-component-name-in-template-casing",
    "vue-multi-word-component-names",
    "vue-no-non-component-keep-alive-child",
    "vue-no-reserved-component-names",
    "vue-require-component-registration",
  ],
  "vue-directive-validity": [
    "vue-rules-directive-validity",
    "vue-valid-v-bind",
    "vue-valid-v-else",
    "vue-valid-v-for",
    "vue-valid-v-if",
    "vue-valid-v-memo",
    "vue-valid-v-model",
    "vue-valid-v-on",
    "vue-valid-v-show",
    "vue-valid-v-slot",
  ],
  "vue-directives": [
    "vue-rules-directive-conventions",
    "vue-scoped-event-names",
    "vue-use-v-on-exact",
    "vue-v-bind-style",
    "vue-v-on-style",
    "vue-v-slot-style",
    "vue-warn-custom-directive",
  ],
  "vue-formatting": [
    "vue-rules-template-formatting",
    "vue-attribute-hyphenation",
    "vue-attribute-order",
    "vue-html-quotes",
    "vue-html-self-closing",
    "vue-mustache-interpolation-spacing",
    "vue-no-boolean-attr-value",
    "vue-no-inline-style",
    "vue-no-multi-spaces",
    "vue-prefer-props-shorthand",
    "vue-prop-name-casing",
    "vue-valid-attribute-name",
  ],
  "vue-sfc": [
    "vue-rules-sfc-blocks",
    "vue-no-preprocessor-lang",
    "vue-no-script-non-standard-lang",
    "vue-no-src-attribute",
    "vue-no-template-lang",
    "vue-require-scoped-style",
    "vue-sfc-element-order",
    "vue-single-style-block",
    "vue-warn-custom-block",
  ],
  "vue-template-safety": [
    "vue-rules-template-safety",
    "vue-no-v-html",
    "vue-no-duplicate-attributes",
    "vue-no-unsafe-url",
    "vue-use-unique-element-ids",
    "vue-no-textarea-mustache",
    "vue-no-v-text-v-html-on-component",
    "vue-permitted-contents",
  ],
  "vue-template-structure": [
    "vue-rules-template-structure",
    "vue-require-v-for-key",
    "vue-no-use-v-if-with-v-for",
    "vue-no-child-content",
    "vue-no-dupe-v-else-if",
    "vue-no-template-shadow",
    "vue-no-lone-template",
    "vue-no-template-key",
    "vue-no-unused-vars",
    "vue-no-useless-template-attributes",
  ],
};
