export const scriptType1Explanations = [
  [
    "script/no-deprecated-dollar-scopedslots-api",
    "`this.$scopedSlots`, `ctx.$scopedSlots`, and the bare `$scopedSlots` reference use the Vue 2 scoped-slot API removed in Vue 3.",
    "Replacing `$scopedSlots` with `$slots` uses the unified slot surface. The example removes the deprecated spelling rather than establishing a setup context for the receivers.",
    "`this.$scopedSlots`、`ctx.$scopedSlots`、裸の `$scopedSlots` 参照が、Vue 3 で削除された Vue 2 の scoped slot API を使っています。",
    "`$scopedSlots` を `$slots` に置き換え、統合された slot API を使います。この例は削除された API 名の置換を示すもので、参照元の setup コンテキストを作る例ではありません。",
  ],
  [
    "script/no-deprecated-events-api",
    "The `$on`, `$once`, and `$off` calls use the instance event-bus methods removed in Vue 3.",
    "`$emit` remains valid, while event-bus subscription moves to the external emitter’s `on` method. The repair separates parent-directed emission from an external event bus.",
    "`$on`、`$once`、`$off` の呼び出しが、Vue 3 で削除されたインスタンスのイベントバスメソッドを使っています。",
    "有効な `$emit` は維持し、イベントバスへの購読は外部 emitter の `on` に移します。親へのイベント送信と外部イベントバスを別々の API で表します。",
  ],
  [
    "script/no-deprecated-props-default-this",
    "The prop default and validator read `this`, but those functions cannot rely on the component instance in Vue 3.",
    "The default reads `props.baseSize` from its argument, and the validator tests its `value` argument. Both stop depending on an unavailable instance receiver.",
    "prop の既定値関数と validator が `this` を参照していますが、Vue 3 ではこれらの関数からコンポーネントインスタンスに依存できません。",
    "既定値関数は引数の `props.baseSize` を使い、validator は引数の `value` を検査します。どちらも利用できないインスタンスの `this` に依存しなくなります。",
  ],
  [
    "script/no-dupe-keys",
    "`foo` is declared by both props and data, and `bar` by both computed and methods. Those declarations compete for the same component instance keys.",
    "The prop, data, and computed declarations use distinct names (`foo`, `bar`, and `baz`), eliminating both cross-option collisions.",
    "`foo` が props と data の両方に、`bar` が computed と methods の両方に宣言され、コンポーネントインスタンス上の同じキーを取り合っています。",
    "prop、data、computed に別々の名前 `foo`、`bar`、`baz` を使い、オプション間の重複を取り除きます。",
  ],
  [
    "script/no-duplicate-attr-inheritance",
    "The explicit `inheritAttrs: true` values restate Vue’s default. This rule reports that redundant literal even when no root `$attrs` spread is shown.",
    "`inheritAttrs: false` expresses a real opt-out, while the empty options object leaves default inheritance implicit. Neither restates the redundant `true` value.",
    "明示的な `inheritAttrs: true` が Vue の既定動作を繰り返しています。このルールは、ルートの `$attrs` 展開が例にない場合もこの冗長なリテラルを報告します。",
    "`inheritAttrs: false` は継承を無効にする指定であり、空のオプションは既定の継承を暗黙に使います。どちらも冗長な `true` を指定しません。",
  ],
  [
    "script/no-export-in-script-setup",
    "`export const count` attempts to expose a module export from `<script setup>`, where runtime exports are prohibited.",
    "Removing `export` keeps `count` as a setup binding rather than a module export.",
    "`export const count` が `<script setup>` からモジュールの値をエクスポートしようとしています。このブロックでは実行時の export は禁止されています。",
    "`export` を取り除き、`count` をモジュールの export ではなく setup の変数にします。",
  ],
  [
    "script/no-get-current-instance",
    "The Vapor-marked setup imports and calls `getCurrentInstance`, relying on an instance API this rule disallows for Vapor-oriented components.",
    '`inject("app-config")` obtains the explicitly provided configuration without importing or calling `getCurrentInstance`.',
    "Vapor を指定した setup が `getCurrentInstance` をインポートして呼び出し、Vapor 向けコンポーネントでこのルールが禁止するインスタンス API に依存しています。",
    '`inject("app-config")` で明示的に提供された設定を受け取り、`getCurrentInstance` のインポートも呼び出しも使いません。',
  ],
  [
    "script/no-import-compiler-macros",
    "The `vue` import includes `defineProps` and `defineEmits`, although these are compiler macros available directly in `<script setup>`.",
    "Removing the macro imports leaves both typed macro calls intact; no runtime import is needed for either declaration.",
    "`vue` から `defineProps` と `defineEmits` をインポートしていますが、これらは `<script setup>` で直接使えるコンパイラーマクロです。",
    "マクロのインポートを除き、型付きのマクロ呼び出しは保ちます。これらの宣言に実行時のインポートは不要です。",
  ],
  [
    "script/no-internal-imports",
    "Both imports address internal `dist` files rather than Vue’s public package entry point, coupling the component to build-file paths.",
    "Importing the required helpers from `vue` removes the dependency on internal distribution file locations.",
    "両方の import が Vue の公開エントリーポイントではなく内部の `dist` ファイルを参照し、コンポーネントをビルド成果物のパスに依存させています。",
    "必要なヘルパーを `vue` からインポートし、内部の配布ファイルの配置への依存を取り除きます。",
  ],
  [
    "script/no-multiple-slot-args",
    "The slot calls pass multiple positional arguments or spread an unknown argument list. Vue slots receive one props object, not a positional parameter list.",
    "`{ foo, bar }` combines the data into one argument; `slotProps` and the argument-free call also stay within the supported slot-call shape.",
    "slot 呼び出しが複数の位置引数、または個数不明の引数展開を渡しています。Vue の slot は位置引数の列ではなく、一つの props オブジェクトを受け取ります。",
    "`{ foo, bar }` でデータを一つの引数にまとめます。`slotProps` を渡す呼び出しと引数を省いた呼び出しも、対応する slot 呼び出し形式に収まります。",
  ],
  [
    "script/no-next-tick",
    "The Vapor-oriented component imports and awaits `nextTick`, introducing the DOM-flush scheduling dependency that this migration rule rejects.",
    "The input is obtained through `useTemplateRef` and focused at `onMounted`. The explicit mount boundary replaces the example’s `nextTick` dependency.",
    "Vapor 向けコンポーネントが `nextTick` をインポートして await し、この移行ルールが拒否する DOM 更新待ちの依存を作っています。",
    "`useTemplateRef` で input を取得し、`onMounted` でフォーカスします。例の `nextTick` への依存を、明示的なマウント時の処理に置き換えます。",
  ],
  [
    "script/no-options-api",
    "The default-export object declares Options API `data()`, a component option form prohibited by this rule.",
    "The component state becomes a Composition API `ref` in Vapor `<script setup>`, removing the Options API object and its `data` option.",
    "default export のオブジェクトに Options API の `data()` を宣言しており、このルールが禁止するコンポーネントオプションの形式です。",
    "状態を Vapor の `<script setup>` 内の Composition API `ref` に移し、Options API のオブジェクトと `data` オプションを取り除きます。",
  ],
  [
    "script/no-potential-component-option-typo",
    "The option is spelled `method`, one edit away from the recognized `methods` option; Vue would not treat it as the intended methods declaration.",
    "Changing the key to `methods` places `save()` under the recognized component option.",
    "オプション名が既知の `methods` から一文字欠けた `method` になり、意図したメソッド宣言として扱われません。",
    "キーを `methods` に修正し、`save()` を既知のコンポーネントオプション内に置きます。",
  ],
  [
    "script/no-reactive-destructure",
    "`const { count, name } = state` copies primitive properties out of the `reactive` object, losing their connection to subsequent property changes.",
    "Destructuring `toRefs(state)` creates refs for `count` and `name`, keeping each binding linked to the original reactive property.",
    "`const { count, name } = state` が `reactive` オブジェクトからプリミティブ値をコピーし、その後のプロパティ更新とのつながりを失います。",
    "`toRefs(state)` を分割代入して `count` と `name` の ref を作り、それぞれを元のリアクティブなプロパティにつなげます。",
  ],
  [
    "script/no-ref-as-operand",
    "`count + 1` uses the ref object itself as the arithmetic operand instead of the number it wraps.",
    "`count.value + 1` reads the wrapped number before adding one; script arithmetic requires this explicit ref access.",
    "`count + 1` は ref が包む数値ではなく、ref オブジェクトそのものを算術演算の対象にしています。",
    "`count.value + 1` で内側の数値を取り出してから加算します。script の演算では ref の値を明示的に参照します。",
  ],
  [
    "script/no-required-prop-with-default",
    '`title` is both required and given the fallback `"Untitled"`, combining a required-input contract with a default intended for missing input.',
    'Removing `required: true` makes `title` optional and leaves `"Untitled"` as its coherent fallback.',
    '`title` に必須指定と `"Untitled"` の既定値を同時に付け、必須の入力という契約と未指定時の代替値を併記しています。',
    '`required: true` を除いて `title` を任意入力にし、`"Untitled"` を未指定時の既定値として残します。',
  ],
  [
    "script/no-reserved-identifiers",
    "The bindings `__props`, `__emit`, and `__sfc__` use identifiers reserved for generated Vue compiler code.",
    "The ordinary names `props`, `emit`, and `componentData` avoid those generated identifiers while retaining props and emits declarations.",
    "変数名 `__props`、`__emit`、`__sfc__` が Vue コンパイラーの生成コード用に予約された識別子と重なっています。",
    "通常の名前 `props`、`emit`、`componentData` を使い、props と emits の宣言を保ったまま生成用識別子との重複を避けます。",
  ],
  [
    "script/no-reserved-keys",
    "The returned data key `$el` collides with Vue’s built-in component-instance property and also uses a reserved `$` prefix.",
    "Renaming the application data to `elementLabel` avoids the built-in instance surface and reserved prefix.",
    "data の `$el` が Vue 組み込みのインスタンスプロパティと重なり、予約された `$` 接頭辞も使っています。",
    "アプリケーションのデータ名を `elementLabel` に変え、組み込みのインスタンス API と予約接頭辞を避けます。",
  ],
  [
    "script/no-reserved-props",
    "The object-form `ref` and `$foo`, plus the array-form `key`, are reserved prop names. `ref` and `key` are framework controls, and `$`-prefixed names are rejected.",
    "The ordinary prop names `name` and `refValue` avoid the reserved names in both spelling and prefix.",
    "オブジェクト形式の `ref` と `$foo`、配列形式の `key` は予約された prop 名です。`ref` と `key` はフレームワーク用であり、`$` で始まる名前も拒否されます。",
    "通常の prop 名 `name` と `refValue` に変え、予約された名前と接頭辞を避けます。",
  ],
  [
    "script/no-restricted-globals",
    "The example reads the default restricted globals `process`, `localStorage`, and `sessionStorage` directly, bypassing the project’s explicit config and storage helpers.",
    "`useFeatureFlag`, `authStorage.read`, and `viewStorage.write` remove those direct restricted-global references. The remaining `window.scrollY` is not a default restriction of this rule; SSR safety is a separate concern.",
    "既定で制限されるグローバル `process`、`localStorage`、`sessionStorage` を直接参照し、設定やストレージ用の明示的なヘルパーを通していません。",
    "`useFeatureFlag`、`authStorage.read`、`viewStorage.write` に移し、制限対象のグローバルの直接参照を除きます。残る `window.scrollY` はこのルールの既定の制限対象ではなく、SSR の安全性は別途確認が必要です。",
  ],
];
