export const scriptType3Explanations = [
  [
    "script/require-prop-types",
    "The array entry declares only the name `status`; the `null` value and empty descriptor declare no runtime prop type either.",
    "`status: String` supplies a shorthand constructor, and `other` supplies `type: Number` inside its descriptor. Both props now carry type declarations.",
    "配列の要素は `status` という名前だけを宣言し、`null` の値と空の descriptor にも実行時の prop 型がありません。",
    "`status: String` で省略形式のコンストラクターを指定し、`other` の descriptor に `type: Number` を付けます。両方の props が型の宣言を持つようになります。",
  ],
  [
    "script/require-symbol-provide",
    "`provide` and `inject` use literal string keys such as `'user'` and `'theme'`, which can collide with another provider using the same spelling.",
    "The shared `UserKey` is created with `Symbol` and annotated as `InjectionKey<User>`; both calls pass that key instead of a literal string.",
    "`provide` と `inject` が `'user'`、`'theme'` のような文字列キーを使い、同じ綴りを使うほかの provider と衝突し得ます。",
    "共有する `UserKey` を `Symbol` で作り、`InjectionKey<User>` の型を付けます。両呼び出しに同じキーを渡し、文字列リテラルを使わないようにします。",
  ],
  [
    "script/require-typed-object-prop",
    "Bare `Object` and `Array` constructors describe only broad runtime categories, so neither `user` nor the `items` element shape has an explicit static type.",
    "`PropType<User>` and `PropType<User[]>` add the object and element types while retaining the same runtime constructors.",
    "裸の `Object` と `Array` は広い実行時の分類しか表さず、`user` や `items` の要素の形を明示する静的な型がありません。",
    "`PropType<User>` と `PropType<User[]>` を付け、実行時のコンストラクターを保ったままオブジェクトと要素の型を指定します。",
  ],
  [
    "script/require-typed-ref",
    "The imported `ref` calls have neither a type argument nor a useful initial value: no argument, `null`, and `undefined` cannot infer the intended future value type.",
    "Explicit type arguments describe the string and nullable User refs. `ref(0)` already has a concrete numeric initializer and can rely on inference.",
    "インポートした `ref` に型引数がなく、引数なし、`null`、`undefined` からは将来代入する値の型を推論できません。",
    "型引数で string と nullable な User の ref を指定します。`ref(0)` には具体的な数値の初期値があり、型推論を使えます。",
  ],
  [
    "script/require-valid-default-prop",
    "The Number and Boolean props receive mismatched scalar defaults, and the Array and Object props use shared literal values instead of factories.",
    "The scalar defaults become `0` and `false`; the array and object defaults become functions returning fresh values. The `[String, Number]` example accepts its string default because it matches one declared type.",
    "Number と Boolean の props に型の合わないスカラー既定値を付け、Array と Object には factory ではなく共有されるリテラル値を使っています。",
    "スカラーの既定値を `0` と `false` にし、配列とオブジェクトの既定値を新しい値を返す関数にします。`[String, Number]` の文字列既定値は、宣言した型の一つに合うため許可されます。",
  ],
  [
    "script/return-in-computed-property",
    "The block-bodied computed getter evaluates `1 + 2` but never returns it, leaving the computed value undefined.",
    "`return 1 + 2` turns the expression into the getter’s returned value. The rule looks for a value-returning return in the getter itself, not merely an expression statement.",
    "ブロック形式の computed getter が `1 + 2` を計算するだけで返さず、computed の値が undefined になります。",
    "`return 1 + 2` で式を getter の戻り値にします。このルールは式文だけでなく、getter 自身の値を返す return を確認します。",
  ],
  [
    "script/return-in-emits-validator",
    "The `submit` validator logs the payload but does not return a validation result, so its block body yields undefined.",
    "`return payload != null` supplies a boolean validation result for the submitted payload instead of ending without a returned value.",
    "`submit` の validator が payload をログ出力するだけで検査結果を返さず、ブロックの結果が undefined になります。",
    "`return payload != null` を追加し、値を返さず終了する代わりに payload の真偽値の検査結果を返します。",
  ],
  [
    "script/valid-define-emits",
    'The same `defineEmits` call supplies both a type argument and the runtime array `["save"]`, mixing two mutually exclusive declarations.',
    "Removing the runtime argument leaves a single type-based event declaration for `save`.",
    '同じ `defineEmits` に型引数と実行時配列 `["save"]` の両方を渡し、併用できない二つの宣言形式を混ぜています。',
    "実行時の引数を除き、`save` の宣言を型ベースの一つの形式に統一します。",
  ],
  [
    "script/valid-define-options",
    "The first call puts the dedicated `props` declaration inside `defineOptions`; the later calls also repeat the macro and include a non-object argument. These illustrate the forbidden shape and repeated-call constraints.",
    "One `defineOptions` call receives an object containing only the supported ordinary options `name` and `inheritAttrs`.",
    "最初の呼び出しが専用マクロで宣言すべき `props` を `defineOptions` に入れています。後続の呼び出しはマクロを繰り返し、オブジェクトでない引数も渡しています。禁止された形式と呼び出し回数の制約を示す例です。",
    "`defineOptions` を一度だけ呼び、通常の対応オプション `name` と `inheritAttrs` を持つオブジェクトを渡します。",
  ],
  [
    "script/valid-define-props",
    "The same `defineProps` call supplies both `{ title: string }` as a type argument and `{ title: String }` as a runtime argument, which the compiler does not permit together.",
    "Removing the runtime object leaves one type-based declaration for `title` instead of combining both declaration forms.",
    "同じ `defineProps` に型引数 `{ title: string }` と実行時引数 `{ title: String }` の両方を渡しています。コンパイラーはこの併用を許可しません。",
    "実行時オブジェクトを除き、二つの形式を併用せず `title` の型ベースの宣言だけを残します。",
  ],
  [
    "script/valid-next-tick",
    "The imported `nextTick()` is a bare expression with no callback, so its returned Promise is ignored and no work waits for the DOM flush.",
    "`await nextTick()` consumes the Promise and explicitly waits for the next DOM update before subsequent setup code continues.",
    "インポートした `nextTick()` をコールバックなしの式文で呼び、返された Promise を無視しています。DOM 更新後まで待つ処理がありません。",
    "`await nextTick()` で Promise を使い、後続の setup 処理へ進む前に次の DOM 更新を明示的に待ちます。",
  ],
  [
    "ssr/no-browser-globals-in-ssr",
    "Setup reads `window.innerWidth` immediately, although `window` does not exist when the component runs on the server.",
    "The initial width is a server-safe ref value, and the browser access moves into `onMounted`, which runs on the client rather than during SSR setup.",
    "setup の実行時に `window.innerWidth` を直接読みますが、サーバー上のコンポーネント実行時には `window` が存在しません。",
    "初期の幅をサーバーでも扱える ref の値にし、ブラウザー API の参照を SSR の setup ではなくクライアントで実行する `onMounted` に移します。",
  ],
  [
    "ssr/no-hydration-mismatch",
    "The template evaluates `Math.random()` during rendering, so the server and client can produce different text for the same paragraph.",
    'The paragraph renders the stable `seed` state instead of a fresh random result. In this Nuxt-style example, `useState` supplies the shared state and the initializer is the constant `"stable"`.',
    "テンプレートが描画時に `Math.random()` を評価し、同じ段落でもサーバーとクライアントで異なるテキストになり得ます。",
    '新たな乱数ではなく、安定した `seed` の状態を段落に描画します。この Nuxt 形式の例では `useState` が状態を共有し、初期値も定数 `"stable"` です。',
  ],
  [
    "type/no-floating-promises",
    "The async `save` function returns a Promise, but the standalone `save()` call neither awaits nor returns it and does not explicitly mark intentional disposal.",
    "`void save()` explicitly marks the fire-and-forget intent accepted by this rule. This is an explicit disposal marker, not a rejection handler.",
    "async の `save` は Promise を返しますが、単独の `save()` 呼び出しが await も return もせず、意図的に捨てる指定もありません。",
    "`void save()` で実行結果を意図的に捨てる指定をし、このルールの条件を満たします。結果を破棄する明示的な印であり、rejection を処理するものではありません。",
  ],
  [
    "type/no-reactivity-loss",
    "`const count = state.count` takes a plain numeric snapshot of the reactive property, so later updates of `state.count` are not reflected in that binding.",
    '`toRef(state, "count")` keeps `count` linked to the original reactive property rather than copying its current primitive value.',
    "`const count = state.count` がリアクティブなプロパティから数値のスナップショットを取り、その後の `state.count` の更新が変数へ反映されなくなります。",
    '`toRef(state, "count")` で現在のプリミティブ値をコピーせず、`count` を元のリアクティブなプロパティにつなげます。',
  ],
  [
    "type/no-unsafe-template-binding",
    "The interpolated `value` is explicitly typed as `any`, so the checker cannot give the template binding a safe concrete type.",
    "Changing the annotation to `string` gives the same interpolation a concrete, checkable type without changing the rendered value.",
    "補間する `value` の型を明示的に `any` とし、チェッカーがテンプレートの binding を安全な具体的な型として確認できません。",
    "型注釈を `string` に変え、描画する値を変えずに、同じ補間へ検査できる具体的な型を与えます。",
  ],
  [
    "type/require-typed-emits",
    'The array-only `defineEmits(["save"])` declares the event name without a typed payload contract.',
    "`defineEmits<{ save: [] }>()` declares the typed `save` event with an empty payload tuple, explicitly stating that it takes no payload arguments.",
    '配列だけの `defineEmits(["save"])` はイベント名を宣言するだけで、型付きの payload 契約がありません。',
    "`defineEmits<{ save: [] }>()` で空の payload タプルを持つ型付きの `save` イベントを宣言し、payload の引数を受け取らないことを明示します。",
  ],
  [
    "type/require-typed-props",
    'The array-only `defineProps(["title"])` declares `title` by name without giving it a type.',
    "`defineProps<{ title: string }>()` gives `title` an explicit string type instead of a name-only runtime declaration.",
    '配列だけの `defineProps(["title"])` は `title` の名前だけを宣言し、型を指定していません。',
    "`defineProps<{ title: string }>()` で、名前だけの実行時宣言に代えて `title` の string 型を明示します。",
  ],
  [
    "type/strict-boolean-expressions",
    "`if (count)` relies on the truthiness of a nullable numeric binding instead of an explicit boolean test; it also conflates zero with absence.",
    "`count !== undefined && count > 0` separately tests presence and positivity, producing an explicit boolean condition after narrowing the optional value.",
    "`if (count)` が nullable な数値の truthiness に依存し、明示的な真偽値の検査を使っていません。ゼロと未指定も同じ偽として扱います。",
    "`count !== undefined && count > 0` で存在と正の値を別々に検査し、省略可能な値を絞り込んだうえで明示的な真偽値の条件を作ります。",
  ],
];
