import type { ExplanationRecord } from "./types.ts";
export const scriptType2Explanations: readonly ExplanationRecord[] = [
  [
    "script/no-restricted-members",
    'With `{ object: "window", property: "localStorage" }` configured in `ruleOptions`, `window.localStorage` accesses the forbidden object/member pair. This rule has no default forbidden members.',
    '`authStorage.read("token")` delegates the read to the application’s storage helper and no longer accesses the configured `window.localStorage` member.',
    '`ruleOptions` に `{ object: "window", property: "localStorage" }` を設定した場合、`window.localStorage` は禁止されたオブジェクトとメンバーの組み合わせです。このルールに既定の禁止メンバーはありません。',
    '`authStorage.read("token")` でアプリケーションのストレージヘルパーに処理を任せ、設定で禁止した `window.localStorage` を参照しなくなります。',
  ],
  [
    "script/no-side-effects-in-computed-properties",
    "`doubled` assigns to `this.count`, and `reversed` mutates `this.items` through `reverse()`. Both getters modify the state they are supposed to derive from.",
    "`doubled` returns the multiplication without assignment. `reversed` copies the array before reversing it, so the original component state is unchanged by the getter.",
    "`doubled` が `this.count` に代入し、`reversed` が `reverse()` で `this.items` を変更しています。どちらも値を導出すべき getter が元の状態を変更しています。",
    "`doubled` は代入せず乗算結果を返します。`reversed` は配列をコピーしてから反転し、getter が元のコンポーネント状態を変更しないようにします。",
  ],
  [
    "script/no-top-level-ref-in-script",
    "The ordinary `<script>` initializes `count` and `user` at module scope. During SSR, these state objects can be shared across component instances and requests.",
    "The setup ref is initialized per component instance; the ordinary script keeps only a constant, a state-producing function, and a ref created inside `setup()`. None creates reactive state at ordinary module scope.",
    "通常の `<script>` がモジュール直下で `count` と `user` を初期化しています。SSR では、この状態がコンポーネントインスタンスやリクエスト間で共有され得ます。",
    "script setup の ref はコンポーネントごとに初期化されます。通常の script には定数、状態を作る関数、`setup()` 内で作る ref を置き、モジュール直下でリアクティブな状態を作りません。",
  ],
  [
    "script/no-unstable-nested-components",
    "`defineComponent` runs inside the parent’s `setup()`, creating a new `Child` component definition whenever that setup executes.",
    "The `Child` definition moves to module scope, and `setup()` returns that existing definition instead of recreating it.",
    "親の `setup()` 内で `defineComponent` を呼び、setup が実行されるたびに新しい `Child` のコンポーネント定義を作っています。",
    "`Child` の定義をモジュール直下に移し、`setup()` は作り直さず既存の定義を返すようにします。",
  ],
  [
    "script/no-unused-emit-declarations",
    "`defineEmits` declares both `change` and `unused`, but the captured `emit` function only emits the literal event `change`.",
    "Removing `unused` makes the declared event list match the observed emission. The example uses a captured, unescaped emit binding so this local usage conclusion is available.",
    "`defineEmits` は `change` と `unused` を宣言していますが、受け取った `emit` 関数が送信する文字列イベントは `change` だけです。",
    "`unused` を除き、イベント宣言を実際の送信にそろえます。この例では emit の参照を外部へ渡していないため、ローカルの使用状況から判断できます。",
  ],
  [
    "script/no-use-computed-property-like-method",
    "`this.total()` calls the value exposed by the computed getter; the getter returns `3`, which is not callable.",
    "`this.total` reads the computed value without call parentheses, so `log` prints the derived number.",
    "`this.total()` は computed getter の公開する値を関数として呼び出しています。この getter が返す `3` は呼び出せません。",
    "呼び出しの括弧を除いて `this.total` とし、`log` から計算済みの数値を参照します。",
  ],
  [
    "script/no-with-defaults",
    "`withDefaults` wraps the typed props declaration solely to supply `count` and `name` defaults, instead of the Vue 3.5+ destructuring-default style preferred here.",
    'The destructuring pattern puts `count = 0` and `name = "Ada"` beside their bindings and removes the `withDefaults` wrapper.',
    "型付きの props 宣言を `withDefaults` で包んで `count` と `name` の既定値を指定しており、ここで推奨する Vue 3.5 以降の分割代入の既定値を使っていません。",
    '分割代入の変数に `count = 0` と `name = "Ada"` を直接指定し、`withDefaults` のラッパーを取り除きます。',
  ],
  [
    "script/prefer-computed",
    "The watcher only copies a derivation of `count` into a second ref, `doubled`, so the derived state is maintained through manual synchronization.",
    "`computed(() => count.value * 2)` expresses the derivation directly and removes both the extra writable ref and its synchronization watcher.",
    "watcher が `count` から求めた値を別の ref `doubled` に書き込むだけであり、派生状態を手作業で同期しています。",
    "`computed(() => count.value * 2)` で導出を直接表し、書き込み可能な追加 ref と同期用 watcher を取り除きます。",
  ],
  [
    "script/prefer-define-options",
    "The plain script’s only meaningful statement exports an object containing just `name` and `inheritAttrs`; these options can be expressed by `defineOptions`.",
    "The shown `data()` method makes the script carry real Options API logic, so it falls outside this rule’s conservative options-only suggestion. This Good demonstrates an allowed exception; the direct migration would put `defineOptions({ name: 'MyComponent', inheritAttrs: false })` in `<script setup>`.",
    "通常の script の処理が `name` と `inheritAttrs` だけを持つオブジェクトの export に限られ、`defineOptions` で表せるオプションだけを宣言しています。",
    "例の `data()` が実際の Options API の処理を持つため、オプションだけの script を対象とする慎重な提案の範囲外になります。この Good は許可される例外を示します。直接移行する場合は `<script setup>` 内で `defineOptions({ name: 'MyComponent', inheritAttrs: false })` を使います。",
  ],
  [
    "script/prefer-import-from-vue",
    "`ref` and `h` are imported from the internal `@vue/runtime-core` and `@vue/runtime-dom` packages rather than the public `vue` package.",
    "Both helpers are imported together from `vue`, using the public package entry point instead of either internal package.",
    "`ref` と `h` を公開パッケージ `vue` ではなく、内部の `@vue/runtime-core` と `@vue/runtime-dom` からインポートしています。",
    "両ヘルパーを `vue` からまとめてインポートし、内部パッケージではなく公開エントリーポイントを使います。",
  ],
  [
    "script/prefer-ref-over-reactive",
    "The state is created with `reactive`, contrary to this opinionated rule’s preference for refs. The example illustrates a style preference, not an inherently invalid reactive object.",
    "The examples create both scalar and object state with `ref`; related fields may also be split into separate refs. This satisfies the preferred state-construction form.",
    "状態を `reactive` で作り、この意見を持つルールが推奨する ref を使っていません。これはスタイルの推奨を示す例であり、reactive オブジェクト自体が不正という意味ではありません。",
    "スカラーとオブジェクトの状態をどちらも `ref` で作ります。関連するフィールドを個別の ref に分ける例も含め、推奨する状態の作成形式にそろえます。",
  ],
  [
    "script/prefer-use-attrs",
    "`setup` obtains `attrs` by destructuring its context parameter, which this rule asks to replace with the Composition API helper.",
    "`useAttrs()` supplies `attrs` inside setup, retaining the `attrs.class` read without depending on the second setup parameter.",
    "`setup` がコンテキスト引数の分割代入で `attrs` を受け取っています。このルールは Composition API のヘルパーへの置換を求めます。",
    "setup 内で `useAttrs()` から `attrs` を取得し、第二引数に依存せず `attrs.class` の参照を保ちます。",
  ],
  [
    "script/prefer-use-id",
    "`id` contains `Math.random()`, so the generated input/label identifier can differ between server and client rendering. Its ID-named binding is the rule’s recognized generation context.",
    "Vue 3.5+ `useId()` generates the identifier, and both `:for` and `:id` continue reading the same binding instead of independently generating random values.",
    "`id` に `Math.random()` の値が含まれ、input と label の識別子がサーバーとクライアントの描画で変わり得ます。ID の名前を持つこの変数が、ルールの認識する生成箇所です。",
    "Vue 3.5 以降の `useId()` で識別子を作り、`:for` と `:id` は同じ変数を参照し続けます。ランダムな値の生成を取り除きます。",
  ],
  [
    "script/prefer-use-slots",
    "`setup` destructures `slots` from its context argument, the access form this rule prefers to replace.",
    "`useSlots()` retrieves the slots inside setup, preserving the render function and its optional default-slot call without a context parameter.",
    "`setup` がコンテキスト引数から `slots` を分割代入で取り出しており、このルールが置換を推奨する参照形式です。",
    "setup 内で `useSlots()` から slot を取得し、コンテキスト引数を使わずに render 関数と default slot の任意の呼び出しを保ちます。",
  ],
  [
    "script/prefer-use-template-ref",
    'The nullable `input` ref is paired with the template’s literal `ref="input"`, identifying it as an element reference rather than ordinary nullable data.',
    "Vue 3.5+ `useTemplateRef<HTMLInputElement>('input')` makes that template reference explicit. The unpaired `error = ref(null)` remains ordinary data and is intentionally outside this rule.",
    'null で初期化した `input` の ref がテンプレートのリテラル `ref="input"` と対応し、通常の nullable なデータではなく要素参照であることが分かります。',
    "Vue 3.5 以降の `useTemplateRef<HTMLInputElement>('input')` でテンプレート参照を明示します。対応する要素参照のない `error = ref(null)` は通常のデータであり、このルールの対象外です。",
  ],
  [
    "script/require-default-prop",
    "`name` and `age` are optional non-Boolean runtime props without defaults, leaving their omitted-input values unspecified.",
    "`name` receives `default: ''`. `enabled` uses Boolean’s implicit false default, and required `id` needs no fallback, illustrating both exemptions.",
    "`name` と `age` は必須でない Boolean 以外の実行時 props で、未指定時の既定値がありません。",
    "`name` に `default: ''` を付けます。`enabled` は Boolean の暗黙の false を使い、必須の `id` には代替値が不要であるため、二つの除外条件も示しています。",
  ],
  [
    "script/require-explicit-emits",
    "The captured emit function emits `save`, but `defineEmits([])` declares no such event.",
    'Adding `"save"` to the declaration makes the emitted literal event part of the component’s explicit event contract.',
    "受け取った emit 関数が `save` を送信しますが、`defineEmits([])` にはそのイベントが宣言されていません。",
    '宣言に `"save"` を追加し、送信する文字列イベントをコンポーネントの明示的なイベント契約に含めます。',
  ],
  [
    "script/require-explicit-slots",
    "The typed `defineProps<{ id: number }>()` establishes TypeScript syntax, but setup uses `useSlots()` without a `defineSlots` declaration. The rule therefore finds consumed slots without an explicit slot contract.",
    "`defineSlots` declares a `default` slot whose props include `msg: string`; `useSlots()` now appears alongside an explicit typed slot contract.",
    "型付きの `defineProps<{ id: number }>()` により TypeScript の構文があることが分かりますが、setup が `defineSlots` の宣言なしに `useSlots()` を使い、参照する slot の明示的な契約がありません。",
    "`defineSlots` で `msg: string` を props に持つ `default` slot を宣言し、`useSlots()` と明示的な型付き slot 契約を併記します。",
  ],
  [
    "script/require-function-return-type",
    "Both `add` and `greet` annotate their parameters but omit a return-type annotation; inferred returns do not satisfy this explicit-annotation policy.",
    "`add` declares `: number`, and `greet` declares `: string`, making the return contracts explicit without changing either body.",
    "`add` と `greet` は引数の型を指定していますが、戻り値の型を省略しています。この明示的な型指定の規則では、戻り値の推論だけでは条件を満たしません。",
    "`add` に `: number`、`greet` に `: string` を付け、本体を変えずに戻り値の契約を明示します。",
  ],
  [
    "script/require-prop-type-constructor",
    'The prop declarations use strings `"String"` and `"Number"` as runtime types, including inside the constructor array. Those strings are not constructor functions.',
    "The declarations use the actual `String` and `Number` identifiers, including the union array `[String, Number]`.",
    'props の実行時の型に文字列 `"String"` と `"Number"` を使い、コンストラクターの配列にも文字列を入れています。これらの文字列はコンストラクター関数ではありません。',
    "型を実際の `String` と `Number` の識別子にし、共用型の配列も `[String, Number]` に変えます。",
  ],
];
