import type { ExplanationRecord } from "./types.ts";
// Each row is [rule, Bad EN, Good EN, Bad JA, Good JA].
export const ecosystemMuseaVaporExplanations: readonly ExplanationRecord[] = [
  [
    "ecosystem/nuxt-prefer-nuxt-link",
    "The internal settings destination uses a plain anchor in a Nuxt application.",
    "NuxtLink handles the same internal destination through the Nuxt router.",
    "Nuxt の内部ページへの移動に通常の a を使っています。",
    "同じ移動先を NuxtLink に指定し、Nuxt のルーターを使います。",
  ],
  [
    "ecosystem/pinia-prefer-store-to-refs",
    "Destructuring `name` directly from the store separates the value from its reactive store access.",
    "The store remains intact and storeToRefs creates a reactive reference for name.",
    "store から name を直接分割代入し、リアクティブな store の読み取りから値を切り離しています。",
    "store は保持し、storeToRefs で name のリアクティブな参照を取り出します。",
  ],
  [
    "ecosystem/router-link-require-to",
    "The nested RouterLink has no `to` destination; it cannot rely on root attribute fallthrough.",
    '`to="/settings"` explicitly supplies the nested link destination.',
    "nav の内側の RouterLink に to がなく、ルートの属性継承にも頼れません。",
    '内部のリンクに `to="/settings"` で移動先を明示します。',
  ],
  [
    "ecosystem/void-link-require-href",
    "The Link imported from @void/vue omits its href destination.",
    "The same imported Link receives the settings destination through href.",
    "@void/vue から import した Link に href がありません。",
    "同じ Link の href に設定画面の移動先を指定します。",
  ],
  [
    "ecosystem/void-link-valid-method",
    "The DELETE action requests prefetching, although prefetch is intended for navigation requests.",
    "Removing prefetch keeps the DELETE action without prefetching that non-GET request.",
    "DELETE の操作に、ページ移動のリクエスト向けの prefetch を指定しています。",
    "prefetch を取り除き、DELETE のリクエストを事前取得しない形にします。",
  ],
  [
    "ecosystem/vue-i18n-no-missing-key",
    "The template requests auth.missing, but the local English messages declare only auth.login.",
    "The template requests the auth.login key that exists in the local messages.",
    "テンプレートは auth.missing を参照しますが、ローカルの英語メッセージには auth.login しかありません。",
    "ローカルのメッセージにある auth.login を参照します。",
  ],
  [
    "ecosystem/vue-router-prefer-named-link",
    "The RouterLink destination is a literal path rather than a named route.",
    "The bound route object identifies the destination by its settings route name.",
    "RouterLink の移動先をルート名ではなく、文字列のパスで指定しています。",
    "バインドする route のオブジェクトに settings の name を指定します。",
  ],
  [
    "ecosystem/vue-router-prefer-named-push",
    "router.push receives a path string that is tied to the current URL spelling.",
    "router.push receives a route object with the stable settings name.",
    "router.push に、現在の URL 表記に結び付く文字列のパスを渡しています。",
    "settings のルート名を持つオブジェクトを router.push に渡します。",
  ],
  [
    "ecosystem/vue-test-utils-no-html-snapshot",
    "The assertion snapshots the complete wrapper HTML instead of checking the expected behavior.",
    "The assertion checks that the rendered text contains Saved.",
    "期待する振る舞いを検査する代わりに、wrapper の HTML 全体を snapshot にしています。",
    "表示された文字に Saved が含まれることを直接検査します。",
  ],
  [
    "musea/no-empty-variant",
    "The named primary variant is empty, so it provides no preview content.",
    "The variant renders a primary Button with its Save content.",
    "primary の名前がある variant が空で、プレビューする内容がありません。",
    "variant の中に primary の Button と Save の内容を入れます。",
  ],
  [
    "musea/prefer-design-tokens",
    "The art example uses the literal blue color instead of the configured primary design token.",
    "The style refers to --color-primary, the token configured for this example.",
    "art の例で、設定した primary のデザイントークンではなく、青の色を直接指定しています。",
    "この例で設定する --color-primary のトークンを参照します。",
  ],
  [
    "musea/require-component",
    "The art block supplies a title but does not identify the component being previewed.",
    "defineArt supplies ./Button.vue as the component for the art block.",
    "art に title はありますが、プレビューする component の指定がありません。",
    "defineArt で ./Button.vue を art の component として指定します。",
  ],
  [
    "musea/require-title",
    "The art block identifies Button.vue but supplies no title.",
    "The defineArt options supply the Button title for the art block.",
    "art に Button.vue の指定はありますが、title がありません。",
    "defineArt のオプションに Button の title を指定します。",
  ],
  [
    "musea/unique-variant-names",
    "Two variants in the same art block both use the primary name.",
    "The variants have distinct primary and secondary names.",
    "同じ art の二つの variant に primary の名前を使っています。",
    "primary と secondary の別々の名前を指定します。",
  ],
  [
    "musea/valid-variant",
    "The variant omits the name needed to identify the preview.",
    "The primary name identifies that variant.",
    "プレビューを識別する variant の name がありません。",
    "variant に primary の name を指定します。",
  ],
  [
    "vapor/no-inline-template",
    "LegacyCard uses the inline-template attribute for its child markup.",
    "The markup is passed through the default slot instead of an inline template.",
    "LegacyCard の内部のマークアップに inline-template を使っています。",
    "同じマークアップを default slot として渡します。",
  ],
  [
    "vapor/no-vue-lifecycle-events",
    "The input uses the @vue:mounted template lifecycle event.",
    "onMounted accesses the named template reference and focuses the input through the supported script lifecycle hook.",
    "input にテンプレートの @vue:mounted を指定しています。",
    "script の onMounted からテンプレートの ref を参照し、input にフォーカスします。",
  ],
  [
    "vapor/prefer-static-class",
    "The class binding evaluates a constant string even though the class does not change.",
    "A static class attribute expresses the same panel classes without a binding.",
    "変化しないクラスの文字列をバインディングで評価しています。",
    "同じ panel のクラスを静的な class 属性に指定します。",
  ],
  [
    "vapor/require-vapor-attribute",
    "The script setup block lacks the Vapor compilation attribute. This is an intended convention: the current empty rule callback does not diagnose it.",
    "Adding vapor selects Vapor compilation. It demonstrates the intended repair and does not imply that the current linter emits this catalog rule.",
    "script setup に Vapor の指定がありません。これは規約を示す例で、現在の空の callback は診断を生成しません。",
    "vapor を追加して Vapor のコンパイルを選択します。修正方針を示す例であり、現在の linter がこのルールを検出するという意味ではありません。",
  ],
];
