import type { ExplanationRecord } from "./types.ts";
// Each row is [rule, Bad EN, Good EN, Bad JA, Good JA].
export const cssHtmlExplanations: readonly ExplanationRecord[] = [
  [
    "css/no-display-none",
    "The `.message` declaration hides the local paragraph through CSS rather than a template visibility condition.",
    '`v-show="isSaved"` makes the visibility condition explicit on the local paragraph and removes `display: none`.',
    "ローカルの p を `.message` の CSS で非表示にし、テンプレートに表示条件を指定していません。",
    '同じ p に `v-show="isSaved"` で表示条件を指定し、display: none を取り除きます。',
  ],
  [
    "css/no-hardcoded-values",
    "The button embeds spacing numbers and a hexadecimal color directly in the declarations.",
    "The declarations refer to named spacing and color custom properties, so these values can be maintained as tokens.",
    "button の余白と色に数値や 16 進の色を直接指定しています。",
    "余白と色を名前付きのカスタムプロパティで参照し、トークンとして管理できる形にします。",
  ],
  [
    "css/no-id-selectors",
    "`#submit` ties the style rule to an ID selector.",
    "The `.submit` class expresses the reusable styling hook without an ID selector.",
    "`#submit` で ID セレクターにスタイルを結び付けています。",
    "再利用できる `.submit` のクラスを使い、ID セレクターを取り除きます。",
  ],
  [
    "css/no-important",
    "The color declaration overrides normal cascade priority with `!important`.",
    "The color comes from a custom property without an important declaration.",
    "color に `!important` を付け、通常のカスケードの優先順位を上書きしています。",
    "important を使わず、カスタムプロパティから色を参照します。",
  ],
  [
    "css/no-utility-classes",
    "The authored selectors use utility-shaped names such as `.flex`, `.mt-4`, and `.text-center`.",
    "A component-specific `.my-component` selector groups the component styling under one semantic name.",
    "`.flex`、`.mt-4`、`.text-center` のように、個々の見た目を名前にしたクラスを定義しています。",
    "コンポーネント固有の `.my-component` にスタイルをまとめます。",
  ],
  [
    "css/no-v-bind-performance",
    "The stylesheet reads the changing `offset` through the SFC CSS `v-bind()` mechanism.",
    "The element receives the changing transform directly through its style binding.",
    "変化する offset を SFC の CSS の v-bind() で参照しています。",
    "変化する transform を要素の style バインディングに直接指定します。",
  ],
  [
    "css/prefer-logical-properties",
    "`margin-left` fixes the margin to a physical side regardless of writing direction.",
    "`margin-inline-start` follows the start of the inline direction instead.",
    "margin-left は文字の方向に関係なく物理的な左側を指定します。",
    "margin-inline-start を使い、インライン方向の開始側に余白を指定します。",
  ],
  [
    "css/prefer-nested-selectors",
    "The `.card .title` descendant selector repeats the parent selector in a flat rule.",
    "The `.title` rule is nested inside `.card`, keeping the parent-child styling relationship together.",
    "平らなルールの `.card .title` に、親のセレクターを含めて指定しています。",
    "`.card` の中に `.title` を入れ、親子のスタイルを一緒に管理します。",
  ],
  [
    "css/prefer-slotted",
    "The scoped stylesheet targets the `slot` outlet rather than the elements supplied through the slot.",
    "`:slotted(.label)` targets the supplied label element through the scoped slot selector.",
    "scoped の CSS で、渡された要素ではなく slot の出口を対象にしています。",
    ":slotted(.label) を使い、slot から渡される label の要素を対象にします。",
  ],
  [
    "css/require-font-display",
    "The font-face declaration defines the font source but omits its font-display policy.",
    "`font-display: swap` explicitly selects the fallback-to-font display policy.",
    "font-face にフォントの参照先はありますが、font-display の方針を指定していません。",
    "font-display: swap を追加し、フォールバックからフォントを表示する方針を指定します。",
  ],
  [
    "html/deprecated-attr",
    "The paragraph uses the deprecated presentational `align` attribute.",
    "The class and `text-align: center` declaration express the alignment through CSS.",
    "p に見た目を指定する旧来の align 属性を使っています。",
    "クラスと text-align: center で、配置を CSS に移します。",
  ],
  [
    "html/deprecated-element",
    "The `center` element uses a deprecated HTML presentation element.",
    "A section and a styling class replace the deprecated element while preserving the content.",
    "旧来の見た目のための center 要素を使っています。",
    "内容は残し、section とスタイル用のクラスに置き換えます。",
  ],
  [
    "html/id-duplication",
    'Both the input and help paragraph declare `id="email"`, so the label target is ambiguous.',
    "The input keeps `email`; the help paragraph uses `email-help`, and aria-describedby refers to that distinct ID.",
    "入力欄と説明の p が同じ email の ID を使い、label の参照先が重複しています。",
    "入力欄は email、説明は email-help に分け、aria-describedby で説明を参照します。",
  ],
  [
    "html/no-consecutive-br",
    "Two consecutive break elements create spacing between blocks inside a single paragraph.",
    "Separate paragraphs express the two content blocks without repeated break elements.",
    "一つの p の中に br を二つ続けて入れ、ブロック間の余白を作っています。",
    "内容を別の p に分け、連続した br を使いません。",
  ],
  [
    "html/no-dupe-style-properties",
    "Each static style repeats one property; `margin` and `MARGIN` also count as the same property.",
    "The static style uses distinct color and background properties. Dynamic style bindings are outside this static-attribute check.",
    "静的な style の中で同じプロパティを重複させています。margin と MARGIN も同じプロパティとして扱われます。",
    "静的な style では color と background を分けます。動的な style バインディングはこの静的属性の検査の対象外です。",
  ],
  [
    "html/no-duplicate-class",
    "The static class list repeats the `btn` token.",
    "The class list keeps one `btn` token and the distinct `primary` token.",
    "静的な class の中に btn が二回あります。",
    "btn は一回だけ残し、別の primary と合わせて指定します。",
  ],
  [
    "html/no-duplicate-dt",
    "The same definition list repeats the `API` term for two descriptions.",
    "One API term is followed by both descriptions, avoiding the repeated term.",
    "同じ dl に API の用語を二回指定しています。",
    "API の dt を一つにし、その後に二つの dd を並べます。",
  ],
  [
    "html/no-empty-palpable-content",
    "The paragraph, list item, and table cell all have empty palpable content.",
    "Text fills the paragraph, interpolation supplies the list item, and aria-label explicitly names the otherwise empty cell.",
    "p、li、td がいずれも空で、意味のある内容がありません。",
    "p は文字、li は補間で内容を入れ、空の td には aria-label で名前を指定します。",
  ],
  [
    "html/require-datetime",
    "The time element contains a human-readable date but no machine-readable datetime value.",
    '`datetime="2026-05-13"` supplies the corresponding machine-readable date.',
    "time に人が読む日付だけがあり、機械が読む datetime がありません。",
    '`datetime="2026-05-13"` に対応する日付を指定します。',
  ],
];
