import type { ExplanationRecord } from "./types.ts";
export const projectExplanations1: readonly ExplanationRecord[] = [
  [
    "prop-type-mismatch",
    "The parent passes the numeric expression `42` to the resolved child's `title: string` prop.",
    'The literal `title="Hello"` supplies a string matching the child\'s declaration.',
    "親が数値式 `42` を、解決した子の `title: string` prop に渡しています。",
    '文字列の `title="Hello"` を渡し、子の宣言と合わせます。',
  ],
  [
    "undeclared-prop",
    "The parent passes `typo` even though the resolved child declares only `title`. This analyzer convention is separate from Vue's general fallthrough-attribute behavior.",
    "Remove the unintended `typo` binding and retain the declared `title` prop.",
    "親が `typo` を渡しますが、解決した子の宣言は `title` だけです。この analyzer の規約は、Vue の属性自動継承の一般的な動作とは別です。",
    "意図しない `typo` binding を除き、宣言済みの `title` を残します。",
  ],
  [
    "undeclared-emit",
    'The child calls `emit("save")` but its `defineEmits` contract declares only `cancel`.',
    "Declare `save` with its empty argument tuple so the emitted event agrees with the component contract.",
    '子が `emit("save")` を呼びますが、`defineEmits` の宣言は `cancel` だけです。',
    "引数なしの `save` を宣言し、emit するイベントをコンポーネントの契約に合わせます。",
  ],
  [
    "unused-emit",
    "The child declares `save` but never calls the emitted-event function with that name.",
    'The example calls `emit("save")`, making the declared event used. Real interactions should emit it when the corresponding action occurs.',
    "子が `save` を宣言していますが、その名前で emit 関数を呼んでいません。",
    '例では `emit("save")` を呼び、宣言したイベントを使います。実際の操作では対応する action の発生時に通知します。',
  ],
  [
    "unmatched-listener",
    "The parent listens for `save`, while the resolved child declares only `cancel`.",
    "The child declares and emits `save`, matching the parent's listener name.",
    "親は `save` を待ちますが、解決した子の宣言は `cancel` だけです。",
    "子が `save` を宣言して emit し、親の listener 名と合わせます。",
  ],
  [
    "event-modifier",
    "`.stop` assumes a native event's propagation method on the child's custom `save` event, whose payload need not be a DOM Event.",
    "Remove `.stop` from the custom-event listener; handle native propagation at the actual DOM listener when needed.",
    "`.stop` を子のカスタム `save` イベントに付けていますが、その payload が DOM Event とは限りません。",
    "カスタム イベントの listener から `.stop` を除きます。必要なら実際の DOM listener で伝播を制御します。",
  ],
  [
    "unhandled-event",
    "`Child.vue` emits `save`, but its immediate wrapper does not listen for it; component events do not automatically bubble through wrappers.",
    "`Wrapper.vue` attaches a `save` listener to its direct child. The empty callback demonstrates handling for this rule, not a complete save implementation.",
    "`Child.vue` が `save` を emit しますが、直接の wrapper が受け取りません。コンポーネントのイベントは wrapper を自動的に通り抜けません。",
    "`Wrapper.vue` が直接の子に `save` listener を付けます。空の callback はこの検査での受信を示すもので、保存処理全体ではありません。",
  ],
  [
    "unregistered-component",
    "A `Child.vue` file exists, but the parent neither imports nor otherwise registers `Child` for its template.",
    "Import `Child` in the parent's script setup so the template resolves the component binding.",
    "`Child.vue` は存在しますが、親がテンプレートの `Child` を import / 登録していません。",
    "親の script setup で `Child` を import し、テンプレートから binding を解決できる形にします。",
  ],
  [
    "unresolved-import",
    "The parent imports `./Missing.vue`, but the project contains `Child.vue` rather than that path.",
    "Point the import at the existing `./Child.vue` file, retaining the same template binding.",
    "親の import は `./Missing.vue` ですが、プロジェクトにあるファイルは `Child.vue` です。",
    "テンプレートの binding を変えず、存在する `./Child.vue` を import します。",
  ],
  [
    "lifecycle-without-cleanup",
    "Mounting registers a window resize listener, but unmounting never removes the same callback.",
    "`onUnmounted` removes the listener with the same event name and function identity used by `addEventListener`.",
    "mount 時に window の resize listener を登録しますが、unmount 時に同じ callback を解除しません。",
    "`onUnmounted` で、登録時と同じイベント名・関数の参照を使って listener を解除します。",
  ],
  [
    "setup-context-violation",
    "`ref(0)` is created at normal script module scope, outside the per-instance setup context represented by this analyzer scenario.",
    "Move the binding into script setup, where each component instance owns its count and the template can read it.",
    "`ref(0)` を通常の script の module scope に作り、この analyzer が扱うインスタンスごとの setup 文脈から外しています。",
    "script setup に移し、各インスタンスが count を持ち、テンプレートから読み取れる形にします。",
  ],
  [
    "inherit-attrs-unused",
    'The child sets `inheritAttrs: false` but never forwards the parent\'s `class="notice"` attribute.',
    "Keep explicit inheritance control and bind `$attrs` to the intended `<main>` target.",
    '子が `inheritAttrs: false` にして、親の `class="notice"` をどこにも渡していません。',
    "明示的な継承制御を保ち、適用先の `<main>` に `$attrs` を binding します。",
  ],
  [
    "multi-root-attrs",
    "The child has `<main>` and `<aside>` roots, so Vue has no single root that can automatically receive the parent's class.",
    "Forward `$attrs` explicitly to `<main>` while keeping the second root.",
    "子に `<main>` と `<aside>` の二つのルートがあり、親の class を自動で受け取る一つのルートがありません。",
    "二つ目のルートを保ったまま、`<main>` に `$attrs` を明示的に渡します。",
  ],
  [
    "unused-attrs",
    "The parent's `tracking-code` is neither consumed as a prop nor forwarded by the multi-root child.",
    "Binding `$attrs` on `<main>` gives that fallthrough attribute an explicit destination.",
    "親の `tracking-code` は prop として使われず、複数ルートの子から転送もされません。",
    "`<main>` に `$attrs` を binding し、継承属性の適用先を明示します。",
  ],
  [
    "html/cross-component-nesting",
    "The parent's `<p>` contains a resolved child whose root is `<div>`, producing invalid paragraph/block nesting after composition.",
    "Use a `<section>` container that can contain the child's block element; the child stays unchanged.",
    "親の `<p>` 内に、ルートが `<div>` の子を合成し、paragraph と block の不正な入れ子を作ります。",
    "子の block 要素を含められる `<section>` を使い、子は変更しません。",
  ],
  [
    "vue/cross-file-attrs-fallthrough",
    'The parent passes `class="notice"` to a resolved fragment child that has no automatic attribute target and never reads `$attrs`.',
    "The child chooses `<main>` as its target by binding `$attrs` there; its sibling `<aside>` remains separate.",
    '親が `class="notice"` を fragment の子に渡しますが、属性の自動適用先がなく、子も `$attrs` を使いません。',
    "子が `<main>` に `$attrs` を binding して適用先を選び、隣の `<aside>` は別に保ちます。",
  ],
  [
    "ecosystem/vue-router-unknown-route",
    "The reachable installed router declares `user-post`, but navigation uses the misspelled `user-posts` name.",
    "Use the registered `user-post` name while retaining both declared path parameters.",
    "到達できる登録済み router の名前は `user-post` ですが、navigation で `user-posts` と誤記しています。",
    "二つの path parameter を保ち、登録名の `user-post` に合わせます。",
  ],
  [
    "ecosystem/vue-router-extra-param",
    "The `user-post` path declares `userId` and `postId`, but the navigation also supplies undeclared `tab` as a path parameter.",
    "Remove `tab` from params and retain only the keys present in the route path. Use query separately if the application needs a tab selection.",
    "`user-post` の path は `userId` と `postId` ですが、宣言にない `tab` も path parameter として渡しています。",
    "params から `tab` を除き、path の key だけを渡します。タブ選択が必要なら別途 query を使います。",
  ],
  [
    "ecosystem/vue-router-param-type",
    '`postId` is a scalar path parameter, but the navigation gives it the array `["2"]`.',
    'Pass the scalar `"2"` for the non-repeatable `postId` segment.',
    '`postId` は一つの値を取る path parameter ですが、配列 `["2"]` を渡しています。',
    '繰り返し指定ではない `postId` の segment に、一つの値 `"2"` を渡します。',
  ],
  [
    "ecosystem/vue-router-missing-param",
    "The navigation omits required `postId` from the `user-post` path. This is a warning because Vue Router may inherit a value from the current route.",
    "Pass both `userId` and `postId` explicitly so navigation does not depend on the current route's parameter state.",
    "`user-post` の必須 `postId` を省略しています。Vue Router は現在の route から値を継承する場合があるため warning です。",
    "`userId` と `postId` を両方明示し、現在の route の parameter に依存しない navigation にします。",
  ],
];
