import {
  catalogOwner,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "../../../catalog/family-catalog-types.ts";

const hoverFamilyRoot = "src/families/interaction/hover/";
const longPressFamilyRoot = "src/families/interaction/long-press/";
const moveFamilyRoot = "src/families/interaction/move/";
const pointerGraceFamilyRoot = "src/families/interaction/pointer-grace/";
const pressFamilyRoot = "src/families/interaction/press/";

export const interactionGestureFamilyCatalog = [
  {
    canonicalName: "hover",
    title: "Hover",
    packageSubpath: "./hover",
    entryFile: `${hoverFamilyRoot}hover.ts`,
    sourceFiles: [`${hoverFamilyRoot}hover.ts`, `${hoverFamilyRoot}hover-types.ts`],
    behaviorContract: `${hoverFamilyRoot}hover.behavior.md`,
    tests: [`${hoverFamilyRoot}hover.test.ts`, `${hoverFamilyRoot}hover-ssr.test.ts`],
    typeTests: [`${hoverFamilyRoot}hover.types.test-d.ts`],
    rendererFixture: "HoverConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createHover",
      retainedSignature: "VIZE_UI_HOVER_DISPOSED",
      maximumJavaScriptGzipBytes: 1_450,
      maximumCssGzipBytes: 0,
    },
    aliases: ["hover", "pointer", "pen"],
    upstreamCoverage: ["React Aria useHover", "Pointer Events hover"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "long-press",
    title: "Long Press",
    packageSubpath: "./long-press",
    entryFile: `${longPressFamilyRoot}long-press.ts`,
    sourceFiles: [
      `${longPressFamilyRoot}long-press.ts`,
      `${longPressFamilyRoot}long-press-internal.ts`,
      `${longPressFamilyRoot}long-press-types.ts`,
    ],
    behaviorContract: `${longPressFamilyRoot}long-press.behavior.md`,
    tests: [
      `${longPressFamilyRoot}long-press.test.ts`,
      `${longPressFamilyRoot}long-press-hardening.test.ts`,
      `${longPressFamilyRoot}long-press-legacy.test.ts`,
      `${longPressFamilyRoot}long-press-ssr.test.ts`,
    ],
    typeTests: [`${longPressFamilyRoot}long-press.types.test-d.ts`],
    rendererFixture: "LongPressConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createLongPress",
      retainedSignature: "VIZE_UI_LONG_PRESS_DISPOSED",
      allowedRetainedFamilies: ["press"],
      maximumJavaScriptGzipBytes: 5_150,
      maximumCssGzipBytes: 0,
    },
    aliases: ["long press", "press and hold"],
    upstreamCoverage: ["React Aria useLongPress"],
    dependencies: ["press"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "move",
    title: "Move",
    packageSubpath: "./move",
    entryFile: `${moveFamilyRoot}move.ts`,
    sourceFiles: [
      `${moveFamilyRoot}move.ts`,
      `${moveFamilyRoot}move-internal.ts`,
      `${moveFamilyRoot}move-types.ts`,
    ],
    behaviorContract: `${moveFamilyRoot}move.behavior.md`,
    tests: [
      `${moveFamilyRoot}move.test.ts`,
      `${moveFamilyRoot}move-internal.test.ts`,
      `${moveFamilyRoot}move-ssr.test.ts`,
    ],
    typeTests: [`${moveFamilyRoot}move.types.test-d.ts`],
    rendererFixture: "MoveConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createMove",
      retainedSignature: "VIZE_UI_MOVE_DISPOSED",
      maximumJavaScriptGzipBytes: 2_750,
      maximumCssGzipBytes: 0,
    },
    aliases: ["move", "drag", "keyboard"],
    upstreamCoverage: ["React Aria useMove", "Pointer Events capture"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "pointer-grace",
    title: "Pointer Grace",
    packageSubpath: "./pointer-grace",
    entryFile: `${pointerGraceFamilyRoot}pointer-grace.ts`,
    sourceFiles: [
      `${pointerGraceFamilyRoot}pointer-grace.ts`,
      `${pointerGraceFamilyRoot}pointer-grace-runtime.ts`,
      `${pointerGraceFamilyRoot}pointer-grace-types.ts`,
    ],
    behaviorContract: `${pointerGraceFamilyRoot}pointer-grace.behavior.md`,
    tests: [
      `${pointerGraceFamilyRoot}pointer-grace.test.ts`,
      `${pointerGraceFamilyRoot}pointer-grace-ssr.test.ts`,
    ],
    typeTests: [`${pointerGraceFamilyRoot}pointer-grace.types.test-d.ts`],
    rendererFixture: "PointerGraceConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createPointerGrace",
      retainedSignature: "VIZE_UI_POINTER_GRACE_DISPOSED",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["safe triangle", "hover bridge", "pointer grace"],
    upstreamCoverage: ["safe triangle", "hover intent polygon"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "press",
    title: "Press",
    packageSubpath: "./press",
    entryFile: `${pressFamilyRoot}press.ts`,
    sourceFiles: [
      `${pressFamilyRoot}press.ts`,
      `${pressFamilyRoot}press-activation-memory.ts`,
      `${pressFamilyRoot}press-event.ts`,
      `${pressFamilyRoot}press-handlers.ts`,
      `${pressFamilyRoot}press-lifecycle.ts`,
      `${pressFamilyRoot}press-types.ts`,
    ],
    behaviorContract: `${pressFamilyRoot}press.behavior.md`,
    tests: [
      `${pressFamilyRoot}press.test.ts`,
      `${pressFamilyRoot}press-lifecycle.test.ts`,
      `${pressFamilyRoot}press-legacy.test.ts`,
      `${pressFamilyRoot}press-ssr.test.ts`,
    ],
    typeTests: [`${pressFamilyRoot}press.types.test-d.ts`],
    rendererFixture: "PressConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createPress",
      retainedSignature: "VIZE_UI_PRESS_DISPOSED",
      maximumJavaScriptGzipBytes: 3_550,
      maximumCssGzipBytes: 0,
    },
    aliases: ["press", "activation", "pointer"],
    upstreamCoverage: ["React Aria usePress", "Pointer Events activation"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
