import {
  catalogOwner,
  componentQualityGates,
  interactionQualityGates,
  type UiFamilyCatalogEntry,
} from "../../../catalog/family-catalog-types.ts";

const measureFamilyRoot = "src/families/interaction/measure/";
const primitiveFamilyRoot = "src/families/foundations/primitive/";
const shortcutFamilyRoot = "src/families/interaction/shortcut/";
const sortableFamilyRoot = "src/families/interaction/sortable/";
const spatialNavigationFamilyRoot = "src/families/interaction/spatial-navigation/";
const typeaheadFamilyRoot = "src/families/interaction/typeahead/";
const virtualizerFamilyRoot = "src/families/interaction/virtualizer/";

export const interactionSupportFamilyCatalog = [
  {
    canonicalName: "measure",
    title: "Measure",
    packageSubpath: "./measure",
    entryFile: `${measureFamilyRoot}measure.ts`,
    sourceFiles: [
      `${measureFamilyRoot}measure.ts`,
      `${measureFamilyRoot}measure-runtime.ts`,
      `${measureFamilyRoot}measure-types.ts`,
    ],
    behaviorContract: `${measureFamilyRoot}measure.behavior.md`,
    tests: [`${measureFamilyRoot}measure.test.ts`, `${measureFamilyRoot}measure-ssr.test.ts`],
    typeTests: [`${measureFamilyRoot}measure.types.test-d.ts`],
    rendererFixture: "MeasureConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSizeObserver",
      retainedSignature: "VIZE_UI_MEASURE_DISPOSED",
      maximumJavaScriptGzipBytes: 1_050,
      maximumCssGzipBytes: 0,
    },
    aliases: ["resize observer", "intersection observer", "element size", "visibility"],
    upstreamCoverage: ["ResizeObserver", "IntersectionObserver"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "primitive",
    title: "Primitive",
    packageSubpath: "./primitive",
    entryFile: `${primitiveFamilyRoot}primitive.ts`,
    sourceFiles: [
      `${primitiveFamilyRoot}primitive-element.vue`,
      `${primitiveFamilyRoot}primitive.ts`,
    ],
    behaviorContract: `${primitiveFamilyRoot}primitive.behavior.md`,
    tests: [`${primitiveFamilyRoot}primitive.test.ts`],
    rendererFixture: "families/foundations/primitive/primitive-element.vue",
    qualityGates: componentQualityGates,
    bundleBudget: {
      exportName: "Primitive",
      retainedSignature: "data-vize-ui.+primitive",
      maximumJavaScriptGzipBytes: 500,
      maximumCssGzipBytes: 0,
    },
    aliases: ["as child", "polymorphic primitive", "slot forwarding primitive"],
    upstreamCoverage: ["Reka UI Primitive", "Radix Slot", "shadcn/ui Slot"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "shortcut",
    title: "Shortcut",
    packageSubpath: "./shortcut",
    entryFile: `${shortcutFamilyRoot}shortcut.ts`,
    sourceFiles: [
      `${shortcutFamilyRoot}shortcut.ts`,
      `${shortcutFamilyRoot}shortcut-format.ts`,
      `${shortcutFamilyRoot}shortcut-parse.ts`,
      `${shortcutFamilyRoot}shortcut-registry.ts`,
      `${shortcutFamilyRoot}shortcut-types.ts`,
    ],
    behaviorContract: `${shortcutFamilyRoot}shortcut.behavior.md`,
    tests: [
      `${shortcutFamilyRoot}shortcut.test.ts`,
      `${shortcutFamilyRoot}shortcut-format.test.ts`,
      `${shortcutFamilyRoot}shortcut-lifecycle.test.ts`,
      `${shortcutFamilyRoot}shortcut-ssr.test.ts`,
    ],
    typeTests: [`${shortcutFamilyRoot}shortcut.types.test-d.ts`],
    rendererFixture: "ShortcutConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createShortcutRegistry",
      retainedSignature: "VIZE_UI_SHORTCUT_DISPOSED",
      maximumJavaScriptGzipBytes: 4_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["keyboard shortcuts", "hotkeys", "keybindings", "kbd formatting"],
    upstreamCoverage: ["VS Code keybindings", "React Aria useKeyboard", "GitHub Hotkey"],
    dependencies: [],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "sortable",
    title: "Sortable",
    packageSubpath: "./sortable",
    entryFile: `${sortableFamilyRoot}sortable.ts`,
    sourceFiles: [
      `${sortableFamilyRoot}sortable.ts`,
      `${sortableFamilyRoot}sortable-internal.ts`,
      `${sortableFamilyRoot}sortable-keyboard.ts`,
      `${sortableFamilyRoot}sortable-types.ts`,
    ],
    behaviorContract: `${sortableFamilyRoot}sortable.behavior.md`,
    tests: [`${sortableFamilyRoot}sortable.test.ts`, `${sortableFamilyRoot}sortable-ssr.test.ts`],
    typeTests: [`${sortableFamilyRoot}sortable.types.test-d.ts`],
    rendererFixture: "SortableConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSortable",
      retainedSignature: "VIZE_UI_SORTABLE_DISPOSED",
      allowedRetainedFamilies: ["drag-and-drop"],
      maximumJavaScriptGzipBytes: 9_000,
      maximumCssGzipBytes: 0,
    },
    aliases: ["sortable list", "reorder", "sortable grid", "sortable tree"],
    upstreamCoverage: ["React Aria useDraggableCollection", "ARIA APG drag reordering"],
    dependencies: ["drag-and-drop"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "spatial-navigation",
    title: "Spatial Navigation",
    packageSubpath: "./spatial-navigation",
    entryFile: `${spatialNavigationFamilyRoot}spatial-navigation.ts`,
    sourceFiles: [
      `${spatialNavigationFamilyRoot}spatial-navigation.ts`,
      `${spatialNavigationFamilyRoot}spatial-navigation-internal.ts`,
      `${spatialNavigationFamilyRoot}spatial-navigation-types.ts`,
    ],
    behaviorContract: `${spatialNavigationFamilyRoot}spatial-navigation.behavior.md`,
    tests: [
      `${spatialNavigationFamilyRoot}spatial-navigation.test.ts`,
      `${spatialNavigationFamilyRoot}spatial-navigation-lifecycle.test.ts`,
      `${spatialNavigationFamilyRoot}spatial-navigation-ssr.test.ts`,
    ],
    typeTests: [`${spatialNavigationFamilyRoot}spatial-navigation.types.test-d.ts`],
    rendererFixture: "SpatialNavigationConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createSpatialNavigation",
      retainedSignature: "VIZE_UI_SPATIAL_NAVIGATION_DISPOSED",
      maximumJavaScriptGzipBytes: 4_100,
      maximumCssGzipBytes: 0,
    },
    aliases: ["spatial navigation", "grid navigation", "geometry navigation"],
    upstreamCoverage: ["CSS Spatial Navigation", "ARIA grid navigation"],
    dependencies: ["collection"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "typeahead",
    title: "Typeahead",
    packageSubpath: "./typeahead",
    entryFile: `${typeaheadFamilyRoot}typeahead.ts`,
    sourceFiles: [
      `${typeaheadFamilyRoot}typeahead.ts`,
      `${typeaheadFamilyRoot}typeahead-internal.ts`,
      `${typeaheadFamilyRoot}typeahead-types.ts`,
    ],
    behaviorContract: `${typeaheadFamilyRoot}typeahead.behavior.md`,
    tests: [
      `${typeaheadFamilyRoot}typeahead.test.ts`,
      `${typeaheadFamilyRoot}typeahead-ssr.test.ts`,
    ],
    typeTests: [`${typeaheadFamilyRoot}typeahead.types.test-d.ts`],
    rendererFixture: "TypeaheadConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createTypeahead",
      retainedSignature: "VIZE_UI_TYPEAHEAD_DISPOSED",
      maximumJavaScriptGzipBytes: 1_375,
      maximumCssGzipBytes: 0,
    },
    aliases: ["typeahead", "collection search", "keyboard search"],
    upstreamCoverage: ["React Aria useTypeSelect", "Ariakit composite typeahead"],
    dependencies: ["collection"],
    maturity: "stable",
    owner: catalogOwner,
  },
  {
    canonicalName: "virtualizer",
    title: "Virtualizer",
    packageSubpath: "./virtualizer",
    entryFile: `${virtualizerFamilyRoot}virtualizer.ts`,
    sourceFiles: [
      `${virtualizerFamilyRoot}virtualizer.ts`,
      `${virtualizerFamilyRoot}virtualizer-grid.ts`,
      `${virtualizerFamilyRoot}virtualizer-infinite.ts`,
      `${virtualizerFamilyRoot}virtualizer-measure-cache.ts`,
      `${virtualizerFamilyRoot}virtualizer-options.ts`,
      `${virtualizerFamilyRoot}virtualizer-runtime.ts`,
      `${virtualizerFamilyRoot}virtualizer-types.ts`,
      `${virtualizerFamilyRoot}virtualizer-viewport.ts`,
      `${virtualizerFamilyRoot}virtualizer-window.ts`,
    ],
    behaviorContract: `${virtualizerFamilyRoot}virtualizer.behavior.md`,
    tests: [
      `${virtualizerFamilyRoot}virtualizer.test.ts`,
      `${virtualizerFamilyRoot}virtualizer-grid.test.ts`,
      `${virtualizerFamilyRoot}virtualizer-infinite.test.ts`,
      `${virtualizerFamilyRoot}virtualizer-measure-cache.test.ts`,
      `${virtualizerFamilyRoot}virtualizer-ssr.test.ts`,
    ],
    typeTests: [`${virtualizerFamilyRoot}virtualizer.types.test-d.ts`],
    rendererFixture: "VirtualizerConsumer.vue",
    qualityGates: interactionQualityGates,
    bundleBudget: {
      exportName: "createVirtualizer",
      retainedSignature: "VIZE_UI_VIRTUALIZER_DISPOSED",
      allowedRetainedFamilies: ["measure"],
      maximumJavaScriptGzipBytes: 4_800,
      maximumCssGzipBytes: 0,
    },
    aliases: ["virtual list", "virtual scroll", "windowing", "infinite scroll"],
    upstreamCoverage: ["windowed rendering", "scroll anchoring", "scroll restoration"],
    dependencies: ["measure"],
    maturity: "stable",
    owner: catalogOwner,
  },
] as const satisfies readonly UiFamilyCatalogEntry[];
