//! Vue helpers this installment can mention, ranked the way
//! `vue_helper_import_rank` orders the shipped preamble. Same-rank
//! helpers mostly follow transform-first registration, then emit order
//! (`Buf::prefer` then first `use_*`), matching `root.helpers`
//! then `used_helpers`; ranks whose shipped order is driven by emitted
//! helper calls are sorted by final alias use.

#[derive(Clone, Copy)]
pub(super) enum Helper {
    ResolveComponent,
    ResolveDynamicComponent,
    ResolveDirective,
    ResolveFilter,
    VModelText,
    VModelCheckbox,
    VModelRadio,
    VModelSelect,
    VShow,
    WithDirectives,
    WithKeys,
    WithModifiers,
    ToDisplayString,
    RenderSlot,
    CreateElementVNode,
    CreateVNode,
    NormalizeClass,
    NormalizeStyle,
    NormalizeProps,
    GuardReactiveProps,
    MergeProps,
    ToHandlers,
    ToHandlerKey,
    Camelize,
    OpenBlock,
    CreateBlock,
    CreateElementBlock,
    Fragment,
    CreateComment,
    CreateText,
    RenderList,
    CreateSlots,
    SetBlockTracking,
    WithMemo,
    IsMemoSame,
    WithCtx,
    Teleport,
    Suspense,
    KeepAlive,
    BaseTransition,
    Transition,
    TransitionGroup,
    Unref,
}

impl Helper {
    pub(super) const ALL: [Self; 43] = [
        Self::ResolveComponent,
        Self::ResolveDynamicComponent,
        Self::ResolveDirective,
        Self::ResolveFilter,
        Self::VModelText,
        Self::VModelCheckbox,
        Self::VModelRadio,
        Self::VModelSelect,
        Self::VShow,
        Self::WithDirectives,
        Self::WithKeys,
        Self::WithModifiers,
        Self::ToDisplayString,
        Self::RenderSlot,
        Self::CreateElementVNode,
        Self::CreateVNode,
        Self::NormalizeClass,
        Self::NormalizeStyle,
        Self::NormalizeProps,
        Self::GuardReactiveProps,
        Self::MergeProps,
        Self::ToHandlers,
        Self::ToHandlerKey,
        Self::Camelize,
        Self::OpenBlock,
        Self::CreateBlock,
        Self::CreateElementBlock,
        Self::Fragment,
        Self::CreateComment,
        Self::CreateText,
        Self::RenderList,
        Self::CreateSlots,
        Self::SetBlockTracking,
        Self::WithMemo,
        Self::IsMemoSame,
        Self::WithCtx,
        Self::Teleport,
        Self::Suspense,
        Self::KeepAlive,
        Self::BaseTransition,
        Self::Transition,
        Self::TransitionGroup,
        Self::Unref,
    ];

    pub(super) const fn rank(self) -> u8 {
        match self {
            Self::ResolveComponent
            | Self::ResolveDynamicComponent
            | Self::ResolveDirective
            | Self::ResolveFilter => 0,
            Self::VModelText | Self::VModelCheckbox | Self::VModelRadio | Self::VModelSelect => 1,
            Self::WithDirectives | Self::WithKeys | Self::WithModifiers => 2,
            Self::ToDisplayString => 3,
            Self::RenderSlot | Self::CreateElementVNode | Self::CreateVNode => 4,
            Self::NormalizeClass
            | Self::NormalizeStyle
            | Self::NormalizeProps
            | Self::GuardReactiveProps
            | Self::MergeProps
            | Self::ToHandlers
            | Self::ToHandlerKey
            | Self::Camelize => 5,
            Self::OpenBlock => 6,
            Self::CreateBlock | Self::CreateElementBlock => 7,
            Self::Fragment => 8,
            Self::CreateComment | Self::CreateText => 9,
            Self::RenderList
            | Self::CreateSlots
            | Self::SetBlockTracking
            | Self::VShow
            | Self::WithMemo
            | Self::IsMemoSame
            | Self::WithCtx
            | Self::Teleport
            | Self::Suspense
            | Self::KeepAlive
            | Self::BaseTransition
            | Self::Transition
            | Self::TransitionGroup
            | Self::Unref => 10,
        }
    }

    pub(super) const fn bit(self) -> u64 {
        match self {
            Self::ToDisplayString => 1,
            Self::CreateElementVNode => 2,
            Self::OpenBlock => 4,
            Self::CreateElementBlock => 8,
            Self::CreateText => 16,
            Self::NormalizeClass => 32,
            Self::NormalizeStyle => 64,
            Self::WithKeys => 128,
            Self::WithModifiers => 256,
            Self::CreateComment => 512,
            Self::Fragment => 1024,
            Self::RenderList => 2048,
            Self::NormalizeProps => 4096,
            Self::GuardReactiveProps => 8192,
            Self::MergeProps => 16384,
            Self::ResolveComponent => 32768,
            Self::CreateVNode => 65536,
            Self::CreateBlock => 131072,
            Self::ToHandlers => 262144,
            Self::Camelize => 524288,
            Self::CreateSlots => 1048576,
            Self::WithCtx => 2097152,
            Self::RenderSlot => 4194304,
            Self::Teleport => 8388608,
            Self::Suspense => 16777216,
            Self::KeepAlive => 33554432,
            Self::BaseTransition => 67108864,
            Self::Transition => 134217728,
            Self::TransitionGroup => 268435456,
            Self::ResolveDynamicComponent => 536870912,
            Self::VModelText => 1073741824,
            Self::VModelCheckbox => 2147483648,
            Self::VModelRadio => 4294967296,
            Self::VModelSelect => 8589934592,
            Self::VShow => 2199023255552,
            Self::WithDirectives => 17179869184,
            Self::ResolveDirective => 34359738368,
            Self::ResolveFilter => 68719476736,
            Self::ToHandlerKey => 137438953472,
            Self::SetBlockTracking => 274877906944,
            Self::WithMemo => 549755813888,
            Self::IsMemoSame => 1099511627776,
            Self::Unref => 4398046511104,
        }
    }

    pub(super) const fn name(self) -> &'static str {
        match self {
            Self::ResolveComponent => "resolveComponent",
            Self::ResolveDynamicComponent => "resolveDynamicComponent",
            Self::ResolveDirective => "resolveDirective",
            Self::ResolveFilter => "resolveFilter",
            Self::VModelText => "vModelText",
            Self::VModelCheckbox => "vModelCheckbox",
            Self::VModelRadio => "vModelRadio",
            Self::VModelSelect => "vModelSelect",
            Self::VShow => "vShow",
            Self::WithDirectives => "withDirectives",
            Self::WithKeys => "withKeys",
            Self::WithModifiers => "withModifiers",
            Self::ToDisplayString => "toDisplayString",
            Self::CreateElementVNode => "createElementVNode",
            Self::CreateVNode => "createVNode",
            Self::RenderSlot => "renderSlot",
            Self::NormalizeClass => "normalizeClass",
            Self::NormalizeStyle => "normalizeStyle",
            Self::NormalizeProps => "normalizeProps",
            Self::GuardReactiveProps => "guardReactiveProps",
            Self::MergeProps => "mergeProps",
            Self::ToHandlers => "toHandlers",
            Self::ToHandlerKey => "toHandlerKey",
            Self::Camelize => "camelize",
            Self::OpenBlock => "openBlock",
            Self::CreateBlock => "createBlock",
            Self::CreateElementBlock => "createElementBlock",
            Self::Fragment => "Fragment",
            Self::CreateText => "createTextVNode",
            Self::CreateComment => "createCommentVNode",
            Self::RenderList => "renderList",
            Self::CreateSlots => "createSlots",
            Self::SetBlockTracking => "setBlockTracking",
            Self::WithMemo => "withMemo",
            Self::IsMemoSame => "isMemoSame",
            Self::WithCtx => "withCtx",
            Self::Teleport => "Teleport",
            Self::Suspense => "Suspense",
            Self::KeepAlive => "KeepAlive",
            Self::BaseTransition => "BaseTransition",
            Self::Transition => "Transition",
            Self::TransitionGroup => "TransitionGroup",
            Self::Unref => "unref",
        }
    }

    pub(super) const fn alias(self) -> &'static str {
        match self {
            Self::ResolveComponent => "_resolveComponent",
            Self::ResolveDynamicComponent => "_resolveDynamicComponent",
            Self::ResolveDirective => "_resolveDirective",
            Self::ResolveFilter => "_resolveFilter",
            Self::VModelText => "_vModelText",
            Self::VModelCheckbox => "_vModelCheckbox",
            Self::VModelRadio => "_vModelRadio",
            Self::VModelSelect => "_vModelSelect",
            Self::VShow => "_vShow",
            Self::WithDirectives => "_withDirectives",
            Self::WithKeys => "_withKeys",
            Self::WithModifiers => "_withModifiers",
            Self::ToDisplayString => "_toDisplayString",
            Self::CreateElementVNode => "_createElementVNode",
            Self::CreateVNode => "_createVNode",
            Self::RenderSlot => "_renderSlot",
            Self::NormalizeClass => "_normalizeClass",
            Self::NormalizeStyle => "_normalizeStyle",
            Self::NormalizeProps => "_normalizeProps",
            Self::GuardReactiveProps => "_guardReactiveProps",
            Self::MergeProps => "_mergeProps",
            Self::ToHandlers => "_toHandlers",
            Self::ToHandlerKey => "_toHandlerKey",
            Self::Camelize => "_camelize",
            Self::OpenBlock => "_openBlock",
            Self::CreateBlock => "_createBlock",
            Self::CreateElementBlock => "_createElementBlock",
            Self::Fragment => "_Fragment",
            Self::CreateText => "_createTextVNode",
            Self::CreateComment => "_createCommentVNode",
            Self::RenderList => "_renderList",
            Self::CreateSlots => "_createSlots",
            Self::SetBlockTracking => "_setBlockTracking",
            Self::WithMemo => "_withMemo",
            Self::IsMemoSame => "_isMemoSame",
            Self::WithCtx => "_withCtx",
            Self::Teleport => "_Teleport",
            Self::Suspense => "_Suspense",
            Self::KeepAlive => "_KeepAlive",
            Self::BaseTransition => "_BaseTransition",
            Self::Transition => "_Transition",
            Self::TransitionGroup => "_TransitionGroup",
            Self::Unref => "_unref",
        }
    }

    pub(super) fn from_alias(alias: &str) -> Option<Self> {
        Some(match alias {
            "_resolveComponent" => Self::ResolveComponent,
            "_resolveDynamicComponent" => Self::ResolveDynamicComponent,
            "_resolveDirective" => Self::ResolveDirective,
            "_resolveFilter" => Self::ResolveFilter,
            "_vModelText" => Self::VModelText,
            "_vModelCheckbox" => Self::VModelCheckbox,
            "_vModelRadio" => Self::VModelRadio,
            "_vModelSelect" => Self::VModelSelect,
            "_vShow" => Self::VShow,
            "_withDirectives" => Self::WithDirectives,
            "_withKeys" => Self::WithKeys,
            "_withModifiers" => Self::WithModifiers,
            "_toDisplayString" => Self::ToDisplayString,
            "_renderSlot" => Self::RenderSlot,
            "_createElementVNode" => Self::CreateElementVNode,
            "_createVNode" => Self::CreateVNode,
            "_normalizeClass" => Self::NormalizeClass,
            "_normalizeStyle" => Self::NormalizeStyle,
            "_normalizeProps" => Self::NormalizeProps,
            "_guardReactiveProps" => Self::GuardReactiveProps,
            "_mergeProps" => Self::MergeProps,
            "_toHandlers" => Self::ToHandlers,
            "_toHandlerKey" => Self::ToHandlerKey,
            "_camelize" => Self::Camelize,
            "_openBlock" => Self::OpenBlock,
            "_createBlock" => Self::CreateBlock,
            "_createElementBlock" => Self::CreateElementBlock,
            "_Fragment" => Self::Fragment,
            "_createCommentVNode" => Self::CreateComment,
            "_createTextVNode" => Self::CreateText,
            "_renderList" => Self::RenderList,
            "_createSlots" => Self::CreateSlots,
            "_setBlockTracking" => Self::SetBlockTracking,
            "_withMemo" => Self::WithMemo,
            "_isMemoSame" => Self::IsMemoSame,
            "_withCtx" => Self::WithCtx,
            "_Teleport" => Self::Teleport,
            "_Suspense" => Self::Suspense,
            "_KeepAlive" => Self::KeepAlive,
            "_BaseTransition" => Self::BaseTransition,
            "_Transition" => Self::Transition,
            "_TransitionGroup" => Self::TransitionGroup,
            "_unref" => Self::Unref,
            _ => return None,
        })
    }
}
