import assert from "node:assert/strict";
import { existsSync, realpathSync } from "node:fs";
import { join } from "node:path";
import type { InlineConfig } from "vite-plus";
import { fingerprintFiles } from "./runtime-bundle-inputs.ts";

type RuntimeOutput = {
  output: Array<
    { type: "asset" } | { type: "chunk"; code: string; imports: string[]; dynamicImports: string[] }
  >;
};

/** Preserve the original one-code-chunk selection; only byte reuse needs tighter proof. */
export function runtimeBundleChunk(outputs: RuntimeOutput[]) {
  const emitted = outputs.flatMap((output) => output.output);
  const chunks = emitted.filter((item) => item.type === "chunk");
  assert.equal(chunks.length, 1, "Vue runtime must bundle into one self-contained module");
  return {
    code: chunks[0].code,
    reusable:
      emitted.length === 1 &&
      chunks[0].imports.length === 0 &&
      chunks[0].dynamicImports.length === 0,
  };
}

export function runtimeBundleOptions(entry: string, production: boolean): InlineConfig {
  assert.equal(typeof production, "boolean", "production runtime mode must be explicit");
  return {
    configFile: false,
    logLevel: "silent",
    define: {
      "process.env.NODE_ENV": JSON.stringify(production ? "production" : "development"),
      __VUE_OPTIONS_API__: "true",
      __VUE_PROD_DEVTOOLS__: "false",
      __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: production ? "false" : "true",
    },
    build: { write: false, minify: production, lib: { entry, formats: ["es"] } },
  };
}

export function boundedRuntimeEnvironment(
  cwd: string,
  env: NodeJS.ProcessEnv,
  execArgv = process.execArgv,
) {
  const envFiles = [".env", ".env.local", ".env.production", ".env.production.local"].map((name) =>
    join(cwd, name),
  );
  // Env expansion and custom loaders/bindings can introduce arbitrary inputs.
  if (
    envFiles.some((path) => existsSync(path)) ||
    env.VITE_USER_NODE_ENV ||
    env.NAPI_RS_NATIVE_LIBRARY_PATH ||
    env.NAPI_RS_FORCE_WASI ||
    process.versions.webcontainer ||
    [env.NODE_OPTIONS ?? "", ...execArgv].some((options) =>
      /--(?:require|import|(?:experimental-)?loader)|(?:^|[\s"'])-r/.test(options),
    )
  )
    return null;
  return {
    cwd,
    envFiles: fingerprintFiles(envFiles),
    env: Object.fromEntries(
      Object.keys(env)
        .filter(
          (key) =>
            key.startsWith("VITE_") ||
            ["NODE_ENV", "NODE_OPTIONS", "NAPI_RS_ENFORCE_VERSION_CHECK"].includes(key),
        )
        .sort()
        .map((key) => [key, env[key]]),
    ),
  };
}

export function runtimeModulesCovered(modules: string[], files: string[], entry: string) {
  const covered = new Set(files);
  let includesEntry = false;
  for (const id of modules) {
    if (id.startsWith("\0")) continue; // Generated by the hashed bundler implementation.
    let path: string;
    try {
      path = realpathSync(id.split("?")[0]);
    } catch {
      return false;
    }
    if (!covered.has(path)) return false;
    includesEntry ||= path === realpathSync(entry);
  }
  return includesEntry;
}
