/** Markdown helpers for the generated reference docs. */
import type { ApiMember } from "./extract.ts";

/** Escape a table cell (pipes, newlines). */
export function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
}

/** Inline code that survives backticks and pipes inside table cells. */
export function code(text: string): string {
  if (text === "" || text === "—") return "—";
  const escaped = cell(text);
  return escaped.includes("`") ? `<code>${escaped.replace(/</g, "&lt;")}</code>` : `\`${escaped}\``;
}

/** A Markdown table; returns "" when there are no rows. */
export function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  if (rows.length === 0) return "";
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ].join("\n");
}

function description(member: ApiMember): string {
  const text = cell(member.description);
  return member.deprecated ? `**Deprecated.** ${text}`.trim() : text;
}

export function propsTable(members: readonly ApiMember[]): string {
  return table(
    ["Prop", "Type", "Default", "Description"],
    members.map((member) => [
      `\`${member.name}\`${member.optional ? "" : " (required)"}`,
      code(member.type),
      member.defaultValue == null ? "—" : code(member.defaultValue),
      description(member),
    ]),
  );
}

export function emitsTable(members: readonly ApiMember[]): string {
  return table(
    ["Event", "Payload", "Description"],
    members.map((member) => [`\`${member.name}\``, code(member.type), description(member)]),
  );
}

export function slotsTable(members: readonly ApiMember[]): string {
  return table(
    ["Slot", "Slot props", "Description"],
    members.map((member) => [`\`${member.name}\``, code(member.type), description(member)]),
  );
}

export function membersTable(members: readonly ApiMember[], first = "Member"): string {
  return table(
    [first, "Type", "Description"],
    members.map((member) => [
      `\`${member.name}\`${member.optional ? "?" : ""}`,
      code(member.type),
      description(member),
    ]),
  );
}

/** Join non-empty blocks with blank lines and end with one newline. */
export function blocks(...parts: readonly string[]): string {
  return `${parts.filter((part) => part.trim().length > 0).join("\n\n")}\n`;
}

/**
 * Embed a behavior contract below an H2: drop its H1 and demote the rest by
 * two levels so it nests under the page structure.
 */
export function embedBehavior(markdown: string): string {
  let inFence = false;
  return markdown
    .split("\n")
    .flatMap((line) => {
      if (line.startsWith("```")) inFence = !inFence;
      if (inFence) return [line];
      if (line.startsWith("# ")) return [];
      const heading = /^(#{2,4}) (.*)$/.exec(line);
      return heading == null ? [line] : [`${heading[1]}## ${heading[2]}`];
    })
    .join("\n")
    .trim();
}

export const GENERATED_NOTICE =
  "<!-- Generated by npm/ui/scripts/generate-reference-docs.ts from the catalogs and source TSDoc. Do not edit by hand. -->";

export function frontmatter(title: string, summary: string): string {
  const quote = (value: string) => JSON.stringify(value);
  return ["---", `title: ${quote(title)}`, `description: ${quote(summary)}`, "---"].join("\n");
}
