// Generated by `nuxi prepare` (committed so `vize check` runs without a Nuxt
// install). Re-exporting `vue-i18n` puts that package's `declare module "vue"`
// augmentation — the one `$t` comes from — into the project's type graph,
// exactly as a prepared Nuxt app does.
export { useI18n } from "vue-i18n";

declare global {
  const useI18n: typeof import("vue-i18n")["useI18n"];
}

export {};
