// Generated by tools/commands/fixtures/generate-css-catalog.ts; do not edit.
// Microsoft vscode-css-languageservice 2a253759802c9aba0d71b30e369fb65f1f062b5c.
// Copyright (c) Microsoft. MIT: tools/data/css/LICENSE.microsoft.txt.
use super::CssEntry;

#[rustfmt::skip]
pub(super) static ENTRIES: [&CssEntry; 25] = [
    &super::at_rules_0::ENTRIES[0], &super::at_rules_0::ENTRIES[1], &super::at_rules_0::ENTRIES[2], &super::at_rules_0::ENTRIES[3], &super::at_rules_0::ENTRIES[4], &super::at_rules_0::ENTRIES[5], &super::at_rules_0::ENTRIES[6], &super::at_rules_0::ENTRIES[7],
    &super::at_rules_0::ENTRIES[8], &super::at_rules_0::ENTRIES[9], &super::at_rules_0::ENTRIES[10], &super::at_rules_0::ENTRIES[11], &super::at_rules_0::ENTRIES[12], &super::at_rules_0::ENTRIES[13], &super::at_rules_0::ENTRIES[14], &super::at_rules_0::ENTRIES[15],
    &super::at_rules_0::ENTRIES[16], &super::at_rules_0::ENTRIES[17], &super::at_rules_0::ENTRIES[18], &super::at_rules_0::ENTRIES[19], &super::at_rules_0::ENTRIES[20], &super::at_rules_0::ENTRIES[21], &super::at_rules_0::ENTRIES[22], &super::at_rules_0::ENTRIES[23],
    &super::at_rules_0::ENTRIES[24],
];
